/**
 * Invoice PDF Generator
 *
 * Generates a basic HTML invoice that can be printed to PDF via browser.
 * Uses jsPDF + jsPDF-AutoTable for programmatic PDF generation.
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export async function generateInvoicePdf(invoiceId: string): Promise<Buffer> {
  const { db } = await import('@/lib/db');

  const invoice = await db.invoice.findUnique({
    where: { id: invoiceId },
  });

  if (!invoice) {
    throw new Error(`Invoice not found: ${invoiceId}`);
  }

  // Parse line items
  let lineItems: Array<{
    description: string;
    quantity: number;
    unitPrice: number;
    totalAmount: number;
    taxRate?: number;
    taxAmount?: number;
  }> = [];

  try {
    lineItems = JSON.parse(invoice.lineItems || '[]');
  } catch {
    lineItems = [];
  }

  // Calculate subtotal from line items for accuracy
  const lineItemSubtotal = lineItems.reduce((sum, item) => sum + (item.totalAmount || 0), 0);
  const lineItemTaxes = lineItems.reduce((sum, item) => sum + (item.taxAmount || 0), 0);

  const subtotal = lineItemSubtotal || invoice.subtotal || 0;
  const taxes = lineItemTaxes || invoice.taxes || 0;
  const discount = invoice.discount || 0;
  const total = invoice.totalAmount || (subtotal + taxes - discount);

  // Create PDF document
  const doc = new jsPDF();

  // ── Header ────────────────────────────────────────────────────
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('INVOICE', 20, 20);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(120, 120, 120);
  doc.text(`Invoice #${invoice.invoiceNumber}`, 20, 30);
  doc.text(`Date: ${invoice.issuedAt ? new Date(invoice.issuedAt).toLocaleDateString() : 'N/A'}`, 20, 36);

  if (invoice.dueAt) {
    doc.text(`Due: ${new Date(invoice.dueAt).toLocaleDateString()}`, 20, 42);
  }

  doc.text(`Status: ${invoice.status.charAt(0).toUpperCase() + invoice.status.slice(1)}`, 20, 48);

  // ── Customer Info ──────────────────────────────────────────────
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Bill To:', 20, 62);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  let y = 70;
  doc.text(invoice.customerName || 'N/A', 20, y); y += 6;
  if (invoice.customerEmail) { doc.text(invoice.customerEmail, 20, y); y += 6; }
  if (invoice.customerAddress) { doc.text(invoice.customerAddress, 20, y); y += 6; }
  if (invoice.customerPhone) { doc.text(invoice.customerPhone, 20, y); y += 6; }

  // ── Line Items Table ────────────────────────────────────────────
  const tableData = lineItems.map((item, index) => [
    (index + 1).toString(),
    item.description || 'N/A',
    item.quantity?.toString() || '1',
    `${(item.unitPrice || 0).toFixed(2)}`,
    `${(item.totalAmount || 0).toFixed(2)}`,
  ]);

  autoTable(doc, {
    startY: y + 6,
    head: [['#', 'Description', 'Qty', 'Unit Price', 'Amount']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [41, 128, 185], textColor: 255, fontStyle: 'bold' },
    styles: { fontSize: 8 },
    columnStyles: {
      0: { cellWidth: 12, halign: 'center' },
      1: { cellWidth: 'auto' },
      2: { cellWidth: 15, halign: 'center' },
      3: { cellWidth: 25, halign: 'right' },
      4: { cellWidth: 25, halign: 'right' },
    },
  });

  // ── Totals ──────────────────────────────────────────────────────
  let totalsY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable?.finalY || y + 60;
  totalsY += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Subtotal: ${subtotal.toFixed(2)} ${invoice.currency}`, 140, totalsY);
  totalsY += 6;
  if (taxes > 0) { doc.text(`Taxes: ${taxes.toFixed(2)} ${invoice.currency}`, 140, totalsY); totalsY += 6; }
  if (discount > 0) { doc.text(`Discount: -${discount.toFixed(2)} ${invoice.currency}`, 140, totalsY); totalsY += 6; }

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(`Total: ${total.toFixed(2)} ${invoice.currency}`, 140, totalsY + 4);

  // ── Footer ──────────────────────────────────────────────────────
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `${invoice.customerName || 'Guest'} — Generated by StaySuite HospitalityOS`,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' },
    );
    doc.text(
      `Page ${i} of ${pageCount}`,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 6,
      { align: 'center' },
    );
  }

  const pdfBuffer = doc.output('arraybuffer');
  return Buffer.from(pdfBuffer);
}
