/* Automatically generated by "build-radpaths-h" */
#define LOGDIR		"/home/z/my-project/freeradius-install/var/log/radius"
#define LIBDIR		"/home/z/my-project/freeradius-install/lib"
#define RADDBDIR	"/home/z/my-project/freeradius-install/etc/raddb"
#define RUNDIR		"/home/z/my-project/freeradius-install/var/run"
#define SBINDIR		"/home/z/my-project/freeradius-install/sbin"
#define RADIR		"/home/z/my-project/freeradius-install/var/log/radius/radacct"
#define DICTDIR		"/home/z/my-project/freeradius-install/share/freeradius"
