const APP_DIR = __dirname;

module.exports = {
  apps: [
    {
      name: 'staysuite-nextjs',
      script: `${APP_DIR}/scripts/start-nextjs.sh`,
      interpreter: 'bash',
      cwd: APP_DIR,
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 10000,
      kill_timeout: 30000,
      listen_timeout: 120000,
      max_memory_restart: '4G',
      env: {
        PORT: 3000,
        DATABASE_URL: 'postgresql://staysuite:Staysuite2025@127.0.0.1:5432/staysuite',
        RADIUS_DATABASE_URL: 'postgresql://staysuite:Staysuite2025@127.0.0.1:5432/staysuite',
        NODE_ENV: 'development',
        LD_LIBRARY_PATH: `${APP_DIR}/freeradius-install/lib:${APP_DIR}/freeradius-install/lib/freeradius:${APP_DIR}/pgsql-runtime/lib`,
      },
      error_file: '/home/z/my-project/.pm2/logs/nextjs-error.log',
      out_file: '/home/z/my-project/.pm2/logs/nextjs-out.log',
    },
    {
      name: 'staysuite-freeradius',
      script: `${APP_DIR}/freeradius-install/sbin/radiusd`,
      args: `-d ${APP_DIR}/freeradius-install/etc/raddb -D ${APP_DIR}/freeradius-install/share/freeradius -f`,
      cwd: APP_DIR,
      interpreter: 'none',
      watch: false,
      autorestart: true,
      env: {
        LD_LIBRARY_PATH: `${APP_DIR}/freeradius-install/lib:${APP_DIR}/freeradius-install/lib/freeradius:${APP_DIR}/pgsql-runtime/lib`,
      },
      error_file: '/home/z/my-project/.pm2/logs/freeradius-error.log',
      out_file: '/home/z/my-project/.pm2/logs/freeradius-out.log',
    },
    {
      name: 'realtime-service',
      script: 'index.ts',
      interpreter: '/usr/local/bin/bun',
      cwd: `${APP_DIR}/mini-services/realtime-service`,
      watch: false,
      autorestart: true,
      env: {
        DATABASE_URL: 'postgresql://staysuite:Staysuite2025@127.0.0.1:5432/staysuite',
      },
      error_file: '/home/z/my-project/.pm2/logs/realtime-error.log',
      out_file: '/home/z/my-project/.pm2/logs/realtime-out.log',
    },
    {
      name: 'availability-service',
      script: 'server.ts',
      interpreter: '/usr/local/bin/bun',
      cwd: `${APP_DIR}/mini-services/availability-service`,
      watch: false,
      autorestart: true,
      env: {
        DATABASE_URL: 'postgresql://staysuite:Staysuite2025@127.0.0.1:5432/staysuite',
      },
      error_file: '/home/z/my-project/.pm2/logs/availability-error.log',
      out_file: '/home/z/my-project/.pm2/logs/availability-out.log',
    },
    {
      name: 'shell-console',
      script: 'index.ts',
      interpreter: '/usr/local/bin/bun',
      cwd: `${APP_DIR}/mini-services/shell-console`,
      watch: false,
      autorestart: true,
      error_file: '/home/z/my-project/.pm2/logs/shell-console-error.log',
      out_file: '/home/z/my-project/.pm2/logs/shell-console-out.log',
    },
  ],
};
