const APP_DIR = __dirname;

module.exports = {
  apps: [
    {
      name: 'staysuite-main',
      script: 'bun',
      args: 'run dev',
      cwd: APP_DIR,
      watch: false,
      instances: 1,
      autorestart: true,
      max_memory_restart: '6500M',
      restart_delay: 5000,
      max_restarts: 10,
      kill_timeout: 10000,
      listen_timeout: 60000,
      env: {
        PORT: 3000,
        DATABASE_URL: 'postgresql://staysuite:Staysuite2025@127.0.0.1:5432/staysuite',
        NODE_ENV: 'development',
        NODE_OPTIONS: '--max-old-space-size=3072',
        LD_LIBRARY_PATH: `${APP_DIR}/freeradius-install/lib:${APP_DIR}/freeradius-install/lib/freeradius:${APP_DIR}/pgsql-runtime/lib`,
        RRD_BIN_PATH: `${APP_DIR}/rrdtool/bin/rrdtool`,
        RRD_LIB_PATH: `${APP_DIR}/rrdtool/lib`,
        RRD_DATA_PATH: `${APP_DIR}/data/rrd`,
        CRON_SECRET: 'staysuite-cron-secret-2025',
      },
      error_file: '/home/z/my-project/.pm2/logs/staysuite-main-error.log',
      out_file: '/home/z/my-project/.pm2/logs/staysuite-main-out.log',
    },
    {
      name: 'staysuite-freeradius',
      script: `${APP_DIR}/freeradius-install/sbin/radiusd`,
      args: `-d ${APP_DIR}/freeradius-install/etc/raddb -D ${APP_DIR}/freeradius-install/share/freeradius -f`,
      cwd: APP_DIR,
      interpreter: 'none',
      watch: false,
      autorestart: true,
      env: {
        LD_LIBRARY_PATH: `${APP_DIR}/freeradius-install/lib:${APP_DIR}/freeradius-install/lib/freeradius:${APP_DIR}/pgsql-runtime/lib`,
      },
      error_file: '/home/z/my-project/.pm2/logs/freeradius-error.log',
      out_file: '/home/z/my-project/.pm2/logs/freeradius-out.log',
    },
    {
      name: 'realtime-service',
      script: 'index.ts',
      interpreter: '/usr/local/bin/bun',
      cwd: `${APP_DIR}/mini-services/realtime-service`,
      watch: false,
      autorestart: true,
      error_file: '/home/z/my-project/.pm2/logs/realtime-error.log',
      out_file: '/home/z/my-project/.pm2/logs/realtime-out.log',
    },
    {
      name: 'availability-service',
      script: 'server.ts',
      interpreter: '/usr/local/bin/bun',
      cwd: `${APP_DIR}/mini-services/availability-service`,
      watch: false,
      autorestart: true,
      error_file: '/home/z/my-project/.pm2/logs/availability-error.log',
      out_file: '/home/z/my-project/.pm2/logs/availability-out.log',
    },
    {
      name: 'shell-console',
      script: 'index.ts',
      interpreter: '/usr/local/bin/bun',
      cwd: `${APP_DIR}/mini-services/shell-console`,
      watch: false,
      autorestart: true,
      error_file: '/home/z/my-project/.pm2/logs/shell-console-error.log',
      out_file: '/home/z/my-project/.pm2/logs/shell-console-out.log',
    },
  ],
};
