import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { wifiUserService } from '@/lib/wifi/services/wifi-user-service';
import { randomUUID, randomInt } from 'crypto';
import { radiusAuth, getRejectMessage } from '@/lib/wifi/utils/radius-auth';
import { addUserCounter } from '@/lib/wifi/utils/nftables-counters';
import {
  runLoginScript,
  generateClassIds,
  lookupBandwidthPool,
  type LoginScriptParams,
} from '@/lib/network/script-runner';

// ────────────────────────────────────────────────────────────
// Device Info Helpers
// ────────────────────────────────────────────────────────────

function parseDeviceTypeFromUA(ua: string): string {
  if (/iPhone/i.test(ua)) return 'mobile';
  if (/iPad/i.test(ua) || (/Macintosh/i.test(ua) && /WebKit/i.test(ua) && !/Safari/i.test(ua))) return 'tablet';
  if (/Android/i.test(ua)) return /Mobile/i.test(ua) ? 'mobile' : 'tablet';
  if (/SmartTV|InternetTV|APPLETV/i.test(ua)) return 'tv';
  if (/Windows|Macintosh|Linux|CrOS/i.test(ua)) return 'desktop';
  return 'unknown';
}

function parseDeviceNameFromUA(ua: string): string {
  if (/iPhone/i.test(ua)) return 'iPhone';
  if (/iPad/i.test(ua)) return 'iPad';
  if (/Android/i.test(ua)) return /Mobile/i.test(ua) ? 'Android Phone' : 'Android Tablet';
  if (/Windows/i.test(ua)) return 'Windows PC';
  if (/Macintosh/i.test(ua)) return 'Mac';
  if (/CrOS/i.test(ua)) return 'Chromebook';
  if (/Linux/i.test(ua)) return 'Linux PC';
  if (/SmartTV/i.test(ua)) return 'Smart TV';
  return 'Unknown Device';
}

/**
 * Create or update a DeviceProfile entry using the REAL browser fingerprint.
 * The fingerprintHash and storageToken are sent from the client (generated by
 * device-fingerprint.ts) — this ensures auto-reauth can match on future visits.
 *
 * Called after successful auth with client-provided fingerprint data.
 * If no fingerprintHash is provided, this is a no-op (profile creation is
 * deferred to the client's auto-auth fire-and-forget with _createProfile).
 */
async function upsertDeviceProfileWithFingerprint(params: {
  wifiUserId: string;
  tenantId: string;
  propertyId: string;
  guestId?: string | null;
  username: string;
  request: NextRequest;
  macAddress?: string | null;
  fingerprintHash?: string | null;
  storageToken?: string | null;
}) {
  const { wifiUserId, tenantId, propertyId, guestId, username, request, macAddress, fingerprintHash, storageToken } = params;

  // If no real fingerprint, skip — don't create a profile with a fake fingerprint
  // that would shadow the real one and break auto-reauth.
  if (!fingerprintHash) {
    console.log('[Auth] No client fingerprint provided — skipping DeviceProfile creation (deferred to auto-auth)');
    return;
  }

  try {
    const clientIp = request.headers.get('x-forwarded-for')?.split(',')[0]?.trim()
      || request.headers.get('x-real-ip')
      || 'unknown';
    const userAgent = request.headers.get('user-agent') || '';
    const deviceType = parseDeviceTypeFromUA(userAgent);
    const deviceName = parseDeviceNameFromUA(userAgent);

    // Normalize MAC address format
    const normalizedMac = macAddress
      ? macAddress.replace(/[:\-\.\s]/g, '').toUpperCase()
      : null;
    const formattedMac = normalizedMac && normalizedMac.length === 12
      ? normalizedMac.match(/.{2}/g)?.join(':') || null
      : null;

    // Upsert by (fingerprintHash, propertyId) unique constraint
    await db.deviceProfile.upsert({
      where: {
        fingerprintHash_propertyId: {
          fingerprintHash,
          propertyId,
        },
      },
      create: {
        tenantId,
        propertyId,
        wifiUserId,
        guestId: guestId || undefined,
        fingerprintHash,
        storageToken: storageToken || undefined,
        ipAddress: clientIp,
        userAgent: userAgent.substring(0, 500),
        macAddress: formattedMac || undefined,
        deviceType,
        deviceName,
        authCount: 1,
        lastAuthAt: new Date(),
        lastSeenAt: new Date(),
        isActive: true,
      },
      update: {
        wifiUserId,
        guestId: guestId || undefined,
        storageToken: storageToken || undefined,
        ipAddress: clientIp,
        userAgent: userAgent.substring(0, 500),
        ...(formattedMac ? { macAddress: formattedMac } : {}),
        deviceType,
        deviceName,
        isActive: true,
        authCount: { increment: 1 },
        lastAuthAt: new Date(),
        lastSeenAt: new Date(),
      },
    });

    console.log(`[Auth] DeviceProfile upserted for ${username} (fingerprint: ${fingerprintHash.substring(0, 12)}...)`);
  } catch (err) {
    console.warn('[Auth] DeviceProfile upsert failed (non-critical):', err instanceof Error ? err.message : err);
  }
}

// ────────────────────────────────────────────────────────────
// In-memory OTP store (sandbox — use Redis in production)
// ────────────────────────────────────────────────────────────
const otpStore = new Map<
  string,
  { code: string; expiresAt: number; phone: string }
>();

if (process.env.NODE_ENV === 'production') {
  console.warn('[OTP] In-memory OTP store used in production — migrate to Redis for multi-instance support');
}

function generateOtp(): string {
  return randomInt(100000, 999999).toString();
}

// ────────────────────────────────────────────────────────────
// IP Pool Validation Helpers
// ────────────────────────────────────────────────────────────

interface MatchedPool {
  poolId: string;
  poolName: string;
  subnet: string | null;
  gateway: string | null;
  captivePortal: boolean;
  isDefault: boolean;
}

/** Extract client IP from request headers (same logic as resolve-zone) */
function extractClientIp(request: NextRequest): string | null {
  const xff = request.headers.get('x-forwarded-for');
  if (xff) {
    const firstIp = xff.split(',')[0].trim();
    if (firstIp) return firstIp;
  }
  const xRealIp = request.headers.get('x-real-ip');
  if (xRealIp) return xRealIp.trim();
  return null;
}

/** Strip IPv6-mapped prefix and normalize to plain IPv4 */
function normalizeIp(raw: string | null): string | null {
  if (!raw) return null;
  let ip = raw.trim();
  if (ip.startsWith('[') && ip.includes(']')) {
    ip = ip.slice(1, ip.indexOf(']'));
  }
  const v4Match = ip.match(/^::ffff:(\d+\.\d+\.\d+\.\d+)$/i);
  if (v4Match) return v4Match[1];
  if (/^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$/.test(ip)) return ip;
  return null;
}

/**
 * Validate that the client IP belongs to an allocated IP pool.
 * Uses PostgreSQL inet range comparison for accurate matching.
 * Returns the matched pool info or null if no pool found.
 *
 * Conditions checked:
 * 1. IP must fall within an IpPoolRange (startIp–endIp)
 * 2. The pool must be enabled
 * 3. The pool must have captivePortal = true (managed network)
 * 4. If allowedPoolIds is provided, the matched pool must be in that list
 *    (enforces plan→pool binding so users can't login from wrong VLANs)
 */
async function validateClientIpInPool(
  clientIp: string,
  allowedPoolIds?: string[] | null
): Promise<MatchedPool | null> {
  try {
    // Build pool restriction clause when plan is bound to specific pools
    const poolFilter = (allowedPoolIds && allowedPoolIds.length > 0)
      ? `AND ip.id = ANY($2::uuid[])`
      : '';

    const params: unknown[] = [clientIp];
    if (allowedPoolIds && allowedPoolIds.length > 0) {
      params.push(allowedPoolIds);
    }

    const result = await db.$queryRawUnsafe<Array<{
      id: string;
      name: string;
      subnet: string | null;
      gateway: string | null;
      captivePortal: boolean;
      "isDefault": boolean;
    }>>(`
      SELECT DISTINCT ON (ip.id)
        ip.id, ip.name, ip.subnet::text as subnet, ip.gateway::text as gateway,
        ip."captivePortal", ip."isDefault"
      FROM "IpPoolRange" r
      JOIN "IpPool" ip ON ip.id = r."poolId"
      WHERE $1::inet BETWEEN r."startIp" AND r."endIp"
        AND ip.enabled = true
        ${poolFilter}
      ORDER BY ip.id, ip."isDefault" DESC
      LIMIT 1
    `, ...params);

    if (result.length === 0) return null;

    const pool = result[0];
    return {
      poolId: pool.id,
      poolName: pool.name,
      subnet: pool.subnet,
      gateway: pool.gateway,
      captivePortal: pool.captivePortal,
      isDefault: pool.isDefault,
    };
  } catch (err) {
    console.error('[IP Pool Validation] Query failed:', err);
    return null;
  }
}

/** Get client IP string for logging/accounting */
function getClientIpString(request: NextRequest): string {
  return extractClientIp(request) || request.headers.get('x-real-ip') || '0.0.0.0';
}

/**
 * Resolve allowed IP pool IDs for a user based on their plan binding.
 *
 * Priority:
 * 1. WiFiUser.ipPoolId — user-level override
 * 2. WiFiPlan.ipPoolId — plan default
 * 3. null — no restriction, any captive portal pool allowed
 *
 * Returns an array of pool UUIDs, or null if unrestricted.
 */
function resolveAllowedPoolIds(
  planIpPoolId?: string | null,
  userIpPoolId?: string | null
): string[] | null {
  // User-level override takes priority over plan-level
  if (userIpPoolId) return [userIpPoolId];
  if (planIpPoolId) return [planIpPoolId];
  return null; // No restriction
}

/**
 * Check if a user has reached their concurrent session limit.
 * Counts active (non-stopped) radacct sessions for the username.
 * Returns true if the limit is reached (should reject login).
 */
async function isSessionLimitReached(username: string, maxSessions: number): Promise<boolean> {
  if (maxSessions <= 0) return false; // 0 or negative = unlimited

  try {
    const result = await db.$queryRawUnsafe<Array<{ count: bigint }>>(`
      SELECT COUNT(*)::bigint as count
      FROM radacct
      WHERE username = $1 AND acctstoptime IS NULL
    `, username);

    const activeCount = Number(result[0]?.count ?? 0);
    return activeCount >= maxSessions;
  } catch (err) {
    console.error('[Session Limit] Failed to count active sessions:', err);
    return true; // Fail closed — deny access on error
  }
}

/**
 * Activate firewall + bandwidth shaping for a user after successful RADIUS auth.
 * Calls staysuite_login.sh which:
 *   - Adds IP to nft loggedinusers set (unblocks traffic)
 *   - Inserts fwmark rules in prerouting
 *   - Adds NAT masquerade rule
 *   - Creates TC HTB classes + fw filters on ifb0/ifb1
 *
 * Runs synchronously but with a 15s timeout.
 * Errors are logged but do NOT block the auth response —
 * the user is authenticated regardless of firewall state.
 * The recovery script will catch up if this fails.
 */
async function activateUserFirewall(params: {
  username: string;
  clientIp: string;
  propertyId: string;
  sessionId?: string;
  macAddress?: string;
  userId?: string;
  maxBandwidthDownBytes?: number;
  maxBandwidthUpBytes?: number;
  subnet?: string | null;
}) {
  try {
    const clientIp = normalizeIp(params.clientIp);
    if (!clientIp || clientIp === '0.0.0.0') {
      console.warn('[Firewall] Skipping activation — no valid client IP');
      return;
    }

    // Generate deterministic class IDs from username
    const classIds = generateClassIds(params.username);

    // Convert bytes/sec → kbps for the login script
    const dnKbps = params.maxBandwidthDownBytes
      ? Math.round(params.maxBandwidthDownBytes * 8 / 1000)
      : 0;
    const upKbps = params.maxBandwidthUpBytes
      ? Math.round(params.maxBandwidthUpBytes * 8 / 1000)
      : 0;

    // Look up BandwidthPool for pool-level rate limiting
    const poolBw = await lookupBandwidthPool(params.propertyId, params.subnet);

    const scriptParams: LoginScriptParams = {
      ip: clientIp,
      action: 'masq',
      poolId: poolBw.poolId,
      poolRateDn: poolBw.poolRateDn,
      poolCeilDn: poolBw.poolCeilDn,
      poolRateUp: poolBw.poolRateUp,
      poolCeilUp: poolBw.poolCeilUp,
      dnClassid: classIds.dn,
      upClassid: classIds.up,
      dnKbps,
      upKbps,
      sessionId: params.sessionId,
      macAddress: params.macAddress,
      userId: params.userId,
    };

    const result = runLoginScript(scriptParams);

    if (result.success) {
      console.log(
        `[Firewall] Login OK: ${params.username} ip=${clientIp} cls=${classIds.dn}/${classIds.up} pool=${poolBw.poolId} dn=${dnKbps}k up=${upKbps}k (${result.durationMs}ms)`
      );
    } else {
      console.error(
        `[Firewall] Login FAIL: ${params.username} exit=${result.exitCode} stderr=${result.stderr || '(none)'} (${result.durationMs}ms)`
      );
    }
  } catch (err) {
    // Non-fatal — firewall activation failure should not block authentication
    console.error('[Firewall] Exception activating firewall:', err);
  }
}

// ────────────────────────────────────────────────────────────
// MAC Address Resolution
// ────────────────────────────────────────────────────────────

/**
 * Resolve client MAC address using multiple methods (priority order):
 *
 * 1. Request body — Captive portal frontend passes MAC from URL query params
 *    (e.g., ?mac=AA:BB:CC:DD:EE:FF from UniFi/Mikrotik/Cisco redirect)
 * 2. HTTP headers — Some network equipment injects MAC as headers:
 *    - X-MAC-Address, Client-MAC, Calling-Station-Id
 *    - mac (Mikrotik, CoovaChilli), nas-mac (UniFi)
 * 3. DHCP lease table — Look up by client IP as last resort
 *    (only works if KEA/DHCP is running and has recorded the lease)
 */
async function resolveMacAddress(
  request: NextRequest,
  bodyMac?: string,
  clientIp?: string,
): Promise<string | null> {
  // 1. Body MAC (from URL params forwarded by captive portal frontend)
  if (bodyMac) {
    const normalized = bodyMac.replace(/[:\-\.\s]/g, '').toUpperCase();
    if (/^[0-9A-F]{12}$/.test(normalized)) {
      return normalized.match(/.{2}/g)?.join(':') || null;
    }
  }

  // 2. HTTP headers from network equipment
  const headerSources = [
    'x-mac-address',
    'client-mac',
    'mac',
    'nas-mac',
    'calling-station-id',
    'x-client-mac',
    'x-forwarded-mac',
  ];
  for (const header of headerSources) {
    const value = request.headers.get(header);
    if (value) {
      // Calling-Station-Id is often "AA:BB:CC:DD:EE:FF" or "AA-BB-CC-DD-EE-FF"
      // Some vendors prefix with SSID: "AA:BB:CC:DD:EE:FF-MyNetwork"
      const macMatch = value.match(/([0-9A-Fa-f]{2}[:\-\.]){5}[0-9A-Fa-f]{2}/);
      if (macMatch) {
        const normalized = macMatch[0].replace(/[:\-\.\s]/g, '').toUpperCase();
        if (/^[0-9A-F]{12}$/.test(normalized)) {
          return normalized.match(/.{2}/g)?.join(':') || null;
        }
      }
    }
  }

  // 3. DHCP lease lookup by client IP (last resort)
  if (clientIp && clientIp !== '0.0.0.0' && clientIp !== 'unknown') {
    try {
      const leaseResult = await db.$queryRawUnsafe<Array<{ "macAddress": string | null }>>(`
        SELECT "macAddress" FROM "DhcpLease"
        WHERE "ipAddress" = $1 AND state = 'active'
        ORDER BY "lastSeenAt" DESC
        LIMIT 1
      `, clientIp);

      if (leaseResult.length > 0 && leaseResult[0].macAddress) {
        const normalized = leaseResult[0].macAddress.replace(/[:\-\.\s]/g, '').toUpperCase();
        if (/^[0-9A-F]{12}$/.test(normalized)) {
          console.log(`[MAC] Resolved from DHCP lease: IP=${clientIp} → MAC=${normalized.match(/.{2}/g)?.join(':')}`);
          return normalized.match(/.{2}/g)?.join(':') || null;
        }
      }
    } catch (err) {
      // Non-critical — DHCP lookup failure should not block auth
      console.warn('[MAC] DHCP lease lookup failed:', err instanceof Error ? err.message : err);
    }
  }

  return null;
}

// ────────────────────────────────────────────────────────────
// Per-IP Rate Limiter (in-memory — use Redis for production)
// ────────────────────────────────────────────────────────────
const authAttempts = new Map<string, { count: number; resetAt: number }>();
function checkRateLimit(ip: string, maxAttempts: number = 10, windowMs: number = 60000): boolean {
  const now = Date.now();
  const entry = authAttempts.get(ip);
  if (!entry || now > entry.resetAt) {
    authAttempts.set(ip, { count: 1, resetAt: now + windowMs });
    return true;
  }
  entry.count++;
  return entry.count <= maxAttempts;
}

// ────────────────────────────────────────────────────────────
// POST /api/v1/wifi/auth — Guest WiFi authentication
//
// Validation order (changed per requirement):
//   1. Parse request body → extract username/method
//   2. Validate credentials (username, password, voucher, room, OTP)
//      → if invalid, log and return credential-specific error
//   3. Validate client IP against allocated IP pools
//      → if invalid, log and return IP error
//   4. Authenticate via FreeRADIUS
//   5. Log success + create accounting session
//
// This ensures auth logs show the CORRECT rejection reason:
//   Wrong password → "Rejected — invalid credentials"
//   Wrong network  → "Rejected — IP not in managed pool"
// ────────────────────────────────────────────────────────────
export async function POST(request: NextRequest) {
  try {
    // ════════════════════════════════════════════════════════════
    // STEP 0: Rate limit check (per-IP)
    // ════════════════════════════════════════════════════════════
    const clientRateLimitIp = extractClientIp(request) || 'unknown';
    if (!checkRateLimit(clientRateLimitIp)) {
      return errorResponse('RATE_LIMITED', 'Too many authentication attempts. Please try again later.', 429);
    }

    // ════════════════════════════════════════════════════════════
    // STEP 1: Parse request body — extract username & method first
    // ════════════════════════════════════════════════════════════
    const body = await request.json();
    const {
      method,
      portalSlug,
      voucherCode,
      roomNumber,
      lastName,
      username,
      password,
      phoneNumber,
      otpCode,
      guestInfo,
      macAddress,
      fingerprintHash,
      storageToken,
    } = body as {
      method?: string;
      portalSlug?: string;
      voucherCode?: string;
      roomNumber?: string;
      lastName?: string;
      username?: string;
      password?: string;
      phoneNumber?: string;
      otpCode?: string;
      guestInfo?: { firstName?: string; lastName?: string; email?: string; phone?: string };
      macAddress?: string;
      fingerprintHash?: string;
      storageToken?: string;
    };

    if (!method) {
      return errorResponse('MISSING_METHOD', 'Authentication method is required');
    }

    // ════════════════════════════════════════════════════════════
    // STEP 1b: Resolve MAC address from multiple sources
    // Priority: request body → HTTP headers → DHCP lease lookup
    // ════════════════════════════════════════════════════════════
    const clientIpForMac = extractClientIp(request) || getClientIpString(request);
    const resolvedMac = await resolveMacAddress(request, macAddress, clientIpForMac);
    // Use resolved MAC (from headers/DHCP) if body didn't provide one
    const effectiveMac = macAddress || resolvedMac || undefined;
    if (effectiveMac && resolvedMac && !macAddress) {
      console.log(`[MAC] Auto-resolved MAC for client: ${clientIpForMac} → ${resolvedMac} (source: header/dhcp)`);
    }

    const validMethods = [
      'voucher',
      'room_number',
      'pms_credentials',
      'sms_otp',
      'open_access',
    ];

    if (!validMethods.includes(method)) {
      return errorResponse(
        'INVALID_METHOD',
        `Invalid authentication method. Supported: ${validMethods.join(', ')}`
      );
    }

    // Fetch portal config for session timeout & bandwidth info
    const portal = portalSlug
      ? await db.captivePortal.findFirst({
          where: { slug: portalSlug, enabled: true },
        })
      : null;

    // Pre-resolve the plan's ipPoolId for pool-restricted validation.
    // Used by SMS OTP and Open Access where no existing user/plan is available.
    // Voucher and PMS Credentials resolve their own plan from user/voucher data.
    let portalPlanIpPoolId: string | null = null;
    if (portal?.propertyId) {
      const aaaConfig = await db.wiFiAAAConfig.findUnique({
        where: { propertyId: portal.propertyId },
        select: { defaultPlanId: true },
      });
      if (aaaConfig?.defaultPlanId) {
        const portalPlan = await db.wiFiPlan.findUnique({
          where: { id: aaaConfig.defaultPlanId },
          select: { ipPoolId: true },
        });
        portalPlanIpPoolId = portalPlan?.ipPoolId ?? null;
      }
    }

    // Portal defaults (sessionTimeout is stored in SECONDS in DB, convert to minutes for display)
    const portalSessionTimeoutMin = portal?.sessionTimeout
      ? Math.round(portal.sessionTimeout / 60)
      : 1440; // default 24h in minutes
    const bwDown = portal
      ? Math.round((portal.maxBandwidthDown || 5242880) / 1000000)
      : 5;
    const bwUp = portal
      ? Math.round((portal.maxBandwidthUp || 1048576) / 1000000)
      : 1;

    // ════════════════════════════════════════════════════════════
    // STEP 2: Validate credentials FIRST
    // Each method validates its own credentials here.
    // If invalid, we log and return immediately — NO IP check yet.
    // ════════════════════════════════════════════════════════════
    switch (method) {
      // ─── Voucher ──────────────────────────────────────────
      case 'voucher': {
        if (!voucherCode?.trim()) {
          return errorResponse('MISSING_VOUCHER', 'Please enter a voucher code');
        }

        const voucher = await db.wiFiVoucher.findUnique({
          where: { code: voucherCode.trim().toUpperCase() },
          include: { plan: true },
        });

        if (!voucher) {
          await logAuthAttempt(voucherCode.trim(), 'Access-Reject', request, 'INVALID_VOUCHER');
          return errorResponse('INVALID_VOUCHER', 'Invalid or expired voucher code');
        }

        if (voucher.status !== 'active' || voucher.isUsed) {
          await logAuthAttempt(`voucher-${voucher.code.toLowerCase()}`, 'Access-Reject', request, 'VOUCHER_USED');
          return errorResponse('VOUCHER_USED', 'This voucher has already been used');
        }

        const now = new Date();
        if (voucher.validUntil < now) {
          await logAuthAttempt(`voucher-${voucher.code.toLowerCase()}`, 'Access-Reject', request, 'VOUCHER_EXPIRED');
          return errorResponse('VOUCHER_EXPIRED', 'This voucher has expired. Please contact front desk for a new one.');
        }

        // ── Credentials valid — now check IP pool ──
        const allowedPools = resolveAllowedPoolIds(voucher.plan?.ipPoolId);
        const pool = await getValidatedPool(request, allowedPools);
        if (!pool) {
          await logAuthAttempt(`voucher-${voucher.code.toLowerCase()}`, 'Access-Reject', request, `IP_NOT_IN_POOL:${getClientIpString(request)}`);
          return errorResponse('IP_NOT_IN_POOL', 'Your device is not connected to a managed WiFi network. Please connect to the hotel WiFi and try again.', 403);
        }

        // Resolve propertyId
        const resolvedPropertyId = voucher.plan?.propertyId
          || await db.property.findFirst({ where: { tenantId: voucher.tenantId }, select: { id: true } }).then(p => p?.id);

        if (!resolvedPropertyId) {
          return errorResponse('NO_PROPERTY', 'No property configured. Please contact front desk.');
        }

        const wifiUsername = `voucher-${voucher.code.toLowerCase()}`;
        const validUntil = new Date(now.getTime() + portalSessionTimeoutMin * 60 * 1000);
        const downloadBps = bwDown * 1000000;
        const uploadBps = bwUp * 1000000;
        const dataLimitMb = voucher.plan?.dataLimit ?? undefined;

        await provisionOrResumeUser(wifiUsername, now, validUntil, {
          tenantId: voucher.tenantId,
          propertyId: resolvedPropertyId,
          guestId: voucher.guestId ?? undefined,
          bookingId: voucher.bookingId ?? undefined,
          username: wifiUsername,
          password: voucher.code,
          planId: voucher.planId ?? undefined,
          planName: voucher.plan?.name,
          downloadSpeed: downloadBps,
          uploadSpeed: uploadBps,
          sessionTimeoutMinutes: portalSessionTimeoutMin,
          idleTimeoutSeconds: portal?.idleTimeout,
          sessionLimit: voucher.plan?.maxDevices,
          dataLimit: dataLimitMb,
        });

        // Check concurrent session limit
        const maxSessions = voucher.plan?.maxDevices || 1;
        if (await isSessionLimitReached(wifiUsername, maxSessions)) {
          await logAuthAttempt(wifiUsername, 'Access-Reject', request, 'MAX_SESSIONS_REACHED');
          return errorResponse('MAX_SESSIONS_REACHED', 'Maximum concurrent sessions reached. Please disconnect another device first.');
        }

        const radiusResult = await radiusAuth(wifiUsername, voucher.code);
        if (!radiusResult.accepted) {
          await logAuthAttempt(wifiUsername, 'Access-Reject', request, radiusResult.rejectReason || 'AUTH_FAILED');
          return errorResponse(radiusResult.rejectReason || 'AUTH_FAILED', getRejectMessage(radiusResult.rejectReason || 'AUTH_FAILED'));
        }

        // Atomically mark voucher as used (prevents double-use race condition)
        const updatedVoucher = await db.wiFiVoucher.updateMany({
          where: { id: voucher.id, isUsed: false },
          data: { isUsed: true, usedAt: new Date(), status: 'used' },
        });
        if (updatedVoucher.count === 0) {
          return NextResponse.json({ success: false, error: 'Voucher already used' }, { status: 409 });
        }

        await logAuthAttempt(wifiUsername, 'Access-Accept', request, `pool:${pool.poolName}`);
        const sessionId = await createAccountingSession(wifiUsername, request, 'portal', effectiveMac, pool);

        // Activate nftables + TC bandwidth shaping
        await activateUserFirewall({
          username: wifiUsername, clientIp: getClientIpString(request),
          propertyId: resolvedPropertyId, sessionId,
          macAddress: effectiveMac,
          maxBandwidthDownBytes: portal?.maxBandwidthDown,
          maxBandwidthUpBytes: portal?.maxBandwidthUp,
          subnet: pool.subnet,
        });

        // Add per-IP byte counter rules for session engine tracking
        const voucherCounterIp = normalizeIp(getClientIpString(request));
        if (voucherCounterIp && voucherCounterIp !== '0.0.0.0') {
          addUserCounter(voucherCounterIp);
        }

        // ── Save device profile with real browser fingerprint ──
        try {
          const voucherUser = await db.wiFiUser.findUnique({ where: { username: wifiUsername }, select: { id: true, tenantId: true, propertyId: true, guestId: true } });
          if (voucherUser) {
            await upsertDeviceProfileWithFingerprint({ wifiUserId: voucherUser.id, tenantId: voucherUser.tenantId, propertyId: voucherUser.propertyId, guestId: voucherUser.guestId, username: wifiUsername, request, macAddress: effectiveMac, fingerprintHash, storageToken });
          }
        } catch { /* best effort */ }

        return successResponse({
          authenticated: true, method: 'voucher', username: wifiUsername,
          sessionTimeout: portalSessionTimeoutMin, bandwidthDown: bwDown, bandwidthUp: bwUp,
          poolName: pool.poolName, message: 'Connected successfully!',
        });
      }

      // ─── Room Number ──────────────────────────────────────
      // Unification: If a PMS-provisioned WiFiUser already exists for this
      // guest/booking, reuse it instead of creating a duplicate room-{number}
      // user. This gives the guest plan-level bandwidth, data limits, and
      // session timeout from their actual WiFi plan (not portal defaults).
      //
      // Lookup priority:
      //   1. WiFiUser where bookingId = match.id  (PMS auto-provisioned for this booking)
      //   2. WiFiUser where guestId = match.primaryGuestId AND status = 'active'
      //   3. Fallback: create room-{number} user (original behavior)
      case 'room_number': {
        if (!roomNumber?.trim()) {
          return errorResponse('MISSING_ROOM', 'Please enter your room number');
        }
        if (!lastName?.trim()) {
          return errorResponse('MISSING_NAME', 'Please enter your last name');
        }

        const bookings = await db.booking.findMany({
          where: { room: { roomNumber: roomNumber.trim().toUpperCase() }, status: 'in_house' },
          include: { primaryGuest: true, room: true, roomType: { select: { wifiPlanId: true } } },
          take: 10,
        });

        const match = bookings.find(
          (b) => b.primaryGuest.lastName.toLowerCase() === lastName.trim().toLowerCase()
        );

        if (!match) {
          await logAuthAttempt(`room-${roomNumber.trim().toLowerCase()}`, 'Access-Reject', request, 'INVALID_CREDENTIALS');
          return errorResponse('ROOM_NOT_FOUND', 'No active guest found for this room number and last name. Please verify and try again.');
        }

        // ── Credentials valid — now check IP pool ──
        // Resolve plan ipPoolId from room type's WiFi plan binding
        let roomPlanIpPoolId: string | null = null;
        if (match.roomType?.wifiPlanId) {
          const roomPlan = await db.wiFiPlan.findUnique({
            where: { id: match.roomType.wifiPlanId },
            select: { ipPoolId: true },
          });
          roomPlanIpPoolId = roomPlan?.ipPoolId ?? null;
        }

        const now = new Date();

        // ── Look for existing PMS-provisioned WiFiUser ──
        // Priority 1: Exact booking match (most precise — created at check-in)
        const existingByBooking = await db.wiFiUser.findFirst({
          where: { bookingId: match.id, status: { in: ['active', 'suspended'] } },
          include: { plan: { select: { ipPoolId: true, maxDevices: true, validityMinutes: true, validityDays: true, downloadSpeed: true, uploadSpeed: true, name: true } } },
        });

        // Priority 2: Same guest, active user (covers cases where bookingId wasn't set)
        const existingByGuest = !existingByBooking
          ? await db.wiFiUser.findFirst({
              where: { guestId: match.primaryGuestId, status: 'active', propertyId: match.propertyId },
              include: { plan: { select: { ipPoolId: true, maxDevices: true, validityMinutes: true, validityDays: true, downloadSpeed: true, uploadSpeed: true, name: true } } },
            })
          : null;

        const existingUser = existingByBooking || existingByGuest;
        const reuseExisting = !!existingUser;

        if (reuseExisting) {
          // ── Reuse existing PMS-provisioned user ──
          // This guest was auto-provisioned at check-in — use their plan attrs
          const pmsUser = existingUser!;

          if (pmsUser.status !== 'active') {
            await logAuthAttempt(pmsUser.username, 'Access-Reject', request, 'ACCOUNT_INACTIVE');
            return errorResponse('ACCOUNT_INACTIVE', 'Your WiFi account is not active. Please contact front desk.');
          }

          if (new Date(pmsUser.validUntil) < now) {
            await logAuthAttempt(pmsUser.username, 'Access-Reject', request, 'ACCOUNT_EXPIRED');
            return errorResponse('ACCOUNT_EXPIRED', 'Your WiFi session has expired. Please contact front desk to renew.');
          }

          const allowedPools = resolveAllowedPoolIds(pmsUser.plan?.ipPoolId || roomPlanIpPoolId, pmsUser.ipPoolId);
          const pool = await getValidatedPool(request, allowedPools);
          if (!pool) {
            await logAuthAttempt(pmsUser.username, 'Access-Reject', request, `IP_NOT_IN_POOL:${getClientIpString(request)}`);
            return errorResponse('IP_NOT_IN_POOL', 'Your device is not connected to a managed WiFi network. Please connect to the hotel WiFi and try again.', 403);
          }

          // Ensure RADIUS credentials exist (may have been deleted between sessions)
          const existingCheck = await db.radCheck.findFirst({ where: { username: pmsUser.username } });
          if (!existingCheck) {
            try { await wifiUserService.resumeUser(pmsUser.id); } catch { /* best effort */ }
          }

          // Check concurrent session limit
          const pmsMaxSessions = pmsUser.maxSessions || pmsUser.plan?.maxDevices || 1;
          if (await isSessionLimitReached(pmsUser.username, pmsMaxSessions)) {
            await logAuthAttempt(pmsUser.username, 'Access-Reject', request, 'MAX_SESSIONS_REACHED');
            return errorResponse('MAX_SESSIONS_REACHED', 'Maximum concurrent sessions reached. Please disconnect another device first.');
          }

          const radiusResult = await radiusAuth(pmsUser.username, pmsUser.password);
          if (!radiusResult.accepted) {
            await logAuthAttempt(pmsUser.username, 'Access-Reject', request, radiusResult.rejectReason || 'AUTH_FAILED');
            return errorResponse(radiusResult.rejectReason || 'AUTH_FAILED', getRejectMessage(radiusResult.rejectReason || 'AUTH_FAILED'));
          }

          // ── Calculate remaining validity (NEVER reset validUntil) ──
          const planValidityMin = pmsUser.plan?.validityMinutes
            || (pmsUser.plan?.validityDays ? pmsUser.plan.validityDays * 1440 : null)
            || portalSessionTimeoutMin;
          const remainingMs = new Date(pmsUser.validUntil).getTime() - now.getTime();
          const remainingMinutes = Math.max(0, Math.ceil(remainingMs / 60000));
          const remainingSeconds = Math.max(0, Math.floor(remainingMs / 1000));

          // Cap RADIUS Session-Timeout to remaining validity
          const cappedSessionTimeoutSec = Math.min(planValidityMin * 60, remainingSeconds);
          await db.radReply.deleteMany({ where: { username: pmsUser.username, attribute: 'Session-Timeout' } });
          await db.radReply.create({
            data: {
              wifiUserId: pmsUser.id, username: pmsUser.username,
              attribute: 'Session-Timeout', op: ':=',
              value: String(cappedSessionTimeoutSec), isActive: true,
            },
          });

          // Update last activity timestamp
          await db.wiFiUser.update({ where: { id: pmsUser.id }, data: { validFrom: now } });

          // Read bandwidth from radreply (user-level overrides > group-level)
          const pmsRadreply = await db.radReply.findMany({ where: { username: pmsUser.username } });
          const getRadReplyVal = (attr: string): string | undefined =>
            pmsRadreply.find(r => r.attribute === attr)?.value;
          const pmsBwDownBps = getRadReplyVal('WISPr-Bandwidth-Max-Down') || getRadReplyVal('Cryptsk-Bandwidth-Max-Down');
          const pmsBwUpBps = getRadReplyVal('WISPr-Bandwidth-Max-Up') || getRadReplyVal('Cryptsk-Bandwidth-Max-Up');
          const pmsBwDown = pmsBwDownBps ? Math.round(Number(pmsBwDownBps) / 1000000) : (pmsUser.plan?.downloadSpeed || bwDown);
          const pmsBwUp = pmsBwUpBps ? Math.round(Number(pmsBwUpBps) / 1000000) : (pmsUser.plan?.uploadSpeed || bwUp);

          await logAuthAttempt(pmsUser.username, 'Access-Accept', request, `pool:${pool.poolName} reuse:pms plan:${pmsUser.plan?.name || 'none'}`);
          const sessionId = await createAccountingSession(pmsUser.username, request, 'portal', effectiveMac, pool);

          await activateUserFirewall({
            username: pmsUser.username, clientIp: getClientIpString(request),
            propertyId: match.propertyId, sessionId,
            macAddress: effectiveMac, userId: pmsUser.id,
            maxBandwidthDownBytes: pmsBwDownBps ? Number(pmsBwDownBps) : portal?.maxBandwidthDown,
            maxBandwidthUpBytes: pmsBwUpBps ? Number(pmsBwUpBps) : portal?.maxBandwidthUp,
            subnet: pool.subnet,
          });

          const pmsCounterIp = normalizeIp(getClientIpString(request));
          if (pmsCounterIp && pmsCounterIp !== '0.0.0.0') {
            addUserCounter(pmsCounterIp);
          }

          // ── Save device profile with real browser fingerprint ──
          await upsertDeviceProfileWithFingerprint({
            wifiUserId: pmsUser.id, tenantId: pmsUser.tenantId,
            propertyId: pmsUser.propertyId, guestId: pmsUser.guestId,
            username: pmsUser.username, request,
            macAddress: effectiveMac, fingerprintHash, storageToken,
          });

          return successResponse({
            authenticated: true, method: 'room_number', username: pmsUser.username,
            sessionTimeout: planValidityMin, remainingMinutes,
            bandwidthDown: pmsBwDown, bandwidthUp: pmsBwUp,
            poolName: pool.poolName, planName: pmsUser.plan?.name || null,
            message: 'Connected successfully!',
          });
        }

        // ── No PMS user found — fallback: create room-{number} user ──
        console.log(`[Room Auth] No PMS user found for booking ${match.id} / guest ${match.primaryGuestId} — falling back to room-${match.room?.roomNumber?.toLowerCase() || roomNumber.trim().toLowerCase()}`);

        const pool = await getValidatedPool(request, resolveAllowedPoolIds(roomPlanIpPoolId));
        if (!pool) {
          await logAuthAttempt(`room-${roomNumber.trim().toLowerCase()}`, 'Access-Reject', request, `IP_NOT_IN_POOL:${getClientIpString(request)}`);
          return errorResponse('IP_NOT_IN_POOL', 'Your device is not connected to a managed WiFi network. Please connect to the hotel WiFi and try again.', 403);
        }

        const validUntil = new Date(now.getTime() + portalSessionTimeoutMin * 60 * 1000);
        const wifiUsername = `room-${match.room?.roomNumber?.toLowerCase() || roomNumber.trim().toLowerCase()}`;
        const userPassword = `${match.primaryGuest.lastName.toLowerCase()}-${match.id.slice(0, 8)}`;
        const downloadBps = bwDown * 1000000;
        const uploadBps = bwUp * 1000000;

        await provisionOrResumeUser(wifiUsername, now, validUntil, {
          tenantId: match.tenantId,
          propertyId: match.propertyId,
          guestId: match.primaryGuestId,
          bookingId: match.id,
          username: wifiUsername,
          password: userPassword,
          downloadSpeed: downloadBps,
          uploadSpeed: uploadBps,
          sessionTimeoutMinutes: portalSessionTimeoutMin,
          idleTimeoutSeconds: portal?.idleTimeout,
        });

        // Check concurrent session limit (default 1 for room users)
        const roomMaxSessions = match.roomType?.wifiPlanId
          ? (await db.wiFiPlan.findUnique({ where: { id: match.roomType.wifiPlanId }, select: { maxDevices: true } }))?.maxDevices ?? 1
          : 1;
        if (await isSessionLimitReached(wifiUsername, roomMaxSessions)) {
          await logAuthAttempt(wifiUsername, 'Access-Reject', request, 'MAX_SESSIONS_REACHED');
          return errorResponse('MAX_SESSIONS_REACHED', 'Maximum concurrent sessions reached. Please disconnect another device first.');
        }

        const radiusResult = await radiusAuth(wifiUsername, userPassword);
        if (!radiusResult.accepted) {
          await logAuthAttempt(wifiUsername, 'Access-Reject', request, radiusResult.rejectReason || 'AUTH_FAILED');
          return errorResponse(radiusResult.rejectReason || 'AUTH_FAILED', getRejectMessage(radiusResult.rejectReason || 'AUTH_FAILED'));
        }

        await logAuthAttempt(wifiUsername, 'Access-Accept', request, `pool:${pool.poolName} fallback:room_user`);
        const sessionId = await createAccountingSession(wifiUsername, request, 'portal', effectiveMac, pool);

        await activateUserFirewall({
          username: wifiUsername, clientIp: getClientIpString(request),
          propertyId: match.propertyId, sessionId,
          macAddress: effectiveMac,
          maxBandwidthDownBytes: portal?.maxBandwidthDown,
          maxBandwidthUpBytes: portal?.maxBandwidthUp,
          subnet: pool.subnet,
        });

        // Add per-IP byte counter rules for session engine tracking
        const roomCounterIp = normalizeIp(getClientIpString(request));
        if (roomCounterIp && roomCounterIp !== '0.0.0.0') {
          addUserCounter(roomCounterIp);
        }

        // ── Save device profile with real browser fingerprint ──
        try {
          const roomUser = await db.wiFiUser.findUnique({ where: { username: wifiUsername }, select: { id: true, tenantId: true, propertyId: true, guestId: true } });
          if (roomUser) {
            await upsertDeviceProfileWithFingerprint({ wifiUserId: roomUser.id, tenantId: roomUser.tenantId, propertyId: roomUser.propertyId, guestId: roomUser.guestId, username: wifiUsername, request, macAddress: effectiveMac, fingerprintHash, storageToken });
          }
        } catch { /* best effort */ }

        return successResponse({
          authenticated: true, method: 'room_number', username: wifiUsername,
          sessionTimeout: portalSessionTimeoutMin, bandwidthDown: bwDown, bandwidthUp: bwUp,
          poolName: pool.poolName, message: 'Connected successfully!',
        });
      }

      // ─── PMS Credentials ──────────────────────────────────
      case 'pms_credentials': {
        if (!username?.trim()) {
          return errorResponse('MISSING_USERNAME', 'Please enter your username');
        }
        if (!password?.trim()) {
          return errorResponse('MISSING_PASSWORD', 'Please enter your password');
        }

        const wifiUser = await db.wiFiUser.findUnique({
          where: { username: username.trim() },
          include: {
            plan: { select: { ipPoolId: true, maxDevices: true, validityMinutes: true } },
            ipPool: { select: { id: true } },
          },
        });

        if (!wifiUser) {
          await logAuthAttempt(username.trim(), 'Access-Reject', request, 'INVALID_CREDENTIALS');
          return errorResponse('INVALID_CREDENTIALS', 'Invalid username or password');
        }

        if (wifiUser.password !== password.trim()) {
          await logAuthAttempt(username.trim(), 'Access-Reject', request, 'INVALID_CREDENTIALS');
          return errorResponse('INVALID_CREDENTIALS', 'Invalid username or password');
        }

        if (wifiUser.status !== 'active') {
          await logAuthAttempt(username.trim(), 'Access-Reject', request, 'ACCOUNT_INACTIVE');
          return errorResponse('ACCOUNT_INACTIVE', 'Your WiFi account is not active. Please contact front desk.');
        }

        const now = new Date();
        if (wifiUser.validUntil < now) {
          await logAuthAttempt(username.trim(), 'Access-Reject', request, 'ACCOUNT_EXPIRED');
          return errorResponse('ACCOUNT_EXPIRED', 'Your WiFi session has expired. Please contact front desk to renew.');
        }

        // ── Credentials valid — now check IP pool ──
        const allowedPools = resolveAllowedPoolIds(wifiUser.plan?.ipPoolId, wifiUser.ipPoolId);
        const pool = await getValidatedPool(request, allowedPools);
        if (!pool) {
          await logAuthAttempt(username.trim(), 'Access-Reject', request, `IP_NOT_IN_POOL:${getClientIpString(request)}`);
          return errorResponse('IP_NOT_IN_POOL', 'Your device is not connected to a managed WiFi network. Please connect to the hotel WiFi and try again.', 403);
        }

        // Ensure RADIUS credentials exist
        const existingCheck = await db.radCheck.findFirst({
          where: { username: wifiUser.username },
        });
        if (!existingCheck) {
          try {
            await wifiUserService.resumeUser(wifiUser.id);
          } catch {
            // Best effort
          }
        }

        // Check concurrent session limit
        const pmsMaxSessions = wifiUser.maxSessions || wifiUser.plan?.maxDevices || 1;
        if (await isSessionLimitReached(username.trim(), pmsMaxSessions)) {
          await logAuthAttempt(username.trim(), 'Access-Reject', request, 'MAX_SESSIONS_REACHED');
          return errorResponse('MAX_SESSIONS_REACHED', 'Maximum concurrent sessions reached. Please disconnect another device first.');
        }

        const radiusResult = await radiusAuth(username.trim(), password.trim());
        if (!radiusResult.accepted) {
          await logAuthAttempt(username.trim(), 'Access-Reject', request, radiusResult.rejectReason || 'AUTH_FAILED');
          return errorResponse(radiusResult.rejectReason || 'AUTH_FAILED', getRejectMessage(radiusResult.rejectReason || 'AUTH_FAILED'));
        }

        await logAuthAttempt(username.trim(), 'Access-Accept', request, `pool:${pool.poolName}`);
        const sessionId = await createAccountingSession(username.trim(), request, 'portal', effectiveMac, pool);

        // ── Calculate plan validity for session timeout & display ──
        // validUntil is NOT reset here — it was set ONCE at user creation.
        // This ensures timed packages (e.g. 4-hr) give exactly that much total time.
        const planValidityMin = wifiUser.plan?.validityMinutes
          || (wifiUser.plan?.validityDays ? wifiUser.plan.validityDays * 1440 : null)
          || portalSessionTimeoutMin;

        // Calculate remaining time for display and Session-Timeout capping
        const remainingMs = wifiUser.validUntil
          ? new Date(wifiUser.validUntil).getTime() - now.getTime()
          : planValidityMin * 60 * 1000;
        const remainingMinutes = Math.max(0, Math.ceil(remainingMs / 60000));
        const remainingSeconds = Math.max(0, Math.floor(remainingMs / 1000));

        // ── Set validFrom to now (tracks last activity), but NEVER reset validUntil ──
        await db.wiFiUser.update({
          where: { id: wifiUser.id },
          data: { validFrom: now },
        });

        // ── Cap RADIUS Session-Timeout to remaining validity ──
        // Prevents RADIUS sessions that outlast the actual account validity.
        const cappedSessionTimeoutSec = Math.min(planValidityMin * 60, remainingSeconds);
        await db.radReply.deleteMany({
          where: { username: wifiUser.username, attribute: 'Session-Timeout' },
        });
        await db.radReply.create({
          data: {
            wifiUserId: wifiUser.id,
            username: wifiUser.username,
            attribute: 'Session-Timeout',
            op: ':=',
            value: String(cappedSessionTimeoutSec),
            isActive: true,
          },
        });

        // ── Read user's bandwidth from radreply ──
        const userRadreply = await db.radReply.findMany({
          where: { username: username.trim() },
        });
        const getRadReplyValue = (attr: string): string | undefined =>
          userRadreply.find(r => r.attribute === attr)?.value;

        const bwDownBps = getRadReplyValue('WISPr-Bandwidth-Max-Down')
          || getRadReplyValue('Cryptsk-Bandwidth-Max-Down');
        const bwUpBps = getRadReplyValue('WISPr-Bandwidth-Max-Up')
          || getRadReplyValue('Cryptsk-Bandwidth-Max-Up');
        const userBwDown = bwDownBps ? Math.round(Number(bwDownBps) / 1000000) : bwDown;
        const userBwUp = bwUpBps ? Math.round(Number(bwUpBps) / 1000000) : bwUp;

        await activateUserFirewall({
          username: username.trim(), clientIp: getClientIpString(request),
          propertyId: wifiUser.propertyId, sessionId,
          macAddress: effectiveMac, userId: wifiUser.id,
          maxBandwidthDownBytes: bwDownBps ? Number(bwDownBps) : portal?.maxBandwidthDown,
          maxBandwidthUpBytes: bwUpBps ? Number(bwUpBps) : portal?.maxBandwidthUp,
          subnet: pool.subnet,
        });

        // Add per-IP byte counter rules for session engine tracking
        const pmsCounterIp = normalizeIp(getClientIpString(request));
        if (pmsCounterIp && pmsCounterIp !== '0.0.0.0') {
          addUserCounter(pmsCounterIp);
        }

        // ── Save device profile with real browser fingerprint ──
        await upsertDeviceProfileWithFingerprint({
          wifiUserId: wifiUser.id,
          tenantId: wifiUser.tenantId,
          propertyId: wifiUser.propertyId,
          guestId: wifiUser.guestId,
          username: wifiUser.username,
          request,
          macAddress: effectiveMac,
          fingerprintHash,
          storageToken,
        });

        return successResponse({
          authenticated: true, method: 'pms_credentials', username: wifiUser.username,
          sessionTimeout: planValidityMin, remainingMinutes, bandwidthDown: userBwDown, bandwidthUp: userBwUp,
          poolName: pool.poolName, message: 'Connected successfully!',
        });
      }

      // ─── SMS OTP ──────────────────────────────────────────
      case 'sms_otp': {
        if (otpCode) {
          // ── Step 2: Verify OTP (credential check) ──
          if (!phoneNumber?.trim()) {
            return errorResponse('MISSING_PHONE', 'Phone number is required for OTP verification');
          }

          const normalizedPhone = phoneNumber.trim().replace(/\s+/g, '');
          const stored = otpStore.get(normalizedPhone);

          if (!stored) {
            return errorResponse('OTP_NOT_FOUND', 'No OTP found. Please request a new one.');
          }

          if (Date.now() > stored.expiresAt) {
            otpStore.delete(normalizedPhone);
            return errorResponse('OTP_EXPIRED', 'Your OTP has expired. Please request a new one.');
          }

          if (stored.code !== otpCode.trim()) {
            return errorResponse('OTP_INVALID', 'Invalid OTP code. Please try again.');
          }

          // ── OTP verified — check IP pool ──
          const pool = await getValidatedPool(request, resolveAllowedPoolIds(portalPlanIpPoolId));
          if (!pool) {
            await logAuthAttempt(`sms-${normalizedPhone.replace(/[^a-z0-9]/gi, '')}`, 'Access-Reject', request, `IP_NOT_IN_POOL:${getClientIpString(request)}`);
            return errorResponse('IP_NOT_IN_POOL', 'Your device is not connected to a managed WiFi network. Please connect to the hotel WiFi and try again.', 403);
          }

          otpStore.delete(normalizedPhone);

          const now = new Date();
          const validUntil = new Date(now.getTime() + portalSessionTimeoutMin * 60 * 1000);
          const wifiUsername = `sms-${normalizedPhone.replace(/[^a-z0-9]/gi, '')}`;
          const downloadBps = bwDown * 1000000;
          const uploadBps = bwUp * 1000000;

          const fallbackPropertyId = portal?.propertyId
            || await (portal?.tenantId
              ? db.property.findFirst({ where: { tenantId: portal.tenantId }, select: { id: true } }).then(p => p?.id)
              : Promise.resolve(undefined));

          if (fallbackPropertyId) {
            await provisionOrResumeUser(wifiUsername, now, validUntil, {
              tenantId: portal?.tenantId || '',
              propertyId: fallbackPropertyId,
              username: wifiUsername,
              password: stored.code,
              downloadSpeed: downloadBps,
              uploadSpeed: uploadBps,
              sessionTimeoutMinutes: portalSessionTimeoutMin,
              idleTimeoutSeconds: portal?.idleTimeout,
            });

            // Check concurrent session limit (SMS users get default 1)
            if (await isSessionLimitReached(wifiUsername, 1)) {
              await logAuthAttempt(wifiUsername, 'Access-Reject', request, 'MAX_SESSIONS_REACHED');
              return errorResponse('MAX_SESSIONS_REACHED', 'Maximum concurrent sessions reached. Please disconnect another device first.');
            }

            const radiusResult = await radiusAuth(wifiUsername, stored.code);
            if (!radiusResult.accepted) {
              await logAuthAttempt(wifiUsername, 'Access-Reject', request, radiusResult.rejectReason || 'AUTH_FAILED');
              return errorResponse(radiusResult.rejectReason || 'AUTH_FAILED', getRejectMessage(radiusResult.rejectReason || 'AUTH_FAILED'));
            }

            await logAuthAttempt(wifiUsername, 'Access-Accept', request, `pool:${pool.poolName}`);
            const sessionId = await createAccountingSession(wifiUsername, request, 'portal', effectiveMac, pool);

            await activateUserFirewall({
              username: wifiUsername, clientIp: getClientIpString(request),
              propertyId: fallbackPropertyId, sessionId,
              macAddress: effectiveMac,
              maxBandwidthDownBytes: portal?.maxBandwidthDown,
              maxBandwidthUpBytes: portal?.maxBandwidthUp,
              subnet: pool.subnet,
            });

            // Add per-IP byte counter rules for session engine tracking
            const smsCounterIp = normalizeIp(getClientIpString(request));
            if (smsCounterIp && smsCounterIp !== '0.0.0.0') {
              addUserCounter(smsCounterIp);
            }
          }

          return successResponse({
            authenticated: true, method: 'sms_otp', username: wifiUsername,
            sessionTimeout: portalSessionTimeoutMin, bandwidthDown: bwDown, bandwidthUp: bwUp,
            poolName: pool.poolName, message: 'Connected successfully!',
          });
        } else {
          // ── Step 1: Send OTP (no credential check needed) ──
          if (!phoneNumber?.trim()) {
            return errorResponse('MISSING_PHONE', 'Please enter your phone number');
          }

          const normalizedPhone = phoneNumber.trim().replace(/\s+/g, '');
          const code = generateOtp();

          otpStore.set(normalizedPhone, {
            code,
            expiresAt: Date.now() + 5 * 60 * 1000,
            phone: normalizedPhone,
          });

          console.log(`[SMS OTP] Code for ${normalizedPhone}: ${code.slice(0, 2)}**** (expires in 5 min)`);

          return NextResponse.json({
            success: true,
            data: {
              otpSent: true,
              message: 'OTP sent to your phone',
              ...(process.env.NODE_ENV === 'development' && { _debugOtp: code }),
            },
          });
        }
      }

      // ─── Open Access ──────────────────────────────────────
      // No credential validation needed — only IP pool check
      case 'open_access': {
        const pool = await getValidatedPool(request, resolveAllowedPoolIds(portalPlanIpPoolId));
        if (!pool) {
          await logAuthAttempt('open-access', 'Access-Reject', request, `IP_NOT_IN_POOL:${getClientIpString(request)}`);
          return errorResponse('IP_NOT_IN_POOL', 'Your device is not connected to a managed WiFi network. Please connect to the hotel WiFi and try again.', 403);
        }

        const now = new Date();
        const validUntil = new Date(now.getTime() + portalSessionTimeoutMin * 60 * 1000);
        let wifiUsername: string | null = null;

        if (portal) {
          const openTimestamp = Date.now();
          wifiUsername = `open-${openTimestamp}`;
          const openPassword = `open-${openTimestamp}`;
          const downloadBps = bwDown * 1000000;
          const uploadBps = bwUp * 1000000;

          try {
            const resolvedPropertyId = portal.propertyId
              || await db.property.findFirst({ where: { tenantId: portal.tenantId }, select: { id: true } }).then(p => p?.id);

            if (resolvedPropertyId) {
              await wifiUserService.provisionUser({
                tenantId: portal.tenantId,
                propertyId: resolvedPropertyId,
                username: wifiUsername,
                password: openPassword,
                validFrom: now,
                validUntil,
                userType: 'guest',
                downloadSpeed: downloadBps,
                uploadSpeed: uploadBps,
                sessionTimeoutMinutes: portalSessionTimeoutMin,
                idleTimeoutSeconds: portal?.idleTimeout,
              });

              // Check concurrent session limit (open access users get default 1)
              if (await isSessionLimitReached(wifiUsername, 1)) {
                await logAuthAttempt(wifiUsername, 'Access-Reject', request, 'MAX_SESSIONS_REACHED');
                return errorResponse('MAX_SESSIONS_REACHED', 'Maximum concurrent sessions reached. Please disconnect another device first.');
              }

              const radiusResult = await radiusAuth(wifiUsername, openPassword);
              if (!radiusResult.accepted) {
                await logAuthAttempt(wifiUsername, 'Access-Reject', request, radiusResult.rejectReason || 'AUTH_FAILED');
                return errorResponse(radiusResult.rejectReason || 'AUTH_FAILED', getRejectMessage(radiusResult.rejectReason || 'AUTH_FAILED'));
              }

              await logAuthAttempt(wifiUsername, 'Access-Accept', request, `pool:${pool.poolName}`);
              const sessionId = await createAccountingSession(wifiUsername, request, 'portal', effectiveMac, pool);

              await activateUserFirewall({
                username: wifiUsername, clientIp: getClientIpString(request),
                propertyId: resolvedPropertyId, sessionId,
                macAddress: effectiveMac,
                maxBandwidthDownBytes: portal?.maxBandwidthDown,
                maxBandwidthUpBytes: portal?.maxBandwidthUp,
                subnet: pool.subnet,
              });

              // Add per-IP byte counter rules for session engine tracking
              const openCounterIp = normalizeIp(getClientIpString(request));
              if (openCounterIp && openCounterIp !== '0.0.0.0') {
                addUserCounter(openCounterIp);
              }
            }
          } catch {
            // Best effort for open access
          }
        }

        return successResponse({
          authenticated: true, method: 'open_access', username: wifiUsername,
          sessionTimeout: portalSessionTimeoutMin, bandwidthDown: bwDown, bandwidthUp: bwUp,
          poolName: pool.poolName, message: 'Connected successfully!',
        });
      }

      default: {
        return errorResponse('INVALID_METHOD', 'Unsupported authentication method');
      }
    }
  } catch (error) {
    console.error('[Guest Auth API] Error:', error);
    return errorResponse('INTERNAL_ERROR', 'An unexpected error occurred. Please try again or contact front desk.');
  }
}

// ────────────────────────────────────────────────────────────
// Helpers
// ────────────────────────────────────────────────────────────

function successResponse(data: Record<string, unknown>) {
  return NextResponse.json({ success: true, data });
}

function errorResponse(code: string, message: string, status = 400) {
  return NextResponse.json(
    { success: false, error: { code, message } },
    { status }
  );
}

/**
 * Validate client IP and check it belongs to an allocated pool.
 * Called AFTER credential validation, BEFORE RADIUS auth.
 * Returns the matched pool or null.
 *
 * @param request - Next.js request object
 * @param allowedPoolIds - Optional list of pool IDs the user is allowed to use.
 *   Derived from WiFiPlan.ipPoolId or WiFiUser.ipPoolId.
 *   If provided and non-empty, the client IP must belong to one of these pools.
 *   If null/empty, any captive portal pool is allowed (backward compatible).
 */
async function getValidatedPool(request: NextRequest, allowedPoolIds?: string[] | null): Promise<MatchedPool | null> {
  const rawIp = extractClientIp(request);
  const clientIp = normalizeIp(rawIp);

  if (!clientIp) {
    console.warn('[Guest Auth] IP pool check: cannot determine client IP');
    return null;
  }

  const pool = await validateClientIpInPool(clientIp, allowedPoolIds);
  if (!pool) {
    if (allowedPoolIds && allowedPoolIds.length > 0) {
      console.warn(`[Guest Auth] IP pool check REJECTED: ${clientIp} is not in any allowed pool (allowed: [${allowedPoolIds.join(', ')}])`);
    } else {
      console.warn(`[Guest Auth] IP pool check REJECTED: ${clientIp} is not in any allocated IP pool`);
    }
    return null;
  }

  console.log(`[Guest Auth] IP pool check PASSED: ${clientIp} → pool "${pool.poolName}" (${pool.subnet || 'no subnet'})${allowedPoolIds?.length ? ' [plan-restricted]' : ''}`);
  return pool;
}

/**
 * Provision a RADIUS user, or resume an existing one if provisioning fails.
 * Reduces code duplication across auth methods.
 */
async function provisionOrResumeUser(
  wifiUsername: string,
  now: Date,
  validUntil: Date,
  params: {
    tenantId: string;
    propertyId: string;
    guestId?: string;
    bookingId?: string;
    username: string;
    password: string;
    planId?: string;
    planName?: string;
    downloadSpeed: number;
    uploadSpeed: number;
    sessionTimeoutMinutes: number;
    idleTimeoutSeconds?: number;
    sessionLimit?: number;
    dataLimit?: number;
  }
) {
  try {
    await wifiUserService.provisionUser({ ...params, validFrom: now, validUntil });
  } catch (provisionErr) {
    console.error('[Guest Auth] RADIUS provisioning failed:', provisionErr);
    try {
      const existingUser = await db.wiFiUser.findUnique({ where: { username: wifiUsername } });
      if (existingUser) {
        await db.wiFiUser.update({
          where: { id: existingUser.id },
          data: {
            status: 'active',
            validFrom: now,
            validUntil,
            radiusSynced: true,
            radiusSyncedAt: now,
          },
        });
      }
    } catch {
      // Best effort
    }
  }
}

/**
 * Write an auth log to RadPostAuth table.
 * This feeds the v_auth_logs view → Auth Logs dashboard tab.
 *
 * IMPORTANT: We populate BOTH clientipaddress AND "nasIpAddress" columns.
 * - clientipaddress: the real client IP (from HTTP headers) — used by v_auth_logs
 *   to show "Source IP" in reject messages and the source_ip_address column.
 * - "nasIpAddress": also set to the client IP so the view's nas_ip_address column
 *   is populated even for application-level rejects (not just RADIUS rejects).
 * - pass: stores the rejection reason code (e.g., IP_NOT_IN_POOL:1.2.3.4,
 *   INVALID_CREDENTIALS, ACCOUNT_EXPIRED) so v_auth_logs can build descriptive
 *   reply_message strings.
 */
async function logAuthAttempt(
  username: string,
  reply: string,
  request: NextRequest,
  extraInfo?: string
) {
  try {
    const clientIp = request.headers.get('x-forwarded-for')?.split(',')[0]?.trim()
      || request.headers.get('x-real-ip')
      || '';

    // clientipaddress = real client IP (from HTTP headers)
    // "nasIpAddress" = 127.0.0.1 for captive portal (the app itself IS the NAS)
    await db.$executeRawUnsafe(
      `INSERT INTO radpostauth (username, pass, reply, authdate, clientipaddress, "nasIpAddress")
       VALUES ($1, $2, $3, NOW(), $4, '127.0.0.1')`,
      username,
      extraInfo || '',
      reply,
      clientIp,
    );
  } catch (err) {
    // Non-fatal — auth logging failure should not block authentication
    console.error('[Guest Auth] Failed to write auth log:', err);
  }
}

/**
 * Create an accounting session in RadAcct table.
 * This feeds the v_active_sessions view → Active Users dashboard tab.
 *
 * The session is marked as 'start' with no stop time (acctstoptime = NULL),
 * which is how FreeRADIUS represents an active session.
 *
 * @param loginType - 'portal' for manual login, 'auto_reauth' for silent re-auth
 */
async function createAccountingSession(
  username: string,
  request: NextRequest,
  loginType: string = 'portal',
  macAddress?: string,
  pool?: MatchedPool | null
): Promise<string> {
  try {
    const clientIp = request.headers.get('x-forwarded-for')?.split(',')[0]?.trim()
      || request.headers.get('x-real-ip')
      || '0.0.0.0';

    const now = new Date();
    const acctSessionId = `${Date.now()}-${randomUUID().slice(0, 8)}`;
    const acctUniqueId = randomUUID();

    // Normalize MAC address format: strip separators, uppercase
    const normalizedMac = macAddress
      ? macAddress.replace(/[:\-\.\s]/g, '').toUpperCase()
      : null;
    // Reformat as AA:BB:CC:DD:EE:FF for RADIUS compatibility
    const formattedMac = normalizedMac && normalizedMac.length === 12
      ? normalizedMac.match(/.{2}/g)?.join(':') || null
      : null;

    // Build connect-info with pool details for audit trail
    const connectInfoStart = pool
      ? `pool_id=${pool.poolId}|pool_name=${pool.poolName}|subnet=${pool.subnet || 'none'}|gateway=${pool.gateway || 'none'}`
      : '';

    await db.$executeRawUnsafe(
      `INSERT INTO radacct (
         acctuniqueid, acctsessionid, username,
         nasipaddress, nasporttype, acctstarttime, acctupdatetime,
         acctauthentic, framedipaddress, acctstatus,
         acctinputoctets, acctoutputoctets, acctsessiontime,
         calledstationid, callingstationid,
         "loginType", connectinfo_start, "createdAt", "updatedAt"
       ) VALUES (
         $1, $2, $3,
         $4, 'Wireless-802.11', $5, $5,
         'PAP', $6, 'start',
         0, 0, 0,
         '00:00:00:00:00:01', $8,
         $7, $9, NOW(), NOW()
       )`,
      acctUniqueId,
      acctSessionId,
      username,
      '127.0.0.1', // NAS IP (this device is the gateway)
      now,
      clientIp,
      loginType,
      formattedMac,
      connectInfoStart
    );

    // Return the session ID so it can be passed to the login script
    return acctSessionId;
  } catch (err) {
    // Non-fatal — accounting failure should not block authentication
    console.error('[Guest Auth] Failed to create accounting session:', err);
    return '';
  }
}
