import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { wifiUserService } from '@/lib/wifi/services/wifi-user-service';
import { sendSMSNow } from '@/lib/services/sms-service';
import { normalizePhoneNumber } from '@/lib/adapters/sms';
import { randomUUID, randomInt, createHash } from 'crypto';
import { radiusAuth, getRejectMessage } from '@/lib/wifi/utils/radius-auth';
import { addUserCounter } from '@/lib/wifi/utils/nftables-counters';
import {
  runLoginScript,
  generateClassIds,
  lookupBandwidthPool,
  type LoginScriptParams,
} from '@/lib/network/script-runner';

// ────────────────────────────────────────────────────────────
// Device Info Helpers
// ────────────────────────────────────────────────────────────

function parseDeviceTypeFromUA(ua: string): string {
  if (/iPhone/i.test(ua)) return 'mobile';
  if (/iPad/i.test(ua) || (/Macintosh/i.test(ua) && /WebKit/i.test(ua) && !/Safari/i.test(ua))) return 'tablet';
  if (/Android/i.test(ua)) return /Mobile/i.test(ua) ? 'mobile' : 'tablet';
  if (/SmartTV|InternetTV|APPLETV/i.test(ua)) return 'tv';
  if (/Windows|Macintosh|Linux|CrOS/i.test(ua)) return 'desktop';
  return 'unknown';
}

function parseDeviceNameFromUA(ua: string): string {
  if (/iPhone/i.test(ua)) return 'iPhone';
  if (/iPad/i.test(ua)) return 'iPad';
  if (/Android/i.test(ua)) return /Mobile/i.test(ua) ? 'Android Phone' : 'Android Tablet';
  if (/Windows/i.test(ua)) return 'Windows PC';
  if (/Macintosh/i.test(ua)) return 'Mac';
  if (/CrOS/i.test(ua)) return 'Chromebook';
  if (/Linux/i.test(ua)) return 'Linux PC';
  if (/SmartTV/i.test(ua)) return 'Smart TV';
  return 'Unknown Device';
}

/**
 * Generate a synthetic fingerprint hash from a MAC address.
 * Used when the browser's crypto.subtle is unavailable (e.g. HTTP connections)
 * so that the DeviceProfile can still be created with MAC-based tracking.
 *
 * The prefix "syn-mac:" ensures these never collide with real browser fingerprints
 * generated by device-fingerprint.ts (which uses SHA-256 of Canvas/WebGL signals).
 */
function syntheticFingerprintFromMac(mac: string): string {
  const normalized = mac.replace(/[:\-\.\s]/g, '').toUpperCase();
  return createHash('sha256')
    .update(`syn-mac:${normalized}`)
    .digest('hex');
}

/**
 * Create or update a DeviceProfile entry.
 *
 * Priority:
 * 1. Real browser fingerprintHash (from device-fingerprint.ts) — preferred for auto-reauth
 * 2. MAC-based synthetic fingerprint — fallback when crypto.subtle unavailable (HTTP)
 * 3. No profile created if neither is available (deferred to auto-auth fire-and-forget)
 */
async function upsertDeviceProfileWithFingerprint(params: {
  wifiUserId: string;
  tenantId: string;
  propertyId: string;
  guestId?: string | null;
  username: string;
  request: NextRequest;
  macAddress?: string | null;
  fingerprintHash?: string | null;
  storageToken?: string | null;
}) {
  const { wifiUserId, tenantId, propertyId, guestId, username, request, macAddress, fingerprintHash, storageToken } = params;

  // Normalize MAC address format
  const normalizedMac = macAddress
    ? macAddress.replace(/[:\-\.\s]/g, '').toUpperCase()
    : null;
  const formattedMac = normalizedMac && normalizedMac.length === 12
    ? normalizedMac.match(/.{2}/g)?.join(':') || null
    : null;

  // Determine fingerprint: prefer real browser fingerprint, fall back to MAC-based synthetic
  let effectiveFingerprint = fingerprintHash;
  let isSynthetic = false;
  if (!effectiveFingerprint && formattedMac) {
    effectiveFingerprint = syntheticFingerprintFromMac(formattedMac);
    isSynthetic = true;
  }

  if (!effectiveFingerprint) {
    console.log(`[Auth] No client fingerprint or MAC address — skipping DeviceProfile creation (deferred to auto-auth) [fp=${fingerprintHash || 'null'} mac=${macAddress || 'null'}]`);
    return;
  }

  console.log(`[Auth] DeviceProfile upsert for ${username}: fp=${effectiveFingerprint ? effectiveFingerprint.substring(0, 16) + '...' : 'none'} mac=${formattedMac || 'none'} synthetic=${isSynthetic}`);

  try {
    const clientIp = request.headers.get('x-forwarded-for')?.split(',')[0]?.trim()
      || request.headers.get('x-real-ip')
      || 'unknown';
    const userAgent = request.headers.get('user-agent') || '';
    const deviceType = parseDeviceTypeFromUA(userAgent);
    const deviceName = parseDeviceNameFromUA(userAgent);

    // Upsert by (fingerprintHash, propertyId) unique constraint
    await db.deviceProfile.upsert({
      where: {
        fingerprintHash_propertyId: {
          fingerprintHash: effectiveFingerprint,
          propertyId,
        },
      },
      create: {
        tenantId,
        propertyId,
        wifiUserId,
        guestId: guestId || undefined,
        fingerprintHash: effectiveFingerprint,
        storageToken: storageToken || undefined,
        ipAddress: clientIp,
        userAgent: userAgent.substring(0, 500),
        macAddress: formattedMac || undefined,
        deviceType,
        deviceName,
        authCount: 1,
        lastAuthAt: new Date(),
        lastSeenAt: new Date(),
        isActive: true,
      },
      update: {
        // If upgrading from synthetic → real fingerprint, keep the real one
        ...(fingerprintHash && isSynthetic === false ? { fingerprintHash } : {}),
        wifiUserId,
        guestId: guestId || undefined,
        storageToken: storageToken || undefined,
        ipAddress: clientIp,
        userAgent: userAgent.substring(0, 500),
        ...(formattedMac ? { macAddress: formattedMac } : {}),
        deviceType,
        deviceName,
        isActive: true,
        authCount: { increment: 1 },
        lastAuthAt: new Date(),
        lastSeenAt: new Date(),
      },
    });

    if (isSynthetic) {
      console.log(`[Auth] DeviceProfile upserted for ${username} (synthetic-fingerprint from MAC: ${formattedMac})`);
    } else {
      console.log(`[Auth] DeviceProfile upserted for ${username} (fingerprint: ${fingerprintHash!.substring(0, 12)}...)`);
    }
  } catch (err) {
    console.warn('[Auth] DeviceProfile upsert failed (non-critical):', err instanceof Error ? err.message : err);
  }
}

// ────────────────────────────────────────────────────────────
// In-memory OTP store (sandbox — use Redis in production)
// ────────────────────────────────────────────────────────────
const otpStore = new Map<
  string,
  { code: string; expiresAt: number; phone: string; attempts: number }
>();

if (process.env.NODE_ENV === 'production') {
  console.warn('[OTP] In-memory OTP store used in production — migrate to Redis for multi-instance support');
}

function generateOtp(): string {
  return randomInt(100000, 999999).toString();
}

// ────────────────────────────────────────────────────────────
// OTP Rate Limiter (per-phone, prevents SMS spam / OTP bombing)
// ────────────────────────────────────────────────────────────
const otpRateLimits = new Map<string, { count: number; resetAt: number }>();

const OTP_MAX_REQUESTS = 5;   // max OTP sends per phone per window
const OTP_WINDOW_MS = 15 * 60 * 1000; // 15 minute window
const OTP_MAX_VERIFY_ATTEMPTS = 5; // max wrong OTP tries before invalidation

function checkOtpRateLimit(phone: string): { allowed: boolean; retryAfterSec: number } {
  const now = Date.now();
  const entry = otpRateLimits.get(phone);
  if (!entry || now > entry.resetAt) {
    otpRateLimits.set(phone, { count: 1, resetAt: now + OTP_WINDOW_MS });
    return { allowed: true, retryAfterSec: 0 };
  }
  entry.count++;
  if (entry.count > OTP_MAX_REQUESTS) {
    const retryAfterSec = Math.ceil((entry.resetAt - now) / 1000);
    return { allowed: false, retryAfterSec };
  }
  return { allowed: true, retryAfterSec: 0 };
}

// ────────────────────────────────────────────────────────────
// Phone Number Validation
// ────────────────────────────────────────────────────────────
function isValidPhoneNumber(phone: string): boolean {
  const digits = phone.replace(/\D/g, '');
  return digits.length >= 10 && digits.length <= 15;
}

function normalizePhoneNumberLocal(phone: string): string {
  // Use the shared normalizer with configurable default country code
  return normalizePhoneNumber(phone, process.env.SMS_DEFAULT_COUNTRY_CODE || process.env.DEFAULT_COUNTRY_CODE || undefined);
}

// ────────────────────────────────────────────────────────────
// IP Pool Validation Helpers
// ────────────────────────────────────────────────────────────

interface MatchedPool {
  poolId: string;
  poolName: string;
  subnet: string | null;
  gateway: string | null;
  captivePortal: boolean;
  isDefault: boolean;
}

/** Extract client IP from request headers (same logic as resolve-zone) */
function extractClientIp(request: NextRequest): string | null {
  const xff = request.headers.get('x-forwarded-for');
  if (xff) {
    const firstIp = xff.split(',')[0].trim();
    if (firstIp) return firstIp;
  }
  const xRealIp = request.headers.get('x-real-ip');
  if (xRealIp) return xRealIp.trim();
  return null;
}

/** Strip IPv6-mapped prefix and normalize to plain IPv4 */
function normalizeIp(raw: string | null): string | null {
  if (!raw) return null;
  let ip = raw.trim();
  if (ip.startsWith('[') && ip.includes(']')) {
    ip = ip.slice(1, ip.indexOf(']'));
  }
  const v4Match = ip.match(/^::ffff:(\d+\.\d+\.\d+\.\d+)$/i);
  if (v4Match) return v4Match[1];
  if (/^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$/.test(ip)) return ip;
  return null;
}

/**
 * Validate that the client IP belongs to an allocated IP pool.
 * Uses PostgreSQL inet range comparison for accurate matching.
 * Returns the matched pool info or null if no pool found.
 *
 * Conditions checked:
 * 1. IP must fall within an IpPoolRange (startIp–endIp)
 * 2. The pool must be enabled
 * 3. The pool must have captivePortal = true (managed network)
 * 4. If allowedPoolIds is provided, the matched pool must be in that list
 *    (enforces plan→pool binding so users can't login from wrong VLANs)
 */
async function validateClientIpInPool(
  clientIp: string,
  allowedPoolIds?: string[] | 'ANY' | null
): Promise<MatchedPool | null> {
  try {
    // Build pool restriction clause when plan is bound to specific pools
    const poolFilter = (Array.isArray(allowedPoolIds) && allowedPoolIds.length > 0)
      ? `AND ip.id = ANY($2::uuid[])`
      : '';

    const params: unknown[] = [clientIp];
    if (Array.isArray(allowedPoolIds) && allowedPoolIds.length > 0) {
      params.push(allowedPoolIds);
    }

    const result = await db.$queryRawUnsafe<Array<{
      id: string;
      name: string;
      subnet: string | null;
      gateway: string | null;
      captivePortal: boolean;
      "isDefault": boolean;
    }>>(`
      SELECT DISTINCT ON (ip.id)
        ip.id, ip.name, ip.subnet::text as subnet, ip.gateway::text as gateway,
        ip."captivePortal", ip."isDefault"
      FROM "IpPoolRange" r
      JOIN "IpPool" ip ON ip.id = r."poolId"
      WHERE $1::inet BETWEEN r."startIp" AND r."endIp"
        AND ip.enabled = true
        ${poolFilter}
      ORDER BY ip.id, ip."isDefault" DESC
      LIMIT 1
    `, ...params);

    if (result.length === 0) return null;

    const pool = result[0];
    return {
      poolId: pool.id,
      poolName: pool.name,
      subnet: pool.subnet,
      gateway: pool.gateway,
      captivePortal: pool.captivePortal,
      isDefault: pool.isDefault,
    };
  } catch (err) {
    console.error('[IP Pool Validation] Query failed:', err);
    return null;
  }
}

/** Get client IP string for logging/accounting */
function getClientIpString(request: NextRequest): string {
  return extractClientIp(request) || request.headers.get('x-real-ip') || '0.0.0.0';
}

/**
 * Resolve allowed IP pool IDs for a user based on their plan binding.
 *
 * Priority:
 * 1. WiFiUser.ipPoolId — user-level override → restrict to that pool only
 * 2. WiFiPlan.ipPoolId — plan default → restrict to that pool only
 * 3. Plan exists but has NO pool → check ALL pools (any pool is OK)
 * 4. No plan at all → don't check, allow any IP
 *
 * Returns:
 *   - string[] — specific pool IDs the user is restricted to
 *   - 'ANY' — check all pools, reject if not found in any
 *   - null — no restriction at all (no plan)
 */
function resolveAllowedPoolIds(
  planIpPoolId?: string | null,
  userIpPoolId?: string | null,
  hasPlan?: boolean,
): string[] | 'ANY' | null {
  // User-level override takes priority over plan-level
  if (userIpPoolId) return [userIpPoolId];
  if (planIpPoolId) return [planIpPoolId];
  // Plan exists but has no pool → check all pools
  if (hasPlan) return 'ANY';
  // No plan at all → no restriction
  return null;
}

/**
 * Check if a user has reached their concurrent session limit.
 * Counts active (non-stopped) radacct sessions for the username.
 * Returns true if the limit is reached (should reject login).
 */
async function isSessionLimitReached(username: string, maxSessions: number): Promise<boolean> {
  if (maxSessions <= 0) return false; // 0 or negative = unlimited

  try {
    // Only count real active sessions — exclude interim-update audit rows
    // which have acctstoptime IS NULL but are NOT actual user sessions.
    // Also exclude any rows with acctterminatecause set (already closed).
    const result = await db.$queryRawUnsafe<Array<{ count: bigint }>>(`
      SELECT COUNT(*)::bigint as count
      FROM radacct
      WHERE username = $1
        AND acctstoptime IS NULL
        AND (acctstatus IS NULL OR acctstatus = '' OR acctstatus = 'start')
        AND acctterminatecause IS NULL
    `, username);

    const activeCount = Number(result[0]?.count ?? 0);
    return activeCount >= maxSessions;
  } catch (err) {
    console.error('[Session Limit] Failed to count active sessions:', err);
    return true; // Fail closed — deny access on error
  }
}

/**
 * Activate firewall + bandwidth shaping for a user after successful RADIUS auth.
 * Calls staysuite_login.sh which:
 *   - Adds IP to nft loggedinusers set (unblocks traffic)
 *   - Inserts fwmark rules in prerouting
 *   - Adds NAT masquerade rule
 *   - Creates TC HTB classes + fw filters on ifb0/ifb1
 *
 * Runs synchronously but with a 15s timeout.
 * Errors are logged but do NOT block the auth response —
 * the user is authenticated regardless of firewall state.
 * The recovery script will catch up if this fails.
 */
/**
 * Resolve per-user bandwidth in kbps from the user's WiFi plan.
 *
 * Priority:
 *   1. radReply WISPr-Bandwidth-Max-Down/Up (user-level override, in bits/sec → /1000 = kbps)
 *   2. WiFiPlan.downloadSpeed/uploadSpeed (plan-level, in Mbps → *1000 = kbps)
 *   3. Portal maxBandwidthDown/Up (zone-level default, in bytes/sec → *8/1000 = kbps)
 *   4. Hardcoded fallback (5000 kbps down / 1000 kbps up)
 *
 * UNIT REFERENCE:
 *   WiFiPlan.downloadSpeed = 5 means 5 Mbps
 *   WISPr-Bandwidth-Max-Down = 5000000 means 5,000,000 bits/sec = 5000 kbps
 *   CaptivePortal.maxBandwidthDown = 5242880 means bytes/sec (legacy, ~40 Mbps)
 *   TC login script expects kbps (e.g. -D 5000 = 5 Mbps)
 */
async function resolvePlanBandwidthKbps(
  planId: string | null | undefined,
  username?: string,
  portalDownBytes?: number,
  portalUpBytes?: number,
): Promise<{ dn: number; up: number; dnCeil: number; upCeil: number }> {
  // Priority 1: RADIUS radReply override (WISPr stores bits/sec → convert to kbps)
  if (username) {
    try {
      const radreply = await db.radReply.findMany({ where: { username } });
      const getVal = (attr: string): string | undefined =>
        radreply.find(r => r.attribute === attr)?.value;
      const radDown = getVal('WISPr-Bandwidth-Max-Down') || getVal('Cryptsk-Bandwidth-Max-Down');
      const radUp = getVal('WISPr-Bandwidth-Max-Up') || getVal('Cryptsk-Bandwidth-Max-Up');
      if (radDown && radUp) {
        const dn = Math.round(Number(radDown) / 1000);
        const up = Math.round(Number(radUp) / 1000);
        // Check for burst ceil override in radreply
        const radDlCeil = getVal('Cryptsk-Bandwidth-Ceil-Down');
        const radUlCeil = getVal('Cryptsk-Bandwidth-Ceil-Up');
        return { dn, up, dnCeil: radDlCeil ? Math.round(Number(radDlCeil) / 1000) : dn, upCeil: radUlCeil ? Math.round(Number(radUlCeil) / 1000) : up };
      }
    } catch { /* non-critical */ }
  }

  // Priority 2: WiFi plan bandwidth (downloadSpeed/uploadSpeed are in Mbps → *1000 = kbps)
  if (planId) {
    try {
      const plan = await db.wiFiPlan.findUnique({
        where: { id: planId },
        select: { downloadSpeed: true, uploadSpeed: true, burstDownloadSpeed: true, burstUploadSpeed: true },
      });
      if (plan && plan.downloadSpeed > 0 && plan.uploadSpeed > 0) {
        const dn = plan.downloadSpeed * 1000;
        const up = plan.uploadSpeed * 1000;
        const dnCeil = (plan.burstDownloadSpeed && plan.burstDownloadSpeed > 0) ? plan.burstDownloadSpeed * 1000 : dn;
        const upCeil = (plan.burstUploadSpeed && plan.burstUploadSpeed > 0) ? plan.burstUploadSpeed * 1000 : up;
        console.log(`[BW] Plan speed: ${plan.downloadSpeed}Mbps/${plan.uploadSpeed}Mbps burst:${plan.burstDownloadSpeed || 'none'}/${plan.burstUploadSpeed || 'none'} → ${dn}/${up}kbps ceil=${dnCeil}/${upCeil}kbps`);
        return { dn, up, dnCeil, upCeil };
      }
    } catch { /* non-critical */ }
  }

  // Priority 3: Portal default (bytes/sec → bits/sec → kbps)
  if (portalDownBytes && portalUpBytes) {
    const dn = Math.round(portalDownBytes * 8 / 1000);
    const up = Math.round(portalUpBytes * 8 / 1000);
    return { dn, up, dnCeil: dn, upCeil: up };
  }

  // Priority 4: Hardcoded fallback
  return { dn: 5000, up: 1000, dnCeil: 5000, upCeil: 1000 }; // 5 Mbps / 1 Mbps
}

async function activateUserFirewall(params: {
  username: string;
  clientIp: string;
  propertyId: string;
  sessionId?: string;
  macAddress?: string;
  userId?: string;
  /** Download bandwidth in kbps (e.g. 5000 = 5 Mbps) */
  dnKbps?: number;
  /** Upload bandwidth in kbps (e.g. 2000 = 2 Mbps) */
  upKbps?: number;
  /** Download burst ceil in kbps (0 or undefined = ceil = rate) */
  dnCeilKbps?: number;
  /** Upload burst ceil in kbps (0 or undefined = ceil = rate) */
  upCeilKbps?: number;
  subnet?: string | null;
}) {
  try {
    const clientIp = normalizeIp(params.clientIp);
    if (!clientIp || clientIp === '0.0.0.0') {
      console.warn('[Firewall] Skipping activation — no valid client IP');
      return;
    }

    // Warn if sessionId is empty — means radacct creation failed
    // The firewall will still work, but session engine can't track this user
    if (!params.sessionId) {
      console.warn(`[Firewall] No sessionId for ${params.username} — radacct creation may have failed. Session engine will NOT track this user.`);
    }

    // Generate deterministic class IDs from username
    const classIds = generateClassIds(params.username);

    // Bandwidth in kbps — passed directly from caller (no conversion needed)
    const dnKbps = params.dnKbps || 0;
    const upKbps = params.upKbps || 0;

    // Look up BandwidthPool for pool-level rate limiting
    const poolBw = await lookupBandwidthPool(params.propertyId, params.subnet);

    const scriptParams: LoginScriptParams = {
      ip: clientIp,
      action: 'masq',
      poolId: poolBw.poolId,
      poolRateDn: poolBw.poolRateDn,
      poolCeilDn: poolBw.poolCeilDn,
      poolRateUp: poolBw.poolRateUp,
      poolCeilUp: poolBw.poolCeilUp,
      dnClassid: classIds.dn,
      upClassid: classIds.up,
      dnKbps,
      upKbps,
      dnCeilKbps: params.dnCeilKbps,
      upCeilKbps: params.upCeilKbps,
      sessionId: params.sessionId,
      macAddress: params.macAddress,
      userId: params.userId,
    };

    const result = runLoginScript(scriptParams);

    if (result.success) {
      console.log(
        `[Firewall] Login OK: ${params.username} ip=${clientIp} cls=${classIds.dn}/${classIds.up} pool=${poolBw.poolId} dn=${dnKbps}k up=${upKbps}k (${result.durationMs}ms)`
      );
    } else {
      console.error(
        `[Firewall] Login FAIL: ${params.username} ip=${clientIp} exit=${result.exitCode} pool=${poolBw.poolId} cls=${classIds.dn}/${classIds.up} stderr=${result.stderr || '(none)'} (${result.durationMs}ms)`
      );
    }
  } catch (err) {
    // Non-fatal — firewall activation failure should not block authentication
    console.error('[Firewall] Exception activating firewall:', err);
  }
}

// ────────────────────────────────────────────────────────────
// MAC Address Resolution
// ────────────────────────────────────────────────────────────

/**
 * Resolve client MAC address using multiple methods (priority order):
 *
 * 1. Request body — Captive portal frontend passes MAC from URL query params
 *    (e.g., ?mac=AA:BB:CC:DD:EE:FF from UniFi/Mikrotik/Cisco redirect)
 * 2. HTTP headers — Some network equipment injects MAC as headers:
 *    - X-MAC-Address, Client-MAC, Calling-Station-Id
 *    - mac (Mikrotik, CoovaChilli), nas-mac (UniFi)
 * 3. DHCP lease table — Look up by client IP as last resort
 *    (only works if KEA/DHCP is running and has recorded the lease)
 */
async function resolveMacAddress(
  request: NextRequest,
  bodyMac?: string,
  clientIp?: string,
): Promise<string | null> {
  // 1. Body MAC (from URL params forwarded by captive portal frontend)
  if (bodyMac) {
    const normalized = bodyMac.replace(/[:\-\.\s]/g, '').toUpperCase();
    if (/^[0-9A-F]{12}$/.test(normalized)) {
      return normalized.match(/.{2}/g)?.join(':') || null;
    }
  }

  // 2. HTTP headers from network equipment
  const headerSources = [
    'x-mac-address',
    'client-mac',
    'mac',
    'nas-mac',
    'calling-station-id',
    'x-client-mac',
    'x-forwarded-mac',
  ];
  for (const header of headerSources) {
    const value = request.headers.get(header);
    if (value) {
      // Calling-Station-Id is often "AA:BB:CC:DD:EE:FF" or "AA-BB-CC-DD-EE-FF"
      // Some vendors prefix with SSID: "AA:BB:CC:DD:EE:FF-MyNetwork"
      const macMatch = value.match(/([0-9A-Fa-f]{2}[:\-\.]){5}[0-9A-Fa-f]{2}/);
      if (macMatch) {
        const normalized = macMatch[0].replace(/[:\-\.\s]/g, '').toUpperCase();
        if (/^[0-9A-F]{12}$/.test(normalized)) {
          return normalized.match(/.{2}/g)?.join(':') || null;
        }
      }
    }
  }

  // 3. DHCP lease lookup by client IP (last resort)
  if (clientIp && clientIp !== '0.0.0.0' && clientIp !== 'unknown') {
    try {
      const leaseResult = await db.$queryRawUnsafe<Array<{ "macAddress": string | null }>>(`
        SELECT "macAddress" FROM "DhcpLease"
        WHERE "ipAddress" = $1 AND state = 'active'
        ORDER BY "lastSeenAt" DESC
        LIMIT 1
      `, clientIp);

      if (leaseResult.length > 0 && leaseResult[0].macAddress) {
        const normalized = leaseResult[0].macAddress.replace(/[:\-\.\s]/g, '').toUpperCase();
        if (/^[0-9A-F]{12}$/.test(normalized)) {
          console.log(`[MAC] Resolved from DHCP lease: IP=${clientIp} → MAC=${normalized.match(/.{2}/g)?.join(':')}`);
          return normalized.match(/.{2}/g)?.join(':') || null;
        }
      }
    } catch (err) {
      // Non-critical — DHCP lookup failure should not block auth
      console.warn('[MAC] DHCP lease lookup failed:', err instanceof Error ? err.message : err);
    }
  }

  return null;
}

// ────────────────────────────────────────────────────────────
// Per-IP Rate Limiter (in-memory — use Redis for production)
// ────────────────────────────────────────────────────────────
const authAttempts = new Map<string, { count: number; resetAt: number }>();
function checkRateLimit(ip: string, maxAttempts: number = 10, windowMs: number = 60000): boolean {
  const now = Date.now();
  const entry = authAttempts.get(ip);
  if (!entry || now > entry.resetAt) {
    authAttempts.set(ip, { count: 1, resetAt: now + windowMs });
    return true;
  }
  entry.count++;
  return entry.count <= maxAttempts;
}

// ────────────────────────────────────────────────────────────
// POST /api/v1/wifi/auth — Guest WiFi authentication
//
// Validation order (changed per requirement):
//   1. Parse request body → extract username/method
//   2. Validate credentials (username, password, voucher, room, OTP)
//      → if invalid, log and return credential-specific error
//   3. Validate client IP against allocated IP pools
//      → if invalid, log and return IP error
//   4. Authenticate via FreeRADIUS
//   5. Log success + create accounting session
//
// This ensures auth logs show the CORRECT rejection reason:
//   Wrong password → "Rejected — invalid credentials"
//   Wrong network  → "Rejected — IP not in managed pool"
// ────────────────────────────────────────────────────────────
export async function POST(request: NextRequest) {
  try {
    // ════════════════════════════════════════════════════════════
    // STEP 0: Rate limit check (per-IP)
    // ════════════════════════════════════════════════════════════
    const clientRateLimitIp = extractClientIp(request) || 'unknown';
    if (!checkRateLimit(clientRateLimitIp)) {
      return errorResponse('RATE_LIMITED', 'Too many authentication attempts. Please try again later.', 429);
    }

    // ════════════════════════════════════════════════════════════
    // STEP 1: Parse request body — extract username & method first
    // ════════════════════════════════════════════════════════════
    const body = await request.json();
    const {
      method,
      portalSlug,
      voucherCode,
      roomNumber,
      lastName,
      username,
      password,
      phoneNumber,
      otpCode,
      guestInfo,
      marketingEmailConsent,
      marketingSmsConsent,
      macAddress,
      fingerprintHash,
      storageToken,
    } = body as {
      method?: string;
      portalSlug?: string;
      voucherCode?: string;
      roomNumber?: string;
      lastName?: string;
      username?: string;
      password?: string;
      phoneNumber?: string;
      otpCode?: string;
      guestInfo?: {
        firstName?: string;
        lastName?: string;
        email?: string;
        phone?: string;
        passport?: string;
        bookingId?: string;
      };
      marketingEmailConsent?: string;
      marketingSmsConsent?: string;
      macAddress?: string;
      fingerprintHash?: string;
      storageToken?: string;
    };

    // Normalize guestInfo — unified form sends it as a JSON string
    let normalizedGuestInfo: GuestInfoPayload | undefined;
    if (typeof guestInfo === 'string') {
      try {
        normalizedGuestInfo = JSON.parse(guestInfo);
      } catch { /* ignore malformed JSON */ }
    } else if (typeof guestInfo === 'object' && guestInfo !== null) {
      normalizedGuestInfo = guestInfo as GuestInfoPayload;
    }


    if (!method) {
      return errorResponse('MISSING_METHOD', 'Authentication method is required');
    }

    // ════════════════════════════════════════════════════════════
    // STEP 1b: Resolve MAC address from multiple sources
    // Priority: request body → HTTP headers → DHCP lease lookup
    // ════════════════════════════════════════════════════════════
    const clientIpForMac = extractClientIp(request) || getClientIpString(request);
    const resolvedMac = await resolveMacAddress(request, macAddress, clientIpForMac);
    // Use resolved MAC (from headers/DHCP) if body didn't provide one
    const effectiveMac = macAddress || resolvedMac || undefined;
    console.log(`[Auth] MAC resolution: body=${macAddress || 'none'} resolved=${resolvedMac || 'none'} effective=${effectiveMac || 'none'} (client: ${clientIpForMac})`);
    if (effectiveMac && resolvedMac && !macAddress) {
      console.log(`[MAC] Auto-resolved MAC for client: ${clientIpForMac} → ${resolvedMac} (source: header/dhcp)`);
    }

    const validMethods = [
      'voucher',
      'room_number',
      'pms_credentials',
      'sms_otp',
      'open_access',
    ];

    if (!validMethods.includes(method)) {
      return errorResponse(
        'INVALID_METHOD',
        `Invalid authentication method. Supported: ${validMethods.join(', ')}`
      );
    }

    // Fetch portal config for session timeout & bandwidth info
    const portal = portalSlug
      ? await db.captivePortal.findFirst({
          where: { slug: portalSlug, enabled: true },
        })
      : null;

    // Pre-resolve the plan's ipPoolId for pool-restricted validation.
    // Used by SMS OTP and Open Access where no existing user/plan is available.
    // Voucher and PMS Credentials resolve their own plan from user/voucher data.
    let portalPlanIpPoolId: string | null = null;
    if (portal?.propertyId) {
      const aaaConfig = await db.wiFiAAAConfig.findUnique({
        where: { propertyId: portal.propertyId },
        select: { defaultPlanId: true },
      });
      if (aaaConfig?.defaultPlanId) {
        const portalPlan = await db.wiFiPlan.findUnique({
          where: { id: aaaConfig.defaultPlanId },
          select: { ipPoolId: true },
        });
        portalPlanIpPoolId = portalPlan?.ipPoolId ?? null;
      }
    }

    // Portal defaults (sessionTimeout is stored in SECONDS in DB, convert to minutes for display)
    const portalSessionTimeoutMin = portal?.sessionTimeout
      ? Math.round(portal.sessionTimeout / 60)
      : 1440; // default 24h in minutes
    const bwDown = portal
      ? Math.round((portal.maxBandwidthDown || 5242880) / 1000000)
      : 5;
    const bwUp = portal
      ? Math.round((portal.maxBandwidthUp || 1048576) / 1000000)
      : 1;

    // ════════════════════════════════════════════════════════════
    // STEP 2: Validate credentials FIRST
    // Each method validates its own credentials here.
    // If invalid, we log and return immediately — NO IP check yet.
    // ════════════════════════════════════════════════════════════
    switch (method) {
      // ─── Voucher ──────────────────────────────────────────
      case 'voucher': {
        if (!voucherCode?.trim()) {
          return errorResponse('MISSING_VOUCHER', 'Please enter a voucher code');
        }

        const voucher = await db.wiFiVoucher.findUnique({
          where: { code: voucherCode.trim().toUpperCase() },
          include: { plan: true },
        });

        if (!voucher) {
          await logAuthAttempt(voucherCode.trim(), 'Access-Reject', request, 'INVALID_VOUCHER');
          return errorResponse('INVALID_VOUCHER', 'Invalid or expired voucher code');
        }

        if (voucher.status !== 'active' || voucher.isUsed) {
          await logAuthAttempt(`voucher-${voucher.code.toLowerCase()}`, 'Access-Reject', request, 'VOUCHER_USED');
          return errorResponse('VOUCHER_USED', 'This voucher has already been used');
        }

        const now = new Date();
        if (voucher.validUntil < now) {
          await logAuthAttempt(`voucher-${voucher.code.toLowerCase()}`, 'Access-Reject', request, 'VOUCHER_EXPIRED');
          return errorResponse('VOUCHER_EXPIRED', 'This voucher has expired. Please contact front desk for a new one.');
        }

        // ── Credentials valid — now check IP pool ──
        const allowedPools = resolveAllowedPoolIds(voucher.plan?.ipPoolId, undefined, !!voucher.plan);
        const pool = await getValidatedPool(request, allowedPools);
        if (!pool) {
          await logAuthAttempt(`voucher-${voucher.code.toLowerCase()}`, 'Access-Reject', request, `IP_NOT_IN_POOL:${getClientIpString(request)}`);
          return errorResponse('IP_NOT_IN_POOL', 'Your device is not connected to a managed WiFi network. Please connect to the hotel WiFi and try again.', 403);
        }

        // Resolve propertyId
        const resolvedPropertyId = voucher.plan?.propertyId
          || await db.property.findFirst({ where: { tenantId: voucher.tenantId }, select: { id: true } }).then(p => p?.id);

        if (!resolvedPropertyId) {
          return errorResponse('NO_PROPERTY', 'No property configured. Please contact front desk.');
        }

        const wifiUsername = `voucher-${voucher.code.toLowerCase()}`;
        const validUntil = new Date(now.getTime() + portalSessionTimeoutMin * 60 * 1000);
        const dataLimitMb = voucher.plan?.dataLimit ?? undefined;

        // Use PLAN bandwidth (Mbps → kbps), NOT portal defaults
        const planDnKbps = (voucher.plan?.downloadSpeed || bwDown) * 1000;
        const planUpKbps = (voucher.plan?.uploadSpeed || bwUp) * 1000;

        await provisionOrResumeUser(wifiUsername, now, validUntil, {
          tenantId: voucher.tenantId,
          propertyId: resolvedPropertyId,
          guestId: voucher.guestId ?? undefined,
          bookingId: voucher.bookingId ?? undefined,
          username: wifiUsername,
          password: voucher.code,
          planId: voucher.planId ?? undefined,
          planName: voucher.plan?.name,
          downloadSpeed: planDnKbps * 1000,  // kbps → bits/sec for RADIUS
          uploadSpeed: planUpKbps * 1000,
          sessionTimeoutMinutes: portalSessionTimeoutMin,
          idleTimeoutSeconds: portal?.idleTimeout,
          sessionLimit: voucher.plan?.maxDevices,
          dataLimit: dataLimitMb,
        });

        // Check concurrent session limit
        const maxSessions = voucher.plan?.maxDevices || 1;
        if (await isSessionLimitReached(wifiUsername, maxSessions)) {
          await logAuthAttempt(wifiUsername, 'Access-Reject', request, 'MAX_SESSIONS_REACHED');
          return errorResponse('MAX_SESSIONS_REACHED', 'Maximum concurrent sessions reached. Please disconnect another device first.');
        }

        const radiusResult = await radiusAuth(wifiUsername, voucher.code);
        if (!radiusResult.accepted) {
          await logAuthAttempt(wifiUsername, 'Access-Reject', request, radiusResult.rejectReason || 'AUTH_FAILED');
          return errorResponse(radiusResult.rejectReason || 'AUTH_FAILED', getRejectMessage(radiusResult.rejectReason || 'AUTH_FAILED'));
        }

        // Atomically mark voucher as used (prevents double-use race condition)
        const updatedVoucher = await db.wiFiVoucher.updateMany({
          where: { id: voucher.id, isUsed: false },
          data: { isUsed: true, usedAt: new Date(), status: 'used' },
        });
        if (updatedVoucher.count === 0) {
          return NextResponse.json({ success: false, error: 'Voucher already used' }, { status: 409 });
        }

        await logAuthAttempt(wifiUsername, 'Access-Accept', request, `pool:${pool.poolName}`);
        const sessionId = await createAccountingSession(wifiUsername, request, 'portal', effectiveMac, pool);

        // Activate nftables + TC bandwidth shaping — use PLAN speed in kbps, not portal defaults
        const voucherBw = await resolvePlanBandwidthKbps(
          voucher.planId, wifiUsername,
          portal?.maxBandwidthDown, portal?.maxBandwidthUp,
        );
        await activateUserFirewall({
          username: wifiUsername, clientIp: getClientIpString(request),
          propertyId: resolvedPropertyId, sessionId,
          macAddress: effectiveMac,
          dnKbps: voucherBw.dn,
          upKbps: voucherBw.up,
          dnCeilKbps: voucherBw.dnCeil,
          upCeilKbps: voucherBw.upCeil,
          subnet: pool.subnet,
        });

        // Add per-IP byte counter rules for session engine tracking
        const voucherCounterIp = normalizeIp(getClientIpString(request));
        if (voucherCounterIp && voucherCounterIp !== '0.0.0.0') {
          addUserCounter(voucherCounterIp);
        }

        // ── Save device profile with real browser fingerprint ──
        try {
          const voucherUser = await db.wiFiUser.findUnique({ where: { username: wifiUsername }, select: { id: true, tenantId: true, propertyId: true, guestId: true } });
          if (voucherUser) {
            await upsertDeviceProfileWithFingerprint({ wifiUserId: voucherUser.id, tenantId: voucherUser.tenantId, propertyId: voucherUser.propertyId, guestId: voucherUser.guestId, username: wifiUsername, request, macAddress: effectiveMac, fingerprintHash, storageToken });
            // Save guest info from portal form
            await saveGuestInfoAfterAuth({
              wifiUserId: voucherUser.id,
              guestId: voucherUser.guestId,
              bookingId: voucher.bookingId,
              guestInfo: normalizedGuestInfo,
              marketingConsent: { emailConsent: marketingEmailConsent === 'true', smsConsent: marketingSmsConsent === 'true' },
            });
          }
        } catch { /* best effort */ }

        return successResponse({
          authenticated: true, method: 'voucher', username: wifiUsername,
          sessionTimeout: portalSessionTimeoutMin, bandwidthDown: bwDown, bandwidthUp: bwUp,
          poolName: pool.poolName, message: 'Connected successfully!',
        });
      }

      // ─── Room Number ──────────────────────────────────────
      // Unification: If a PMS-provisioned WiFiUser already exists for this
      // guest/booking, reuse it instead of creating a duplicate room-{number}
      // user. This gives the guest plan-level bandwidth, data limits, and
      // session timeout from their actual WiFi plan (not portal defaults).
      //
      // Lookup priority:
      //   1. WiFiUser where bookingId = match.id  (PMS auto-provisioned for this booking)
      //   2. WiFiUser where guestId = match.primaryGuestId AND status = 'active'
      //   3. Fallback: create room-{number} user (original behavior)
      case 'room_number': {
        if (!roomNumber?.trim()) {
          return errorResponse('MISSING_ROOM', 'Please enter your room number');
        }
        if (!lastName?.trim()) {
          return errorResponse('MISSING_NAME', 'Please enter your last name');
        }

        const bookings = await db.booking.findMany({
          where: { room: { roomNumber: roomNumber.trim().toUpperCase() }, status: 'in_house' },
          include: { primaryGuest: true, room: true, roomType: { select: { wifiPlanId: true } } },
          take: 10,
        });

        const match = bookings.find(
          (b) => b.primaryGuest.lastName.toLowerCase() === lastName.trim().toLowerCase()
        );

        if (!match) {
          await logAuthAttempt(`room-${roomNumber.trim().toLowerCase()}`, 'Access-Reject', request, 'INVALID_CREDENTIALS');
          return errorResponse('ROOM_NOT_FOUND', 'No active guest found for this room number and last name. Please verify and try again.');
        }

        // ── Credentials valid — now resolve plan ──
        // Priority: roomType's WiFi plan → property's default AAA plan
        // This plan determines bandwidth, device limit, data cap, session timeout
        let roomPlanIpPoolId: string | null = null;
        let roomPlanId: string | null = match.roomType?.wifiPlanId ?? null;

        if (roomPlanId) {
          const roomPlan = await db.wiFiPlan.findUnique({
            where: { id: roomPlanId },
            select: { ipPoolId: true },
          });
          roomPlanIpPoolId = roomPlan?.ipPoolId ?? null;
        } else {
          // No plan on room type — fall back to property's default AAA plan
          const aaaConfig = await db.wiFiAAAConfig.findUnique({
            where: { propertyId: match.propertyId },
            select: { defaultPlanId: true },
          });
          if (aaaConfig?.defaultPlanId) {
            roomPlanId = aaaConfig.defaultPlanId;
            const defaultPlan = await db.wiFiPlan.findUnique({
              where: { id: roomPlanId },
              select: { ipPoolId: true },
            });
            roomPlanIpPoolId = defaultPlan?.ipPoolId ?? null;
          }
        }

        const now = new Date();

        // ── Look for existing PMS-provisioned WiFiUser ──
        // Priority 1: Exact booking match (most precise — created at check-in)
        const existingByBooking = await db.wiFiUser.findFirst({
          where: { bookingId: match.id, status: { in: ['active', 'suspended'] } },
          include: { plan: { select: { ipPoolId: true, maxDevices: true, validityMinutes: true, validityDays: true, downloadSpeed: true, uploadSpeed: true, name: true } } },
        });

        // Priority 2: Same guest, active user (covers cases where bookingId wasn't set)
        const existingByGuest = !existingByBooking
          ? await db.wiFiUser.findFirst({
              where: { guestId: match.primaryGuestId, status: 'active', propertyId: match.propertyId },
              include: { plan: { select: { ipPoolId: true, maxDevices: true, validityMinutes: true, validityDays: true, downloadSpeed: true, uploadSpeed: true, name: true } } },
            })
          : null;

        const existingUser = existingByBooking || existingByGuest;
        const reuseExisting = !!existingUser;

        if (reuseExisting) {
          // ── Reuse existing PMS-provisioned user ──
          // This guest was auto-provisioned at check-in — use their plan attrs
          const pmsUser = existingUser!;

          if (pmsUser.status !== 'active') {
            await logAuthAttempt(pmsUser.username, 'Access-Reject', request, 'ACCOUNT_INACTIVE');
            return errorResponse('ACCOUNT_INACTIVE', 'Your WiFi account is not active. Please contact front desk.');
          }

          if (new Date(pmsUser.validUntil) < now) {
            await logAuthAttempt(pmsUser.username, 'Access-Reject', request, 'ACCOUNT_EXPIRED');
            return errorResponse('ACCOUNT_EXPIRED', 'Your WiFi session has expired. Please contact front desk to renew.');
          }

          const allowedPools = resolveAllowedPoolIds(pmsUser.plan?.ipPoolId || roomPlanIpPoolId, pmsUser.ipPoolId, !!(pmsUser.plan?.ipPoolId || roomPlanIpPoolId));
          const pool = await getValidatedPool(request, allowedPools);
          if (!pool) {
            await logAuthAttempt(pmsUser.username, 'Access-Reject', request, `IP_NOT_IN_POOL:${getClientIpString(request)}`);
            return errorResponse('IP_NOT_IN_POOL', 'Your device is not connected to a managed WiFi network. Please connect to the hotel WiFi and try again.', 403);
          }

          // Ensure RADIUS credentials exist (may have been deleted between sessions)
          const existingCheck = await db.radCheck.findFirst({ where: { username: pmsUser.username } });
          if (!existingCheck) {
            try { await wifiUserService.resumeUser(pmsUser.id); } catch { /* best effort */ }
          }

          // Check concurrent session limit
          const pmsMaxSessions = pmsUser.maxSessions || pmsUser.plan?.maxDevices || 1;
          if (await isSessionLimitReached(pmsUser.username, pmsMaxSessions)) {
            await logAuthAttempt(pmsUser.username, 'Access-Reject', request, 'MAX_SESSIONS_REACHED');
            return errorResponse('MAX_SESSIONS_REACHED', 'Maximum concurrent sessions reached. Please disconnect another device first.');
          }

          const radiusResult = await radiusAuth(pmsUser.username, pmsUser.password);
          if (!radiusResult.accepted) {
            await logAuthAttempt(pmsUser.username, 'Access-Reject', request, radiusResult.rejectReason || 'AUTH_FAILED');
            return errorResponse(radiusResult.rejectReason || 'AUTH_FAILED', getRejectMessage(radiusResult.rejectReason || 'AUTH_FAILED'));
          }

          // ── Calculate remaining validity (NEVER reset validUntil) ──
          const planValidityMin = pmsUser.plan?.validityMinutes
            || (pmsUser.plan?.validityDays ? pmsUser.plan.validityDays * 1440 : null)
            || portalSessionTimeoutMin;
          const remainingMs = new Date(pmsUser.validUntil).getTime() - now.getTime();
          const remainingMinutes = Math.max(0, Math.ceil(remainingMs / 60000));
          const remainingSeconds = Math.max(0, Math.floor(remainingMs / 1000));

          // Cap RADIUS Session-Timeout to remaining validity
          const cappedSessionTimeoutSec = Math.min(planValidityMin * 60, remainingSeconds);
          await db.radReply.deleteMany({ where: { username: pmsUser.username, attribute: 'Session-Timeout' } });
          await db.radReply.create({
            data: {
              wifiUserId: pmsUser.id, username: pmsUser.username,
              attribute: 'Session-Timeout', op: ':=',
              value: String(cappedSessionTimeoutSec), isActive: true,
            },
          });

          // Update last activity timestamp
          await db.wiFiUser.update({ where: { id: pmsUser.id }, data: { validFrom: now } });

          // Read bandwidth from radreply (user-level overrides > group-level)
          const pmsRadreply = await db.radReply.findMany({ where: { username: pmsUser.username } });
          const getRadReplyVal = (attr: string): string | undefined =>
            pmsRadreply.find(r => r.attribute === attr)?.value;
          const pmsBwDownBps = getRadReplyVal('WISPr-Bandwidth-Max-Down') || getRadReplyVal('Cryptsk-Bandwidth-Max-Down');
          const pmsBwUpBps = getRadReplyVal('WISPr-Bandwidth-Max-Up') || getRadReplyVal('Cryptsk-Bandwidth-Max-Up');
          const pmsBwDown = pmsBwDownBps ? Math.round(Number(pmsBwDownBps) / 1000000) : (pmsUser.plan?.downloadSpeed || bwDown);
          const pmsBwUp = pmsBwUpBps ? Math.round(Number(pmsBwUpBps) / 1000000) : (pmsUser.plan?.uploadSpeed || bwUp);

          await logAuthAttempt(pmsUser.username, 'Access-Accept', request, `pool:${pool.poolName} reuse:pms plan:${pmsUser.plan?.name || 'none'}`);
          const sessionId = await createAccountingSession(pmsUser.username, request, 'portal', effectiveMac, pool);

          // Activate firewall — resolve from plan in kbps
          const pmsBw = await resolvePlanBandwidthKbps(
            pmsUser.planId, pmsUser.username,
            portal?.maxBandwidthDown, portal?.maxBandwidthUp,
          );
          await activateUserFirewall({
            username: pmsUser.username, clientIp: getClientIpString(request),
            propertyId: match.propertyId, sessionId,
            macAddress: effectiveMac, userId: pmsUser.id,
            dnKbps: pmsBw.dn,
            upKbps: pmsBw.up,
            dnCeilKbps: pmsBw.dnCeil,
            upCeilKbps: pmsBw.upCeil,
            subnet: pool.subnet,
          });

          const pmsCounterIp = normalizeIp(getClientIpString(request));
          if (pmsCounterIp && pmsCounterIp !== '0.0.0.0') {
            addUserCounter(pmsCounterIp);
          }

          // ── Save device profile with real browser fingerprint ──
          await upsertDeviceProfileWithFingerprint({
            wifiUserId: pmsUser.id, tenantId: pmsUser.tenantId,
            propertyId: pmsUser.propertyId, guestId: pmsUser.guestId,
            username: pmsUser.username, request,
            macAddress: effectiveMac, fingerprintHash, storageToken,
          });

          // Save guest info from portal form
          saveGuestInfoAfterAuth({
            wifiUserId: pmsUser.id,
            guestId: pmsUser.guestId,
            bookingId: match.id,
            guestInfo: normalizedGuestInfo,
            marketingConsent: { emailConsent: marketingEmailConsent === 'true', smsConsent: marketingSmsConsent === 'true' },
          }).catch(() => {});

          return successResponse({
            authenticated: true, method: 'room_number', username: pmsUser.username,
            sessionTimeout: planValidityMin, remainingMinutes,
            bandwidthDown: pmsBwDown, bandwidthUp: pmsBwUp,
            poolName: pool.poolName, planName: pmsUser.plan?.name || null,
            message: 'Connected successfully!',
          });
        }

        // ── No PMS user found — fallback: create room-{number} user ──
        console.log(`[Room Auth] No PMS user found for booking ${match.id} / guest ${match.primaryGuestId} — falling back to room-${match.room?.roomNumber?.toLowerCase() || roomNumber.trim().toLowerCase()}`);

        const pool = await getValidatedPool(request, resolveAllowedPoolIds(roomPlanIpPoolId, undefined, !!roomPlanIpPoolId));
        if (!pool) {
          await logAuthAttempt(`room-${roomNumber.trim().toLowerCase()}`, 'Access-Reject', request, `IP_NOT_IN_POOL:${getClientIpString(request)}`);
          return errorResponse('IP_NOT_IN_POOL', 'Your device is not connected to a managed WiFi network. Please connect to the hotel WiFi and try again.', 403);
        }

        const validUntil = new Date(now.getTime() + portalSessionTimeoutMin * 60 * 1000);
        const wifiUsername = `room-${match.room?.roomNumber?.toLowerCase() || roomNumber.trim().toLowerCase()}`;
        const userPassword = `${match.primaryGuest.lastName.toLowerCase()}-${match.id.slice(0, 8)}`;

        // Resolve plan attrs for bandwidth, device limit and data cap
        let roomMaxDevices = 1; // safe default
        let roomDataLimit: number | undefined;
        let roomPlanDnKbps = bwDown * 1000;  // kbps
        let roomPlanUpKbps = bwUp * 1000;    // kbps
        if (roomPlanId) {
          const planAttrs = await db.wiFiPlan.findUnique({
            where: { id: roomPlanId },
            select: { maxDevices: true, dataLimit: true, downloadSpeed: true, uploadSpeed: true },
          });
          if (planAttrs?.maxDevices && planAttrs.maxDevices > 0) {
            roomMaxDevices = planAttrs.maxDevices;
          }
          if (planAttrs?.dataLimit && planAttrs.dataLimit > 0) {
            roomDataLimit = planAttrs.dataLimit;
          }
          if (planAttrs?.downloadSpeed && planAttrs.downloadSpeed > 0) {
            roomPlanDnKbps = planAttrs.downloadSpeed * 1000;  // Mbps → kbps
            roomPlanUpKbps = planAttrs.uploadSpeed * 1000;
          }
        }

        await provisionOrResumeUser(wifiUsername, now, validUntil, {
          tenantId: match.tenantId,
          propertyId: match.propertyId,
          guestId: match.primaryGuestId,
          bookingId: match.id,
          username: wifiUsername,
          password: userPassword,
          planId: roomPlanId ?? undefined,
          downloadSpeed: roomPlanDnKbps * 1000,  // kbps → bits/sec for RADIUS
          uploadSpeed: roomPlanUpKbps * 1000,
          sessionTimeoutMinutes: portalSessionTimeoutMin,
          idleTimeoutSeconds: portal?.idleTimeout,
          sessionLimit: roomMaxDevices,
          dataLimit: roomDataLimit,
        });

        // Check concurrent session limit (from resolved plan, not hardcoded)
        if (await isSessionLimitReached(wifiUsername, roomMaxDevices)) {
          await logAuthAttempt(wifiUsername, 'Access-Reject', request, 'MAX_SESSIONS_REACHED');
          return errorResponse('MAX_SESSIONS_REACHED', 'Maximum concurrent sessions reached. Please disconnect another device first.');
        }

        const radiusResult = await radiusAuth(wifiUsername, userPassword);
        if (!radiusResult.accepted) {
          await logAuthAttempt(wifiUsername, 'Access-Reject', request, radiusResult.rejectReason || 'AUTH_FAILED');
          return errorResponse(radiusResult.rejectReason || 'AUTH_FAILED', getRejectMessage(radiusResult.rejectReason || 'AUTH_FAILED'));
        }

        await logAuthAttempt(wifiUsername, 'Access-Accept', request, `pool:${pool.poolName} fallback:room_user`);
        const sessionId = await createAccountingSession(wifiUsername, request, 'portal', effectiveMac, pool);

        await activateUserFirewall({
          username: wifiUsername, clientIp: getClientIpString(request),
          propertyId: match.propertyId, sessionId,
          macAddress: effectiveMac,
          dnKbps: roomPlanDnKbps,
          upKbps: roomPlanUpKbps,
          subnet: pool.subnet,
        });

        // Add per-IP byte counter rules for session engine tracking
        const roomCounterIp = normalizeIp(getClientIpString(request));
        if (roomCounterIp && roomCounterIp !== '0.0.0.0') {
          addUserCounter(roomCounterIp);
        }

        // ── Save device profile with real browser fingerprint ──
        try {
          const roomUser = await db.wiFiUser.findUnique({ where: { username: wifiUsername }, select: { id: true, tenantId: true, propertyId: true, guestId: true } });
          if (roomUser) {
            await upsertDeviceProfileWithFingerprint({ wifiUserId: roomUser.id, tenantId: roomUser.tenantId, propertyId: roomUser.propertyId, guestId: roomUser.guestId, username: wifiUsername, request, macAddress: effectiveMac, fingerprintHash, storageToken });
            // Save guest info from portal form
            await saveGuestInfoAfterAuth({
              wifiUserId: roomUser.id,
              guestId: roomUser.guestId,
              bookingId: match.id,
              guestInfo: normalizedGuestInfo,
              marketingConsent: { emailConsent: marketingEmailConsent === 'true', smsConsent: marketingSmsConsent === 'true' },
            });
          }
        } catch { /* best effort */ }

        return successResponse({
          authenticated: true, method: 'room_number', username: wifiUsername,
          sessionTimeout: portalSessionTimeoutMin, bandwidthDown: bwDown, bandwidthUp: bwUp,
          poolName: pool.poolName, message: 'Connected successfully!',
        });
      }

      // ─── PMS Credentials ──────────────────────────────────
      case 'pms_credentials': {
        if (!username?.trim()) {
          return errorResponse('MISSING_USERNAME', 'Please enter your username');
        }
        if (!password?.trim()) {
          return errorResponse('MISSING_PASSWORD', 'Please enter your password');
        }

        const wifiUser = await db.wiFiUser.findUnique({
          where: { username: username.trim() },
          include: {
            plan: { select: { ipPoolId: true, maxDevices: true, validityMinutes: true, downloadSpeed: true, uploadSpeed: true } },
            ipPool: { select: { id: true } },
          },
        });

        if (!wifiUser) {
          await logAuthAttempt(username.trim(), 'Access-Reject', request, 'INVALID_CREDENTIALS');
          return errorResponse('INVALID_CREDENTIALS', 'Invalid username or password');
        }

        if (wifiUser.password !== password.trim()) {
          await logAuthAttempt(username.trim(), 'Access-Reject', request, 'INVALID_CREDENTIALS');
          return errorResponse('INVALID_CREDENTIALS', 'Invalid username or password');
        }

        if (wifiUser.status !== 'active') {
          await logAuthAttempt(username.trim(), 'Access-Reject', request, 'ACCOUNT_INACTIVE');
          return errorResponse('ACCOUNT_INACTIVE', 'Your WiFi account is not active. Please contact front desk.');
        }

        const now = new Date();
        if (wifiUser.validUntil < now) {
          await logAuthAttempt(username.trim(), 'Access-Reject', request, 'ACCOUNT_EXPIRED');
          return errorResponse('ACCOUNT_EXPIRED', 'Your WiFi session has expired. Please contact front desk to renew.');
        }

        // ── Credentials valid — now check IP pool ──
        const allowedPools = resolveAllowedPoolIds(wifiUser.plan?.ipPoolId, wifiUser.ipPoolId, !!wifiUser.planId);
        const pool = await getValidatedPool(request, allowedPools);
        if (!pool) {
          await logAuthAttempt(username.trim(), 'Access-Reject', request, `IP_NOT_IN_POOL:${getClientIpString(request)}`);
          return errorResponse('IP_NOT_IN_POOL', 'Your device is not connected to a managed WiFi network. Please connect to the hotel WiFi and try again.', 403);
        }

        // Ensure RADIUS credentials exist
        const existingCheck = await db.radCheck.findFirst({
          where: { username: wifiUser.username },
        });
        if (!existingCheck) {
          try {
            await wifiUserService.resumeUser(wifiUser.id);
          } catch {
            // Best effort
          }
        }

        // Check concurrent session limit
        const pmsMaxSessions = wifiUser.maxSessions || wifiUser.plan?.maxDevices || 1;
        if (await isSessionLimitReached(username.trim(), pmsMaxSessions)) {
          await logAuthAttempt(username.trim(), 'Access-Reject', request, 'MAX_SESSIONS_REACHED');
          return errorResponse('MAX_SESSIONS_REACHED', 'Maximum concurrent sessions reached. Please disconnect another device first.');
        }

        const radiusResult = await radiusAuth(username.trim(), password.trim());
        if (!radiusResult.accepted) {
          await logAuthAttempt(username.trim(), 'Access-Reject', request, radiusResult.rejectReason || 'AUTH_FAILED');
          return errorResponse(radiusResult.rejectReason || 'AUTH_FAILED', getRejectMessage(radiusResult.rejectReason || 'AUTH_FAILED'));
        }

        await logAuthAttempt(username.trim(), 'Access-Accept', request, `pool:${pool.poolName}`);
        const sessionId = await createAccountingSession(username.trim(), request, 'portal', effectiveMac, pool);

        // ── Calculate plan validity for session timeout & display ──
        // validUntil is NOT reset here — it was set ONCE at user creation.
        // This ensures timed packages (e.g. 4-hr) give exactly that much total time.
        const planValidityMin = wifiUser.plan?.validityMinutes
          || (wifiUser.plan?.validityDays ? wifiUser.plan.validityDays * 1440 : null)
          || portalSessionTimeoutMin;

        // Calculate remaining time for display and Session-Timeout capping
        const remainingMs = wifiUser.validUntil
          ? new Date(wifiUser.validUntil).getTime() - now.getTime()
          : planValidityMin * 60 * 1000;
        const remainingMinutes = Math.max(0, Math.ceil(remainingMs / 60000));
        const remainingSeconds = Math.max(0, Math.floor(remainingMs / 1000));

        // ── Set validFrom to now (tracks last activity), but NEVER reset validUntil ──
        await db.wiFiUser.update({
          where: { id: wifiUser.id },
          data: { validFrom: now },
        });

        // ── Cap RADIUS Session-Timeout to remaining validity ──
        // Prevents RADIUS sessions that outlast the actual account validity.
        const cappedSessionTimeoutSec = Math.min(planValidityMin * 60, remainingSeconds);
        await db.radReply.deleteMany({
          where: { username: wifiUser.username, attribute: 'Session-Timeout' },
        });
        await db.radReply.create({
          data: {
            wifiUserId: wifiUser.id,
            username: wifiUser.username,
            attribute: 'Session-Timeout',
            op: ':=',
            value: String(cappedSessionTimeoutSec),
            isActive: true,
          },
        });

        // ── Read user's bandwidth from radreply ──
        const userRadreply = await db.radReply.findMany({
          where: { username: username.trim() },
        });
        const getRadReplyValue = (attr: string): string | undefined =>
          userRadreply.find(r => r.attribute === attr)?.value;

        const bwDownBps = getRadReplyValue('WISPr-Bandwidth-Max-Down')
          || getRadReplyValue('Cryptsk-Bandwidth-Max-Down');
        const bwUpBps = getRadReplyValue('WISPr-Bandwidth-Max-Up')
          || getRadReplyValue('Cryptsk-Bandwidth-Max-Up');
        const userBwDown = bwDownBps ? Math.round(Number(bwDownBps) / 1000000) : bwDown;
        const userBwUp = bwUpBps ? Math.round(Number(bwUpBps) / 1000000) : bwUp;

        await activateUserFirewall({
          username: username.trim(), clientIp: getClientIpString(request),
          propertyId: wifiUser.propertyId, sessionId,
          macAddress: effectiveMac, userId: wifiUser.id,
          dnKbps: bwDownBps ? Math.round(Number(bwDownBps) / 1000) : (wifiUser.plan?.downloadSpeed || bwDown) * 1000,
          upKbps: bwUpBps ? Math.round(Number(bwUpBps) / 1000) : (wifiUser.plan?.uploadSpeed || bwUp) * 1000,
          subnet: pool.subnet,
        });

        // Add per-IP byte counter rules for session engine tracking
        const pmsCounterIp = normalizeIp(getClientIpString(request));
        if (pmsCounterIp && pmsCounterIp !== '0.0.0.0') {
          addUserCounter(pmsCounterIp);
        }

        // ── Save device profile with real browser fingerprint ──
        await upsertDeviceProfileWithFingerprint({
          wifiUserId: wifiUser.id,
          tenantId: wifiUser.tenantId,
          propertyId: wifiUser.propertyId,
          guestId: wifiUser.guestId,
          username: wifiUser.username,
          request,
          macAddress: effectiveMac,
          fingerprintHash,
          storageToken,
        });

          // Save guest info from portal form
          saveGuestInfoAfterAuth({
            wifiUserId: wifiUser.id,
            guestId: wifiUser.guestId,
            bookingId: wifiUser.bookingId,
            guestInfo: normalizedGuestInfo,
            marketingConsent: { emailConsent: marketingEmailConsent === 'true', smsConsent: marketingSmsConsent === 'true' },
          }).catch(() => {});

        return successResponse({
          authenticated: true, method: 'pms_credentials', username: wifiUser.username,
          sessionTimeout: planValidityMin, remainingMinutes, bandwidthDown: userBwDown, bandwidthUp: userBwUp,
          poolName: pool.poolName, message: 'Connected successfully!',
        });
      }

      // ─── SMS OTP ──────────────────────────────────────────
      // Two-step flow:
      //   Step 1 (no otpCode): Validate phone → generate OTP → send via SMS → store in otpStore
      //   Step 2 (with otpCode): Validate OTP → provision RADIUS user → authenticate
      //
      // Security:
      //   - Per-phone rate limiting (5 sends per 15 min)
      //   - Max 5 wrong OTP attempts per OTP
      //   - 5-minute OTP expiry
      //   - Phone number format validation
      case 'sms_otp': {
        if (otpCode) {
          // ── Step 2: Verify OTP (credential check) ──
          if (!phoneNumber?.trim()) {
            return errorResponse('MISSING_PHONE', 'Phone number is required for OTP verification');
          }

          const normalizedPhone = normalizePhoneNumberLocal(phoneNumber.trim());
          const stored = otpStore.get(normalizedPhone);

          if (!stored) {
            return errorResponse('OTP_NOT_FOUND', 'No OTP found. Please request a new one.');
          }

          if (Date.now() > stored.expiresAt) {
            otpStore.delete(normalizedPhone);
            return errorResponse('OTP_EXPIRED', 'Your OTP has expired. Please request a new one.');
          }

          // Track wrong attempts — invalidate after too many tries
          stored.attempts++;
          if (stored.attempts > OTP_MAX_VERIFY_ATTEMPTS) {
            otpStore.delete(normalizedPhone);
            return errorResponse('OTP_MAX_ATTEMPTS', 'Too many incorrect attempts. Please request a new OTP.');
          }

          if (stored.code !== otpCode.trim()) {
            const remaining = OTP_MAX_VERIFY_ATTEMPTS - stored.attempts;
            return errorResponse('OTP_INVALID', `Invalid OTP code. ${remaining} attempt${remaining !== 1 ? 's' : ''} remaining.`);
          }

          // ── OTP verified — check IP pool ──
          const smsPool = await getValidatedPool(request, resolveAllowedPoolIds(portalPlanIpPoolId, undefined, !!portalPlanIpPoolId));
          if (!smsPool) {
            await logAuthAttempt(`sms-${normalizedPhone.replace(/[^a-z0-9]/gi, '')}`, 'Access-Reject', request, `IP_NOT_IN_POOL:${getClientIpString(request)}`);
            return errorResponse('IP_NOT_IN_POOL', 'Your device is not connected to a managed WiFi network. Please connect to the hotel WiFi and try again.', 403);
          }

          otpStore.delete(normalizedPhone);

          const now = new Date();
          const validUntil = new Date(now.getTime() + portalSessionTimeoutMin * 60 * 1000);
          const wifiUsername = `sms-${normalizedPhone.replace(/[^a-z0-9]/gi, '')}`;

          const fallbackPropertyId = portal?.propertyId
            || await (portal?.tenantId
              ? db.property.findFirst({ where: { tenantId: portal.tenantId }, select: { id: true } }).then(p => p?.id)
              : Promise.resolve(undefined));

          if (fallbackPropertyId) {
            // ── Resolve plan for proper bandwidth, device limit + data cap ──
            let smsPlanId: string | null = null;
            let smsMaxDevices = 1;
            let smsDataLimit: number | undefined;
            let smsPlanDnKbps = bwDown * 1000;  // kbps
            let smsPlanUpKbps = bwUp * 1000;    // kbps

            if (portalPlanIpPoolId || fallbackPropertyId) {
              // Try property default AAA plan
              const aaaConfig = await db.wiFiAAAConfig.findUnique({
                where: { propertyId: fallbackPropertyId },
                select: { defaultPlanId: true },
              });
              if (aaaConfig?.defaultPlanId) {
                smsPlanId = aaaConfig.defaultPlanId;
                const planAttrs = await db.wiFiPlan.findUnique({
                  where: { id: smsPlanId },
                  select: { maxDevices: true, dataLimit: true, downloadSpeed: true, uploadSpeed: true },
                });
                if (planAttrs?.maxDevices && planAttrs.maxDevices > 0) {
                  smsMaxDevices = planAttrs.maxDevices;
                }
                if (planAttrs?.dataLimit && planAttrs.dataLimit > 0) {
                  smsDataLimit = planAttrs.dataLimit;
                }
                if (planAttrs?.downloadSpeed && planAttrs.downloadSpeed > 0) {
                  smsPlanDnKbps = planAttrs.downloadSpeed * 1000;  // Mbps → kbps
                  smsPlanUpKbps = planAttrs.uploadSpeed * 1000;
                }
              }
            }

            await provisionOrResumeUser(wifiUsername, now, validUntil, {
              tenantId: portal?.tenantId || '',
              propertyId: fallbackPropertyId,
              username: wifiUsername,
              password: stored.code,
              planId: smsPlanId ?? undefined,
              downloadSpeed: smsPlanDnKbps * 1000,  // kbps → bits/sec for RADIUS
              uploadSpeed: smsPlanUpKbps * 1000,
              sessionTimeoutMinutes: portalSessionTimeoutMin,
              idleTimeoutSeconds: portal?.idleTimeout,
              sessionLimit: smsMaxDevices,
              dataLimit: smsDataLimit,
            });

            // Check concurrent session limit (from resolved plan, not hardcoded)
            if (await isSessionLimitReached(wifiUsername, smsMaxDevices)) {
              await logAuthAttempt(wifiUsername, 'Access-Reject', request, 'MAX_SESSIONS_REACHED');
              return errorResponse('MAX_SESSIONS_REACHED', 'Maximum concurrent sessions reached. Please disconnect another device first.');
            }

            const radiusResult = await radiusAuth(wifiUsername, stored.code);
            if (!radiusResult.accepted) {
              await logAuthAttempt(wifiUsername, 'Access-Reject', request, radiusResult.rejectReason || 'AUTH_FAILED');
              return errorResponse(radiusResult.rejectReason || 'AUTH_FAILED', getRejectMessage(radiusResult.rejectReason || 'AUTH_FAILED'));
            }

            await logAuthAttempt(wifiUsername, 'Access-Accept', request, `pool:${smsPool.poolName}${smsPlanId ? ' plan:aaa' : ''}`);
            const sessionId = await createAccountingSession(wifiUsername, request, 'portal', effectiveMac, smsPool);

            await activateUserFirewall({
              username: wifiUsername, clientIp: getClientIpString(request),
              propertyId: fallbackPropertyId, sessionId,
              macAddress: effectiveMac,
              dnKbps: smsPlanDnKbps,
              upKbps: smsPlanUpKbps,
              subnet: smsPool.subnet,
            });

            // Add per-IP byte counter rules for session engine tracking
            const smsCounterIp = normalizeIp(getClientIpString(request));
            if (smsCounterIp && smsCounterIp !== '0.0.0.0') {
              addUserCounter(smsCounterIp);
            }

            // ── Save device profile for auto-reauth ──
            try {
              const smsUser = await db.wiFiUser.findUnique({
                where: { username: wifiUsername },
                select: { id: true, tenantId: true, propertyId: true, guestId: true },
              });
              if (smsUser) {
                await upsertDeviceProfileWithFingerprint({
                  wifiUserId: smsUser.id, tenantId: smsUser.tenantId,
                  propertyId: smsUser.propertyId, guestId: smsUser.guestId,
                  username: wifiUsername, request,
                  macAddress: effectiveMac, fingerprintHash, storageToken,
                });
                // Save guest info from portal form
                await saveGuestInfoAfterAuth({
                  wifiUserId: smsUser.id,
                  propertyId: fallbackPropertyId,
                  guestInfo: normalizedGuestInfo,
                  marketingConsent: { emailConsent: marketingEmailConsent === 'true', smsConsent: marketingSmsConsent === 'true' },
                });
              }
            } catch { /* best effort */ }
          }

          return successResponse({
            authenticated: true, method: 'sms_otp', username: wifiUsername,
            sessionTimeout: portalSessionTimeoutMin, bandwidthDown: bwDown, bandwidthUp: bwUp,
            poolName: smsPool.poolName, message: 'Connected successfully!',
          });
        } else {
          // ── Step 1: Send OTP ──
          if (!phoneNumber?.trim()) {
            return errorResponse('MISSING_PHONE', 'Please enter your phone number');
          }

          const normalizedPhone = normalizePhoneNumberLocal(phoneNumber.trim());

          // Validate phone number format
          if (!isValidPhoneNumber(phoneNumber.trim())) {
            return errorResponse('INVALID_PHONE', 'Please enter a valid phone number (10-15 digits).');
          }

          // Per-phone rate limiting (prevent OTP bombing)
          const rateCheck = checkOtpRateLimit(normalizedPhone);
          if (!rateCheck.allowed) {
            return errorResponse(
              'OTP_RATE_LIMITED',
              `Too many OTP requests. Please try again in ${rateCheck.retryAfterSec} seconds.`,
              429,
            );
          }

          const code = generateOtp();

          otpStore.set(normalizedPhone, {
            code,
            expiresAt: Date.now() + 5 * 60 * 1000,
            phone: normalizedPhone,
            attempts: 0,
          });

          // ── Actually send the OTP via SMS ──
          let smsSent = false;
          let smsError: string | undefined;

          try {
            const tenantId = portal?.tenantId || '';
            const result = await sendSMSNow({
              to: normalizedPhone,
              message: `Your StaySuite WiFi verification code is: ${code}. Valid for 5 minutes. Do not share this code.`,
              tenantId: tenantId || undefined,
            });
            smsSent = result.success;
            if (!result.success) {
              smsError = result.error;
              console.error(`[SMS OTP] Failed to send to ${normalizedPhone}: ${smsError}`);
            } else {
              console.log(`[SMS OTP] Sent via ${result.provider} to ${normalizedPhone} (messageId: ${result.messageId})`);
            }
          } catch (err) {
            smsError = err instanceof Error ? err.message : 'SMS delivery failed';
            console.error(`[SMS OTP] Exception sending to ${normalizedPhone}:`, smsError);
          }

          // Always return success if OTP was generated (even if SMS delivery failed,
          // the debug OTP is always available in the response — prevents locking out guests
          // when SMS provider has temporary issues)
          //
          // Always log the full OTP for testing / debugging (visible in dev.log)
          console.log(`[SMS OTP] ═══════════════════════════════════════════════════════`);
          console.log(`[SMS OTP] ★ DEBUG OTP for ${normalizedPhone}: ${code}`);
          console.log(`[SMS OTP]   Expires: 5 min | SMS Sent: ${smsSent} | Provider: ${smsSent ? 'ok' : 'N/A'}`);
          console.log(`[SMS OTP] ═══════════════════════════════════════════════════════`);

          return NextResponse.json({
            success: true,
            data: {
              otpSent: smsSent,
              message: smsSent
                ? 'OTP sent to your phone'
                : 'OTP generated but SMS delivery failed. Please try again.',
              // Always expose OTP for testing without SMS gateway
              // In production with a real SMS gateway, this is harmless —
              // the guest receives the OTP via SMS and ignores this field.
              _debugOtp: code,
              _smsSent: smsSent,
              ...(!smsSent && smsError && { _error: smsError }),
            },
          });
        }
      }

      // ─── Open Access ──────────────────────────────────────
      // No credential validation needed — only IP pool check
      case 'open_access': {
        const pool = await getValidatedPool(request, resolveAllowedPoolIds(portalPlanIpPoolId, undefined, !!portalPlanIpPoolId));
        if (!pool) {
          await logAuthAttempt('open-access', 'Access-Reject', request, `IP_NOT_IN_POOL:${getClientIpString(request)}`);
          return errorResponse('IP_NOT_IN_POOL', 'Your device is not connected to a managed WiFi network. Please connect to the hotel WiFi and try again.', 403);
        }

        const now = new Date();
        const validUntil = new Date(now.getTime() + portalSessionTimeoutMin * 60 * 1000);
        let wifiUsername: string | null = null;

        if (portal) {
          const openTimestamp = Date.now();
          wifiUsername = `open-${openTimestamp}`;
          const openPassword = `open-${openTimestamp}`;

          try {
            const resolvedPropertyId = portal.propertyId
              || await db.property.findFirst({ where: { tenantId: portal.tenantId }, select: { id: true } }).then(p => p?.id);

            if (resolvedPropertyId) {
              // Resolve plan bandwidth for open access users (AAA default plan if configured)
              let openPlanDnKbps = bwDown * 1000;  // kbps
              let openPlanUpKbps = bwUp * 1000;    // kbps
              const aaaConfig = await db.wiFiAAAConfig.findUnique({
                where: { propertyId: resolvedPropertyId },
                select: { defaultPlanId: true },
              }).catch(() => null);
              if (aaaConfig?.defaultPlanId) {
                const openPlan = await db.wiFiPlan.findUnique({
                  where: { id: aaaConfig.defaultPlanId },
                  select: { downloadSpeed: true, uploadSpeed: true },
                }).catch(() => null);
                if (openPlan?.downloadSpeed && openPlan.downloadSpeed > 0) {
                  openPlanDnKbps = openPlan.downloadSpeed * 1000;  // Mbps → kbps
                  openPlanUpKbps = openPlan.uploadSpeed * 1000;
                }
              }

              await wifiUserService.provisionUser({
                tenantId: portal.tenantId,
                propertyId: resolvedPropertyId,
                username: wifiUsername,
                password: openPassword,
                validFrom: now,
                validUntil,
                userType: 'guest',
                downloadSpeed: openPlanDnKbps * 1000,  // kbps → bits/sec for RADIUS
                uploadSpeed: openPlanUpKbps * 1000,
                sessionTimeoutMinutes: portalSessionTimeoutMin,
                idleTimeoutSeconds: portal?.idleTimeout,
              });

              // Check concurrent session limit (open access users get default 1)
              if (await isSessionLimitReached(wifiUsername, 1)) {
                await logAuthAttempt(wifiUsername, 'Access-Reject', request, 'MAX_SESSIONS_REACHED');
                return errorResponse('MAX_SESSIONS_REACHED', 'Maximum concurrent sessions reached. Please disconnect another device first.');
              }

              const radiusResult = await radiusAuth(wifiUsername, openPassword);
              if (!radiusResult.accepted) {
                await logAuthAttempt(wifiUsername, 'Access-Reject', request, radiusResult.rejectReason || 'AUTH_FAILED');
                return errorResponse(radiusResult.rejectReason || 'AUTH_FAILED', getRejectMessage(radiusResult.rejectReason || 'AUTH_FAILED'));
              }

              await logAuthAttempt(wifiUsername, 'Access-Accept', request, `pool:${pool.poolName}`);
              const sessionId = await createAccountingSession(wifiUsername, request, 'portal', effectiveMac, pool);

              await activateUserFirewall({
                username: wifiUsername, clientIp: getClientIpString(request),
                propertyId: resolvedPropertyId, sessionId,
                macAddress: effectiveMac,
                dnKbps: openPlanDnKbps,
                upKbps: openPlanUpKbps,
                subnet: pool.subnet,
              });

              // Add per-IP byte counter rules for session engine tracking
              const openCounterIp = normalizeIp(getClientIpString(request));
              if (openCounterIp && openCounterIp !== '0.0.0.0') {
                addUserCounter(openCounterIp);
              }
            }
          } catch {
            // Best effort for open access
          }

          // Save guest info from portal form
          saveGuestInfoAfterAuth({
            wifiUsername,
            propertyId: resolvedPropertyId,
            guestInfo: normalizedGuestInfo,
            marketingConsent: { emailConsent: marketingEmailConsent === 'true', smsConsent: marketingSmsConsent === 'true' },
          }).catch(() => {});
        }

        return successResponse({
          authenticated: true, method: 'open_access', username: wifiUsername,
          sessionTimeout: portalSessionTimeoutMin, bandwidthDown: bwDown, bandwidthUp: bwUp,
          poolName: pool.poolName, message: 'Connected successfully!',
        });
      }

      default: {
        return errorResponse('INVALID_METHOD', 'Unsupported authentication method');
      }
    }
  } catch (error) {
    console.error('[Guest Auth API] Error:', error);
    return errorResponse('INTERNAL_ERROR', 'An unexpected error occurred. Please try again or contact front desk.');
  }
}

// ────────────────────────────────────────────────────────────
// Helpers
// ────────────────────────────────────────────────────────────

function successResponse(data: Record<string, unknown>) {
  return NextResponse.json({ success: true, data });
}

function errorResponse(code: string, message: string, status = 400) {
  return NextResponse.json(
    { success: false, error: { code, message } },
    { status }
  );
}

// ────────────────────────────────────────────────────────────
// Guest Info Persistence
// ────────────────────────────────────────────────────────────

interface GuestInfoPayload {
  firstName?: string;
  lastName?: string;
  email?: string;
  phone?: string;
  passport?: string;
  bookingId?: string;
}

interface MarketingConsent {
  emailConsent?: boolean;
  smsConsent?: boolean;
}

/**
 * Save guest information collected from the captive portal form.
 * Called AFTER successful authentication in all flows.
 *
 * Strategy:
 *  1. If wifiUserId is known, look up the WiFiUser → get guestId/propertyId/tenantId
 *  2. If guestId exists, UPDATE the existing Guest record (enrich profile)
 *  3. If no guestId, CREATE a new Guest record (for SMS OTP / voucher / open_access guests)
 *  4. Link the new Guest to the WiFiUser via guestId
 *  5. Save passport as idNumber/idType on the Guest record
 *  6. If bookingId provided and no booking linked, try to link
 *  7. Update marketing consent flags (emailOptIn / smsOptIn)
 *
 * All operations are best-effort — failures are logged but don't block auth.
 */
async function saveGuestInfoAfterAuth(params: {
  wifiUserId?: string | null;
  wifiUsername?: string | null;
  tenantId?: string;
  propertyId?: string;
  guestId?: string | null;
  bookingId?: string | null;
  guestInfo?: GuestInfoPayload;
  marketingConsent?: MarketingConsent;
}): Promise<void> {
  const { wifiUserId, wifiUsername, tenantId, propertyId, guestId: existingGuestId, bookingId: existingBookingId, guestInfo, marketingConsent } = params;

  if (!guestInfo && !marketingConsent) return;

  try {
    // Resolve tenantId/propertyId from WiFiUser if not directly available
    let resolvedTenantId = tenantId;
    let resolvedPropertyId = propertyId;
    let resolvedGuestId = existingGuestId;
    let resolvedBookingId = existingBookingId;
    let resolvedWifiUserId = wifiUserId;

    // Look up WiFiUser by ID or by username
    if (!resolvedWifiUserId && wifiUsername) {
      const userByUname = await db.wiFiUser.findUnique({
        where: { username: wifiUsername },
        select: { id: true, tenantId: true, propertyId: true, guestId: true, bookingId: true },
      });
      if (userByUname) {
        resolvedWifiUserId = userByUname.id;
        resolvedTenantId = resolvedTenantId || userByUname.tenantId;
        resolvedPropertyId = resolvedPropertyId || userByUname.propertyId;
        resolvedGuestId = resolvedGuestId || userByUname.guestId;
        resolvedBookingId = resolvedBookingId || userByUname.bookingId;
      }
    }

    if (resolvedWifiUserId && (!resolvedTenantId || !resolvedPropertyId || !resolvedGuestId)) {
      const wifiUser = await db.wiFiUser.findUnique({
        where: { id: resolvedWifiUserId },
        select: { tenantId: true, propertyId: true, guestId: true, bookingId: true },
      });
      if (wifiUser) {
        resolvedTenantId = resolvedTenantId || wifiUser.tenantId;
        resolvedPropertyId = resolvedPropertyId || wifiUser.propertyId;
        resolvedGuestId = resolvedGuestId || wifiUser.guestId;
        resolvedBookingId = resolvedBookingId || wifiUser.bookingId;
      }
    }

    if (!resolvedTenantId || !resolvedPropertyId) {
      console.warn('[GuestInfo] Skipped — no tenantId/propertyId resolved');
      return;
    }

    const updates: Record<string, unknown> = {};
    const createData: Record<string, unknown> = { tenantId: resolvedTenantId, firstName: '', lastName: '' };

    if (guestInfo) {
      if (guestInfo.firstName?.trim()) {
        updates.firstName = guestInfo.firstName.trim();
        createData.firstName = guestInfo.firstName.trim();
      }
      if (guestInfo.lastName?.trim()) {
        updates.lastName = guestInfo.lastName.trim();
        createData.lastName = guestInfo.lastName.trim();
      }
      if (guestInfo.email?.trim()) {
        updates.email = guestInfo.email.trim().toLowerCase();
        createData.email = guestInfo.email.trim().toLowerCase();
      }
      if (guestInfo.phone?.trim()) {
        updates.phone = guestInfo.phone.trim();
        createData.phone = guestInfo.phone.trim();
      }
      if (guestInfo.passport?.trim()) {
        // Save passport/ID as idType + idNumber on Guest
        updates.idType = 'passport';
        updates.idNumber = guestInfo.passport.trim();
        createData.idType = 'passport';
        createData.idNumber = guestInfo.passport.trim();
      }
    }

    if (marketingConsent) {
      if (marketingConsent.emailConsent) {
        updates.emailOptIn = true;
        createData.emailOptIn = true;
      }
      if (marketingConsent.smsConsent) {
        updates.smsOptIn = true;
        createData.smsOptIn = true;
      }
    }

    // Skip if nothing to save
    if (Object.keys(updates).length === 0 && !resolvedGuestId) return;

    if (resolvedGuestId) {
      // Update existing guest record
      await db.guest.update({
        where: { id: resolvedGuestId },
        data: updates,
      });
      console.log(`[GuestInfo] Updated guest ${resolvedGuestId} with ${Object.keys(updates).join(', ')}`);
    } else {
      // Create new guest for anonymous auth flows (SMS OTP, voucher, open_access)
      const newGuest = await db.guest.create({
        data: createData,
      });
      resolvedGuestId = newGuest.id;
      console.log(`[GuestInfo] Created guest ${resolvedGuestId} (${createData.firstName} ${createData.lastName})`);

      // Link guest to WiFiUser
      if (resolvedWifiUserId) {
        await db.wiFiUser.update({
          where: { id: resolvedWifiUserId },
          data: { guestId: resolvedGuestId },
        });
      }
    }

    // If guestInfo.bookingId provided and no booking linked to WiFiUser, try to link
    if (guestInfo?.bookingId?.trim() && resolvedWifiUserId) {
      const bookingRef = guestInfo.bookingId.trim();
      // Try matching by confirmationCode first, then by ID
      const booking = await db.booking.findFirst({
        where: {
          OR: [
            { confirmationCode: bookingRef },
            { id: bookingRef },
            { externalRef: bookingRef },
          ],
          propertyId: resolvedPropertyId,
        },
        select: { id: true },
      });
      if (booking) {
        await db.wiFiUser.update({
          where: { id: resolvedWifiUserId },
          data: { bookingId: booking.id },
        });
        console.log(`[GuestInfo] Linked booking ${booking.id} to WiFiUser ${resolvedWifiUserId}`);
      } else {
        console.warn(`[GuestInfo] Booking not found for ref: ${bookingRef}`);
      }
    }
  } catch (err) {
    // Non-fatal — guest info persistence should never block authentication
    console.error('[GuestInfo] Failed to save guest info:', err instanceof Error ? err.message : err);
  }
}

/**
 * Validate client IP and check it belongs to an allocated pool.
 * Called AFTER credential validation, BEFORE RADIUS auth.
 * Returns the matched pool or null.
 *
 * @param request - Next.js request object
 * @param allowedPoolIds - Optional list of pool IDs the user is allowed to use.
 *   Derived from WiFiPlan.ipPoolId or WiFiUser.ipPoolId.
 *   If provided and non-empty, the client IP must belong to one of these pools.
 *   If null/empty, any captive portal pool is allowed (backward compatible).
 */
async function getValidatedPool(request: NextRequest, allowedPoolIds?: string[] | 'ANY' | null): Promise<MatchedPool | null> {
  const rawIp = extractClientIp(request);
  const clientIp = normalizeIp(rawIp);

  if (!clientIp || clientIp === '127.0.0.1' || clientIp === '::1') {
    // Cannot determine real client IP — happens in sandbox/dev/proxy environments
    // where the reverse proxy doesn't forward the original client IP.
    // Fall through to pool validation with the raw IP (will likely not match any pool).
    // If no pool match, allow auth anyway (sandbox-safe behavior).
    console.warn(`[Guest Auth] IP pool check: client IP is ${clientIp || 'null'} (sandbox/proxy env) — skipping pool validation`);
    return {
      poolId: 'sandbox',
      poolName: 'Sandbox',
      subnet: null,
      gateway: null,
      captivePortal: true,
      isDefault: true,
    };
  }

  // No restriction (no plan) → skip pool validation entirely
  if (allowedPoolIds === null) {
    return {
      poolId: 'unrestricted',
      poolName: 'Unrestricted',
      subnet: null,
      gateway: null,
      captivePortal: false,
      isDefault: false,
    };
  }

  const pool = await validateClientIpInPool(clientIp, allowedPoolIds);
  if (!pool) {
    if (Array.isArray(allowedPoolIds)) {
      console.warn(`[Guest Auth] IP pool check REJECTED: ${clientIp} is not in any allowed pool (allowed: [${allowedPoolIds.join(', ')}])`);
    } else {
      console.warn(`[Guest Auth] IP pool check REJECTED: ${clientIp} is not in any allocated IP pool`);
    }
    return null;
  }

  console.log(`[Guest Auth] IP pool check PASSED: ${clientIp} → pool "${pool.poolName}" (${pool.subnet || 'no subnet'})${Array.isArray(allowedPoolIds) ? ' [plan-restricted]' : ''}`);
  return pool;
}

/**
 * Provision a RADIUS user, or resume an existing one if provisioning fails.
 * Reduces code duplication across auth methods.
 */
async function provisionOrResumeUser(
  wifiUsername: string,
  now: Date,
  validUntil: Date,
  params: {
    tenantId: string;
    propertyId: string;
    guestId?: string;
    bookingId?: string;
    username: string;
    password: string;
    planId?: string;
    planName?: string;
    downloadSpeed: number;
    uploadSpeed: number;
    sessionTimeoutMinutes: number;
    idleTimeoutSeconds?: number;
    sessionLimit?: number;
    dataLimit?: number;
  }
) {
  try {
    await wifiUserService.provisionUser({ ...params, validFrom: now, validUntil });
  } catch (provisionErr) {
    console.error('[Guest Auth] RADIUS provisioning failed:', provisionErr);
    try {
      const existingUser = await db.wiFiUser.findUnique({ where: { username: wifiUsername } });
      if (existingUser) {
        await db.wiFiUser.update({
          where: { id: existingUser.id },
          data: {
            status: 'active',
            validFrom: now,
            validUntil,
            radiusSynced: true,
            radiusSyncedAt: now,
          },
        });
      }
    } catch {
      // Best effort
    }
  }
}

/**
 * Write an auth log to RadPostAuth table.
 * This feeds the v_auth_logs view → Auth Logs dashboard tab.
 *
 * IMPORTANT: We populate BOTH clientipaddress AND "nasIpAddress" columns.
 * - clientipaddress: the real client IP (from HTTP headers) — used by v_auth_logs
 *   to show "Source IP" in reject messages and the source_ip_address column.
 * - "nasIpAddress": also set to the client IP so the view's nas_ip_address column
 *   is populated even for application-level rejects (not just RADIUS rejects).
 * - pass: stores the rejection reason code (e.g., IP_NOT_IN_POOL:1.2.3.4,
 *   INVALID_CREDENTIALS, ACCOUNT_EXPIRED) so v_auth_logs can build descriptive
 *   reply_message strings.
 */
/**
 * Convert a rejection reason code (stored in radpostauth.pass) to a
 * human-readable message for the replyMessage column.
 */
function getRejectMessageFromCode(code: string): string | null {
  if (code.startsWith('IP_NOT_IN_POOL:')) return `IP not in managed pool: ${code.replace('IP_NOT_IN_POOL:', '')}`;
  if (code === 'IP_NOT_DETERMINED') return 'Could not determine client IP';
  if (code.startsWith('MAX_SESSION')) return 'Max concurrent sessions reached';
  if (code === 'RADIUS_UNREACHABLE') return 'RADIUS server unreachable';
  if (code.startsWith('ACCOUNT_')) return code.replace(/_/g, ' ').toLowerCase();
  if (code.startsWith('INVALID_') || code.startsWith('MISSING_') || code.startsWith('VOUCHER_') || code.startsWith('AUTH_')) return code.replace(/_/g, ' ').toLowerCase();
  return null;
}

async function logAuthAttempt(
  username: string,
  reply: string,
  request: NextRequest,
  extraInfo?: string,
  macAddress?: string,
) {
  try {
    const clientIp = request.headers.get('x-forwarded-for')?.split(',')[0]?.trim()
      || request.headers.get('x-real-ip')
      || '';

    // Resolve MAC: use provided MAC, then fall back to DeviceProfile lookup
    let effectiveMac = macAddress || null;
    if (!effectiveMac) {
      try {
        const wifiUser = await db.wiFiUser.findUnique({ where: { username }, select: { id: true } });
        if (wifiUser) {
          const dp = await db.deviceProfile.findFirst({
            where: { wifiUserId: wifiUser.id, isActive: true, macAddress: { not: null } },
            select: { macAddress: true },
            orderBy: { lastSeenAt: 'desc' },
          });
          if (dp?.macAddress) effectiveMac = dp.macAddress;
        }
      } catch { /* non-fatal */ }
    }

    // clientipaddress = real client IP (from HTTP headers)
    // "nasIpAddress" = 127.0.0.1 for captive portal (the app itself IS the NAS)
    await db.$executeRawUnsafe(
      `INSERT INTO radpostauth (username, pass, reply, authdate, clientipaddress, "nasIpAddress", callingstationid, "replyMessage")
       VALUES ($1, $2, $3, NOW(), $4, '127.0.0.1', $5, $6)`,
      username,
      extraInfo || '',
      reply,
      clientIp,
      effectiveMac,
      extraInfo ? getRejectMessageFromCode(extraInfo) : null,
    );
  } catch (err) {
    // Non-fatal — auth logging failure should not block authentication
    console.error('[Guest Auth] Failed to write auth log:', err);
  }
}

/**
 * Create an accounting session in RadAcct table.
 * This feeds the v_active_sessions view → Active Users dashboard tab.
 *
 * The session is marked as 'start' with no stop time (acctstoptime = NULL),
 * which is how FreeRADIUS represents an active session.
 *
 * @param loginType - 'portal' for manual login, 'auto_reauth' for silent re-auth
 */
async function createAccountingSession(
  username: string,
  request: NextRequest,
  loginType: string = 'portal',
  macAddress?: string,
  pool?: MatchedPool | null
): Promise<string> {
  try {
    const clientIp = request.headers.get('x-forwarded-for')?.split(',')[0]?.trim()
      || request.headers.get('x-real-ip')
      || '0.0.0.0';

    const now = new Date();
    const acctSessionId = `${Date.now()}-${randomUUID().slice(0, 8)}`;
    const acctUniqueId = randomUUID();

    // Normalize MAC address format: strip separators, uppercase
    const normalizedMac = macAddress
      ? macAddress.replace(/[:\-\.\s]/g, '').toUpperCase()
      : null;
    // Reformat as AA:BB:CC:DD:EE:FF for RADIUS compatibility
    let formattedMac = normalizedMac && normalizedMac.length === 12
      ? normalizedMac.match(/.{2}/g)?.join(':') || null
      : null;

    // Fallback: if no MAC from request, look up DeviceProfile for this user
    if (!formattedMac) {
      try {
        const wifiUser = await db.wiFiUser.findUnique({ where: { username }, select: { id: true } });
        if (wifiUser) {
          const dp = await db.deviceProfile.findFirst({
            where: { wifiUserId: wifiUser.id, isActive: true, macAddress: { not: null } },
            select: { macAddress: true },
            orderBy: { lastSeenAt: 'desc' },
          });
          if (dp?.macAddress) formattedMac = dp.macAddress;
        }
      } catch { /* non-fatal */ }
    }

    // Build connect-info with pool details for audit trail
    const connectInfoStart = pool
      ? `pool_id=${pool.poolId}|pool_name=${pool.poolName}|subnet=${pool.subnet || 'none'}|gateway=${pool.gateway || 'none'}`
      : '';

    await db.$executeRawUnsafe(
      `INSERT INTO radacct (
         acctuniqueid, acctsessionid, username,
         nasipaddress, nasporttype, acctstarttime, acctupdatetime,
         acctauthentic, framedipaddress, acctstatus,
         acctinputoctets, acctoutputoctets, acctsessiontime,
         calledstationid, callingstationid,
         "loginType", connectinfo_start, createdat, updatedat
       ) VALUES (
         $1, $2, $3,
         $4, 'Wireless-802.11', $5, $5,
         'PAP', $6, 'start',
         0, 0, 0,
         '00:00:00:00:00:01', $8,
         $7, $9, NOW(), NOW()
       )`,
      acctUniqueId,
      acctSessionId,
      username,
      '127.0.0.1', // NAS IP (this device is the gateway)
      now,
      clientIp,
      loginType,
      formattedMac,
      connectInfoStart
    );

    // Return the session ID so it can be passed to the login script
    return acctSessionId;
  } catch (err) {
    // Non-fatal — accounting failure should not block authentication
    console.error('[Guest Auth] Failed to create accounting session:', err);
    return '';
  }
}
