#!/bin/bash
##################################################################################
#  StaySuite HospitalityOS — Generate DGD Configuration                         #
#  Reads Gateway + GatewayHealthRule from PostgreSQL, generates /etc/dgd/dgd.conf#
#  Updated: tblgateway → Gateway, tbldgdgatewayrule → GatewayHealthRule         #
#  Note: action string is stored in a properties file, not in DB                #
##################################################################################

. /etc/staysuite/dgd/env.sh

GATEWAY_FILE=$DGD_DIR/gateway.tmp
TMP_CONDITION=$DGD_DIR/condition.tmp
ACTION_PROP=$DGD_DIR/gateway_actions.properties

echo "# File: dgd.conf — Auto-generated by StaySuite DGD" > ${DGD_CONF}.tmp
echo "# Generated on: `date`" >> ${DGD_CONF}.tmp
echo "" >> ${DGD_CONF}.tmp
echo "script live_to_dead /sbin/arp -s GWIP GWMAC" >> ${DGD_CONF}.tmp
echo "script dead_to_live /sbin/ip neigh replace GWIP lladdr GWMAC dev GWIFNAME nud reachable" >> ${DGD_CONF}.tmp
echo "" >> ${DGD_CONF}.tmp

# Read ping timeout from MultiWanConfig
ping_timeout=`db_query "SELECT \"pingTimeout\" FROM \"MultiWanConfig\" WHERE enabled = true LIMIT 1;" | awk '{print $1}'`
ping_timeout=${ping_timeout:-10}
echo "timeout ping $ping_timeout" >> ${DGD_CONF}.tmp
echo "timeout traceroute 60" >> ${DGD_CONF}.tmp
echo "timeout loop 60" >> ${DGD_CONF}.tmp
echo "" >> ${DGD_CONF}.tmp

# ── Fetch all gateways: id (UUID), ipAddress ──
db_query "SELECT id, \"ipAddress\" FROM \"Gateway\"
           WHERE \"multiWanConfigId\" = (
             SELECT id FROM \"MultiWanConfig\" WHERE enabled = true LIMIT 1
           )
           ORDER BY \"routingTableId\";" | awk 'NF' > $GATEWAY_FILE

rm -f $ACTION_PROP

cat $GATEWAY_FILE | while read line
do
        gateway_uuid=`echo $line | awk -F',' '{print $1}' | tr -d ' '`
        gateway_ip=`echo $line | awk -F',' '{print $2}' | tr -d ' '`

        echo "# Gateway: $gateway_ip" >> ${DGD_CONF}.tmp
        echo "{" >> ${DGD_CONF}.tmp
        echo -e "\t$gateway_ip" >> ${DGD_CONF}.tmp

        # ── Fetch health rules for this gateway ──
        # Protocol, Host, Port, sortOrder (used for numbering)
        db_query "SELECT protocol, host, port, \"sortOrder\"
                   FROM \"GatewayHealthRule\"
                   WHERE \"gatewayId\" = '$gateway_uuid'
                   ORDER BY \"sortOrder\";" | awk 'NF' | tr -d ' ' | \
        sed -e 's/,/ /g' -e 's/PING/ping/g' -e 's/TCP/tcp/g' | \
        awk '{printf "\trule %s %s %s %s\n", $1, $2, $3, $4}' >> ${DGD_CONF}.tmp

        # ── Build action string based on operators ──
        # Action = !(!(1) !(2) !(3) )  meaning: gateway FAILS if ANY health check fails
        echo -en "\taction =  !(" >> ${DGD_CONF}.tmp

        # Read operators (skip first rule's operator which is empty/separator)
        db_query "SELECT operator FROM \"GatewayHealthRule\"
                   WHERE \"gatewayId\" = '$gateway_uuid'
                   ORDER BY \"sortOrder\";" | awk 'NF' | tr -d ' ' | sed '1d' > $TMP_CONDITION

        action="!(!1 "
        iterator=1
        while read line
        do
                # Convert & to space (for display), but keep in action string
                echo -n "!$(expr $iterator + 1) $line " >> ${DGD_CONF}.tmp
                action=$action"!$(expr $iterator + 1) $line "
                iterator=`expr $iterator + 1`
        done < $TMP_CONDITION

        echo "!$(expr $iterator + 1) )" >> ${DGD_CONF}.tmp
        action=$action"!$(expr $iterator + 1) )"

        echo "}" >> ${DGD_CONF}.tmp
        echo "" >> ${DGD_CONF}.tmp

        # Store action string in properties file (keyed by gateway UUID)
        echo "${gateway_uuid}.action=$action" >> $ACTION_PROP
        echo "Generated action for $gateway_ip : $action" >> $LOGFILE
done

echo "# Last Updated on: `date`" >> ${DGD_CONF}.tmp
echo "# End of File" >> ${DGD_CONF}.tmp
mv -f ${DGD_CONF}.tmp $DGD_CONF

echo "`date` : dgd.conf generated successfully" >> $LOGFILE
echo "DGD configuration generated at $DGD_CONF"
