// Apply Arabic translations for 538 remaining keys
import fs from 'fs';

function deepSet(obj, path, val) {
  const parts = path.split('.');
  let cur = obj;
  for (let i = 0; i < parts.length - 1; i++) {
    if (!(parts[i] in cur) || typeof cur[parts[i]] !== 'object') cur[parts[i]] = {};
    cur = cur[parts[i]];
  }
  cur[parts[parts.length - 1]] = val;
}

const translations = {
  "pos.guestPhonePlaceholder": "+1 555 123 4567",
  "reports.excel": "إكسل",
  "marketing.bookyourhotelcom": "book.yourhotel.com",
  "notifications.saveChanges": "حفظ التغييرات",
  "notifications.enableEmailNotifications": "تفعيل إشعارات البريد الإلكتروني",
  "notifications.fromAddress": "عنوان المرسل",
  "notifications.trackOpens": "تتبع فتح الرسائل",
  "notifications.fromNumber": "من الرقم",
  "notifications.pushNotifications": "الإشعارات الفورية",
  "notifications.enablePushNotifications": "تفعيل الإشعارات الفورية",
  "notifications.quietHours": "ساعات الهدوء",
  "notifications.enableQuietHours": "تفعيل ساعات الهدوء",
  "notifications.startTime": "وقت البدء",
  "notifications.endTime": "وقت الانتهاء",
  "notifications.notificationTriggers": "محفزات الإشعارات",
  "integrations.usdEurGbp": "USD, EUR, GBP",
  "integrations.pkxxxxx": "pk_xxxxx",
  "integrations.skxxxxx": "sk_xxxxx",
  "integrations.pkxxxxx_1": "pk_xxxxx",
  "integrations.skxxxxx_1": "sk_xxxxx",
  "integrations.thirdpartyApis": "واجهات برمجة التطبيقات الخارجية",
  "integrations.apiKey_4": "مفتاح واجهة البرمجة",
  "integrations.rateLimit": "حد المعدل",
  "integrations.perMinute": "في الدقيقة",
  "integrations.perHour": "في الساعة",
  "integrations.perDay": "في اليوم",
  "integrations.perMonth": "في الشهر",
  "integrations.apiKeyCopiedToClipboard": "تم نسخ مفتاح واجهة البرمجة إلى الحافظة",
  "integrations.wifiGateways": "بوابات الواي فاي",
  "integrations.gatewayName_3": "اسم البوابة",
  "integrations.controllerType": "نوع المتحكم",
  "integrations.apiKey_5": "مفتاح واجهة البرمجة",
  "integrations.syncIntervalMin": "فترة المزامنة (دقيقة)",
  "integrations.autoSync": "مزامنة تلقائية",
  "integrations.saveGateway_2": "حفظ البوابة",
  "integrations.connectedGateways": "البوابات المتصلة",
  "integrations.bandwidthUsage": "استخدام عرض النطاق",
  "integrations.accessPoints": "نقاط الوصول",
  "integrations.syncNow_1": "مزامنة الآن",
  "integrations.myWifiController": "جهاز التحكم بالواي فاي",
  "integrations.serverRoomBuildingA": "غرفة الخادم، المبنى أ",
  "webhooks.webhookDelivery": "تسليم الويب هوك",
  "webhooks.deliveredAt": "تم التسليم في",
  "webhooks.webhookEndpoints": "نقاط نهاية الويب هوك",
  "webhooks.secretKey": "المفتاح السري",
  "webhooks.saveEndpoint": "حفظ نقطة النهاية",
  "webhooks.avgSuccessRate": "متوسط معدل النجاح",
  "webhooks.eventTypes": "أنواع الأحداث",
  "webhooks.successRate": "معدل النجاح",
  "webhooks.lastTriggered": "آخر تفعيل",
  "webhooks.secret": "السري",
  "webhooks.subscribedEvents": "الأحداث المشتركة",
  "webhooks.myWebhook": "الويب هوك الخاص بي",
  "webhooks.secretCopiedToClipboard": "تم نسخ المفتاح السري إلى الحافظة",
  "webhooks.retryQueue": "قائمة إعادة المحاولة",
  "webhooks.pendingRetry": "في انتظار إعادة المحاولة",
  "webhooks.failedMaxAttempts": "فشل (الحد الأقصى للمحاولات)",
  "webhooks.nextRetry": "إعادة المحاولة التالية",
  "webhooks.lastError": "آخر خطأ",
  "help.watchVideo": "مشاهدة الفيديو",
  "help.relatedArticles": "المقالات ذات الصلة",
  "help.contactSupport": "تواصل مع الدعم",
  "help.knowledgeBase": "قاعدة المعرفة",
  "help.newArticle": "مقال جديد",
  "help.newestFirst": "الأحدث أولاً",
  "help.oldestFirst": "الأقدم أولاً",
  "help.mostViewed": "الأكثر مشاهدة",
  "help.mostHelpful": "الأكثر فائدة",
  "help.clearFilters": "مسح الفلاتر",
  "help.gettingStarted": "البدء",
  "help.knowledgeBase_1": "قاعدة المعرفة",
  "help.helpCenter": "مركز المساعدة",
  "help.popularArticles": "المقالات الشائعة",
  "help.frequentlyAskedQuestions": "الأسئلة الشائعة",
  "help.stillNeedHelp": "هل تحتاج مساعدة؟",
  "help.contactSupport_1": "تواصل مع الدعم",
  "help.submitARequest": "تقديم طلب",
  "help.submitRequest": "إرسال الطلب",
  "help.helpCenter_1": "مركز المساعدة",
  "help.newArticle_1": "مقال جديد",
  "help.slug": "الرابط المختصر",
  "help.contentMarkdown": "المحتوى (ماركداون)",
  "help.restartTutorial": "إعادة تشغيل البرنامج التعليمي",
  "help.startTutorial": "بدء البرنامج التعليمي",
  "help.skipTutorial": "تخطي البرنامج التعليمي",
  "help.tutorialProgress": "تقدم البرنامج التعليمي",
  "help.yesReset": "نعم، إعادة تعيين",
  "help.resetAllProgress": "إعادة تعيين كل التقدم",
  "help.tutorialsAvailable": "البرامج التعليمية المتاحة",
  "help.inProgress": "قيد التنفيذ",
  "help.overallProgress": "التقدم العام",
  "help.availableTutorials": "البرامج التعليمية المتاحة",
  "help.startTutorial_1": "بدء البرنامج التعليمي",
  "help.reviewTutorial": "مراجعة البرنامج التعليمي",
  "parking.noPropertySelected": "لم يتم اختيار عقار",
  "parking.parkingBilling": "فوترة مواقف السيارات",
  "parking.checkin": "تسجيل الدخول",
  "parking.averageFee": "متوسط الرسوم",
  "parking.thisMonth": "هذا الشهر",
  "parking.clearFilters": "مسح الفلاتر",
  "parking.checkInVehicle": "تسجيل دخول مركبة",
  "parking.entryTime": "وقت الدخول",
  "parking.exitTime": "وقت الخروج",
  "parking.parkingFee": "رسوم المواقف",
  "parking.hourlyRate": "الساعة",
  "parking.dailyMax": "الحد الأقصى اليومي",
  "parking.paymentPending": "في انتظار الدفع",
  "parking.paymentComplete": "تم الدفع",
  "parking.recordPayment": "تسجيل الدفع",
  "parking.amountDue": "المبلغ المستحق",
  "parking.paymentMethod": "طريقة الدفع",
  "parking.newVehicleCheckin": "تسجيل دخول مركبة جديدة",
  "parking.parkingSlotOptional": "موقف السيارات (اختياري)",
  "parking.dailyMaxRate": "الحد الأقصى اليومي",
  "parking.recordExit": "تسجيل الخروج",
  "parking.licensePlate": "رقم اللوحة *",
  "parking.noPropertySelected_1": "لم يتم اختيار عقار",
  "parking.parkingSlots": "مواقف السيارات",
  "parking.slotNumber": "رقم الموقف",
  "parking.slotType": "نوع الموقف",
  "parking.vehicleType": "نوع المركبة",
  "parking.chargerType": "نوع الشاحن",
  "parking.parkedVehicle": "مركبة متوقفة",
  "parking.setAvailable": "تعيين كمتاح",
  "parking.noPropertySelected_2": "لم يتم اختيار عقار",
  "parking.vehicleTracking": "تتبع المركبات",
  "parking.logEntry": "تسجيل الدخول",
  "parking.currentlyParked": "متوقفة حالياً",
  "parking.exitedToday": "غادرت اليوم",
  "parking.entryTime_1": "وقت الدخول",
  "parking.logVehicleEntry": "تسجيل دخول مركبة",
  "parking.exitTime_1": "وقت الخروج",
  "parking.parkingFee_1": "رسوم المواقف",
  "parking.paymentPending_1": "في انتظار الدفع",
  "parking.licensePlate_1": "رقم اللوحة *",
  "iot.lastSeen": "آخر ظهور",
  "iot.unlockDoor": "فتح الباب",
  "iot.deviceName": "اسم الجهاز",
  "iot.deviceType": "نوع الجهاز",
  "iot.smartLock": "قفل ذكي",
  "iot.motorizedBlinds": "ستائر أوتوماتيكية",
  "iot.airConditioner": "مكيف الهواء",
  "iot.zigbee": "زيجبي",
  "iot.zwave": "زد-ويف",
  "iot.lockDoor": "قفل الباب",
  "iot.turnOff": "إيقاف التشغيل",
  "iot.turnOn": "تشغيل",
  "iot.energyDashboard": "لوحة الطاقة",
  "iot.carbonFootprint": "البصمة الكربونية",
  "iot.costSavings": "توفير التكاليف",
  "iot.carbonReduction": "تقليل الكربون",
  "iot.consumptionTrends": "اتجاهات الاستهلاك",
  "iot.costBreakdown": "تفصيل التكاليف",
  "iot.byProperty": "حسب العقار",
  "iot.dailyEnergyConsumption": "الاستهلاك اليومي للطاقة",
  "iot.carbonFootprintTrend": "اتجاه البصمة الكربونية",
  "iot.dailyCostTrend": "اتجاه التكلفة اليومية",
  "iot.electricityKwh": "الكهرباء (كيلوواط ساعة)",
  "iot.propertyComparison": "مقارنة العقارات",
  "iot.dailyAverages": "المتوسطات اليومية",
  "iot.avgElectricity": "متوسط الكهرباء",
  "iot.avgGas": "متوسط الغاز",
  "iot.avgWater": "متوسط المياه",
  "iot.avgDailyCost": "متوسط التكلفة اليومية",
  "iot.gasM": "الغاز (متر مكعب)",
  "iot.waterM": "المياه (متر مكعب)",
  "iot.fanSpeed": "سرعة المروحة",
  "iot.roomControls": "أدوات التحكم في الغرفة",
  "iot.sensorNoControls": "مستشعر - بدون أدوات تحكم",
  "iot.confirmDoorUnlock": "تأكيد فتح الباب",
  "iot.unlockDoor_1": "فتح الباب",
  "iot.quickActions": "إجراءات سريعة",
  "iot.morningMode": "وضع الصباح",
  "iot.nightMode": "وضع الليل",
  "chain.primaryColor": "اللون الأساسي",
  "chain.secondaryColor": "اللون الثانوي",
  "chain.grandHotels": "فنادق الكراند",
  "chain.brandName": "اسم العلامة التجارية *",
  "chain.brandCode": "رمز العلامة التجارية *",
  "chain.chainDashboard": "لوحة معلومات السلسلة",
  "chain.occupancyRate": "معدل الإشغال",
  "chain.monthlyBookings": "الحجوزات الشهرية",
  "chain.monthlyRevenue": "الإيرادات الشهرية",
  "chain.todayapossArrivals": "وصولات اليوم",
  "chain.todayapossDepartures": "مغادرات اليوم",
  "chain.propertyPerformance": "أداء العقار",
  "chain.brandDistribution": "توزيع العلامات التجارية",
  "chain.propertiesPerformance": "أداء العقارات",
  "chain.thisWeek": "هذا الأسبوع",
  "chain.thisMonth": "هذا الشهر",
  "chain.thisYear": "هذه السنة",
  "chain.avgOccupancy": "متوسط الإشغال",
  "chain.byProperty": "حسب العقار",
  "chain.byBrand": "حسب العلامة التجارية",
  "chain.bookingSources": "مصادر الحجوزات",
  "chain.guestDemographics": "الديموغرافيا النزلاء",
  "chain.propertyPerformanceComparison": "مقارنة أداء العقارات",
  "chain.revenueTrend": "اتجاه الإيرادات",
  "chain.propertyComparison": "مقارنة العقارات",
  "ads.adCampaigns": "الحملات الإعلانية",
  "ads.newCampaign": "حملة جديدة",
  "ads.budgetUsed": "الميزانية المستخدمة",
  "ads.basicInformation": "المعلومات الأساسية",
  "ads.campaignName": "اسم الحملة",
  "ads.campaignType": "نوع الحملة",
  "ads.budgetBidding": "الميزانية والمزايدة",
  "ads.budgetType": "نوع الميزانية",
  "ads.bidStrategy": "استراتيجية المزايدة",
  "ads.bidAmountOptional": "مبلغ المزايدة (اختياري)",
  "ads.startDate": "تاريخ البدء",
  "ads.endDate": "تاريخ الانتهاء",
  "ads.performanceTrend": "اتجاه الأداء",
  "ads.bidStrategy_1": "استراتيجية المزايدة",
  "ads.autoBidding": "مزايدة تلقائية",
  "ads.baseBidModifier": "معدل المزايدة الأساسي",
  "ads.lastPriceFeed": "آخر تغذية أسعار",
  "ads.lastBookingFeed": "آخر تغذية حجوزات",
  "ads.feedFormat": "تنسيق التغذية",
  "ads.connectionMode": "وضع الاتصال",
  "ads.performanceTracking": "تتبع الأداء",
  "ads.convRate": "معدل التحويل",
  "ads.performanceTrend_1": "اتجاه الأداء",
  "ads.conversionTrend": "اتجاه التحويل",
  "ads.dailyBreakdown": "التفصيل اليومي",
  "ads.netProfit": "صافي الربح",
  "ads.channelComparison": "مقارنة القنوات",
  "ads.trendInsights": "رؤى الاتجاهات",
  "ads.profitTrend": "اتجاه الربح",
  "portal.inProgress": "قيد التنفيذ",
  "portal.uploadFirstDocument": "رفع المستند الأول",
  "portal.uploadAnotherDocument": "رفع مستند آخر",
  "portal.uploadDocument": "رفع مستند",
  "portal.egPassportJohnDoe": "مثال، جواز سفر - أحمد محمد",
  "portal.documentType": "نوع المستند *",
  "portal.documentName": "اسم المستند *",
  "portal.documentFile": "ملف المستند *",
  "portal.termsSignature": "الشروط والتوقيع",
  "portal.termsAccepted": "تم قبول الشروط",
  "portal.yourSignature": "توقيعك",
  "portal.signAcceptTerms": "التوقيع وقبول الشروط",
  "portal.alternatePhone": "هاتف بديل",
  "portal.streetAddress": "العنوان",
  "portal.postalCode": "الرمز البريدي",
  "portal.newYork": "نيويورك",
  "portal.firstName": "الاسم الأول *",
  "portal.lastName": "اسم العائلة *",
  "portal.phoneNumber": "رقم الهاتف *",
  "portal.paymentSummary": "ملخص الدفع",
  "portal.balanceDue": "الرصيد المستحق",
  "portal.taxesFees": "الضرائب والرسوم",
  "portal.amountPaid": "المبلغ المدفوع",
  "portal.payNow": "ادفع الآن",
  "portal.paymentComplete": "تم الدفع",
  "portal.floorPreference": "تفضيل الطابق",
  "portal.bedType": "نوع السرير",
  "portal.pillowType": "نوع الوسادة",
  "portal.additionalRoomPreferences": "تفضيلات إضافية للغرفة",
  "portal.dietaryRequirements": "المتطلبات الغذائية",
  "portal.roomAmenities": "وسائل الراحة في الغرفة",
  "portal.preferredLanguage": "اللغة المفضلة",
  "portal.notificationPreferences": "تفضيلات الإشعارات",
  "gdpr.privacyNotice": "إشعار الخصوصية",
  "gdpr.acceptAll": "قبول الكل",
  "gdpr.rejectOptional": "رفض الاختياري",
  "gdpr.privacyPolicy": "سياسة الخصوصية",
  "gdpr.declineOptional": "رفض الاختياري",
  "gdpr.requestTypes": "أنواع الطلبات",
  "gdpr.exportData": "تصدير البيانات",
  "gdpr.exportGuestData": "تصدير بيانات النزيل؟",
  "gdpr.confirmExport": "تأكيد التصدير",
  "gdpr.anonymizeData": "إخفاء هوية البيانات",
  "gdpr.anonymizeGuestData": "إخفاء هوية بيانات النزيل؟",
  "gdpr.confirmAnonymization": "تأكيد إخفاء الهوية",
  "gdpr.softDelete": "حذف مؤقت",
  "gdpr.softDeleteGuestData": "حذف مؤقت لبيانات النزيل؟",
  "gdpr.confirmSoftDelete": "تأكيد الحذف المؤقت",
  "gdpr.hardDelete": "حذف نهائي",
  "gdpr.permanentlyDeleteGuestData": "حذف بيانات النزيل نهائياً؟",
  "gdpr.confirmPermanentDelete": "تأكيد الحذف النهائي",
  "gdpr.recordConsent": "تسجيل الموافقة",
  "audit.securityEvents": "أحداث الأمن",
  "audit.failedLogins": "محاولات الدخول الفاشلة",
  "audit.activityLog": "سجل النشاط",
  "audit.entityType": "نوع الكيان",
  "audit.userAgent": "وكيل المستخدم",
  "audit.oldValue": "القيمة القديمة",
  "audit.newValue": "القيمة الجديدة",
  "communication.changeStatus": "تغيير الحالة",
  "communication.assignTo": "تعيين إلى",
  "communication.quickReplies": "الردود السريعة:",
  "communication.messageTemplates": "قوالب الرسائل",
  "communication.insertLink": "إدراج رابط",
  "communication.bulletList": "قائمة نقطية",
  "communication.numberedList": "قائمة مرقمة",
  "communication.attachFile": "إرفاق ملف",
  "profile.personalInformation": "المعلومات الشخصية",
  "profile.firstName": "الاسم الأول",
  "profile.lastName": "اسم العائلة",
  "profile.jobTitle": "المسمى الوظيفي",
  "profile.newPassword": "كلمة المرور الجديدة",
  "profile.confirmPassword": "تأكيد كلمة المرور",
  "profile.twofactorAuthentication": "المصادقة الثنائية",
  "profile.authenticatorApp": "تطبيق المصادقة",
  "profile.emailNotifications": "إشعارات البريد الإلكتروني",
  "profile.pushNotifications": "الإشعارات الفورية",
  "profile.marketingEmails": "رسائل التسويق",
  "profile.darkMode": "الوضع الداكن",
  "profile.compactMode": "الوضع المضغوط",
  "profile.dateFormat": "تنسيق التاريخ",
  "frontdesk.todaysArrivalsCount": "وصولات اليوم",
  "frontdesk.checkedIn": "تم تسجيل الدخول",
  "frontdesk.checkInBtn": "تسجيل الدخول",
  "frontdesk.roomType": "نوع الغرفة",
  "frontdesk.assignedRoom": "الغرفة المخصصة",
  "frontdesk.roomsAvailable": "غرفة (غرف) متاحة {count}",
  "frontdesk.driverLicense": "رخصة القيادة",
  "frontdesk.wifiCredentials": "بيانات الواي فاي",
  "frontdesk.validUntil": "صالح حتى",
  "frontdesk.specialRequests": "طلبات خاصة",
  "frontdesk.specialRequestsLabel": "طلبات خاصة",
  "frontdesk.copiedToClipboard": "تم نسخ {label} إلى الحافظة",
  "frontdesk.couldNotCopy": "تعذر نسخ {label}",
  "frontdesk.validationError": "خطأ في التحقق",
  "frontdesk.checkInSuccessMsg": "تم تسجيل دخول النزيل إلى الغرفة {room}. بيانات الواي فاي جاهزة.",
  "frontdesk.seaView": "إطلالة بحرية",
  "frontdesk.mountainView": "إطلالة جبلية",
  "frontdesk.markClean": "تحديد كنظيفة",
  "frontdesk.markAvailable": "تحديد كمتاحة",
  "frontdesk.checkOut": "تسجيل الخروج",
  "frontdesk.quickActions": "إجراءات سريعة",
  "frontdesk.todaysDeparturesCount": "مغادرات اليوم",
  "frontdesk.checkingOut": "جاري تسجيل الخروج",
  "frontdesk.outstandingBalance": "الرصيد المتبقي",
  "frontdesk.outstandingBalanceAmount": "الرصيد المتبقي: {amount}",
  "frontdesk.checkOutBtn": "تسجيل الخروج",
  "frontdesk.stayDuration": "مدة الإقامة",
  "frontdesk.takePayment": "استلام الدفع",
  "frontdesk.paymentRecorded": "تم تسجيل الدفع",
  "frontdesk.paymentOf": "تم معالجة دفعة بمبلغ {amount}",
  "frontdesk.outstandingBalanceLabel": "الرصيد المتبقي",
  "frontdesk.paymentMethod": "طريقة الدفع",
  "frontdesk.referenceOptional": "المرجع (اختياري)",
  "frontdesk.recordPayment": "تسجيل الدفع",
  "frontdesk.guestCheckedOut": "تم تسجيل خروج النزيل من الغرفة {room}",
  "frontdesk.creditDebitCard": "بطاقة ائتمان/خصم",
  "frontdesk.bankTransfer": "تحويل بنكي",
  "frontdesk.digitalWallet": "محفظة رقمية",
  "frontdesk.nightsLabel": "{count} ليالي",
  "frontdesk.propertyAndRoom": "العقار والغرفة",
  "frontdesk.assignRoom": "تخصيص غرفة",
  "frontdesk.guestInformation": "معلومات النزيل",
  "frontdesk.existingGuest": "نزيل موجود",
  "frontdesk.stateProvince": "الولاية / المحافظة / المنطقة",
  "frontdesk.guestName": "اسم النزيل",
  "frontdesk.bookingSummary": "ملخص الحجز",
  "frontdesk.taxBreakdown": "تفصيل الضرائب",
  "frontdesk.serviceCharge": "رسوم الخدمة",
  "frontdesk.grandTotal": "المجموع الكلي",
  "frontdesk.guestCreationFailed": "فشل إنشاء النزيل",
  "frontdesk.bookingCreated": "تم إنشاء الحجز",
  "frontdesk.bookingFailed": "فشل الحجز",
  "frontdesk.roomGridTitle": "شبكة الغرف",
  "frontdesk.seaViewLegend": "إطلالة بحرية",
  "frontdesk.liveUpdate": "تحديث مباشر",
  "frontdesk.roomFeatures": "مميزات الغرفة",
  "frontdesk.roomBookingInfo": "معلومات حجز الغرفة",
  "frontdesk.connectionError": "خطأ في الاتصال",
  "frontdesk.roomStatusUpdated": "تم تحديث حالة الغرفة",
  "frontdesk.roomStatusUpdatedMsg": "الغرفة {id} أصبحت {status}",
  "frontdesk.roomAssignmentTitle": "تخصيص الغرفة",
  "frontdesk.unassignedBookings": "الحجوزات غير المخصصة",
  "frontdesk.availableRooms": "الغرف المتاحة",
  "frontdesk.arrivingToday": "القادمون اليوم",
  "frontdesk.compatibleRooms": "غرفة (غرف) متوافقة {count}",
  "frontdesk.assignRoomTitle": "تخصيص غرفة",
  "frontdesk.bookingInfo": "معلومات الحجز",
  "frontdesk.roomPreview": "معاينة الغرفة",
  "frontdesk.roomAssignmentSuccess": "تم تخصيص الغرفة",
  "frontdesk.roomAssignmentSuccessMsg": "تم تخصيص الغرفة {room} للحجز {code}",
  "frontdesk.allBookingsTab": "الحجوزات غير المخصصة",
  "frontdesk.availableRoomsTab": "الغرف المتاحة",
  "frontdesk.roomMoveTitle": "نقل / تحويل الغرفة",
  "frontdesk.moveToRoom": "الانتقال إلى الغرفة",
  "frontdesk.roomComparison": "مقارنة الغرف",
  "frontdesk.sameRate": "نفس السعر",
  "frontdesk.notesOptional": "ملاحظات (اختياري)",
  "frontdesk.moveToRoomBtn": "الانتقال إلى الغرفة {room}",
  "frontdesk.moveHistoryTable.rateChange": "تغيير السعر",
  "frontdesk.confirmRoomMove": "تأكيد نقل الغرفة",
  "frontdesk.rateChange": "تغيير السعر",
  "frontdesk.roomMovedMsg": "تم نقل النزيل إلى الغرفة {room} ({roomType})",
  "frontdesk.moveFailed": "فشل النقل",
  "frontdesk.confirmMove": "تأكيد النقل",
  "frontdesk.guestRequest": "طلب النزيل",
  "frontdesk.maintenanceIssue": "مشكلة صيانة",
  "frontdesk.complimentaryUpgrade": "ترقية مجانية",
  "frontdesk.availabilityIssue": "مشكلة التوفر",
  "frontdesk.targetRoomStatus": "حالة الغرفة المستهدفة: {status}. قد يكون التنظيف مطلوباً.",
  "frontdesk.registrationCardTitle": "بطاقة التسجيل",
  "frontdesk.fullName": "الاسم الكامل",
  "frontdesk.roomNumber": "رقم الغرفة",
  "frontdesk.roomTypeLabel": "نوع الغرفة",
  "frontdesk.accompanyingGuests": "النزلاء المرافقون",
  "frontdesk.vehicleInformation": "معلومات المركبة",
  "frontdesk.existingCard": "بطاقة موجودة",
  "frontdesk.cardNo": "رقم البطاقة",
  "frontdesk.termsAndConditions": "الشروط والأحكام",
  "frontdesk.regeneratePrint": "إعادة إنشاء وطباعة",
  "frontdesk.generatePrint": "إنشاء وطباعة",
  "frontdesk.leisure": "ترفيه / عطلة",
  "frontdesk.business": "سفر عمل",
  "frontdesk.conference": "مؤتمر / اجتماع",
  "frontdesk.medical": "زيارة طبية",
  "frontdesk.transit": "عبور / توقف",
  "frontdesk.termsRequired": "الشروط مطلوبة",
  "frontdesk.registrationCardGenerated": "تم إنشاء بطاقة التسجيل",
  "frontdesk.expressCheckIn": "تسجيل دخول سريع",
  "frontdesk.findYourBooking": "ابحث عن حجزك",
  "frontdesk.findBooking": "البحث عن حجز",
  "frontdesk.confirmCheckIn": "تأكيد وتسجيل الدخول",
  "frontdesk.detailsCorrect": "التفاصيل صحيحة",
  "frontdesk.checkingIn": "جاري تسجيل الدخول...",
  "frontdesk.checkInNow": "تسجيل الدخول الآن",
  "frontdesk.yourRoom": "غرفتك",
  "frontdesk.wifiCredentialsTitle": "بيانات الواي فاي",
  "frontdesk.validUntilDate": "صالح حتى {date}",
  "frontdesk.tryAgain": "حاول مرة أخرى",
  "frontdesk.startOver": "البدء من جديد",
  "frontdesk.paymentComplete": "تم الدفع",
  "frontdesk.paymentIssue": "مشكلة في الدفع",
  "frontdesk.cardPayment": "دفع بالبطاقة",
  "frontdesk.cashPayment": "دفع نقدي",
  "frontdesk.cardNumber": "رقم البطاقة",
  "frontdesk.expiryDate": "تاريخ الانتهاء",
  "frontdesk.pay": "ادفع {amount}",
  "frontdesk.upiIdPlaceholder": "yourname@upi",
  "frontdesk.amountDue": "المبلغ المستحق",
  "frontdesk.confirmCashPayment": "تأكيد الدفع النقدي",
  "frontdesk.processingPayment": "جاري معالجة الدفع...",
  "frontdesk.paymentSuccessful": "تم الدفع بنجاح!",
  "frontdesk.receiptNo": "رقم الإيصال",
  "frontdesk.remainingBalance": "الرصيد المتبقي",
  "frontdesk.paymentFailed": "فشل الدفع",
  "frontdesk.hotelName": "اسم الفندق",
  "frontdesk.welcomeMessage": "رسالة الترحيب",
  "frontdesk.primaryColor": "اللون الأساسي",
  "frontdesk.backgroundStyle": "نمط الخلفية",
  "frontdesk.idleTimeout": "مهلة الخمول",
  "frontdesk.enableCheckIn": "تفعيل تسجيل الدخول",
  "frontdesk.enableCheckOut": "تفعيل تسجيل الخروج",
  "frontdesk.enablePayment": "تفعيل الدفع",
  "frontdesk.kioskAddress": "عنوان الكشك",
  "frontdesk.saveChanges": "حفظ التغييرات",
  "pms.propertyName": "اسم العقار",
  "pms.propertyNamePlaceholder": "فندق الكراند",
  "pms.phonePlaceholder": "+91 98765 43210",
  "pms.taxComponent": "مكون الضريبة",
  "pms.generalInfo": "معلومات عامة",
  "pms.contactInfo": "معلومات الاتصال",
  "pms.validationError": "خطأ في التحقق",
  "pms.exportComplete": "تم التصدير",
  "pms.importFailed": "فشل الاستيراد",
  "pms.roomNumber": "رقم الغرفة",
  "pms.roomName": "اسم الغرفة",
  "pms.roomNamePlaceholder": "جناح العسل",
  "pms.roomTypesTitle": "أنواع الغرف",
  "pms.typeName": "اسم النوع",
  "pms.typeNamePlaceholder": "غرفة ديلوكس",
  "pms.basePrice": "السعر الأساسي",
  "pms.maxOccupancy": "الحد الأقصى للإشغال",
  "pms.inventoryTitle": "تقويم المخزون",
  "pms.availabilityTitle": "التحكم في التوفر",
  "pms.lockingTitle": "قفل المخزون",
  "pms.lockType": "نوع القفل",
  "pms.unlockInventory": "فتح المخزون",
  "pms.enableOverbooking": "تفعيل الحجز الزائد",
  "pms.pricingTitle": "مدير التسعير",
  "pms.ratePlanName": "اسم خطة السعر",
  "pms.maxPrice": "الحد الأقصى للسعر",
  "pms.priceOverride": "تجاوز السعر",
  "pms.roomType": "نوع الغرفة",
  "pms.revenueTitle": "لوحة الإيرادات",
  "pms.bulkPriceTitle": "تحديث أسعار جماعي",
  "pms.minPrice": "الحد الأدنى للسعر",
  "pms.bulkUpdateComplete": "تم التحديث الجماعي",
  "pms.floorPlansTitle": "المخططات الأرضية",
  "pms.floorPlanName": "اسم المخطط الأرضي",
  "pms.resetView": "إعادة تعيين العرض",
  "pms.toggleGrid": "تبديل الشبكة",
  "pms.zoomIn": "تكبير",
  "pms.zoomOut": "تصغير",
  "pms.alignLeft": "محاذاة لليسار",
  "pms.alignCenterH": "محاذاة في الوسط",
  "pms.alignTop": "محاذاة للأعلى",
  "pms.confirmRemoval": "تأكيد الإزالة",
  "pms.floorPlanViewer": "عارض المخطط الأرضي",
  "pms.pricingRulesTitle": "خطط الأسعار وقواعد التسعير",
  "pms.roomRateCalendarTitle": "تقويم أسعار الغرف",
  "pms.rateUpdated": "تم تحديث السعر",
  "pms.costEstimate": "تقدير التكلفة",
  "pms.galleryTitle": "معرض صور الغرف",
  "pms.fileTooLarge": "الملف كبير جداً",
  "bookings.changeStatus": "تغيير الحالة",
  "bookings.bookingDetailsCopied": "تم نسخ تفاصيل الحجز",
  "bookings.printView": "عرض الطباعة",
  "bookings.calendarTitle": "تقويم الحجوزات",
  "bookings.wifiAccessCreated": "تم إنشاء وصول الواي فاي",
  "bookings.wifiProvisioningSkipped": "تم تخطي توفير الواي فاي",
  "bookings.wifiUserExists": "مستخدم الواي فاي موجود",
  "bookings.calendarListTitle": "قائمة تقويم الحجوزات",
  "bookings.conflictsTitle": "تعارضات الحجوزات",
  "bookings.groupBookingsTitle": "الحجوزات الجماعية",
  "bookings.groupName": "اسم المجموعة",
  "bookings.contactPerson": "جهة الاتصال",
  "bookings.contactEmail": "البريد الإلكتروني للاتصال",
  "bookings.contactPhone": "هاتف الاتصال",
  "bookings.actionType": "نوع الإجراء",
  "bookings.noShowTitle": "أتمتة عدم الحضور",
  "guests.guestProfiles": "ملفات النزلاء",
  "guests.firstName": "الاسم الأول",
  "guests.lastName": "اسم العائلة",
  "guests.phonePlaceholder": "+1 555 123 4567",
  "guests.cityPlaceholder": "نيويورك",
  "guests.countryPlaceholder": "الولايات المتحدة",
  "guests.loyaltyTier": "مستوى الولاء",
  "guests.validationError": "خطأ في التحقق",
  "guests.documentName": "اسم المستند",
  "guests.fileTooLarge": "الملف كبير جداً",
  "guests.guestPreferencesTitle": "تفضيلات النزيل",
  "guests.loyaltyTitle": "برنامج الولاء",
  "guests.adjustPoints": "تعديل النقاط",
  "guests.loyaltyPointsTitle": "نقاط الولاء",
  "guests.redemptionOptions": "خيارات الاستبدال",
  "guests.insufficientPoints": "نقاط غير كافية",
  "guests.exportComplete": "تم التصدير",
  "guests.guestProfileTitle": "ملف النزيل",
  "guests.guestJourneyTitle": "رحلة النزيل",
  "guests.eventType": "نوع الحدث"
};

const locale = JSON.parse(fs.readFileSync('src/messages/ar.json', 'utf-8'));
let applied = 0;
for (const [k, v] of Object.entries(translations)) {
  if (v && typeof v === 'string') {
    deepSet(locale, k, v);
    applied++;
  }
}
fs.writeFileSync('src/messages/ar.json', JSON.stringify(locale, null, 2) + '\n', 'utf-8');
console.log(`Applied ${applied} Arabic translations`);
