// Apply French translations for remaining keys
import fs from 'fs';

function deepSet(obj, path, val) {
  const parts = path.split('.');
  let cur = obj;
  for (let i = 0; i < parts.length - 1; i++) {
    if (!(parts[i] in cur) || typeof cur[parts[i]] !== 'object') cur[parts[i]] = {};
    cur = cur[parts[i]];
  }
  cur[parts[parts.length - 1]] = val;
}

const translations = {
  "notifications.saveChanges": "Enregistrer les modifications",
  "notifications.enableEmailNotifications": "Activer les notifications par e-mail",
  "notifications.fromAddress": "Adresse d'expédition",
  "notifications.trackOpens": "Suivre les ouvertures",
  "notifications.fromNumber": "Numéro de l'expéditeur",
  "notifications.pushNotifications": "Notifications push",
  "notifications.enablePushNotifications": "Activer les notifications push",
  "notifications.quietHours": "Heures calmes",
  "notifications.enableQuietHours": "Activer les heures calmes",
  "notifications.startTime": "Heure de début",
  "notifications.endTime": "Heure de fin",
  "notifications.notificationTriggers": "Déclencheurs de notifications",
  "integrations.thirdpartyApis": "API tierces",
  "integrations.apiKey_4": "Clé API",
  "integrations.rateLimit": "Limite de débit",
  "integrations.perMinute": "Par minute",
  "integrations.perHour": "Par heure",
  "integrations.perDay": "Par jour",
  "integrations.perMonth": "Par mois",
  "integrations.apiKeyCopiedToClipboard": "Clé API copiée dans le presse-papiers",
  "integrations.wifiGateways": "Passerelles WiFi",
  "integrations.gatewayName_3": "Nom de la passerelle",
  "integrations.controllerType": "Type de contrôleur",
  "integrations.apiKey_5": "Clé API",
  "integrations.syncIntervalMin": "Intervalle de synchronisation (min)",
  "integrations.autoSync": "Synchronisation automatique",
  "integrations.saveGateway_2": "Enregistrer la passerelle",
  "integrations.connectedGateways": "Passerelles connectées",
  "integrations.bandwidthUsage": "Utilisation de la bande passante",
  "integrations.accessPoints": "Points d'accès",
  "integrations.syncNow_1": "Synchroniser maintenant",
  "integrations.myWifiController": "Mon contrôleur WiFi",
  "integrations.serverRoomBuildingA": "Salle serveur, Bâtiment A",
  "webhooks.webhookDelivery": "Livraison du webhook",
  "webhooks.deliveredAt": "Livré à",
  "webhooks.webhookEndpoints": "Points de terminaison webhook",
  "webhooks.secretKey": "Clé secrète",
  "webhooks.saveEndpoint": "Enregistrer le point de terminaison",
  "webhooks.avgSuccessRate": "Taux de réussite moyen",
  "webhooks.eventTypes": "Types d'événements",
  "webhooks.successRate": "Taux de réussite",
  "webhooks.lastTriggered": "Dernier déclenchement",
  "webhooks.secret": "Secret",
  "webhooks.subscribedEvents": "Événements souscrits",
  "webhooks.myWebhook": "Mon webhook",
  "webhooks.secretCopiedToClipboard": "Secret copié dans le presse-papiers",
  "webhooks.retryQueue": "File de nouvelles tentatives",
  "webhooks.pendingRetry": "Nouvelle tentative en attente",
  "webhooks.failedMaxAttempts": "Échoué (tentatives max)",
  "webhooks.nextRetry": "Prochaine tentative",
  "webhooks.lastError": "Dernière erreur",
  "help.watchVideo": "Regarder la vidéo",
  "help.relatedArticles": "Articles associés",
  "help.contactSupport": "Contacter le support",
  "help.knowledgeBase": "Base de connaissances",
  "help.newArticle": "Nouvel article",
  "help.newestFirst": "Plus récents",
  "help.oldestFirst": "Plus anciens",
  "help.mostViewed": "Plus consultés",
  "help.mostHelpful": "Plus utiles",
  "help.clearFilters": "Effacer les filtres",
  "help.gettingStarted": "Premiers pas",
  "help.knowledgeBase_1": "Base de connaissances",
  "help.helpCenter": "Centre d'aide",
  "help.popularArticles": "Articles populaires",
  "help.frequentlyAskedQuestions": "Questions fréquentes",
  "help.stillNeedHelp": "Besoin d'aide ?",
  "help.contactSupport_1": "Contacter le support",
  "help.submitARequest": "Soumettre une demande",
  "help.submitRequest": "Envoyer la demande",
  "help.helpCenter_1": "Centre d'aide",
  "help.newArticle_1": "Nouvel article",
  "help.slug": "Slug",
  "help.contentMarkdown": "Contenu (Markdown)",
  "help.restartTutorial": "Redémarrer le tutoriel",
  "help.startTutorial": "Démarrer le tutoriel",
  "help.skipTutorial": "Ignorer le tutoriel",
  "help.tutorialProgress": "Progression du tutoriel",
  "help.yesReset": "Oui, réinitialiser",
  "help.resetAllProgress": "Réinitialiser toute la progression",
  "help.tutorialsAvailable": "Tutoriels disponibles",
  "help.inProgress": "En cours",
  "help.overallProgress": "Progression globale",
  "help.availableTutorials": "Tutoriels disponibles",
  "help.startTutorial_1": "Démarrer le tutoriel",
  "help.reviewTutorial": "Réviser le tutoriel",
  "parking.noPropertySelected": "Aucun établissement sélectionné",
  "parking.parkingBilling": "Facturation du parking",
  "parking.checkin": "Enregistrement",
  "parking.averageFee": "Tarif moyen",
  "parking.thisMonth": "Ce mois-ci",
  "parking.clearFilters": "Effacer les filtres",
  "parking.checkInVehicle": "Enregistrer un véhicule",
  "parking.entryTime": "Heure d'entrée",
  "parking.exitTime": "Heure de sortie",
  "parking.parkingFee": "Frais de parking",
  "parking.hourlyRate": "Tarif horaire",
  "parking.dailyMax": "Maximum journalier",
  "parking.paymentPending": "Paiement en attente",
  "parking.paymentComplete": "Paiement effectué",
  "parking.recordPayment": "Enregistrer le paiement",
  "parking.amountDue": "Montant dû",
  "parking.paymentMethod": "Mode de paiement",
  "parking.newVehicleCheckin": "Nouvel enregistrement de véhicule",
  "parking.parkingSlotOptional": "Place de parking (facultatif)",
  "parking.dailyMaxRate": "Tarif maximum journalier",
  "parking.recordExit": "Enregistrer la sortie",
  "parking.licensePlate": "Immatriculation *",
  "parking.noPropertySelected_1": "Aucun établissement sélectionné",
  "parking.parkingSlots": "Places de parking",
  "parking.slotNumber": "Numéro de place",
  "parking.slotType": "Type de place",
  "parking.vehicleType": "Type de véhicule",
  "parking.chargerType": "Type de chargeur",
  "parking.parkedVehicle": "Véhicule stationné",
  "parking.setAvailable": "Rendre disponible",
  "parking.noPropertySelected_2": "Aucun établissement sélectionné",
  "parking.vehicleTracking": "Suivi des véhicules",
  "parking.logEntry": "Entrée d'enregistrement",
  "parking.currentlyParked": "Actuellement stationnés",
  "parking.exitedToday": "Sortis aujourd'hui",
  "parking.entryTime_1": "Heure d'entrée",
  "parking.logVehicleEntry": "Enregistrer l'entrée du véhicule",
  "parking.exitTime_1": "Heure de sortie",
  "parking.parkingFee_1": "Frais de parking",
  "parking.paymentPending_1": "Paiement en attente",
  "parking.licensePlate_1": "Immatriculation *",
  "iot.lastSeen": "Dernière activité",
  "iot.unlockDoor": "Déverrouiller la porte",
  "iot.deviceName": "Nom de l'appareil",
  "iot.deviceType": "Type d'appareil",
  "iot.smartLock": "Serrure intelligente",
  "iot.motorizedBlinds": "Stores motorisés",
  "iot.airConditioner": "Climatiseur",
  "iot.zigbee": "Zigbee",
  "iot.zwave": "Z-Wave",
  "iot.lockDoor": "Verrouiller la porte",
  "iot.turnOff": "Éteindre",
  "iot.turnOn": "Allumer",
  "iot.energyDashboard": "Tableau de bord énergétique",
  "iot.carbonFootprint": "Empreinte carbone",
  "iot.costSavings": "Économies de coûts",
  "iot.carbonReduction": "Réduction du carbone",
  "iot.consumptionTrends": "Tendances de consommation",
  "iot.costBreakdown": "Répartition des coûts",
  "iot.byProperty": "Par établissement",
  "iot.dailyEnergyConsumption": "Consommation d'énergie journalière",
  "iot.carbonFootprintTrend": "Tendance de l'empreinte carbone",
  "iot.dailyCostTrend": "Tendance des coûts quotidiens",
  "iot.electricityKwh": "Électricité (kWh)",
  "iot.propertyComparison": "Comparaison des établissements",
  "iot.dailyAverages": "Moyennes quotidiennes",
  "iot.avgElectricity": "Électricité moy.",
  "iot.avgGas": "Gaz moy.",
  "iot.avgWater": "Eau moy.",
  "iot.avgDailyCost": "Coût quotidien moy.",
  "iot.gasM": "Gaz (m³)",
  "iot.waterM": "Eau (m³)",
  "iot.fanSpeed": "Vitesse du ventilateur",
  "iot.roomControls": "Commandes de la chambre",
  "iot.sensorNoControls": "Capteur - Pas de commandes",
  "iot.confirmDoorUnlock": "Confirmer le déverrouillage",
  "iot.unlockDoor_1": "Déverrouiller la porte",
  "iot.quickActions": "Actions rapides",
  "iot.morningMode": "Mode matin",
  "iot.nightMode": "Mode nuit",
  "chain.primaryColor": "Couleur principale",
  "chain.secondaryColor": "Couleur secondaire",
  "chain.grandHotels": "Grands Hôtels",
  "chain.brandName": "Nom de la marque *",
  "chain.brandCode": "Code de la marque *",
  "chain.chainDashboard": "Tableau de bord de la chaîne",
  "chain.occupancyRate": "Taux d'occupation",
  "chain.monthlyBookings": "Réservations mensuelles",
  "chain.monthlyRevenue": "Revenus mensuels",
  "chain.todayapossArrivals": "Arrivées du jour",
  "chain.todayapossDepartures": "Départs du jour",
  "chain.propertyPerformance": "Performance de l'établissement",
  "chain.brandDistribution": "Distribution des marques",
  "chain.propertiesPerformance": "Performances des établissements",
  "chain.thisWeek": "Cette semaine",
  "chain.thisMonth": "Ce mois-ci",
  "chain.thisYear": "Cette année",
  "chain.avgOccupancy": "Occupation moy.",
  "chain.byProperty": "Par établissement",
  "chain.byBrand": "Par marque",
  "chain.bookingSources": "Sources de réservation",
  "chain.guestDemographics": "Démographie des clients",
  "chain.propertyPerformanceComparison": "Comparaison des performances",
  "chain.revenueTrend": "Tendance des revenus",
  "chain.propertyComparison": "Comparaison des établissements",
  "ads.adCampaigns": "Campagnes publicitaires",
  "ads.newCampaign": "Nouvelle campagne",
  "ads.budgetUsed": "Budget utilisé",
  "ads.basicInformation": "Informations de base",
  "ads.campaignName": "Nom de la campagne",
  "ads.campaignType": "Type de campagne",
  "ads.budgetBidding": "Budget et enchères",
  "ads.budgetType": "Type de budget",
  "ads.bidStrategy": "Stratégie d'enchère",
  "ads.bidAmountOptional": "Montant de l'enchère (facultatif)",
  "ads.startDate": "Date de début",
  "ads.endDate": "Date de fin",
  "ads.performanceTrend": "Tendance de performance",
  "ads.bidStrategy_1": "Stratégie d'enchère",
  "ads.autoBidding": "Enchères automatiques",
  "ads.baseBidModifier": "Modificateur d'enchère de base",
  "ads.lastPriceFeed": "Dernier flux de prix",
  "ads.lastBookingFeed": "Dernier flux de réservations",
  "ads.feedFormat": "Format du flux",
  "ads.connectionMode": "Mode de connexion",
  "ads.performanceTracking": "Suivi des performances",
  "ads.convRate": "Taux de conversion",
  "ads.performanceTrend_1": "Tendance de performance",
  "ads.conversionTrend": "Tendance des conversions",
  "ads.dailyBreakdown": "Répartition quotidienne",
  "ads.netProfit": "Bénéfice net",
  "ads.channelComparison": "Comparaison des canaux",
  "ads.trendInsights": "Analyses de tendances",
  "ads.profitTrend": "Tendance des bénéfices",
  "portal.inProgress": "En cours",
  "portal.uploadFirstDocument": "Télécharger le premier document",
  "portal.uploadAnotherDocument": "Télécharger un autre document",
  "portal.uploadDocument": "Télécharger un document",
  "portal.egPassportJohnDoe": "ex., Passeport - Jean Dupont",
  "portal.documentType": "Type de document *",
  "portal.documentName": "Nom du document *",
  "portal.documentFile": "Fichier du document *",
  "portal.termsSignature": "Conditions et signature",
  "portal.termsAccepted": "Conditions acceptées",
  "portal.yourSignature": "Votre signature",
  "portal.signAcceptTerms": "Signer et accepter les conditions",
  "portal.alternatePhone": "Téléphone secondaire",
  "portal.streetAddress": "Adresse",
  "portal.postalCode": "Code postal",
  "portal.newYork": "New York",
  "portal.firstName": "Prénom *",
  "portal.lastName": "Nom *",
  "portal.phoneNumber": "Numéro de téléphone *",
  "portal.paymentSummary": "Résumé du paiement",
  "portal.balanceDue": "Solde dû",
  "portal.taxesFees": "Taxes et frais",
  "portal.amountPaid": "Montant payé",
  "portal.payNow": "Payer maintenant",
  "portal.paymentComplete": "Paiement effectué",
  "portal.floorPreference": "Préférence d'étage",
  "portal.bedType": "Type de lit",
  "portal.pillowType": "Type d'oreiller",
  "portal.additionalRoomPreferences": "Préférences supplémentaires",
  "portal.dietaryRequirements": "Exigences alimentaires",
  "portal.roomAmenities": "Équipements de la chambre",
  "portal.preferredLanguage": "Langue préférée",
  "portal.notificationPreferences": "Préférences de notification",
  "gdpr.privacyNotice": "Avis de confidentialité",
  "gdpr.acceptAll": "Tout accepter",
  "gdpr.rejectOptional": "Refuser les options",
  "gdpr.privacyPolicy": "Politique de confidentialité",
  "gdpr.declineOptional": "Refuser les options",
  "gdpr.requestTypes": "Types de demandes",
  "gdpr.exportData": "Exporter les données",
  "gdpr.exportGuestData": "Exporter les données du client ?",
  "gdpr.confirmExport": "Confirmer l'exportation",
  "gdpr.anonymizeData": "Anonymiser les données",
  "gdpr.anonymizeGuestData": "Anonymiser les données du client ?",
  "gdpr.confirmAnonymization": "Confirmer l'anonymisation",
  "gdpr.softDelete": "Suppression logique",
  "gdpr.softDeleteGuestData": "Supprimer logiquement les données du client ?",
  "gdpr.confirmSoftDelete": "Confirmer la suppression logique",
  "gdpr.hardDelete": "Suppression définitive",
  "gdpr.permanentlyDeleteGuestData": "Supprimer définitivement les données du client ?",
  "gdpr.confirmPermanentDelete": "Confirmer la suppression définitive",
  "gdpr.recordConsent": "Enregistrer le consentement",
  "audit.securityEvents": "Événements de sécurité",
  "audit.failedLogins": "Connexions échouées",
  "audit.activityLog": "Journal d'activité",
  "audit.entityType": "Type d'entité",
  "audit.userAgent": "Agent utilisateur",
  "audit.oldValue": "Ancienne valeur",
  "audit.newValue": "Nouvelle valeur",
  "communication.changeStatus": "Changer le statut",
  "communication.assignTo": "Assigner à",
  "communication.quickReplies": "Réponses rapides :",
  "communication.messageTemplates": "Modèles de messages",
  "communication.insertLink": "Insérer un lien",
  "communication.bulletList": "Liste à puces",
  "communication.numberedList": "Liste numérotée",
  "communication.attachFile": "Joindre un fichier",
  "profile.personalInformation": "Informations personnelles",
  "profile.firstName": "Prénom",
  "profile.lastName": "Nom",
  "profile.jobTitle": "Intitulé du poste",
  "profile.newPassword": "Nouveau mot de passe",
  "profile.confirmPassword": "Confirmer le mot de passe",
  "profile.twofactorAuthentication": "Authentification à deux facteurs",
  "profile.authenticatorApp": "Application d'authentification",
  "profile.emailNotifications": "Notifications par e-mail",
  "profile.pushNotifications": "Notifications push",
  "profile.marketingEmails": "E-mails marketing",
  "profile.darkMode": "Mode sombre",
  "profile.compactMode": "Mode compact",
  "profile.dateFormat": "Format de date",
  "frontdesk.todaysArrivalsCount": "Arrivées du jour",
  "frontdesk.checkedIn": "Enregistré",
  "frontdesk.checkInBtn": "Enregistrer l'arrivée",
  "frontdesk.roomType": "Type de chambre",
  "frontdesk.assignedRoom": "Chambre attribuée",
  "frontdesk.roomsAvailable": "{count} chambre(s) disponible(s)",
  "frontdesk.driverLicense": "Permis de conduire",
  "frontdesk.wifiCredentials": "Identifiants WiFi",
  "frontdesk.validUntil": "Valide jusqu'au",
  "frontdesk.specialRequests": "Demandes spéciales",
  "frontdesk.specialRequestsLabel": "Demandes spéciales",
  "frontdesk.copiedToClipboard": "{label} copié dans le presse-papiers",
  "frontdesk.couldNotCopy": "Impossible de copier {label}",
  "frontdesk.validationError": "Erreur de validation",
  "frontdesk.checkInSuccessMsg": "Client enregistré dans la chambre {room}. Identifiants WiFi prêts.",
  "frontdesk.seaView": "Vue sur la mer",
  "frontdesk.mountainView": "Vue sur la montagne",
  "frontdesk.markClean": "Marquer comme nettoyée",
  "frontdesk.markAvailable": "Marquer comme disponible",
  "frontdesk.checkOut": "Départ",
  "frontdesk.quickActions": "Actions rapides",
  "frontdesk.todaysDeparturesCount": "Départs du jour",
  "frontdesk.checkingOut": "En cours de départ",
  "frontdesk.outstandingBalance": "Solde restant dû",
  "frontdesk.outstandingBalanceAmount": "Solde restant : {amount}",
  "frontdesk.checkOutBtn": "Enregistrer le départ",
  "frontdesk.stayDuration": "Durée du séjour",
  "frontdesk.takePayment": "Encaisser le paiement",
  "frontdesk.paymentRecorded": "Paiement enregistré",
  "frontdesk.paymentOf": "Paiement de {amount} traité",
  "frontdesk.outstandingBalanceLabel": "Solde restant dû",
  "frontdesk.paymentMethod": "Mode de paiement",
  "frontdesk.referenceOptional": "Référence (facultatif)",
  "frontdesk.recordPayment": "Enregistrer le paiement",
  "frontdesk.guestCheckedOut": "Client parti de la chambre {room}",
  "frontdesk.creditDebitCard": "Carte de crédit/débit",
  "frontdesk.bankTransfer": "Virement bancaire",
  "frontdesk.digitalWallet": "Portefeuille numérique",
  "frontdesk.nightsLabel": "{count} nuits",
  "frontdesk.propertyAndRoom": "Établissement et chambre",
  "frontdesk.assignRoom": "Attribuer une chambre",
  "frontdesk.guestInformation": "Informations client",
  "frontdesk.existingGuest": "Client existant",
  "frontdesk.stateProvince": "Région / Province",
  "frontdesk.guestName": "Nom du client",
  "frontdesk.bookingSummary": "Résumé de la réservation",
  "frontdesk.taxBreakdown": "Détail des taxes",
  "frontdesk.serviceCharge": "Frais de service",
  "frontdesk.grandTotal": "Total général",
  "frontdesk.guestCreationFailed": "Échec de la création du client",
  "frontdesk.bookingCreated": "Réservation créée",
  "frontdesk.bookingFailed": "Échec de la réservation",
  "frontdesk.roomGridTitle": "Grille des chambres",
  "frontdesk.seaViewLegend": "Vue mer",
  "frontdesk.liveUpdate": "Mise à jour en direct",
  "frontdesk.roomFeatures": "Caractéristiques de la chambre",
  "frontdesk.roomBookingInfo": "Infos de réservation",
  "frontdesk.connectionError": "Erreur de connexion",
  "frontdesk.roomStatusUpdated": "Statut de chambre mis à jour",
  "frontdesk.roomStatusUpdatedMsg": "La chambre {id} est maintenant {status}",
  "frontdesk.roomAssignmentTitle": "Attribution de chambre",
  "frontdesk.unassignedBookings": "Réservations non attribuées",
  "frontdesk.availableRooms": "Chambres disponibles",
  "frontdesk.arrivingToday": "Arrivées d'aujourd'hui",
  "frontdesk.compatibleRooms": "{count} chambre(s) compatible(s)",
  "frontdesk.assignRoomTitle": "Attribuer une chambre",
  "frontdesk.bookingInfo": "Infos de réservation",
  "frontdesk.roomPreview": "Aperçu de la chambre",
  "frontdesk.roomAssignmentSuccess": "Chambre attribuée",
  "frontdesk.roomAssignmentSuccessMsg": "Chambre {room} attribuée à la réservation {code}",
  "frontdesk.allBookingsTab": "Réservations non attribuées",
  "frontdesk.availableRoomsTab": "Chambres disponibles",
  "frontdesk.roomMoveTitle": "Transfert de chambre",
  "frontdesk.moveToRoom": "Déplacer vers la chambre",
  "frontdesk.roomComparison": "Comparaison des chambres",
  "frontdesk.sameRate": "Même tarif",
  "frontdesk.notesOptional": "Notes (facultatif)",
  "frontdesk.moveToRoomBtn": "Déplacer vers la chambre {room}",
  "frontdesk.moveHistoryTable.rateChange": "Variation tarif",
  "frontdesk.confirmRoomMove": "Confirmer le transfert",
  "frontdesk.rateChange": "Variation de tarif",
  "frontdesk.roomMovedMsg": "Client déplacé vers la chambre {room} ({roomType})",
  "frontdesk.moveFailed": "Échec du transfert",
  "frontdesk.confirmMove": "Confirmer le déplacement",
  "frontdesk.guestRequest": "Demande du client",
  "frontdesk.maintenanceIssue": "Problème de maintenance",
  "frontdesk.complimentaryUpgrade": "Surclassement gratuit",
  "frontdesk.availabilityIssue": "Problème de disponibilité",
  "frontdesk.targetRoomStatus": "Statut cible de la chambre : {status}. Le ménage peut être nécessaire.",
  "frontdesk.registrationCardTitle": "Fiche d'enregistrement",
  "frontdesk.fullName": "Nom complet",
  "frontdesk.roomNumber": "Numéro de chambre",
  "frontdesk.roomTypeLabel": "Type de chambre",
  "frontdesk.accompanyingGuests": "Clients accompagnants",
  "frontdesk.vehicleInformation": "Informations du véhicule",
  "frontdesk.existingCard": "Carte existante",
  "frontdesk.cardNo": "N° de carte",
  "frontdesk.termsAndConditions": "Conditions générales",
  "frontdesk.regeneratePrint": "Régénérer et imprimer",
  "frontdesk.generatePrint": "Générer et imprimer",
  "frontdesk.leisure": "Loisirs / Vacances",
  "frontdesk.business": "Voyage d'affaires",
  "frontdesk.conference": "Conférence / Réunion",
  "frontdesk.medical": "Visite médicale",
  "frontdesk.transit": "Transit / Escale",
  "frontdesk.termsRequired": "Conditions requises",
  "frontdesk.registrationCardGenerated": "Fiche d'enregistrement générée",
  "frontdesk.expressCheckIn": "Enregistrement express",
  "frontdesk.findYourBooking": "Trouvez votre réservation",
  "frontdesk.findBooking": "Rechercher une réservation",
  "frontdesk.confirmCheckIn": "Confirmer et enregistrer",
  "frontdesk.detailsCorrect": "Informations correctes",
  "frontdesk.checkingIn": "Enregistrement en cours...",
  "frontdesk.checkInNow": "S'enregistrer maintenant",
  "frontdesk.yourRoom": "Votre chambre",
  "frontdesk.wifiCredentialsTitle": "Identifiants WiFi",
  "frontdesk.validUntilDate": "Valide jusqu'au {date}",
  "frontdesk.tryAgain": "Réessayer",
  "frontdesk.startOver": "Recommencer",
  "frontdesk.paymentComplete": "Paiement effectué",
  "frontdesk.paymentIssue": "Problème de paiement",
  "frontdesk.cardPayment": "Paiement par carte",
  "frontdesk.cashPayment": "Paiement en espèces",
  "frontdesk.cardNumber": "Numéro de carte",
  "frontdesk.expiryDate": "Date d'expiration",
  "frontdesk.pay": "Payer {amount}",
  "frontdesk.upiIdPlaceholder": "yourname@upi",
  "frontdesk.amountDue": "Montant dû",
  "frontdesk.confirmCashPayment": "Confirmer le paiement en espèces",
  "frontdesk.processingPayment": "Traitement du paiement...",
  "frontdesk.paymentSuccessful": "Paiement réussi !",
  "frontdesk.receiptNo": "N° de reçu",
  "frontdesk.remainingBalance": "Solde restant",
  "frontdesk.paymentFailed": "Échec du paiement",
  "frontdesk.hotelName": "Nom de l'hôtel",
  "frontdesk.welcomeMessage": "Message de bienvenue",
  "frontdesk.primaryColor": "Couleur principale",
  "frontdesk.backgroundStyle": "Style d'arrière-plan",
  "frontdesk.idleTimeout": "Délai d'inactivité",
  "frontdesk.enableCheckIn": "Activer l'enregistrement",
  "frontdesk.enableCheckOut": "Activer le départ",
  "frontdesk.enablePayment": "Activer le paiement",
  "frontdesk.kioskAddress": "Adresse du kiosque",
  "frontdesk.saveChanges": "Enregistrer les modifications",
  "pms.propertyName": "Nom de l'établissement",
  "pms.propertyNamePlaceholder": "Grand Hôtel",
  "pms.phonePlaceholder": "+91 98765 43210",
  "pms.taxComponent": "Composante fiscale",
  "pms.generalInfo": "Informations générales",
  "pms.contactInfo": "Coordonnées",
  "pms.validationError": "Erreur de validation",
  "pms.exportComplete": "Exportation terminée",
  "pms.importFailed": "Échec de l'importation",
  "pms.roomNumber": "Numéro de chambre",
  "pms.roomName": "Nom de la chambre",
  "pms.roomNamePlaceholder": "Suite de noces",
  "pms.roomTypesTitle": "Types de chambres",
  "pms.typeName": "Nom du type",
  "pms.typeNamePlaceholder": "Chambre deluxe",
  "pms.basePrice": "Prix de base",
  "pms.maxOccupancy": "Occupation maximale",
  "pms.inventoryTitle": "Calendrier des stocks",
  "pms.availabilityTitle": "Contrôle de disponibilité",
  "pms.lockingTitle": "Verrouillage des stocks",
  "pms.lockType": "Type de verrou",
  "pms.unlockInventory": "Déverrouiller le stock",
  "pms.enableOverbooking": "Activer la surréservation",
  "pms.pricingTitle": "Gestionnaire des tarifs",
  "pms.ratePlanName": "Nom du plan tarifaire",
  "pms.maxPrice": "Prix maximum",
  "pms.priceOverride": "Remplacement de prix",
  "pms.roomType": "Type de chambre",
  "pms.revenueTitle": "Tableau de bord des revenus",
  "pms.bulkPriceTitle": "Mise à jour en masse des prix",
  "pms.minPrice": "Prix minimum",
  "pms.bulkUpdateComplete": "Mise à jour en masse terminée",
  "pms.floorPlansTitle": "Plans d'étage",
  "pms.floorPlanName": "Nom du plan d'étage",
  "pms.resetView": "Réinitialiser la vue",
  "pms.toggleGrid": "Afficher/masquer la grille",
  "pms.zoomIn": "Zoom avant",
  "pms.zoomOut": "Zoom arrière",
  "pms.alignLeft": "Aligner à gauche",
  "pms.alignCenterH": "Centrer horizontalement",
  "pms.alignTop": "Aligner en haut",
  "pms.confirmRemoval": "Confirmer la suppression",
  "pms.floorPlanViewer": "Visualiseur de plan d'étage",
  "pms.pricingRulesTitle": "Plans tarifaires et règles de prix",
  "pms.roomRateCalendarTitle": "Calendrier des tarifs",
  "pms.rateUpdated": "Tarif mis à jour",
  "pms.costEstimate": "Estimation des coûts",
  "pms.galleryTitle": "Galerie d'images des chambres",
  "pms.fileTooLarge": "Fichier trop volumineux",
  "bookings.changeStatus": "Changer le statut",
  "bookings.bookingDetailsCopied": "Détails de réservation copiés",
  "bookings.printView": "Vue d'impression",
  "bookings.calendarTitle": "Calendrier des réservations",
  "bookings.wifiAccessCreated": "Accès WiFi créé",
  "bookings.wifiProvisioningSkipped": "Configuration WiFi ignorée",
  "bookings.wifiUserExists": "Utilisateur WiFi existant",
  "bookings.calendarListTitle": "Liste du calendrier des réservations",
  "bookings.conflictsTitle": "Conflits de réservations",
  "bookings.groupBookingsTitle": "Réservations de groupe",
  "bookings.groupName": "Nom du groupe",
  "bookings.contactPerson": "Personne à contacter",
  "bookings.contactEmail": "E-mail de contact",
  "bookings.contactPhone": "Téléphone de contact",
  "bookings.actionType": "Type d'action",
  "bookings.noShowTitle": "Automatisation des no-shows",
  "guests.guestProfiles": "Profils clients",
  "guests.firstName": "Prénom",
  "guests.lastName": "Nom",
  "guests.phonePlaceholder": "+1 555 123 4567",
  "guests.cityPlaceholder": "New York",
  "guests.countryPlaceholder": "États-Unis",
  "guests.loyaltyTier": "Niveau de fidélité",
  "guests.validationError": "Erreur de validation",
  "guests.documentName": "Nom du document",
  "guests.fileTooLarge": "Fichier trop volumineux",
  "guests.guestPreferencesTitle": "Préférences du client",
  "guests.loyaltyTitle": "Programme de fidélité",
  "guests.adjustPoints": "Ajuster les points",
  "guests.loyaltyPointsTitle": "Points de fidélité",
  "guests.redemptionOptions": "Options d'échange",
  "guests.insufficientPoints": "Points insuffisants",
  "guests.exportComplete": "Exportation terminée",
  "guests.guestProfileTitle": "Profil client",
  "guests.guestJourneyTitle": "Parcours client",
  "guests.eventType": "Type d'événement"
};

const locale = JSON.parse(fs.readFileSync('src/messages/fr.json', 'utf-8'));
let applied = 0;
for (const [k, v] of Object.entries(translations)) {
  if (v && typeof v === 'string') {
    deepSet(locale, k, v);
    applied++;
  }
}
fs.writeFileSync('src/messages/fr.json', JSON.stringify(locale, null, 2) + '\n', 'utf-8');
console.log(`Applied ${applied} French translations`);
