// Apply remaining French translations (batch 2)
import fs from 'fs';

function deepSet(obj, path, val) {
  const parts = path.split('.');
  let cur = obj;
  for (let i = 0; i < parts.length - 1; i++) {
    if (!(parts[i] in cur) || typeof cur[parts[i]] !== 'object') cur[parts[i]] = {};
    cur = cur[parts[i]];
  }
  cur[parts[parts.length - 1]] = val;
}

const translations = {
  "common.actions": "Actions",
  "common.notifications": "Notifications",
  "common.description": "Description",
  "common.premium": "Premium",
  "navigation.sessions": "Sessions",
  "navigation.maintenance": "Maintenance",
  "navigation.tables": "Tables",
  "navigation.parking": "Parking",
  "navigation.incidents": "Incidents",
  "navigation.restrictions": "Restrictions",
  "navigation.notifications": "Notifications",
  "navigation.webhooks": "Webhooks",
  "navigation.admin": "Administration",
  "navigation.guests-kyc": "KYC / Documents",
  "navigation.pos-tables": "Tables",
  "navigation.channel-restrictions": "Restrictions",
  "navigation.marketing": "Marketing",
  "navigation.help-articles": "Articles",
  "navigation.surveillance": "Surveillance",
  "layout.notificationsTitle": "Notifications",
  "layout.hospitalityOs": "Hospitality OS",
  "layout.navigationGroup": "Navigation",
  "layout.actionsGroup": "Actions",
  "status.maintenance": "Maintenance",
  "dashboard.urgent": "Urgent",
  "dashboard.maintenance": "Maintenance",
  "dashboard.categoryMaintenance": "Maintenance",
  "dashboard.eventBanquet": "Banquet",
  "dashboard.gradeExcellent": "Excellent",
  "dashboard.daysAgoShort": "{count}j",
  "dashboard.hoursAgoShort": "{count}h",
  "dashboard.legendMaintenance": "Maintenance",
  "dashboard.minutesAgoShort": "{count}m",
  "dashboard.total": "Total",
  "dashboard.totalLower": "total",
  "dashboard.service": "Service",
  "dashboard.message": "Message",
  "forms.notes": "Notes",
  "forms.description": "Description",
  "forms.code": "Code",
  "forms.total": "Total",
  "settings.base": "Base",
  "settings.description": "Description",
  "settings.canada": "Canada",
  "settings.notifications": "Notifications",
  "settings.parisCet": "Paris (CET)",
  "settings.canada_1": "Canada",
  "settings.france": "France",
  "settings.taxes": "Taxes",
  "settings.code": "Code",
  "settings.type": "Type",
  "settings.actions": "Actions",
  "billing.total": "Total",
  "billing.description": "Description",
  "billing.taxes": "Taxes",
  "billing.services": "Services",
  "billing.paymentDate": "Date",
  "billing.totalInvoices": "Total",
  "billing.transaction": "Transaction",
  "billing.folioLabel": "Folio",
  "billing.date": "Date",
  "billing.actions": "Actions",
  "billing.code": "Code",
  "billing.discountCode": "Code",
  "billing.discountDescriptionLabel": "Description",
  "billing.notesLabel": "Notes",
  "billing.noteNumber": "Note N°",
  "billing.totalLabel": "Total",
  "billing.messages": "Messages",
  "billing.plansLabel": "Forfaits",
  "billing.source": "Source",
  "billing.noteLabel": "Note",
  "billing.direction": "Direction",
  "billing.sourceLabel": "Source",
  "billing.auto": "Auto",
  "billing.policyDesc": "Description",
  "billing.exemptions": "Exemptions",
  "billing.noShowLabel": "No-Show",
  "pos.table": "Table",
  "pos.type": "Type",
  "pos.tablesTitle": "Tables",
  "pos.totalTables": "Total des tables",
  "pos.patio": "Terrasse",
  "pos.bar": "Bar",
  "pos.itemDescription": "Description",
  "pos.grill": "Grillade",
  "pos.sauté": "Sauté",
  "pos.dessert": "Dessert",
  "pos.dateRequired": "Date *",
  "pos.occasion": "Occasion",
  "pos.guestPhonePlaceholder": "+1 555 123 4567",
  "pos.guestNamePlaceholder": "Jean Dupont",
  "pos.position": "Position",
  "pos.menuTab": "Menu",
  "pos.tablesTab": "Tables",
  "pos.sections": "Sections",
  "pos.selectionType": "Type",
  "pos.optionsLabel": "Options",
  "pos.calories": "Calories",
  "revenue.standard": "Standard",
  "revenue.suite": "Suite",
  "revenue.marketingTab": "Marketing",
  "reports.satisfaction": "Satisfaction",
  "reports.format": "Format",
  "reports.excel": "Excel",
  "admin.permissions": "Permissions",
  "admin.type": "Type",
  "admin.actions": "Actions",
  "admin.date": "Date",
  "admin.action": "Action",
  "admin.audit": "Audit",
  "admin.description": "Description",
  "admin.plan": "Forfait",
  "admin.actions_1": "Actions",
  "admin.slug": "Slug",
  "admin.actions_2": "Actions",
  "admin.messages": "Messages",
  "admin.actions_3": "Actions",
  "admin.newPassword": "Nouveau mot de passe *",
  "channels.bookingSync": "Synchronisation des réservations",
  "channels.totalBookings": "Total des réservations",
  "channels.confirmation": "Confirmation",
  "channels.direction": "Direction",
  "channels.actions": "Actions",
  "channels.source": "Source",
  "channels.type": "Type",
  "channels.commission": "Commission",
  "channels.direction_1": "Direction",
  "channels.syncInv": "Sync Inv.",
  "channels.syncRest": "Sync Rest.",
  "channels.global": "Global",
  "channels.europe": "Europe",
  "channels.docs": "Docs",
  "channels.diff": "Diff",
  "channels.date": "Date",
  "channels.type_1": "Type",
  "channels.direction_2": "Direction",
  "crm.type": "Type",
  "crm.description": "Description",
  "crm.compliments": "Compliments",
  "crm.suggestions": "Suggestions",
  "crm.type_1": "Type",
  "crm.description_1": "Description",
  "crm.tierminpointstolocalestringTiermaxpoints999999TiermaxpointstolocalestringPoints": "{tier.minPoints.toLocaleString()} - {tier.maxPoints === 999999 ? '∞' : tier.maxPoints.toLocaleString()} points",
  "marketing.logo": "Logo",
  "marketing.bookyourhotelcom": "book.yourhotel.com",
  "marketing.description": "Description",
  "marketing.restrictions": "Restrictions",
  "marketing.source": "Source",
  "marketing.sentiment": "Sentiment",
  "marketing.source_1": "Source",
  "marketing.actions": "Actions",
  "automation.description": "Description",
  "automation.actions": "Actions",
  "automation.premium": "Premium",
  "automation.description_1": "Description",
  "automation.condition": "Condition",
  "automation.action": "Action",
  "inventory.date": "Date",
  "inventory.type": "Type",
  "inventory.notes": "Notes",
  "inventory.type_1": "Type *",
  "inventory.total": "Total",
  "inventory.actions": "Actions",
  "inventory.notes_1": "Notes",
  "inventory.actions_1": "Actions",
  "inventory.description": "Description",
  "inventory.contact": "Contact",
  "inventory.type_2": "Type",
  "inventory.actions_2": "Actions",
  "inventory.notes_2": "Notes",
  "inventory.type_3": "Type *",
  "events.total": "Total",
  "events.gala": "Gala",
  "events.banquet": "Banquet",
  "events.date": "Date",
  "events.actions": "Actions",
  "events.description": "Description",
  "events.notes": "Notes",
  "events.johnDoe": "Jean Dupont",
  "events.total_1": "Total",
  "events.notes_1": "Notes",
  "events.total_2": "Total",
  "events.actions_1": "Actions",
  "events.description_1": "Description",
  "events.notes_2": "Notes",
  "events.maintenance": "Maintenance",
  "events.description_2": "Description",
  "notifications.type": "Type",
  "notifications.engagement": "Engagement",
  "notifications.wifi": "WiFi",
  "notifications.notifications": "Notifications",
  "notifications.push": "Push",
  "notifications.type_1": "Type",
  "notifications.email_1": "E-mail",
  "notifications.marketing": "Marketing",
  "notifications.push_1": "Push",
  "notifications.actions": "Actions",
  "notifications.variables": "Variables",
  "staff.actions": "Actions",
  "staff.date": "Date",
  "staff.date_1": "Date",
  "staff.actions_1": "Actions",
  "staff.notes": "Notes",
  "staff.certification": "Certification",
  "staff.actions_2": "Actions",
  "staff.notes_1": "Notes",
  "staff.urgent": "Urgent",
  "staff.actions_3": "Actions",
  "staff.description": "Description",
  "staff.notes_2": "Notes",
  "integrations.mode": "Mode",
  "integrations.testsandbox": "Test/Bac à sable",
  "integrations.live": "Production",
  "integrations.transactions": "Transactions",
  "integrations.volume": "Volume",
  "integrations.mode_1": "Mode",
  "integrations.testsandbox_1": "Test/Bac à sable",
  "integrations.live_1": "Production",
  "integrations.sandbox": "Bac à sable",
  "integrations.apiCredentials": "Identifiants API",
  "integrations.apiKey": "Clé API",
  "integrations.secretKey_1": "Clé secrète",
  "integrations.merchantId_1": "ID marchand",
  "integrations.webhookSecret_1": "Secret webhook",
  "integrations.transactions_1": "Transactions",
  "integrations.volume_1": "Volume",
  "integrations.test": "Test",
  "integrations.mode_2": "Mode :",
  "integrations.apiKey_1": "Clé API :",
  "integrations.apiKey_2": "Clé API",
  "integrations.secretKey_2": "Clé secrète",
  "integrations.merchantId_2": "ID marchand",
  "integrations.mode_3": "Mode",
  "integrations.testsandbox_2": "Test/Bac à sable",
  "integrations.live_2": "Production",
  "integrations.transactions_2": "Transactions",
  "integrations.volume_2": "Volume",
  "integrations.test_1": "Test",
  "integrations.apiEndpoint": "Point de terminaison API",
  "integrations.apiKey_3": "Clé API",
  "integrations.merchantId_3": "ID marchand",
  "integrations.menu": "Menu",
  "integrations.actions": "Actions",
  "integrations.port": "Port",
  "webhooks.actions": "Actions",
  "help.articleurlslug": "slug-de-l-article",
  "help.articles": "Articles",
  "help.slug": "Slug",
  "help.articleurlslug_1": "slug-de-l-article",
  "parking.actions": "Actions",
  "parking.toyota": "Toyota",
  "parking.camry": "Camry",
  "parking.maintenance": "Maintenance",
  "parking.type": "Type",
  "parking.actions_1": "Actions",
  "parking.toyota_1": "Toyota",
  "parking.camry_1": "Camry",
  "iot.thermostat": "Thermostat",
  "iot.type": "Type",
  "iot.actions": "Actions",
  "iot.wifi": "WiFi",
  "iot.zigbee": "Zigbee",
  "iot.zwave": "Z-Wave",
  "iot.bluetooth": "Bluetooth",
  "iot.coKg": "CO₂ (kg)",
  "iot.auto": "Auto",
  "iot.volume": "Volume",
  "chain.code": "Code",
  "chain.actions": "Actions",
  "chain.description": "Description",
  "chain.logoUrl": "URL du logo",
  "chain.brandStandardsJson": "Normes de marque (JSON)",
  "chain.jsonObjectDefiningBrandStandardsCheckinoutTimesAmenitiesEtc": "Objet JSON définissant les normes de marque (horaires d'enregistrement/départ, équipements, etc.)",
  "chain.brandDescription": "Description de la marque...",
  "chain.nameAndCodeAreRequired": "Le nom et le code sont requis",
  "chain.codeMustBe110UppercaseLettersAndNumbersOnly": "Le code doit contenir 1 à 10 lettres majuscules et chiffres uniquement",
  "chain.aUniqueCodeMax10Characters": "Un code unique (max 10 caractères)",
  "chain.noDataAvailable": "Aucune donnée disponible",
  "chain.overviewOfAllPropertiesInYourHotelChain": "Vue d'ensemble de tous les établissements de votre chaîne hôtelière",
  "chain.totalProperties_1": "Total des établissements",
  "chain.totalRooms": "Total des chambres",
  "chain.acrossAllProperties": "Tous établissements confondus",
  "chain.currentlyStaying": "Actuellement en séjour",
  "chain.checkinsScheduled": "Arrivées planifiées",
  "chain.checkoutsScheduled": "Départs planifiés",
  "chain.revenueAndOccupancyByProperty": "Revenus et occupation par établissement",
  "chain.noPropertyDataAvailable": "Aucune donnée d'établissement disponible",
  "chain.propertiesByBrand": "Établissements par marque",
  "chain.noBrandDataAvailable": "Aucune donnée de marque disponible",
  "chain.noBrandsCreatedYet": "Aucune marque créée",
  "chain.performanceMetricsForEachProperty": "Indicateurs de performance pour chaque établissement",
  "chain.noPropertiesAvailable": "Aucun établissement disponible",
  "chain.property": "Établissement",
  "chain.type": "Type",
  "chain.location": "Emplacement",
  "chain.rooms": "Chambres",
  "chain.bookings": "Réservations",
  "chain.revenue": "Revenus",
  "chain.occupancy": "Occupation",
  "chain.filterByBrand": "Filtrer par marque",
  "chain.noDataAvailable_1": "Aucune donnée disponible",
  "chain.comparePerformanceAcrossAllProperties": "Comparer les performances de tous les établissements",
  "chain.totalRevenue": "Revenus totaux",
  "chain.averageDailyRate": "Tarif journalier moyen",
  "chain.properties_1": "Établissements",
  "chain.trends": "Tendances",
  "chain.revenueByProperty": "Revenus par établissement",
  "chain.topPerformingPropertiesByRevenue": "Meilleurs établissements par revenus",
  "chain.breakdownByBookingChannel": "Répartition par canal de réservation",
  "chain.topByRevenue": "Top par revenus",
  "chain.topByOccupancy": "Top par occupation",
  "chain.topByBookings": "Top par réservations",
  "chain.topNationalitiesByBookingCount": "Top nationalités par nombre de réservations",
  "chain.noDemographicDataAvailable": "Aucune donnée démographique disponible",
  "chain.detailedMetricsForEachProperty": "Métriques détaillées pour chaque établissement",
  "chain.noPropertyDataAvailable_1": "Aucune donnée d'établissement disponible",
  "chain.property_1": "Établissement",
  "chain.type_1": "Type",
  "chain.location_1": "Emplacement",
  "chain.rooms_1": "Chambres",
  "chain.bookings_1": "Réservations",
  "chain.revenue_1": "Revenus",
  "chain.occupancy_1": "Occupation",
  "chain.revenueByBrand": "Revenus par marque",
  "chain.compareBrandPerformance": "Comparer les performances des marques",
  "chain.noBrandDataAvailable_1": "Aucune donnée de marque disponible",
  "chain.summaryByBrand": "Résumé par marque",
  "chain.dailyRevenueOverTheSelectedPeriod": "Revenus quotidiens sur la période sélectionnée",
  "chain.noTrendDataAvailable": "Aucune donnée de tendance disponible",
  "chain.occupancyAndBookingsComparison": "Comparaison d'occupation et de réservations",
  "chain.noComparisonDataAvailable": "Aucune donnée de comparaison disponible",
  "chain.filterByBrand_1": "Filtrer par marque",
  "ads.total": "Total",
  "ads.paused": "En pause",
  "ads.budget": "Budget",
  "ads.spent": "Dépensé",
  "ads.draft": "Brouillon",
  "ads.impressions": "Impressions",
  "ads.clicks": "Clics",
  "ads.conversions": "Conversions",
  "ads.revenue": "Revenus",
  "ads.pause": "Pause",
  "ads.activate": "Activer",
  "ads.configureYourAdvertisingCampaign": "Configurez votre campagne publicitaire",
  "ads.platform": "Plateforme",
  "ads.description": "Description",
  "ads.daily": "Quotidien",
  "ads.lifetime": "Durée de vie",
  "ads.automatic": "Automatique",
  "ads.manual": "Manuel",
  "ads.enhancedCpc": "CPC amélioré",
  "ads.targetCpaOptional": "CPA cible (facultatif)",
  "ads.targetRoasOptional": "ROAS cible (facultatif)",
  "ads.schedule": "Planification",
  "ads.egSummerPromotion2024": "ex., Promotion estivale 2024",
  "ads.optionalDescription": "Description facultative",
  "ads.manualBidAmount": "Montant de l'enchère manuelle",
  "ads.costPerAcquisition": "Coût par acquisition",
  "ads.returnOnAdSpend": "Retour sur dépense publicitaire",
  "ads.campaignNameIsRequired": "Le nom de la campagne est requis",
  "ads.campaignDeleted": "Campagne supprimée",
  "ads.disconnect": "Déconnecter",
  "ads.totalBudget": "Budget total",
  "ads.totalRevenue": "Revenus totaux",
  "ads.test": "Test",
  "ads.meta": "Meta",
  "ads.impressions_1": "Impressions",
  "ads.conversions_1": "Conversions",
  "ads.conv": "Conv.",
  "ads.totalRevenue_1": "Revenus totaux",
  "ads.totalSpend": "Dépenses totales",
  "portal.total": "Total",
  "portal.identification": "Identification",
  "portal.newYork": "New York",
  "portal.totalAmount": "Montant total",
  "portal.allergies": "Allergies",
  "gdpr.totalRequests": "Total des demandes",
  "gdpr.actions": "Actions",
  "gdpr.format": "Format",
  "audit.module": "Module",
  "audit.action": "Action",
  "communication.total": "Total",
  "communication.whatsapp": "WhatsApp",
  "profile.sessions": "Sessions",
  "profile.notifications": "Notifications",
  "profile.parisCet": "Paris (CET)",
  "profile.tokyoJst": "Tokyo (JST)",
  "frontdesk.totalAmount": "Montant total",
  "frontdesk.notes": "Notes",
  "frontdesk.accessible": "Accessible",
  "frontdesk.maintenance": "Maintenance",
  "frontdesk.folio": "Folio",
  "frontdesk.taxes": "Taxes",
  "frontdesk.total": "Total",
  "frontdesk.totalRooms": "Total des chambres",
  "frontdesk.dates": "Dates",
  "frontdesk.moveHistoryTable.date": "Date",
  "frontdesk.upiIdPlaceholder": "yourname@upi",
  "frontdesk.date": "Date",
  "frontdesk.branding": "Image de marque",
  "frontdesk.image": "Image",
  "pms.propertyType": "Type",
  "pms.phonePlaceholder": "+91 98765 43210",
  "pms.latitude": "Latitude",
  "pms.longitude": "Longitude",
  "pms.description": "Description",
  "pms.ratePlanCode": "Code",
  "pms.totalRevenue": "Revenus totaux",
  "pms.revenueCardDesc": "Revenus totaux",
  "guests.phonePlaceholder": "+1 555 123 4567",
  "guests.cityPlaceholder": "New York"
};

const locale = JSON.parse(fs.readFileSync('src/messages/fr.json', 'utf-8'));
let applied = 0;
for (const [k, v] of Object.entries(translations)) {
  if (v && typeof v === 'string') {
    deepSet(locale, k, v);
    applied++;
  }
}
fs.writeFileSync('src/messages/fr.json', JSON.stringify(locale, null, 2) + '\n', 'utf-8');
console.log(`Applied ${applied} French translations (batch 2)`);
