// Apply Marathi translations for all 1201 untranslated keys
import fs from 'fs';

function deepSet(obj, path, val) {
  const parts = path.split('.');
  let cur = obj;
  for (let i = 0; i < parts.length - 1; i++) {
    if (!(parts[i] in cur) || typeof cur[parts[i]] !== 'object') cur[parts[i]] = {};
    cur = cur[parts[i]];
  }
  cur[parts[parts.length - 1]] = val;
}

const translations = {
  // ===== DASHBOARD =====
  "dashboard.daysAgoShort": "{count}d",
  "dashboard.hoursAgoShort": "{count}h",
  "dashboard.minutesAgoShort": "{count}m",
  "dashboard.networkConnectivity": "नेटवर्क आणि कनेक्टिव्हिटी",

  // ===== POS (Restaurant & POS) =====
  "pos.dateRequired": "तारीख *",
  "pos.timeRequired": "वेळ *",
  "pos.tableOptional": "टेबल (ऐच्छिक)",
  "pos.specialRequestsLabel": "विशेष विनंत्या",
  "pos.guestPhonePlaceholder": "+1 555 123 4567",
  "pos.guestNamePlaceholder": "John Doe",
  "pos.lowStockAlerts": "कमी स्टॉक अलर्ट",
  "pos.inStock": "स्टॉकमध्ये",
  "pos.lowStock": "कमी स्टॉक",
  "pos.itemNameRequired": "आयटमचे नाव *",
  "pos.unitCost": "एकक किंमत",
  "pos.lowThreshold": "किमान पातळी",
  "pos.lastRestocked": "शेवटचे रीस्टॉक",
  "pos.adjustStock": "स्टॉक समायोजित करा",
  "pos.roomServiceTitle": "रूम सर्व्हिस",
  "pos.noRoomSelected": "कोणतीही खोली निवडलेली नाही",
  "pos.orderSummary": "ऑर्डर सारांश",
  "pos.tableLayoutTitle": "टेबल लेआउट",
  "pos.tableNumberRequired": "टेबल क्रमांक *",
  "pos.tableName": "टेबलचे नाव",
  "pos.widthPx": "रुंदी (px)",
  "pos.heightPx": "उंची (px)",
  "pos.noTableSelected": "कोणतीही टेबल निवडलेली नाही",
  "pos.noTablesYet": "अद्याप टेबल नाहीत",
  "pos.resetZoom": "झूम रीसेट करा",
  "pos.zoomIn": "झूम इन",
  "pos.zoomOut": "झूम आउट",
  "pos.toggleGridSnap": "ग्रिड स्नॅप टॉगल करा",
  "pos.staffAssignmentTitle": "स्टाफ असाइनमेंट",
  "pos.onDutyBadge": "ड्युटीवर",
  "pos.staffMember": "स्टाफ सदस्य",
  "pos.prepTimeLabel": "तयारी वेळ (मिनिटे)",
  "pos.cookTime": "शिजवण्याचा वेळ (मिनिटे)",
  "pos.yieldServings": "परिणाम (सर्व्हिंग्स)",
  "pos.sellingPrice": "विक्री किंमत:",
  "pos.foodCost": "अन्न खर्च:",
  "pos.restaurantReportsTitle": "रेस्टॉरंट अहवाल",
  "pos.avgOrderValue": "सरासरी ऑर्डर मूल्य",
  "pos.tableOccupancy": "टेबल ऑक्युपन्सी",
  "pos.revenueTrend": "रेव्हेन्यू ट्रेंड",
  "pos.topSellingItems": "सर्वाधिक विक्री होणारी आयटमे",
  "pos.salesSummary": "विक्री सारांश",
  "pos.categoryPerformance": "श्रेणी कामगिरी",
  "pos.ghostItems": "घोस्ट आयटमे (कधीही ऑर्डर झालेली नाहीत)",
  "pos.avgDiningDuration": "सरासरी जेवण वेळ",
  "pos.mostUsed": "सर्वाधिक वापरले",
  "pos.leastUsed": "किमान वापरले",
  "pos.tableTurnover": "टेबल टर्नओव्हर",
  "pos.receiptTemplatesTitle": "रिसीट टेम्पलेट",
  "pos.printSample": "नमुना छापा",
  "pos.restaurantName": "रेस्टॉरंटचे नाव",
  "pos.thankYouMessage": "आभार संदेश",
  "pos.fontSize": "फॉन्ट आकार",
  "pos.livePreview": "लाइव्ह प्रीव्ह्यू",
  "pos.noActiveOrder": "कोणताही सक्रिय ऑर्डर नाही",
  "pos.menuModifiersTitle": "मेन्यू मॉडिफायर",
  "pos.noModifierGroups": "कोणतेही मॉडिफायर ग्रुप नाहीत",
  "pos.appliedTo": "यावर लागू",
  "pos.groupNameRequired": "ग्रुपचे नाव *",
  "pos.selectionTypeLabel": "निवड प्रकार",
  "pos.minSelections": "किमान निवडी",
  "pos.maxSelections": "कमाल निवडी",
  "pos.appliesToMenuItems": "मेन्यू आयटमवर लागू",
  "pos.menuVariantsTitle": "मेन्यू व्हेरिअंट / आकार",
  "pos.itemsWithVariants": "व्हेरिअंटसह आयटमे",
  "pos.menuItemRequired": "मेन्यू आयटम *",
  "pos.variantNameRequired": "व्हेरिअंट नाव *",
  "pos.variantPriceRequired": "किंमत *",
  "pos.sortOrder": "क्रमवारी",
  "pos.defaultVariant": "डिफॉल्ट व्हेरिअंट",
  "pos.bulkCreateVariants": "बल्क व्हेरिअंट तयार करा",
  "pos.menuItemImage": "मेन्यू आयटम प्रतिमा",
  "pos.applyDiscount": "डिस्काउंट लागू करा",
  "pos.recentDiscounts": "अलीकडील डिस्काउंट",
  "pos.specialInstructionsLabel": "विशेष सूचना",
  "pos.splitOrder": "ऑर्डर विभाजित करा",
  "pos.splitEqually": "समान विभाजन करा",
  "pos.tableMergeTitle": "टेबल विलीन / विभाजन",
  "pos.availableTablesLabel": "उपलब्ध टेबल",
  "pos.mergeTables": "टेबल विलीन करा",
  "pos.partySizeLabel": "पार्टीचा आकार",

  // ===== REVENUE =====
  "revenue.pricingRulesTitle": "किंमत नियम",
  "revenue.avgAdjustment": "सरासरी समायोजन",
  "revenue.seasonalRules": "हंगामी नियम",
  "revenue.ruleName": "नियमाचे नाव",
  "revenue.ruleType": "नियमाचा प्रकार",
  "revenue.priceIncrease": "किंमत वाढ",
  "revenue.priceDecrease": "किंमत घट",
  "revenue.dynamicPricing": "डायनॅमिक किंमत",
  "revenue.seasonalRate": "हंगामी दर",
  "revenue.valueType": "मूल्य प्रकार",
  "revenue.fixedAmount": "निश्चित रक्कम",
  "revenue.adjustmentValue": "समायोजन मूल्य",
  "revenue.effectiveFrom": "यापासून प्रभावी",
  "revenue.effectiveTo": "यापर्यंत प्रभावी (ऐच्छिक)",
  "revenue.demandForecastingTitle": "मागणी अंदाज",
  "revenue.noForecastData": "अंदाज डेटा उपलब्ध नाही",
  "revenue.predictedOccupancy": "अंदाजित ऑक्युपन्सी",
  "revenue.forecastAccuracy": "अंदाज अचूकता",
  "revenue.peakDemandDays": "सर्वाधिक मागणीचे दिवस",
  "revenue.bookingPace": "बुकिंग गती",
  "revenue.seasonalFactor": "हंगामी घटक",
  "revenue.forecastChart": "अंदाज चार्ट",
  "revenue.seasonalTrends": "हंगामी ट्रेंड",
  "revenue.eventImpact": "इव्हेंट प्रभाव",
  "revenue.demandForecast": "मागणी अंदाज",
  "revenue.confidenceInterval": "विश्वासार्ह अंतर",
  "revenue.dailyForecastBreakdown": "दैनिक अंदाज विभाजन",
  "revenue.seasonalOccupancy": "हंगामी ऑक्युपन्सी पॅटर्न",
  "revenue.dailyForecast": "दैनिक अंदाज",
  "revenue.competitorPricingTitle": "स्पर्धक किंमत",
  "revenue.ourPrice": "आमची किंमत",
  "revenue.marketAverage": "बाजार सरासरी",
  "revenue.competitorsTracked": "ट्रॅक केलेले स्पर्धक",
  "revenue.marketPosition": "बाजार स्थिती",
  "revenue.priceHistoryComparison": "किंमत इतिहास तुलना",
  "revenue.competitorRates": "स्पर्धक दर",
  "revenue.pricePositionAnalysis": "किंमत स्थिती विश्लेषण",
  "revenue.marketLow": "बाजार किमान",
  "revenue.marketHigh": "बाजार कमाल",
  "revenue.marketAvg": "बाजार सरासरी",
  "revenue.competitorNameRequired": "स्पर्धकाचे नाव *",
  "revenue.potentialRevenue": "संभाव्य रेव्हेन्यू",
  "revenue.avgConfidence": "सरासरी विश्वास",
  "revenue.appliedThisMonth": "या महिन्यात लागू केले",
  "revenue.appliedSuggestions": "लागू केलेले सूचना",

  // ===== REPORTS =====
  "reports.staffPerformanceTitle": "स्टाफ कामगिरी",
  "reports.avgRating": "सरासरी रेटिंग",
  "reports.tasksCompleted": "पूर्ण झालेली कार्ये",
  "reports.avgResponse": "सरासरी प्रतिसाद",
  "reports.weeklyTaskTrend": "साप्ताहिक कार्य ट्रेंड",
  "reports.departmentPerformance": "विभाग कामगिरी",
  "reports.topPerformers": "उत्कृष्ट कार्यकर्ते",
  "reports.avgTime": "सरासरी वेळ",
  "reports.guestAnalyticsTitle": "पाहुणा अॅनॅलिटिक्स अहवाल",
  "reports.bookingPatternsTab": "बुकिंग पॅटर्न",
  "reports.returningRate": "पुन्हा येण्याचा दर",
  "reports.monthlyBookingTrend": "मासिक बुकिंग ट्रेंड",
  "reports.topMarkets": "सर्वोत्तम बाजार",
  "reports.loyaltyProgram": "ऑयल्टी प्रोग्राम",
  "reports.ageGroups": "वयोगट",
  "reports.topNationalities": "सर्वाधिक राष्ट्रीयता",
  "reports.scheduledReportsTitle": "शेड्यूल्ड अहवाल",
  "reports.reportName": "अहवालाचे नाव",
  "reports.reportType": "अहवालाचा प्रकार",
  "reports.revenueReport": "रेव्हेन्यू अहवाल",
  "reports.occupancyReport": "ऑक्युपन्सी अहवाल",
  "reports.staffPerformanceReport": "स्टाफ कामगिरी",
  "reports.customReport": "कस्टम अहवाल",
  "reports.performanceSummary": "कामगिरी सारांश",
  "reports.revenueReportsTitle": "रेव्हेन्यू अहवाल",
  "reports.paymentsCollected": "गोळा केलेली पेमेंट",
  "reports.avgBookingValue": "सरासरी बुकिंग मूल्य",
  "reports.occupancyReportsTitle": "ऑक्युपन्सी अहवाल",
  "reports.avgOccupancy": "सरासरी ऑक्युपन्सी",
  "reports.peakOccupancy": "कमाल ऑक्युपन्सी",
  "reports.lowOccupancy": "किमान ऑक्युपन्सी",
  "reports.occupancyTrend": "ऑक्युपन्सी ट्रेंड",
  "reports.roomStatusDistribution": "खोली स्थिती वितरण",
  "reports.peakDays": "सर्वाधिक दिवस",
  "reports.lowOccupancyDays": "किमान ऑक्युपन्सी दिवस",

  // ===== ADMIN =====
  "admin.monthlyRecurringRevenue": "मासिक पुनरावर्ती उत्पन्न",
  "admin.annualRecurringRevenue": "वार्षिक पुनरावर्ती उत्पन्न",
  "admin.revenueGrowth": "रेव्हेन्यू वाढ",
  "admin.churnRate": "कर्जचक्र दर",
  "admin.customerLifetimeValue": "ग्राहक आयुष्य मूल्य",
  "admin.customerAcquisitionCost": "ग्राहक प्राप्ती खर्च",
  "admin.monthlyRevenueTrend": "मासिक रेव्हेन्यू ट्रेंड",
  "admin.systemRoles": "सिस्टम भूमिका",
  "admin.customRoles": "कस्टम भूमिका",
  "admin.testPermissions": "परवानगी चाचणी",
  "admin.adminRoleProtected": "ॲडमिन भूमिका सुरक्षित",
  "admin.permissionTester": "परवानगी चाचणीकर्ता",
  "admin.roleComparison": "भूमिका तुलना",
  "admin.commonPermissions": "सामान्य परवानग्या",
  "admin.permissionComparisonMatrix": "परवानगी तुलना मॅट्रिक्स",
  "admin.bothGranted": "दोन्ही प्रदान केली",
  "admin.rolePermissionAuditLog": "भूमिका आणि परवानगी ऑडिट लॉग",
  "admin.auditTrail": "ऑडिट ट्रेल",
  "admin.rolesPermissions": "भूमिका आणि परवानग्या",
  "admin.permissionMatrix": "परवानगी मॅट्रिक्स",
  "admin.auditLog": "ऑडिट लॉग",
  "admin.displayName": "प्रदर्शन नाव",
  "admin.quickPermissions": "द्रुत परवानग्या",
  "admin.noAccess": "प्रवेश नाही",
  "admin.fullAccess": "संपूर्ण प्रवेश",
  "admin.manageRolesAndTheirPermissionAssignmentsAcrossTotalmodulesModulesAndTotalpermissionsPermissions": "{totalModules} मॉड्यूल आणि {totalPermissions} परवानग्यांवर भूमिका आणि त्यांच्या परवानगी असाइनमेंट व्यवस्थापित करा",
  "admin.effectivepermssizeEffectivePermissionsIncludingWildcards": "{effectivePerms.size} प्रभावी परवानग्या (वाइल्डकार्डसह)",
  "admin.permissionsSavedForRoledisplayname": "${role.displayName} साठी परवानग्या जतन केल्या",
  "admin.role1": "भूमिका 1",
  "admin.role2": "भूमिका 2",
  "admin.roleName": "भूमिका नाव *",
  "admin.displayName_1": "प्रदर्शन नाव *",
  "admin.systemHealth": "सिस्टम आरोग्य",
  "admin.memoryUsage": "मेमरी वापर",
  "admin.systemUptime": "सिस्टम अपटाइम",
  "admin.serviceStatus": "सेवा स्थिती",
  "admin.databaseMetrics": "डेटाबेस मेट्रिक्स",
  "admin.avgLatency": "सरासरी विलंब",
  "admin.connectionPool": "कनेक्शन पूल",
  "admin.storageUsed": "वापरलेले स्टोरेज",
  "admin.diskUsage": "डिस्क वापर",
  "admin.recentAlerts": "अलीकडील अलर्ट",
  "admin.onTrial": "ट्रायलवर",
  "admin.trialsExpiringSoon": "ट्रायल लवकरच संपत आहेत",
  "admin.tenantSubscriptions": "टेनंट सबस्क्रिप्शन",
  "admin.planChangeSummary": "योजना बदल सारांश",
  "admin.confirmStatusChange": "स्थिती बदल पुष्टी करा",
  "admin.downgradePlan": "योजना डाउनग्रेड करा",
  "admin.upgradePlan": "योजना अपग्रेड करा",
  "admin.tenantStatusChangedToNewstatus": "टेनंट स्थिती ${newStatus} मध्ये बदलली",
  "admin.maxProperties": "कमाल मालमत्ता",
  "admin.maxUsers": "कमाल वापरकर्ते",
  "admin.maxRooms": "कमाल खोल्या",
  "admin.onTrial_1": "ट्रायलवर",
  "admin.monthlyRevenue": "मासिक रेव्हेन्यू",
  "admin.usageTracking": "वापर ट्रॅकिंग",
  "admin.accountLimits": "खाते मर्यादा",
  "admin.usageAlerts": "वापर अलर्ट",
  "admin.loadingUserManagement": "यूजर व्यवस्थापन लोड होत आहे...",
  "admin.noRole": "भूमिका नाही",
  "admin.lastLogin": "शेवटचा लॉग इन",
  "admin.platformAdmin": "प्लॅटफॉर्म ॲडमिन",
  "admin.resetPassword": "पासवर्ड रीसेट करा",
  "admin.jobTitle": "पदाचे नाव",
  "admin.frontDesk": "फ्रंट डेस्क",
  "admin.isplatformadminAListOfAllUsersAcrossTenantsAListOfAllUsersInYourOrganization": "{isPlatformAdmin\n              ? 'सर्व टेनंटमधील सर्व वापरकर्त्यांची यादी'\n              : 'तुमच्या संस्थेतील सर्व वापरकर्त्यांची यादी'\n            }",
  "admin.tenant_4": "टेनंट *",
  "admin.firstName": "पहिले नाव *",
  "admin.lastName": "आडनाव *",
  "admin.email_1": "ईमेल *",
  "admin.newPassword": "नवीन पासवर्ड *",

  // ===== CHANNELS =====
  "channels.bookingSync": "बुकिंग सिंक",
  "channels.roomType": "खोली प्रकार",
  "channels.centralReservationSystem": "केंद्रीय आरक्षण प्रणाली",
  "channels.bookingSources": "बुकिंग स्रोत",
  "channels.lastSync": "शेवटचा सिंक",
  "channels.syncInterval": "सिंक अंतराल",
  "channels.autoSync": "ऑटो सिंक",
  "channels.connectionName": "कनेक्शनचे नाव",
  "channels.apiKey": "API की",
  "channels.syncIntervalMinutes": "सिंक अंतराल (मिनिटे)",
  "channels.inventorySync": "इन्व्हेंटरी सिंक",
  "channels.syncRate": "सिंक दर",
  "channels.syncProgress": "सिंक प्रगती",
  "channels.roomType_1": "खोली प्रकार",
  "channels.lastSync_1": "शेवटचा सिंक",
  "channels.syncingInventoryForChannelname": "${channelName} साठी इन्व्हेंटरी सिंक होत आहे",
  "channels.channelMapping": "चॅनेल मॅपिंग",
  "channels.roomType_2": "खोली प्रकार",
  "channels.ratePlanOptional": "रेट प्लॅन (ऐच्छिक)",
  "channels.externalRoomName": "बाह्य खोली नाव",
  "channels.externalRateName": "बाह्य दर नाव",
  "channels.syncInventory": "इन्व्हेंटरी सिंक करा",
  "channels.syncRates": "दर सिंक करा",
  "channels.syncRestrictions": "निर्बंध सिंक करा",
  "channels.inventorySync_1": "इन्व्हेंटरी सिंक",
  "channels.rateSync": "दर सिंक",
  "channels.ratePlan": "रेट प्लॅन",
  "channels.externalRoom": "बाह्य खोली",
  "channels.externalRate": "बाह्य दर",
  "channels.syncInv": "इन्व्हेंटरी सिंक.",
  "channels.syncRest": "निर्बंध सिंक.",
  "channels.itemslengthMappingsConfigured": "{items.length} मॅपिंग कॉन्फिगर केले",
  "channels.asiaPacific": "आशिया पॅसिफिक",
  "channels.middleEast": "मध्य पूर्व",
  "channels.displayName": "प्रदर्शन नाव",
  "channels.autoSync_1": "ऑटो सिंक",
  "channels.syncInterval_1": "सिंक अंतराल",
  "channels.integrationProgress": "इंटिग्रेशन प्रगती",
  "channels.noChannelConnections": "कोणतेही चॅनेल कनेक्शन नाहीत",
  "channels.testConnection": "कनेक्शन चाचणी",
  "channels.syncNow": "आता सिंक करा",
  "channels.criticalPriority": "गंभीर प्राधान्य",
  "channels.rateSync_1": "दर सिंक",
  "channels.avgRate": "सरासरी दर",
  "channels.roomType_3": "खोली प्रकार",
  "channels.ratePlan_1": "रेट प्लॅन",
  "channels.basePrice": "बेस किंमत",
  "channels.channelPrice": "चॅनेल किंमत",
  "channels.autoAdjust": "ऑटो समायोजन",
  "channels.lastSync_2": "शेवटचा सिंक",
  "channels.basePriceReference": "बेस किंमत (संदर्भ)",
  "channels.saveChanges": "बदल जतन करा",
  "channels.channelRestrictions": "चॅनेल निर्बंध",
  "channels.stopSell": "विक्री थांबवा",
  "channels.minStay": "किमान राहणे",
  "channels.maxStay": "कमाल राहणे",
  "channels.roomType_4": "खोली प्रकार",
  "channels.minimumStayNights": "किमान राहण्याच्या रात्री",
  "channels.maximumStayNights": "कमाल राहण्याच्या रात्री",
  "channels.saveChanges_1": "बदल जतन करा",
  "channels.itemslengthRestrictionRulesConfigured": "{items.length} निर्बंध नियम कॉन्फिगर केले",
  "channels.successRate": "यश दर",

  // ===== CRM =====
  "crm.marketingCampaigns": "मार्केटिंग कॅम्पेइन",
  "crm.avgOpenRate": "सरासरी ओपन दर",
  "crm.avgClickRate": "सरासरी क्लिक दर",
  "crm.newCampaign": "नवीन कॅम्पेइन",
  "crm.campaignName": "कॅम्पेइनचे नाव",
  "crm.subjectLine": "विषय ओळ",
  "crm.targetSegments": "लक्षित सेगमेंट",
  "crm.scheduleOptional": "वेळापत्रक (ऐच्छिक)",
  "crm.scheduleCampaign": "कॅम्पेइन शेड्यूल करा",
  "crm.deliveryProgress": "डिलिव्हरी प्रगती",
  "crm.feedbackReviews": "फीडबॅक आणि रिव्ह्यू",
  "crm.avgRating": "सरासरी रेटिंग",
  "crm.responseRate": "प्रतिसाद दर",
  "crm.positiveSentiment": "सकारात्मक भावना",
  "crm.openFeedback": "खुले फीडबॅक",
  "crm.guestFeedback": "पाहुणा फीडबॅक",
  "crm.reviewResponse": "रिव्ह्यू प्रतिसाद",
  "crm.yourResponse": "तुमचा प्रतिसाद",
  "crm.resolveFeedback": "फीडबॅक सोडवा",
  "crm.guestSegments": "पाहुणा सेगमेंट",
  "crm.avgMemberssegment": "सरासरी सदस्य/सेगमेंट",
  "crm.segmentName": "सेगमेंट नाव",
  "crm.segmentationRules": "सेगमेंटेशन नियम",
  "crm.loyaltyPrograms": "ऑयल्टी प्रोग्राम",
  "crm.pointsEarnedMonth": "मिळवलेले गुण (महिना)",
  "crm.pointsRedeemedMonth": "वापरलेले गुण (महिना)",
  "crm.avgPointsmember": "सरासरी गुण/सदस्य",
  "crm.tierLevels": "टायर स्तर",
  "crm.redemptionOptions": "रिडेम्प्शन पर्याय",
  "crm.topMembers": "शीर्ष सदस्य",
  "crm.memberDistribution": "सदस्य वितरण",
  "crm.pointsRedemptionOptions": "गुण रिडेम्प्शन पर्याय",
  "crm.pointsValue": "गुण मूल्य",
  "crm.perPointValue": "प्रति गुण मूल्य",
  "crm.topLoyaltyMembers": "शीर्ष ऑयल्टी सदस्य",
  "crm.tierminpointstolocalestringTiermaxpoints999999TiermaxpointstolocalestringPoints": "{tier.minPoints.toLocaleString()} - {tier.maxPoints === 999999 ? '∞' : tier.maxPoints.toLocaleString()} गुण",
  "crm.cohortAnalysis": "कोहॉर्ट विश्लेषण",
  "crm.atriskGuests": "जोखीमीचे पाहुणे",
  "crm.lifetimeValue": "आयुष्य मूल्य",
  "crm.guestJourneyFunnel": "पाहुणा प्रवास फनेल",
  "crm.retentionInsights": "रिटेंशन अंतर्दृष्टी",
  "crm.retentionActivity": "रिटेंशन क्रियाकलाप",
  "crm.cohortRetentionAnalysis": "कोहॉर्ट रिटेंशन विश्लेषण",
  "crm.cohort": "कोहॉर्ट",
  "crm.averageLifetimeValue": "सरासरी आयुष्य मूल्य",
  "crm.avgStays": "सरासरी राहणे",
  "crm.avgSpend": "सरासरी खर्च",

  // ===== MARKETING =====
  "marketing.directBookingEngine": "डायरेक्ट बुकिंग इंजिन",
  "marketing.directBookings": "डायरेक्ट बुकिंग",
  "marketing.conversionRate": "रूपांतर दर",
  "marketing.bookingSources": "बुकिंग स्रोत",
  "marketing.directBooking": "डायरेक्ट बुकिंग",
  "marketing.recentPerformance": "अलीकडील कामगिरी",
  "marketing.pageViews": "पृष्ठ दृश्ये",
  "marketing.bookingAttempts": "बुकिंग प्रयत्न",
  "marketing.completedBookings": "पूर्ण झालेल्या बुकिंग",
  "marketing.abandonmentRate": "सोडून देण्याचा दर",
  "marketing.commissionComparison": "कमिशन तुलना",
  "marketing.directBookingSavings": "डायरेक्ट बुकिंग बचत",
  "marketing.enableBookingEngine": "बुकिंग इंजिन सक्षम करा",
  "marketing.customDomainOptional": "कस्टम डोमेन (ऐच्छिक)",
  "marketing.requirePayment": "पेमेंट आवश्यक",
  "marketing.depositPercentage": "डिपॉझिट टक्केवारी",
  "marketing.cancellationPolicy": "रद्दीकरण धोरण",
  "marketing.brandingAppearance": "ब्रँडिंग आणि दृश्य",
  "marketing.primaryColor": "प्राथमिक रंग",
  "marketing.secondaryColor": "द्वितीयक रंग",
  "marketing.uploadLogo": "लोगो अपलोड करा",
  "marketing.bookNow": "आता बुक करा",
  "marketing.embedWidget": "विजेट एम्बेड करा",
  "marketing.analyticsIntegration": "अॅनॅलिटिक्स इंटिग्रेशन",
  "marketing.bookyourhotelcom": "book.yourhotel.com",
  "marketing.promotionsAmpOffers": "प्रमोशन आणि ऑफर",
  "marketing.expiringSoon": "लवकर संपणारे",
  "marketing.fixedAmount": "निश्चित रक्कम",
  "marketing.freeNight": "मोफत रात्री",
  "marketing.basicInfo": "मूलभूत माहिती",
  "marketing.minNights": "किमान रात्री",
  "marketing.applicableRoomTypes": "लागू खोली प्रकार",
  "marketing.usageLimits": "वापर मर्यादा",
  "marketing.maxTotalUses": "कमाल एकूण वापर",
  "marketing.maxUsesPerUser": "प्रति वापरकर्ता कमाल वापर",
  "marketing.promoCode": "प्रमो कोड *",
  "marketing.discountType": "डिस्काउंट प्रकार *",
  "marketing.discountValue": "डिस्काउंट मूल्य *",
  "marketing.startDate": "सुरुवात तारीख *",
  "marketing.endDate": "समाप्ती तारीख *",
  "marketing.averageRating": "सरासरी रेटिंग",
  "marketing.responseRate": "प्रतिसाद दर",
  "marketing.sentimentScore": "भावना स्कोर",
  "marketing.ratingDistribution": "रेटिंग वितरण",
  "marketing.categoryScores": "श्रेणी गुण",
  "marketing.recentReviews": "अलीकडील रिव्ह्यू",
  "marketing.propertyResponse": "मालमत्ता प्रतिसाद",
  "marketing.yourResponse": "तुमचा प्रतिसाद",
  "marketing.showingDatareviewslengthOfDatapaginationtotalReviews": "{data.pagination.total} पैकी {data.reviews.length} रिव्ह्यू दाखवत आहे",
  "marketing.reviewSources": "रिव्ह्यू स्रोत",
  "marketing.connectedSources": "कनेक्टेड स्रोत",
  "marketing.avgRating": "सरासरी रेटिंग",
  "marketing.syncStatus": "सिंक स्थिती",
  "marketing.lastSync": "शेवटचा सिंक",
  "marketing.autoSync": "ऑटो सिंक",
  "marketing.availablePlatforms": "उपलब्ध प्लॅटफॉर्म",
  "marketing.connectReviewSource": "रिव्ह्यू स्रोत कनेक्ट करा",
  "marketing.connectionName": "कनेक्शनचे नाव",
  "marketing.apiKey": "API की",
  "marketing.syncNow": "आता सिंक करा",
  "marketing.startingSyncForSourcename": "${source.name} साठी सिंक सुरू करत आहे...",

  // ===== AUTOMATION =====
  "automation.successRate": "यश दर",
  "automation.thisWeek": "या आठवड्यात",
  "automation.thisMonth": "या महिन्यात",
  "automation.triggerData": "ट्रिगर डेटा",
  "automation.actionsResult": "क्रिया परिणाम",
  "automation.showingLogslengthOfStatstotalexecutionsTotalExecutions": "{stats.totalExecutions} एकूण एक्सिक्युशनपैकी {logs.length} दाखवत आहे",
  "automation.rulesEngine": "रूल्स इंजिन",
  "automation.successRate_1": "यश दर",
  "automation.ruleName": "नियमाचे नाव",
  "automation.triggerEvent": "ट्रिगर इव्हेंट",
  "automation.triggerConditions": "ट्रिगर अटी",
  "automation.sendEmail": "ईमेल पाठवा",
  "automation.pushNotification": "पुश नोटिफिकेशन",
  "automation.automationTemplates": "ऑटोमेशन टेम्पलेट",
  "automation.useTemplate": "टेम्पलेट वापरा",
  "automation.customizeTemplate": "टेम्पलेट कस्टमाइज करा",
  "automation.workflowBuilder": "वर्कफ्लो बिल्डर",
  "automation.savedWorkflows": "जतन केलेले वर्कफ्लो",
  "automation.startBuildingYourWorkflow": "तुमचा वर्कफ्लो तयार करणे सुरू करा",
  "automation.emailTemplate": "ईमेल टेम्पलेट",
  "automation.welcomeEmail": "स्वागत ईमेल",
  "automation.bookingConfirmation": "बुकिंग पुष्टीकरण",
  "automation.feedbackRequest": "फीडबॅक विनंती",
  "automation.messageTemplate": "संदेश टेम्पलेट",
  "automation.workflowName": "वर्कफ्लो नाव",
  "automation.descriptionOptional": "वर्णन (ऐच्छिक)",

  // ===== INVENTORY =====
  "inventory.netMovement": "निव्वळ हालचाल",
  "inventory.consumedToday": "आज वापरले",
  "inventory.logEntry": "लॉग प्रविष्ट",
  "inventory.logStockMovement": "स्टॉक हालचाल नोंदवा",
  "inventory.stockItem": "स्टॉक आयटम *",
  "inventory.type_1": "प्रकार *",
  "inventory.quantity_1": "प्रमाण *",
  "inventory.lowStock": "कमी स्टॉक",
  "inventory.stockLevel": "स्टॉक पातळी",
  "inventory.quickReorder": "द्रुत पुन्हा ऑर्डर",
  "inventory.minimumLevel": "किमान पातळी:",
  "inventory.unitCost": "एकक किंमत:",
  "inventory.estimatedCost": "अंदाजित खर्च:",
  "inventory.vendor": "विक्रेता *",
  "inventory.orderQuantity": "ऑर्डर प्रमाण *",
  "inventory.newOrder": "नवीन ऑर्डर",
  "inventory.purchaseOrders": "खरेदी ऑर्डर",
  "inventory.orderDate": "ऑर्डर तारीख",
  "inventory.expectedDate": "अपेक्षित तारीख",
  "inventory.orderItems": "ऑर्डर आयटम",
  "inventory.unitPrice": "एकक किंमत",
  "inventory.receiveOrder": "ऑर्डर मिळवा",
  "inventory.cancelOrder": "ऑर्डर रद्द करा",
  "inventory.noKeepOrder": "नाही, ऑर्डर ठेवा",
  "inventory.orderNewstatus": "ऑर्डर ${newStatus}",
  "inventory.order": "ऑर्डर #",
  "inventory.vendor_2": "विक्रेता *",
  "inventory.lowStockItems": "कमी स्टॉक आयटम",
  "inventory.lowStock_1": "कमी स्टॉक",
  "inventory.stockItems": "स्टॉक आयटम",
  "inventory.stockLevel_1": "स्टॉक पातळी",
  "inventory.unitCost_1": "एकक किंमत",
  "inventory.minQuantity": "किमान प्रमाण",
  "inventory.maxQuantity": "कमाल प्रमाण",
  "inventory.reorderPoint": "पुन्हा ऑर्डर बिंदू",
  "inventory.serviceProviders": "सेवा प्रदाते",
  "inventory.paymentTerms": "पेमेंट अटी",
  "inventory.contactPerson": "संपर्क व्यक्ती",
  "inventory.deactivateVendor": "विक्रेता निष्क्रिय करा",
  "inventory.companyName_1": "कंपनीचे नाव *",
  "inventory.type_3": "प्रकार *",

  // ===== EVENTS =====
  "events.eventBookings": "इव्हेंट बुकिंग",
  "events.newEvent": "नवीन इव्हेंट",
  "events.inProgress": "प्रगतीत",
  "events.productLaunch": "उत्पादन प्रक्षेपण",
  "events.teamBuilding": "टीम बिल्डिंग",
  "events.propertySpace": "मालमत्ता / जागा",
  "events.newEventBooking": "नवीन इव्हेंट बुकिंग",
  "events.eventSpace": "इव्हेंट जागा",
  "events.eventType": "इव्हेंट प्रकार",
  "events.expectedGuests": "अपेक्षित पाहुणे",
  "events.dateTime": "तारीख आणि वेळ",
  "events.startTime": "सुरुवातीचा वेळ",
  "events.endTime": "समाप्तीचा वेळ",
  "events.eventName": "इव्हेंटचे नाव",
  "events.startDate": "सुरुवात तारीख",
  "events.endDate": "समाप्ती तारीख",
  "events.johnDoe": "John Doe",
  "events.eventStatusUpdatedToNewstatus": "इव्हेंट स्थिती ${newStatus} मध्ये अद्ययावत केली",
  "events.property_1": "मालमत्ता *",
  "events.eventName_1": "इव्हेंटचे नाव *",
  "events.name_1": "नाव *",
  "events.startDate_1": "सुरुवात तारीख *",
  "events.endDate_1": "समाप्ती तारीख *",
  "events.eventCalendar": "इव्हेंट कॅलेंडर",
  "events.inProgress_1": "प्रगतीत",
  "events.spaceCharge": "जागा शुल्क",
  "events.cateringCharge": "केटरिंग शुल्क",
  "events.otherCharges": "इतर शुल्क",
  "events.eventResources": "इव्हेंट संसाधने",
  "events.inUse": "वापरात",
  "events.categorySummary": "श्रेणी सारांश",
  "events.unitPrice": "एकक किंमत",
  "events.vendorName": "विक्रेत्याचे नाव",
  "events.staffName": "स्टाफचे नाव",
  "events.setupTime": "सेटअप वेळ",
  "events.teardownTime": "डिसमँटल वेळ",
  "events.resourceName": "संसाधनाचे नाव",
  "events.projectorMicrophoneCatering": "प्रोजेक्टर, माइक्रोफोन, केटरिंग...",
  "events.resourceName_1": "संसाधनाचे नाव *",
  "events.eventSpaces": "इव्हेंट जागा",
  "events.minCapacity": "किमान क्षमता",
  "events.maxCapacity": "कमाल क्षमता",
  "events.grandBallroom": "ग्रँड बॅलरूम",
  "events.property_2": "मालमत्ता *",
  "events.name_2": "नाव *",

  // ===== AI =====
  "ai.newChat": "नवीन चॅट",
  "ai.potentialRevenue": "संभाव्य रेव्हेन्यू",
  "ai.saveChanges": "बदल जतन करा",
  "ai.smartRecommendations": "स्मार्ट शिफारसी",
  "ai.autoTagging": "ऑटो टॅगिंग",
  "ai.sentimentAnalysis": "भावना विश्लेषण",
  "ai.apiKey": "API की",
  "ai.maxTokens": "कमाल टोकन",
  "ai.usageThisMonth": "या महिन्यातील वापर",
  "ai.defaultProvider": "डिफॉल्ट प्रदाता",

  // ===== NOTIFICATIONS =====
  "notifications.deliveryRate": "डिलिव्हरी दर",
  "notifications.sentAt": "पाठवलेले वेळी",
  "notifications.deliveredAt": "डिलिव्हर वेळी",
  "notifications.markAllRead": "सर्व वाचले म्हणून चिन्हांकित करा",
  "notifications.wifi": "WiFi",
  "notifications.saveChanges": "बदल जतन करा",
  "notifications.enableEmailNotifications": "ईमेल सूचना सक्षम करा",
  "notifications.fromAddress": "पाठवणाराचा पत्ता",
  "notifications.trackOpens": "ओपन ट्रॅक करा",
  "notifications.fromNumber": "पाठवणाराचा क्रमांक",
  "notifications.pushNotifications": "पुश नोटिफिकेशन",
  "notifications.enablePushNotifications": "पुश नोटिफिकेशन सक्षम करा",
  "notifications.quietHours": "शांत तास",
  "notifications.enableQuietHours": "शांत तास सक्षम करा",
  "notifications.startTime": "सुरुवातीचा वेळ",
  "notifications.endTime": "समाप्तीचा वेळ",
  "notifications.notificationTriggers": "सूचना ट्रिगर",
  "notifications.notificationTemplates": "सूचना टेम्पलेट",
  "notifications.templateName": "टेम्पलेट नाव",
  "notifications.pushNotification": "पुश नोटिफिकेशन",
  "notifications.inapp": "अॅप मध्ये",
  "notifications.subjectLine": "विषय ओळ",
  "notifications.messageBody": "संदेश मजकूर",
  "notifications.availableVariables": "उपलब्ध व्हेरिएबल्स:",
  "notifications.saveTemplate": "टेम्पलेट जतन करा",
  "notifications.emailTemplates": "ईमेल टेम्पलेट",
  "notifications.lastModified": "शेवटचे सुधारित",
  "notifications.templatePreview": "टेम्पलेट प्रीव्ह्यू",
  "notifications.useVariablenameForDynamicContent": "डायनॅमिक कंटेंटसाठी {{variable_name}} वापरा",

  // ===== STAFF =====
  "staff.attendanceTracking": "हजेरी ट्रॅकिंग",
  "staff.presentToday": "आज उपस्थित",
  "staff.absentToday": "आज अनुपस्थित",
  "staff.lateToday": "आज उशीरा",
  "staff.attendanceRate": "हजेरी दर",
  "staff.todaysAttendance": "आजची हजेरी",
  "staff.checkIn": "चेक इन",
  "staff.checkOut": "चेक आउट",
  "staff.notClocked": "क्लॉक नाही",
  "staff.clockIn": "क्लॉक इन",
  "staff.clockOut": "क्लॉक आउट",
  "staff.startDate": "सुरुवात तारीख",
  "staff.endDate": "समाप्ती तारीख",
  "staff.staffMember": "स्टाफ सदस्य",
  "staff.lateMin": "उशीरा (मिनिटे)",
  "staff.earlyLeaveMin": "लवकर जाणे (मिनिटे)",
  "staff.notesOptional": "नोट्स (ऐच्छिक)",
  "staff.clockedClockactionSuccessfullyForSelectedstaffforclockfirstname": "${selectedStaffForClock.firstName} साठी ${clockAction} यशस्वीरित्या क्लॉक केले",
  "staff.exportedAttendanceAsFormattouppercase": "हजेरी ${format.toUpperCase()} म्हणून एक्सपोर्ट केली",
  "staff.internalCommunication": "अंतर्गत संवाद",
  "staff.newChannel": "नवीन चॅनेल",
  "staff.channelName": "चॅनेलचे नाव",
  "staff.activechannelmemberslengthMembers": "{activeChannel.members.length} सदस्य",
  "staff.staffScheduling": "स्टाफ शेड्यूलिंग",
  "staff.scheduledToday": "आज शेड्यूल केले",
  "staff.startTime": "सुरुवातीचा वेळ",
  "staff.endTime": "समाप्तीचा वेळ",
  "staff.todaysAttendance_1": "आजची हजेरी",
  "staff.checkIn_1": "चेक इन",
  "staff.checkOut_1": "चेक आउट",
  "staff.checkedOut": "चेक आउट झाले",
  "staff.checkedIn": "चेक इन झाले",
  "staff.notCheckedIn": "चेक इन झालेले नाही",
  "staff.clockIn_1": "क्लॉक इन",
  "staff.clockOut_1": "क्लॉक आउट",
  "staff.staffMember_1": "स्टाफ सदस्य",
  "staff.shiftslengthShiftsScheduled": "{shifts.length} शिफ्ट शेड्यूल केले",
  "staff.staffSkills": "स्टाफ कौशल्ये",
  "staff.staffMembers": "स्टाफ सदस्य",
  "staff.avgProficiency": "सरासरी प्रवीणता",
  "staff.staffMember_2": "स्टाफ सदस्य",
  "staff.certifiedOnly": "केवळ प्रमाणित",
  "staff.skill": "कौशल्य",
  "staff.skillsOverviewByCategory": "श्रेणीनुसार कौशल्ये आढावा",
  "staff.proficiencyLevel": "प्रवीणता पातळी",
  "staff.certificationDate": "प्रमाणपत्र तारीख",
  "staff.staffMember_3": "स्टाफ सदस्य *",
  "staff.skillName": "कौशल्य नाव *",
  "staff.taskAssignment": "कार्य असाइनमेंट",
  "staff.newTask": "नवीन कार्य",
  "staff.inProgress": "प्रगतीत",
  "staff.myTasks": "माझी कार्ये",
  "staff.assignedTo": "याला असाइन केले",
  "staff.dueDate": "अंतिम तारीख",
  "staff.assignTo": "याला असाइन करा",
  "staff.scheduledDate": "शेड्यूल तारीख",
  "staff.title": "शीर्षक *",

  // ===== INTEGRATIONS =====
  "integrations.paymentGateways": "पेमेंट गेटवे",
  "integrations.feesLimits": "फी आणि मर्यादा",
  "integrations.gatewayName": "गेटवेचे नाव",
  "integrations.apiKeyClientId": "API की / क्लायंट ID",
  "integrations.secretKey": "सिक्रेट की",
  "integrations.webhookSecret": "वेबहूक सिक्रेट",
  "integrations.processingFee": "प्रोसेसिंग फी",
  "integrations.setPrimary": "प्राथमिक सेट करा",
  "integrations.failoverProtection": "फेलओव्हर संरक्षण",
  "integrations.myPaymentGateway": "माझे पेमेंट गेटवे",
  "integrations.usdEurGbp": "USD, EUR, GBP",
  "integrations.gatewaynameConnectionTestInitiatedVerifyInGatewayDashboard": "${gateway.name} कनेक्शन चाचणी सुरू केली. गेटवे डॅशबोर्डमध्ये सत्यापित करा.",
  "integrations.paymentGateways_1": "पेमेंट गेटवे",
  "integrations.gatewayName_1": "गेटवेचे नाव",
  "integrations.apiKey": "API की",
  "integrations.secretKey_1": "सिक्रेट की",
  "integrations.webhookSecret_1": "वेबहूक सिक्रेट",
  "integrations.saveGateway": "गेटवे जतन करा",
  "integrations.successRate": "यश दर",
  "integrations.processingFee_1": "प्रोसेसिंग फी",
  "integrations.testConnection": "कनेक्शन चाचणी",
  "integrations.apiKey_1": "API की:",
  "integrations.myPaymentGateway_1": "माझे पेमेंट गेटवे",
  "integrations.pkxxxxx": "pk_xxxxx",
  "integrations.skxxxxx": "sk_xxxxx",
  "integrations.connectionTestInitiatedForTestgatewaynameVerifyInGatewayDashboard": "${testGateway.name} साठी कनेक्शन चाचणी सुरू केली. गेटवे डॅशबोर्डमध्ये सत्यापित करा.",
  "integrations.paymentGateways_2": "पेमेंट गेटवे",
  "integrations.gatewayName_2": "गेटवेचे नाव",
  "integrations.apiKey_2": "API की",
  "integrations.secretKey_2": "सिक्रेट की",
  "integrations.saveGateway_1": "गेटवे जतन करा",
  "integrations.processingFee_2": "प्रोसेसिंग फी",
  "integrations.myPaymentGateway_2": "माझे पेमेंट गेटवे",
  "integrations.pkxxxxx_1": "pk_xxxxx",
  "integrations.skxxxxx_1": "sk_xxxxx",
  "integrations.systemName": "सिस्टमचे नाव",
  "integrations.apiKey_3": "API की",
  "integrations.syncMenu": "मेन्यू सिंक",
  "integrations.syncOrders": "ऑर्डर सिंक",
  "integrations.syncPayments": "पेमेंट सिंक",
  "integrations.syncGuests": "पाहुणे सिंक",
  "integrations.saveSystem": "सिस्टम जतन करा",
  "integrations.connectedSystems": "कनेक्टेड सिस्टम",
  "integrations.menuItems": "मेन्यू आयटम",
  "integrations.lastSync": "शेवटचा सिंक",
  "integrations.syncNow": "आता सिंक करा",
  "integrations.thirdpartyApis": "थर्ड-पार्टी API",
  "integrations.apiKey_4": "API की",
  "integrations.rateLimit": "रेट मर्यादा",
  "integrations.perMinute": "प्रति मिनिट",
  "integrations.perHour": "प्रति तास",
  "integrations.perDay": "प्रति दिवस",
  "integrations.perMonth": "प्रति महिना",
  "integrations.endpoint_1": "एंडपॉईंट",
  "integrations.apiKeyCopiedToClipboard": "API की क्लिपबोर्डवर कॉपी केली",
  "integrations.wifiGateways": "WiFi गेटवे",
  "integrations.gatewayName_3": "गेटवेचे नाव",
  "integrations.controllerType": "कंट्रोलर प्रकार",
  "integrations.apiKey_5": "API की",
  "integrations.syncIntervalMin": "सिंक अंतराल (मिनिटे)",
  "integrations.autoSync": "ऑटो सिंक",
  "integrations.saveGateway_2": "गेटवे जतन करा",
  "integrations.connectedGateways": "कनेक्टेड गेटवे",
  "integrations.bandwidthUsage": "बँडविड्थ वापर",
  "integrations.accessPoints": "ऍक्सेस पॉईंट",
  "integrations.syncNow_1": "आता सिंक करा",
  "integrations.myWifiController": "माझे WiFi कंट्रोलर",
  "integrations.serverRoomBuildingA": "सर्व्हर रूम, बिल्डिंग A",

  // ===== WEBHOOKS =====
  "webhooks.webhookDelivery": "वेबहूक डिलिव्हरी",
  "webhooks.deliveredAt": "डिलिव्हर वेळी",
  "webhooks.webhookEndpoints": "वेबहूक एंडपॉईंट",
  "webhooks.secretKey": "सिक्रेट की",
  "webhooks.saveEndpoint": "एंडपॉईंट जतन करा",
  "webhooks.avgSuccessRate": "सरासरी यश दर",
  "webhooks.eventTypes": "इव्हेंट प्रकार",
  "webhooks.successRate": "यश दर",
  "webhooks.lastTriggered": "शेवटचे ट्रिगर",
  "webhooks.secret": "सिक्रेट",
  "webhooks.subscribedEvents": "सबस्क्राइब केलेले इव्हेंट",
  "webhooks.myWebhook": "माझे वेबहूक",
  "webhooks.secretCopiedToClipboard": "सिक्रेट क्लिपबोर्डवर कॉपी केली",
  "webhooks.retryQueue": "रिट्री क्यू",
  "webhooks.pendingRetry": "प्रलंबित रिट्री",
  "webhooks.failedMaxAttempts": "अयशस्वी (कमाल प्रयत्न)",
  "webhooks.nextRetry": "पुढील रिट्री",
  "webhooks.lastError": "शेवटची त्रुटी",

  // ===== HELP =====
  "help.watchVideo": "व्हिडिओ पहा",
  "help.relatedArticles": "संबंधित लेख",
  "help.contactSupport": "सहाय्य विभागाशी संपर्क करा",
  "help.knowledgeBase": "ज्ञानावली",
  "help.newArticle": "नवीन लेख",
  "help.newestFirst": "नवीन आधी",
  "help.oldestFirst": "जुने आधी",
  "help.mostViewed": "सर्वाधिक पाहिलेले",
  "help.mostHelpful": "सर्वाधिक उपयुक्त",
  "help.clearFilters": "फिल्टर हटवा",
  "help.gettingStarted": "सुरुवात करा",
  "help.knowledgeBase_1": "ज्ञानावली",
  "help.helpCenter": "मदत केंद्र",
  "help.popularArticles": "लोकप्रिय लेख",
  "help.frequentlyAskedQuestions": "वारंवार विचारले जाणारे प्रश्न",
  "help.stillNeedHelp": "अजून मदत हवी आहे?",
  "help.contactSupport_1": "सहाय्य विभागाशी संपर्क करा",
  "help.submitARequest": "विनंती पाठवा",
  "help.submitRequest": "विनंती सबमिट करा",
  "help.helpCenter_1": "मदत केंद्र",
  "help.newArticle_1": "नवीन लेख",
  "help.contentMarkdown": "कंटेंट (Markdown)",
  "help.restartTutorial": "ट्यूटोरियल पुन्हा सुरू करा",
  "help.startTutorial": "ट्यूटोरियल सुरू करा",
  "help.skipTutorial": "ट्यूटोरियल वगळा",
  "help.tutorialProgress": "ट्यूटोरियल प्रगती",
  "help.yesReset": "होय, रीसेट करा",
  "help.resetAllProgress": "सर्व प्रगती रीसेट करा",
  "help.tutorialsAvailable": "उपलब्ध ट्यूटोरियल",
  "help.inProgress": "प्रगतीत",
  "help.overallProgress": "एकूण प्रगती",
  "help.availableTutorials": "उपलब्ध ट्यूटोरियल",
  "help.startTutorial_1": "ट्यूटोरियल सुरू करा",
  "help.reviewTutorial": "ट्यूटोरियल पुनरावलोकन",

  // ===== PARKING =====
  "parking.noPropertySelected": "कोणतीही मालमत्ता निवडलेली नाही",
  "parking.parkingBilling": "पार्किंग बिलिंग",
  "parking.checkin": "चेक-इन",
  "parking.averageFee": "सरासरी शुल्क",
  "parking.thisMonth": "या महिन्यात",
  "parking.clearFilters": "फिल्टर हटवा",
  "parking.checkInVehicle": "वाहन चेक इन करा",
  "parking.entryTime": "प्रवेश वेळ",
  "parking.exitTime": "बाहेर जाण्याचा वेळ",
  "parking.parkingFee": "पार्किंग शुल्क",
  "parking.hourlyRate": "तासिक दर",
  "parking.dailyMax": "दैनिक कमाल",
  "parking.paymentPending": "पेमेंट प्रलंबित",
  "parking.paymentComplete": "पेमेंट पूर्ण",
  "parking.recordPayment": "पेमेंट नोंदवा",
  "parking.amountDue": "देय रक्कम",
  "parking.paymentMethod": "पेमेंट पद्धत",
  "parking.newVehicleCheckin": "नवीन वाहन चेक-इन",
  "parking.parkingSlotOptional": "पार्किंग स्लॉट (ऐच्छिक)",
  "parking.dailyMaxRate": "दैनिक कमाल दर",
  "parking.recordExit": "बाहेर जाणे नोंदवा",
  "parking.licensePlate": "नंबर प्लेट *",
  "parking.noPropertySelected_1": "कोणतीही मालमत्ता निवडलेली नाही",
  "parking.parkingSlots": "पार्किंग स्लॉट",
  "parking.slotNumber": "स्लॉट क्रमांक",
  "parking.slotType": "स्लॉट प्रकार",
  "parking.vehicleType": "वाहन प्रकार",
  "parking.chargerType": "चार्जर प्रकार",
  "parking.parkedVehicle": "पार्क केलेले वाहन",
  "parking.setAvailable": "उपलब्ध सेट करा",
  "parking.noPropertySelected_2": "कोणतीही मालमत्ता निवडलेली नाही",
  "parking.vehicleTracking": "वाहन ट्रॅकिंग",
  "parking.logEntry": "लॉग प्रविष्ट",
  "parking.currentlyParked": "सध्या पार्क केलेले",
  "parking.exitedToday": "आज बाहेर गेले",
  "parking.entryTime_1": "प्रवेश वेळ",
  "parking.logVehicleEntry": "वाहन प्रवेश नोंदवा",
  "parking.exitTime_1": "बाहेर जाण्याचा वेळ",
  "parking.parkingFee_1": "पार्किंग शुल्क",
  "parking.paymentPending_1": "पेमेंट प्रलंबित",
  "parking.licensePlate_1": "नंबर प्लेट *",

  // ===== IoT =====
  "iot.lastSeen": "शेवटचे पाहिले",
  "iot.unlockDoor": "दरवाजा उघडा",
  "iot.deviceName": "डिव्हाइसचे नाव",
  "iot.deviceType": "डिव्हाइस प्रकार",
  "iot.smartLock": "स्मार्ट लॉक",
  "iot.motorizedBlinds": "मोटराइज्ड ब्लाइंड्स",
  "iot.airConditioner": " वातानुकूलित यंत्र",
  "iot.zwave": "Z-Wave",
  "iot.lockDoor": "दरवाजा बंद करा",
  "iot.turnOff": "बंद करा",
  "iot.turnOn": "चालू करा",
  "iot.energyDashboard": "एनर्जी डॅशबोर्ड",
  "iot.carbonFootprint": "कार्बन फूटप्रिंट",
  "iot.costSavings": "खर्च बचत",
  "iot.carbonReduction": "कार्बन कमी करणे",
  "iot.consumptionTrends": "वापर ट्रेंड",
  "iot.costBreakdown": "खर्च विभाजन",
  "iot.byProperty": "मालमत्तानुसार",
  "iot.dailyEnergyConsumption": "दैनिक ऊर्जा वापर",
  "iot.carbonFootprintTrend": "कार्बन फूटप्रिंट ट्रेंड",
  "iot.dailyCostTrend": "दैनिक खर्च ट्रेंड",
  "iot.electricityKwh": "वीज (kWh)",
  "iot.propertyComparison": "मालमत्ता तुलना",
  "iot.dailyAverages": "दैनिक सरासरी",
  "iot.avgElectricity": "सरासरी वीज",
  "iot.avgGas": "सरासरी गॅस",
  "iot.avgWater": "सरासरी पाणी",
  "iot.avgDailyCost": "सरासरी दैनिक खर्च",
  "iot.gasM": "गॅस (m³)",
  "iot.waterM": "पाणी (m³)",
  "iot.fanSpeed": "पंख्याचा वेग",
  "iot.roomControls": "खोली कंट्रोल",
  "iot.sensorNoControls": "सेन्सर - कंट्रोल नाही",
  "iot.confirmDoorUnlock": "दरवाजा उघडणे पुष्टी करा",
  "iot.unlockDoor_1": "दरवाजा उघडा",
  "iot.quickActions": "द्रुत क्रिया",
  "iot.morningMode": "सकाळ मोड",
  "iot.nightMode": "रात्री मोड",

  // ===== CHAIN =====
  "chain.primaryColor": "प्राथमिक रंग",
  "chain.secondaryColor": "द्वितीयक रंग",
  "chain.grandHotels": "ग्रँड हॉटेल्स",
  "chain.brandName": "ब्रँडचे नाव *",
  "chain.brandCode": "ब्रँड कोड *",
  "chain.chainDashboard": "चेन डॅशबोर्ड",
  "chain.occupancyRate": "ऑक्युपन्सी दर",
  "chain.monthlyBookings": "मासिक बुकिंग",
  "chain.monthlyRevenue": "मासिक रेव्हेन्यू",
  "chain.todayapossArrivals": "आजची आगमने",
  "chain.todayapossDepartures": "आजची निर्गमने",
  "chain.propertyPerformance": "मालमत्ता कामगिरी",
  "chain.brandDistribution": "ब्रँड वितरण",
  "chain.propertiesPerformance": "मालमत्ता कामगिरी",
  "chain.thisWeek": "या आठवड्यात",
  "chain.thisMonth": "या महिन्यात",
  "chain.thisYear": "या वर्षी",
  "chain.avgOccupancy": "सरासरी ऑक्युपन्सी",
  "chain.byProperty": "मालमत्तानुसार",
  "chain.byBrand": "ब्रँडनुसार",
  "chain.bookingSources": "बुकिंग स्रोत",
  "chain.guestDemographics": "पाहुणा लोकसंख्या",
  "chain.propertyPerformanceComparison": "मालमत्ता कामगिरी तुलना",
  "chain.revenueTrend": "रेव्हेन्यू ट्रेंड",
  "chain.propertyComparison": "मालमत्ता तुलना",

  // ===== ADS =====
  "ads.adCampaigns": "अॅड कॅम्पेइन",
  "ads.newCampaign": "नवीन कॅम्पेइन",
  "ads.budgetUsed": "वापरलेले बजेट",
  "ads.basicInformation": "मूलभूत माहिती",
  "ads.campaignName": "कॅम्पेइनचे नाव",
  "ads.campaignType": "कॅम्पेइन प्रकार",
  "ads.budgetBidding": "बजेट आणि बिडिंग",
  "ads.budgetType": "बजेट प्रकार",
  "ads.bidStrategy": "बिड रणनीती",
  "ads.enhancedCpc": "वर्धित CPC",
  "ads.bidAmountOptional": "बिड रक्कम (ऐच्छिक)",
  "ads.targetCpaOptional": "लक्षित CPA (ऐच्छिक)",
  "ads.targetRoasOptional": "लक्षित ROAS (ऐच्छिक)",
  "ads.startDate": "सुरुवात तारीख",
  "ads.endDate": "समाप्ती तारीख",
  "ads.optionalDescription": "ऐच्छिक वर्णन",
  "ads.manualBidAmount": "मॅन्युअल बिड रक्कम",
  "ads.costPerAcquisition": "प्रति प्राप्ती खर्च",
  "ads.returnOnAdSpend": "जाहिरात खर्चावर परतावा",
  "ads.campaignNameIsRequired": "कॅम्पेइनचे नाव आवश्यक आहे",
  "ads.campaignDeleted": "कॅम्पेइन हटवले",
  "ads.disconnect": "डिस्कनेक्ट",
  "ads.connect": "कनेक्ट",
  "ads.avgCtr": "सरासरी CTR",
  "ads.clickthroughRate": "क्लिक-थ्रू दर",
  "ads.performanceTrend": "कामगिरी ट्रेंड",
  "ads.noPerformanceDataAvailable": "कामगिरी डेटा उपलब्ध नाही",
  "ads.bidStrategy_1": "बिड रणनीती",
  "ads.howBidsAreCalculated": "बिड कसे गणले जातात",
  "ads.autoBidding": "ऑटो बिडिंग",
  "ads.automaticallyAdjustBids": "स्वयं बिड समायोजित करा",
  "ads.baseBidModifier": "बेस बिड मॉडिफायर",
  "ads.appliedToAllBids": "सर्व बिडवर लागू",
  "ads.lastPriceFeed": "शेवटचा किंमत फीड",
  "ads.priceUpdateSync": "किंमत अपडेट सिंक",
  "ads.lastBookingFeed": "शेवटचा बुकिंग फीड",
  "ads.bookingDataSync": "बुकिंग डेटा सिंक",
  "ads.feedFormat": "फीड फॉरमॅट",
  "ads.dataFormatType": "डेटा फॉरमॅट प्रकार",
  "ads.accountId": "खाते ID",
  "ads.subAccountId": "उप खाते ID",
  "ads.hotelId": "हॉटेल ID",
  "ads.partnerId": "पार्टनर ID",
  "ads.connectionMode": "कनेक्शन मोड",
  "ads.performanceTracking": "कामगिरी ट्रॅकिंग",
  "ads.convRate": "रूपांतर दर",
  "ads.performanceTrend_1": "कामगिरी ट्रेंड",
  "ads.conversionTrend": "रूपांतर ट्रेंड",
  "ads.dailyBreakdown": "दैनिक विभाजन",
  "ads.netProfit": "निव्वळ नफा",
  "ads.channelComparison": "चॅनेल तुलना",
  "ads.trendInsights": "ट्रेंड अंतर्दृष्टी",
  "ads.profitTrend": "नफा ट्रेंड",

  // ===== PORTAL =====
  "portal.inProgress": "प्रगतीत",
  "portal.uploadFirstDocument": "पहिला दस्तऐवज अपलोड करा",
  "portal.uploadAnotherDocument": "आणखी दस्तऐवज अपलोड करा",
  "portal.uploadDocument": "दस्तऐवज अपलोड करा",
  "portal.egPassportJohnDoe": "उदा., पासपोर्ट - John Doe",
  "portal.documentType": "दस्तऐवज प्रकार *",
  "portal.documentName": "दस्तऐवजाचे नाव *",
  "portal.documentFile": "दस्तऐवज फाईल *",
  "portal.termsSignature": "अटी आणि स्वाक्षरी",
  "portal.termsAccepted": "अटी स्वीकारल्या",
  "portal.yourSignature": "तुमची स्वाक्षरी",
  "portal.signAcceptTerms": "स्वाक्षरी करा आणि अटी स्वीकारा",
  "portal.alternatePhone": "पर्यायी फोन",
  "portal.streetAddress": "रस्ता पत्ता",
  "portal.postalCode": "पिन कोड",
  "portal.newYork": "नवी दिल्ली",
  "portal.firstName": "पहिले नाव *",
  "portal.lastName": "आडनाव *",
  "portal.phoneNumber": "फोन क्रमांक *",
  "portal.paymentSummary": "पेमेंट सारांश",
  "portal.balanceDue": "बाकी रक्कम",
  "portal.taxesFees": "कर आणि फी",
  "portal.amountPaid": "जमा रक्कम",
  "portal.payNow": "आता द्या",
  "portal.paymentComplete": "पेमेंट पूर्ण",
  "portal.floorPreference": "मजला प्राधान्य",
  "portal.bedType": "बेड प्रकार",
  "portal.pillowType": "ओलख प्रकार",
  "portal.additionalRoomPreferences": "अतिरिक्त खोली प्राधान्ये",
  "portal.dietaryRequirements": "आहार आवश्यकता",
  "portal.roomAmenities": "खोली सुविधा",
  "portal.preferredLanguage": "पसंतीची भाषा",
  "portal.notificationPreferences": "सूचना प्राधान्ये",

  // ===== GDPR =====
  "gdpr.privacyNotice": "गोपनीयता सूचना",
  "gdpr.acceptAll": "सर्व स्वीकारा",
  "gdpr.rejectOptional": "ऐच्छिक नाकारा",
  "gdpr.privacyPolicy": "गोपनीयता धोरण",
  "gdpr.declineOptional": "ऐच्छिक नाकारा",
  "gdpr.requestTypes": "विनंती प्रकार",
  "gdpr.exportData": "डेटा एक्सपोर्ट करा",
  "gdpr.exportGuestData": "पाहुणा डेटा एक्सपोर्ट करायचा?",
  "gdpr.confirmExport": "एक्सपोर्ट पुष्टी करा",
  "gdpr.anonymizeData": "डेटा अनामिक करा",
  "gdpr.anonymizeGuestData": "पाहुणा डेटा अनामिक करायचा?",
  "gdpr.confirmAnonymization": "अनामिकीकरण पुष्टी करा",
  "gdpr.softDelete": "सॉफ्ट डिलीट",
  "gdpr.softDeleteGuestData": "पाहुणा डेटा सॉफ्ट डिलीट करायचा?",
  "gdpr.confirmSoftDelete": "सॉफ्ट डिलीट पुष्टी करा",
  "gdpr.hardDelete": "हार्ड डिलीट",
  "gdpr.permanentlyDeleteGuestData": "पाहुणा डेटा स्थायी हटवायचा?",
  "gdpr.confirmPermanentDelete": "स्थायी डिलीट पुष्टी करा",
  "gdpr.recordConsent": "संमती नोंदवा",

  // ===== AUDIT =====
  "audit.securityEvents": "सुरक्षा इव्हेंट",
  "audit.failedLogins": "अयशस्वी लॉग इन",
  "audit.activityLog": "क्रियाकलाप लॉग",
  "audit.entityType": "एंटिटी प्रकार",
  "audit.userAgent": "यूजर एजंट",
  "audit.oldValue": "जुने मूल्य",
  "audit.newValue": "नवीन मूल्य",

  // ===== COMMUNICATION =====
  "communication.changeStatus": "स्थिती बदला",
  "communication.assignTo": "याला असाइन करा",
  "communication.quickReplies": "द्रुत प्रतिसाद:",
  "communication.messageTemplates": "संदेश टेम्पलेट",
  "communication.insertLink": "लिंक समाविष्ट करा",
  "communication.bulletList": "बुलेट सूची",
  "communication.numberedList": "क्रमांकित सूची",
  "communication.attachFile": "फाईल संलग्न करा",

  // ===== PROFILE =====
  "profile.personalInformation": "वैयक्तिक माहिती",
  "profile.firstName": "पहिले नाव",
  "profile.lastName": "आडनाव",
  "profile.jobTitle": "पदाचे नाव",
  "profile.newPassword": "नवीन पासवर्ड",
  "profile.confirmPassword": "पासवर्ड पुष्टी करा",
  "profile.twofactorAuthentication": "दोन-स्तरीय प्रमाणीकरण",
  "profile.authenticatorApp": "ऑथेंटिकेटर ॲप",
  "profile.emailNotifications": "ईमेल सूचना",
  "profile.pushNotifications": "पुश नोटिफिकेशन",
  "profile.marketingEmails": "मार्केटिंग ईमेल",
  "profile.darkMode": "डार्क मोड",
  "profile.compactMode": "कॉम्पॅक्ट मोड",
  "profile.dateFormat": "तारीख फॉरमॅट",

  // ===== FRONTDESK =====
  "frontdesk.todaysArrivalsCount": "आजची आगमने",
  "frontdesk.checkedIn": "चेक-इन झाले",
  "frontdesk.checkInBtn": "चेक-इन",
  "frontdesk.roomType": "खोली प्रकार",
  "frontdesk.assignedRoom": "असाइन केलेली खोली",
  "frontdesk.roomsAvailable": "{count} खोली(या) उपलब्ध",
  "frontdesk.driverLicense": "ड्रायव्हिंग लायसन्स",
  "frontdesk.wifiCredentials": "WiFi क्रेडेन्शियल",
  "frontdesk.validUntil": "यापर्यंत वैध",
  "frontdesk.specialRequests": "विशेष विनंत्या",
  "frontdesk.specialRequestsLabel": "विशेष विनंत्या",
  "frontdesk.copiedToClipboard": "{label} क्लिपबोर्डवर कॉपी केले",
  "frontdesk.couldNotCopy": "{label} कॉपी करता आले नाही",
  "frontdesk.validationError": "वैधता त्रुटी",
  "frontdesk.checkInSuccessMsg": "पाहुणा खोली {room} मध्ये चेक-इन झाला. WiFi क्रेडेन्शियल तयार.",
  "frontdesk.seaView": "समुद्र दृश्य",
  "frontdesk.mountainView": "डोंगर दृश्य",
  "frontdesk.markClean": "स्वच्छ चिन्हांकित करा",
  "frontdesk.markAvailable": "उपलब्ध चिन्हांकित करा",
  "frontdesk.checkOut": "चेक-आउट",
  "frontdesk.quickActions": "द्रुत क्रिया",
  "frontdesk.todaysDeparturesCount": "आजची निर्गमने",
  "frontdesk.checkingOut": "चेक-आउट होत आहे",
  "frontdesk.outstandingBalance": "बाकी रक्कम",
  "frontdesk.outstandingBalanceAmount": "बाकी रक्कम: {amount}",
  "frontdesk.checkOutBtn": "चेक-आउट",
  "frontdesk.stayDuration": "राहण्याचा कालावधी",
  "frontdesk.takePayment": "पेमेंट घ्या",
  "frontdesk.paymentRecorded": "पेमेंट नोंदवले",
  "frontdesk.paymentOf": "{amount} पेमेंट प्रक्रिया केली",
  "frontdesk.outstandingBalanceLabel": "बाकी रक्कम",
  "frontdesk.paymentMethod": "पेमेंट पद्धत",
  "frontdesk.referenceOptional": "संदर्भ (ऐच्छिक)",
  "frontdesk.recordPayment": "पेमेंट नोंदवा",
  "frontdesk.guestCheckedOut": "पाहुणा खोली {room} मधून चेक-आउट झाला",
  "frontdesk.creditDebitCard": "क्रेडिट/डेबिट कार्ड",
  "frontdesk.bankTransfer": "बँक हस्तांतरण",
  "frontdesk.digitalWallet": "डिजिटल वॉलेट",
  "frontdesk.nightsLabel": "{count} रात्री",
  "frontdesk.propertyAndRoom": "मालमत्ता आणि खोली",
  "frontdesk.assignRoom": "खोली असाइन करा",
  "frontdesk.guestInformation": "पाहुणा माहिती",
  "frontdesk.existingGuest": "अस्तित्वात असलेला पाहुणा",
  "frontdesk.stateProvince": "राज्य / प्रदेश / प्रदेश",
  "frontdesk.guestName": "पाहुण्याचे नाव",
  "frontdesk.bookingSummary": "बुकिंग सारांश",
  "frontdesk.taxBreakdown": "कर विभाजन",
  "frontdesk.serviceCharge": "सेवा शुल्क",
  "frontdesk.grandTotal": "एकूण रक्कम",
  "frontdesk.guestCreationFailed": "पाहुणा तयार करणे अयशस्वी",
  "frontdesk.bookingCreated": "बुकिंग तयार झाली",
  "frontdesk.bookingFailed": "बुकिंग अयशस्वी",
  "frontdesk.roomGridTitle": "रूम ग्रिड",
  "frontdesk.seaViewLegend": "समुद्र दृश्य",
  "frontdesk.liveUpdate": "लाइव्ह अपडेट",
  "frontdesk.roomFeatures": "खोली वैशिष्ट्ये",
  "frontdesk.roomBookingInfo": "खोली बुकिंग माहिती",
  "frontdesk.connectionError": "कनेक्शन त्रुटी",
  "frontdesk.roomStatusUpdated": "खोली स्थिती अद्ययावत केली",
  "frontdesk.roomStatusUpdatedMsg": "खोली {id} आता {status} आहे",
  "frontdesk.roomAssignmentTitle": "खोली असाइनमेंट",
  "frontdesk.unassignedBookings": "अनॅसाइन्ड बुकिंग",
  "frontdesk.availableRooms": "उपलब्ध खोल्या",
  "frontdesk.arrivingToday": "आज येणारे",
  "frontdesk.compatibleRooms": "{count} सुसंगत खोली(या)",
  "frontdesk.assignRoomTitle": "खोली असाइन करा",
  "frontdesk.bookingInfo": "बुकिंग माहिती",
  "frontdesk.roomPreview": "खोली प्रीव्ह्यू",
  "frontdesk.roomAssignmentSuccess": "खोली असाइन केली",
  "frontdesk.roomAssignmentSuccessMsg": "खोली {room} बुकिंग {code} ला असाइन केली",
  "frontdesk.allBookingsTab": "अनॅसाइन्ड बुकिंग",
  "frontdesk.availableRoomsTab": "उपलब्ध खोल्या",
  "frontdesk.roomMoveTitle": "खोली बदली / हस्तांतरण",
  "frontdesk.moveToRoom": "या खोलीत जा",
  "frontdesk.roomComparison": "खोली तुलना",
  "frontdesk.sameRate": "समान दर",
  "frontdesk.notesOptional": "नोट्स (ऐच्छिक)",
  "frontdesk.moveToRoomBtn": "खोली {room} मध्ये जा",
  "frontdesk.moveHistoryTable.rateChange": "दर बदल",
  "frontdesk.confirmRoomMove": "खोली बदली पुष्टी करा",
  "frontdesk.rateChange": "दर बदल",
  "frontdesk.roomMovedMsg": "पाहुणा खोली {room} ({roomType}) मध्ये हलले",
  "frontdesk.moveFailed": "हस्तांतरण अयशस्वी",
  "frontdesk.confirmMove": "हस्तांतरण पुष्टी करा",
  "frontdesk.guestRequest": "पाहुणा विनंती",
  "frontdesk.maintenanceIssue": "देखभाल समस्या",
  "frontdesk.complimentaryUpgrade": "विनामूल्य अपग्रेड",
  "frontdesk.availabilityIssue": "उपलब्धता समस्या",
  "frontdesk.targetRoomStatus": "लक्षित खोली स्थिती: {status}. हाउसकीपिंगची आवश्यकता असू शकते.",
  "frontdesk.registrationCardTitle": "नोंदणी कार्ड",
  "frontdesk.fullName": "पूर्ण नाव",
  "frontdesk.roomNumber": "खोली क्रमांक",
  "frontdesk.roomTypeLabel": "खोली प्रकार",
  "frontdesk.accompanyingGuests": "सोबतीचे पाहुणे",
  "frontdesk.vehicleInformation": "वाहन माहिती",
  "frontdesk.existingCard": "अस्तित्वात असलेले कार्ड",
  "frontdesk.cardNo": "कार्ड क्रमांक",
  "frontdesk.termsAndConditions": "अटी आणि शर्ती",
  "frontdesk.regeneratePrint": "पुन्हा तयार करा आणि छापा",
  "frontdesk.generatePrint": "तयार करा आणि छापा",
  "frontdesk.leisure": "विश्रांती / सुट्टी",
  "frontdesk.business": "व्यवसाय प्रवास",
  "frontdesk.conference": "परिषद / बैठक",
  "frontdesk.medical": "वैद्यकीय भेट",
  "frontdesk.transit": "ट्रान्झिट / थांबा",
  "frontdesk.termsRequired": "अटी आवश्यक",
  "frontdesk.registrationCardGenerated": "नोंदणी कार्ड तयार झाले",
  "frontdesk.expressCheckIn": "एक्सप्रेस चेक-इन",
  "frontdesk.findYourBooking": "तुमची बुकिंग शोधा",
  "frontdesk.findBooking": "बुकिंग शोधा",
  "frontdesk.confirmCheckIn": "पुष्टी करा आणि चेक-इन करा",
  "frontdesk.detailsCorrect": "तपशील बरोबर आहेत",
  "frontdesk.checkingIn": "चेक-इन होत आहे...",
  "frontdesk.checkInNow": "आता चेक-इन करा",
  "frontdesk.yourRoom": "तुमची खोली",
  "frontdesk.wifiCredentialsTitle": "WiFi क्रेडेन्शियल",
  "frontdesk.validUntilDate": "{date} पर्यंत वैध",
  "frontdesk.tryAgain": "पुन्हा प्रयत्न करा",
  "frontdesk.startOver": "पुन्हा सुरू करा",
  "frontdesk.paymentComplete": "पेमेंट पूर्ण",
  "frontdesk.paymentIssue": "पेमेंत समस्या",
  "frontdesk.cardPayment": "कार्ड पेमेंट",
  "frontdesk.cashPayment": "रोख पेमेंट",
  "frontdesk.cardNumber": "कार्ड क्रमांक",
  "frontdesk.expiryDate": "वैधता तारीख",
  "frontdesk.pay": "{amount} द्या",
  "frontdesk.upiIdPlaceholder": "yourname@upi",
  "frontdesk.amountDue": "देय रक्कम",
  "frontdesk.confirmCashPayment": "रोख पेमेंट पुष्टी करा",
  "frontdesk.processingPayment": "पेमेंट प्रक्रिया होत आहे...",
  "frontdesk.paymentSuccessful": "पेमेंट यशस्वी!",
  "frontdesk.receiptNo": "रिसीट क्रमांक",
  "frontdesk.remainingBalance": "शिल्लक रक्कम",
  "frontdesk.paymentFailed": "पेमेंट अयशस्वी",
  "frontdesk.hotelName": "हॉटेलचे नाव",
  "frontdesk.welcomeMessage": "स्वागत संदेश",
  "frontdesk.primaryColor": "प्राथमिक रंग",
  "frontdesk.backgroundStyle": "बॅकग्राउंड स्टाइल",
  "frontdesk.idleTimeout": "निष्क्रिय वेळ मर्यादा",
  "frontdesk.enableCheckIn": "चेक-इन सक्षम करा",
  "frontdesk.enableCheckOut": "चेक-आउट सक्षम करा",
  "frontdesk.enablePayment": "पेमेंट सक्षम करा",
  "frontdesk.kioskAddress": "कियोस्क पत्ता",
  "frontdesk.saveChanges": "बदल जतन करा",

  // ===== PMS =====
  "pms.propertyName": "मालमत्तेचे नाव",
  "pms.propertyNamePlaceholder": "ग्रँड हॉटेल",
  "pms.phonePlaceholder": "+91 98765 43210",
  "pms.taxComponent": "कर घटक",
  "pms.generalInfo": "सामान्य माहिती",
  "pms.contactInfo": "संपर्क माहिती",
  "pms.validationError": "वैधता त्रुटी",
  "pms.exportComplete": "एक्सपोर्ट पूर्ण",
  "pms.importFailed": "इम्पोर्ट अयशस्वी",
  "pms.roomNumber": "खोली क्रमांक",
  "pms.roomName": "खोलीचे नाव",
  "pms.roomNamePlaceholder": "हनीमून सुइट",
  "pms.roomTypesTitle": "खोली प्रकार",
  "pms.typeName": "प्रकाराचे नाव",
  "pms.typeNamePlaceholder": "डिलक्स खोली",
  "pms.basePrice": "बेस किंमत",
  "pms.maxOccupancy": "कमाल क्षमता",
  "pms.inventoryTitle": "इन्व्हेंटरी कॅलेंडर",
  "pms.availabilityTitle": "उपलब्धता नियंत्रण",
  "pms.lockingTitle": "इन्व्हेंटरी लॉकिंग",
  "pms.lockType": "लॉक प्रकार",
  "pms.unlockInventory": "इन्व्हेंटरी अनलॉक करा",
  "pms.unlock": "अनलॉक करा",
  "pms.enableOverbooking": "ओव्हरबुकिंग सक्षम करा",
  "pms.pricingTitle": "किंमत व्यवस्थापक",
  "pms.ratePlanName": "रेट प्लॅन नाव",
  "pms.maxPrice": "कमाल किंमत",
  "pms.priceOverride": "किंमत ओव्हरराइड",
  "pms.roomType": "खोली प्रकार",
  "pms.revenueTitle": "रेव्हेन्यू डॅशबोर्ड",
  "pms.bulkPriceTitle": "बल्क किंमत अपडेट",
  "pms.minPrice": "किमान किंमत",
  "pms.bulkUpdateComplete": "बल्क अपडेट पूर्ण",
  "pms.floorPlansTitle": "फ्लोर प्लॅन",
  "pms.floorPlanName": "फ्लोर प्लॅन नाव",
  "pms.resetView": "व्ह्यू रीसेट करा",
  "pms.toggleGrid": "ग्रिड टॉगल करा",
  "pms.zoomIn": "झूम इन",
  "pms.zoomOut": "झूम आउट",
  "pms.alignLeft": "डावीकडे संरेषित करा",
  "pms.alignCenterH": "आडवे मध्यभागी संरेषित करा",
  "pms.alignTop": "वर संरेषित करा",
  "pms.confirmRemoval": "हटवणे पुष्टी करा",
  "pms.floorPlanViewer": "फ्लोर प्लॅन व्यूअर",
  "pms.pricingRulesTitle": "रेट प्लॅन आणि किंमत नियम",
  "pms.roomRateCalendarTitle": "रूम रेट कॅलेंडर",
  "pms.rateUpdated": "दर अद्ययावत केला",
  "pms.costEstimate": "खर्च अंदाज",
  "pms.galleryTitle": "खोली प्रतिमा गॅलरी",
  "pms.fileTooLarge": "फाईल खूप मोठी आहे",

  // ===== BOOKINGS =====
  "bookings.changeStatus": "स्थिती बदला",
  "bookings.bookingDetailsCopied": "बुकिंग तपशील कॉपी केले",
  "bookings.printView": "प्रिंट व्ह्यू",
  "bookings.calendarTitle": "बुकिंग कॅलेंडर",
  "bookings.wifiAccessCreated": "WiFi ऍक्सेस तयार केले",
  "bookings.wifiProvisioningSkipped": "WiFi प्रोव्हिजनिंग वगळले",
  "bookings.wifiUserExists": "WiFi वापरकर्ता अस्तित्वात आहे",
  "bookings.calendarListTitle": "बुकिंग कॅलेंडर यादी",
  "bookings.conflictsTitle": "बुकिंग विसंवाद",
  "bookings.groupBookingsTitle": "ग्रुप बुकिंग",
  "bookings.groupName": "ग्रुपचे नाव",
  "bookings.contactPerson": "संपर्क व्यक्ती",
  "bookings.contactEmail": "संपर्क ईमेल",
  "bookings.contactPhone": "संपर्क फोन",
  "bookings.actionType": "क्रिया प्रकार",
  "bookings.noShowTitle": "नो-शो ऑटोमेशन",

  // ===== GUESTS =====
  "guests.guestProfiles": "पाहुणा प्रोफाइल",
  "guests.firstName": "पहिले नाव",
  "guests.lastName": "आडनाव",
  "guests.phonePlaceholder": "+1 555 123 4567",
  "guests.cityPlaceholder": "मुंबई",
  "guests.countryPlaceholder": "भारत",
  "guests.loyaltyTier": "ऑयल्टी टायर",
  "guests.validationError": "वैधता त्रुटी",
  "guests.documentName": "दस्तऐवजाचे नाव",
  "guests.fileTooLarge": "फाईल खूप मोठी आहे",
  "guests.guestPreferencesTitle": "पाहुणा प्राधान्ये",
  "guests.loyaltyTitle": "ऑयल्टी प्रोग्राम",
  "guests.adjustPoints": "गुण समायोजित करा",
  "guests.loyaltyPointsTitle": "ऑयल्टी गुण",
  "guests.redemptionOptions": "रिडेम्प्शन पर्याय",
  "guests.insufficientPoints": "अपुरे गुण",
  "guests.exportComplete": "एक्सपोर्ट पूर्ण",
  "guests.guestProfileTitle": "पाहुणा प्रोफाइल",
  "guests.guestJourneyTitle": "पाहुणा प्रवास",
  "guests.eventType": "इव्हेंट प्रकार"
};

const locale = JSON.parse(fs.readFileSync('src/messages/mr.json', 'utf-8'));
let applied = 0;
for (const [k, v] of Object.entries(translations)) {
  if (v && typeof v === 'string') {
    deepSet(locale, k, v);
    applied++;
  }
}
fs.writeFileSync('src/messages/mr.json', JSON.stringify(locale, null, 2) + '\n', 'utf-8');
console.log(`Applied ${applied} Marathi translations`);
