import fs from 'fs';
import path from 'path';

function deepSet(obj, path, val) {
  const parts = path.split('.');
  let cur = obj;
  for (let i = 0; i < parts.length - 1; i++) {
    if (!(parts[i] in cur) || typeof cur[parts[i]] !== 'object') cur[parts[i]] = {};
    cur = cur[parts[i]];
  }
  cur[parts[parts.length - 1]] = val;
}

const translations = {
  "common.goBack": "পিছনে যান",
  "common.upgradePlan": "প্ল্যান আপগ্রেড করুন",
  "common.accessDenied": "প্রবেশাধিকার অস্বীকৃত",
  "common.tryAgain": "পুনরায় চেষ্টা করুন",
  "common.unauthorizedAccess": "অননুমোদিত প্রবেশ",
  "common.exportData": "ডেটা এক্সপোর্ট করুন",
  "layout.globalSearch": "গ্লোবাল সার্চ",
  "layout.commandPalette": "কমান্ড প্যালেট",
  "dashboard.activeRate": "সক্রিয় হার",
  "dashboard.avgRate": "গড় হার",
  "dashboard.baseRate": "ভিত্তি হার",
  "dashboard.basedOnReviews": "{count, plural, one {#টি পর্যালোচনার ভিত্তিতে} other {#টি পর্যালোচনার ভিত্তিতে}}",
  "dashboard.categoryScores": "বিভাগ স্কোর",
  "dashboard.channelPerformance": "চ্যানেল পারফরম্যান্স",
  "dashboard.daysAgoShort": "{count}দিন",
  "dashboard.departuresToday": "আজকের প্রস্থান",
  "dashboard.expectedCount": "প্রত্যাশিত {count}",
  "dashboard.guestCommunications": "অতিথি যোগাযোগ",
  "dashboard.guestFeedback": "অতিথি মতামত",
  "dashboard.guestLoyalty": "অতিথি অনুগত্ব",
  "dashboard.guestSatisfaction": "অতিথি সন্তুষ্টি",
  "dashboard.guestSegments": "অতিথি সেগমেন্ট",
  "dashboard.hoursAgoShort": "{count}ঘ",
  "dashboard.maintenanceTracker": "রক্ষণাবেক্ষণ ট্র্যাকার",
  "dashboard.minutesAgoShort": "{count}মি",
  "dashboard.moreSegments": "+{count} আরও",
  "dashboard.onTime": "সময়মত",
  "dashboard.overallSatisfaction": "সামগ্রিক সন্তুষ্টি",
  "dashboard.pointsIssued": "প্রদত্ত পয়েন্ট",
  "dashboard.ratePlanComparison": "রেট প্ল্যান তুলনা",
  "dashboard.recentReviews": "সাম্প্রতিক পর্যালোচনা",
  "dashboard.revenueBreakdown": "আয় বিবরণ",
  "dashboard.roomRevenue": "কক্ষ আয়",
  "dashboard.roomStatusOverview": "কক্ষ অবস্থা সারসংক্ষেপ",
  "dashboard.scheduledCount": "নির্ধারিত {count}",
  "dashboard.sentimentBreakdown": "সেন্টিমেন্ট বিবরণ",
  "dashboard.shiftDone": "শিফট সম্পন্ন",
  "dashboard.staffOnDuty": "দায়িত্বরত কর্মী",
  "dashboard.staffPerformance": "কর্মী পারফরম্যান্স",
  "dashboard.tasksDone": "সম্পন্ন কাজ",
  "dashboard.thisShift": "এই শিফট",
  "dashboard.tierDistribution": "টায়ার বণ্টন",
  "dashboard.topMembers": "শীর্ষ সদস্য",
  "dashboard.topPerformers": "শীর্ষ পারফরমার",
  "dashboard.totalChannels": "মোট চ্যানেল",
  "dashboard.viewAll": "সব দেখুন",
  "dashboard.viewAllActivity": "সকল কার্যকলাপ দেখুন",
  "dashboard.viewAllPlans": "সকল প্ল্যান দেখুন",
  "dashboard.viewAllReviews": "সকল পর্যালোচনা দেখুন",
  "dashboard.viewRoomGrid": "কক্ষ গ্রিড দেখুন",
  "settings.featureFlags": "ফিচার ফ্ল্যাগ",
  "settings.saveChanges": "পরিবর্তনগুলো সংরক্ষণ করুন",
  "settings.baseModules": "বেস মডিউল",
  "settings.addonModules": "অ্যাড-অন মডিউল",
  "settings.alwaysOn": "সর্বদা সক্রিয়",
  "settings.enableAll": "সব সক্রিয় করুন",
  "settings.disableAll": "সব নিষ্ক্রিয় করুন",
  "settings.controlsMenuItems": "মেনু আইটেম নিয়ন্ত্রণ করে:",
  "settings.saveChanges_1": "পরিবর্তনগুলো সংরক্ষণ করুন",
  "settings.propertyInformation": "সম্পত্তির তথ্য",
  "settings.propertyName": "সম্পত্তির নাম",
  "settings.legalName": "আইনি নাম",
  "settings.unitedStates": "মার্কিন যুক্তরাষ্ট্র",
  "settings.unitedKingdom": "যুক্তরাজ্য",
  "settings.postalCode": "পোস্টাল কোড",
  "settings.defaultCurrency": "ডিফল্ট মুদ্রা",
  "settings.emailNotifications": "ইমেইল বিজ্ঞপ্তি",
  "settings.pushNotifications": "পুশ বিজ্ঞপ্তি",
  "settings.weeklyReport": "সাপ্তাহিক রিপোর্ট",
  "settings.dailyDigest": "দৈনিক সারসংক্ষেপ",
  "settings.currencySettingImpact": "মুদ্রা সেটিং প্রভাব",
  "settings.timezoneFormatImpact": "টাইমজোন ও ফরম্যাট প্রভাব",
  "settings.saveChanges_2": "পরিবর্তনগুলো সংরক্ষণ করুন",
  "settings.availableLanguages": "উপলব্ধ ভাষা",
  "settings.unitedStates_1": "মার্কিন যুক্তরাষ্ট্র",
  "settings.unitedKingdom_1": "যুক্তরাজ্য",
  "settings.englishIndia": "ইংরেজি (ভারত)",
  "settings.hindiIndia": "হিন্দি (ভারত)",
  "settings.autoLanguageDetection": "স্বয়ংক্রিয় ভাষা সনাক্তকরণ",
  "settings.rememberPreference": "পছন্দ মনে রাখুন",
  "settings.saveChanges_3": "পরিবর্তনগুলো সংরক্ষণ করুন",
  "settings.multifactorAuthentication": "মাল্টি-ফ্যাক্টর প্রমাণীকরণ",
  "settings.authenticatorApp": "অথেনটিকেটর অ্যাপ",
  "settings.sessionTimeoutMinutes": "সেশন টাইমআউট (মিনিট)",
  "settings.maxConcurrentSessions": "সর্বোচ্চ সমবর্তী সেশন",
  "settings.minimumLength": "সর্বনিম্ন দৈর্ঘ্য",
  "settings.passwordExpiryDays": "পাসওয়ার্ড মেয়াদ (দিন)",
  "settings.specialChars": "বিশেষ অক্ষর",
  "settings.dataProtection": "ডেটা সুরক্ষা",
  "settings.dataRetentionPeriodDays": "ডেটা সংরক্ষণ সময়কাল (দিন)",
  "settings.rateLimiting": "হার সীমাবদ্ধতা",
  "settings.apiKeyRotation": "API কী রোটেশন",
  "settings.dataProcessingAgreement": "ডেটা প্রসেসিং চুক্তি",
  "settings.recentSecurityActivity": "সাম্প্রতিক নিরাপত্তা কার্যকলাপ",
  "settings.systemIntegrations": "সিস্টেম ইন্টিগ্রেশন",
  "settings.clearReset": "মুছুন / রিসেট",
  "settings.fieldlabelIsRequired": "${field.label} আবশ্যক",
  "settings.saveChanges_4": "পরিবর্তনগুলো সংরক্ষণ করুন",
  "settings.exchangeRates": "বিনিময় হার",
  "settings.defaultCurrency_1": "ডিফল্ট মুদ্রা",
  "settings.symbolPosition": "প্রতীক অবস্থান",
  "settings.decimalPlaces": "দশমিক স্থান",
  "settings.thousandSeparator": "হাজার বিভাজক",
  "settings.space": "স্পেস ( )",
  "settings.decimalSeparator": "দশমিক বিভাজক",
  "settings.currencyConverter": "মুদ্রা রূপান্তরকারী",
  "settings.currencyName": "মুদ্রার নাম",
  "settings.taxName": "করের নাম",
  "settings.appliesTo": "প্রযোজ্য",
  "settings.taxGroups": "কর গ্রুপ",
  "settings.taxCalculationBasis": "কর হিসাব ভিত্তি",
  "settings.lineItemLevel": "লাইন আইটেম স্তর",
  "settings.invoiceTotalLevel": "চালান মোট স্তর",
  "settings.taxinclusivePricing": "কর-সমেত মূল্য",
  "settings.taxRoundingMethod": "কর পূর্ণসংখ্যায়ন পদ্ধতি",
  "settings.alwaysRoundUp": "সর্বদা উপরে পূর্ণসংখ্যায়ন",
  "settings.alwaysRoundDown": "সর্বদা নিচে পূর্ণসংখ্যায়ন",
  "settings.roundingPrecision": "পূর্ণসংখ্যায়ন নির্ভুলতা",
  "settings.taxApplicationOrder": "কর প্রয়োগ ক্রম",
  "settings.compoundTax": "যৌগিক কর",
  "settings.rateVsSettingscurrencydefault": "হার ({settings.currency.default} এর বিপরীতে)",
  "settings.taxName_1": "করের নাম *",
  "settings.rate_1": "হার *",
  "auth.checkYourEmail": "আপনার ইমেইল চেক করুন",
  "auth.emailAddress": "ইমেইল ঠিকানা",
  "auth.sendingResetLink": "রিসেট লিংক পাঠানো হচ্ছে...",
  "auth.invalidLink": "অবৈধ লিংক",
  "auth.requestNewResetLink": "নতুন রিসেট লিংক অনুরোধ করুন",
  "auth.passwordResetSuccessful": "পাসওয়ার্ড সফলভাবে রিসেট হয়েছে",
  "auth.resetYourPassword": "আপনার পাসওয়ার্ড রিসেট করুন",
  "auth.passwordRequirements": "পাসওয়ার্ড প্রয়োজনীয়তা:",
  "auth.resettingPassword": "পাসওয়ার্ড রিসেট হচ্ছে...",
  "auth.twofactorAuthenticationSetup": "দুই-ফ্যাক্টর প্রমাণীকরণ সেটআপ",
  "auth.manualEntryKey": "ম্যানুয়াল এন্ট্রি কী",
  "auth.verificationCode": "যাচাইকরণ কোড",
  "auth.copyAllBackupCodes": "সকল ব্যাকআপ কোড কপি করুন",
  "auth.secretKeyCopiedToClipboard": "গোপন কী ক্লিপবোর্ডে কপি হয়েছে",
  "billing.creditNotes": "ক্রেডিট নোট",
  "billing.saasPlans": "SaaS প্ল্যান",
  "billing.usageBilling": "ব্যবহার বিলিং",
  "billing.paymentPlans": "পেমেন্ট প্ল্যান",
  "billing.folioTransfer": "ফোলিও স্থানান্তর",
  "billing.multiCurrency": "বহু-মুদ্রা",
  "billing.cancellationPolicies": "বাতিলকরণ নীতি",
  "billing.newFolio": "নতুন ফোলিও",
  "billing.openFolios": "খোলা ফোলিও",
  "billing.lineItems": "লাইন আইটেম",
  "billing.unitPrice": "একক মূল্য",
  "billing.closeFolio": "ফোলিও বন্ধ করুন",
  "billing.roomCharge": "কক্ষ চার্জ",
  "billing.foodBeverage": "খাদ্য ও পানীয়",
  "billing.partiallyPaid": "আংশিক পরিশোধিত",
  "billing.newInvoice": "নতুন চালান",
  "billing.markSent": "প্রেরিত হিসেবে চিহ্নিত",
  "billing.markPaid": "পরিশোধিত হিসেবে চিহ্নিত",
  "billing.cancelInvoice": "চালান বাতিল",
  "billing.nameRequired": "নাম *",
  "billing.dueDate": "নির্ধারিত তারিখ",
  "billing.taxPercent": "কর %",
  "billing.lineItemsSection": "লাইন আইটেম",
  "billing.emailSent": "ইমেইল পাঠানো হয়েছে",
  "billing.emailFailed": "ইমেইল প্রেরণ ব্যর্থ",
  "billing.noEmail": "কোনো ইমেইল নেই",
  "billing.streetCityCountry": "রাস্তা, শহর, দেশ",
  "billing.newPayment": "নতুন পেমেন্ট",
  "billing.processPayment": "পেমেন্ট প্রক্রিয়া",
  "billing.paymentAmount": "পেমেন্টের পরিমাণ",
  "billing.fullAmount": "পূর্ণ পরিমাণ",
  "billing.paymentMethodLabel": "পেমেন্ট পদ্ধতি",
  "billing.creditDebitCard": "ক্রেডিট/ডেবিট কার্ড",
  "billing.bankTransfer": "ব্যাংক স্থানান্তর",
  "billing.digitalWallet": "ডিজিটাল ওয়ালেট",
  "billing.paymentGateway": "পেমেন্ট গেটওয়ে",
  "billing.cardType": "কার্ডের ধরন",
  "billing.last4Digits": "শেষ ৪ সংখ্যা",
  "billing.referenceNotes": "রেফারেন্স / নোট",
  "billing.netAmount": "নিট পরিমাণ",
  "billing.processRefund": "ফেরত প্রক্রিয়া",
  "billing.originalAmount": "মূল পরিমাণ",
  "billing.alreadyRefunded": "ইতোমধ্যে ফেরত দেওয়া হয়েছে",
  "billing.refundAmount": "ফেরতের পরিমাণ",
  "billing.partialRefund": "আংশিক ফেরত",
  "billing.guestRequest": "অতিথি অনুরোধ",
  "billing.bookingCancellation": "বুকিং বাতিল",
  "billing.serviceIssue": "সেবা সমস্যা",
  "billing.billingError": "বিলিং ত্রুটি",
  "billing.duplicateCharge": "অনুলিপি চার্জ",
  "billing.validationError": "যাচাইকরণ ত্রুটি",
  "billing.partialRefundLabel": "আংশিক ফেরত",
  "billing.alreadyRefundedAmount": "ইতোমধ্যে ফেরত দেওয়া হয়েছে",
  "billing.newDiscount": "নতুন ছাড়",
  "billing.fixedAmount": "নির্দিষ্ট পরিমাণ",
  "billing.codePlaceholder": "গ্রীষ্মকালীন বিক্রয়",
  "billing.generateCode": "কোড তৈরি করুন",
  "billing.discountName": "নাম *",
  "billing.discountType": "ছাড়ের ধরন *",
  "billing.value": "মান *",
  "billing.startDate": "শুরুর তারিখ",
  "billing.endDate": "শেষ তারিখ",
  "billing.minNights": "সর্বনিম্ন রাত",
  "billing.maxUses": "সর্বোচ্চ ব্যবহার",
  "billing.discountValue": "ছাড়ের মান",
  "billing.validFrom": "প্রযোজ্য হতে",
  "billing.validUntil": "প্রযোজ্য পর্যন্ত",
  "billing.timesUsed": "ব্যবহারের সংখ্যা",
  "billing.creditNotesTitle": "ক্রেডিট নোট",
  "billing.newCreditNote": "নতুন ক্রেডিট নোট",
  "billing.noteNumber": "নোট #",
  "billing.reasonRequired": "কারণ *",
  "billing.descriptionOptional": "বিবরণ (ঐচ্ছিক)",
  "billing.itemsRequired": "আইটেম *",
  "billing.cancelCreditNote": "ক্রেডিট নোট বাতিল",
  "billing.saasPlansTitle": "SaaS প্ল্যান",
  "billing.monthlyRevenue": "মাসিক আয়",
  "billing.professionalUsers": "পেশাদার ব্যবহারকারী",
  "billing.subscribeTenant": "টেন্যান্ট সাবস্ক্রাইব",
  "billing.mostPopular": "সবচেয়ে জনপ্রিয়",
  "billing.displayName": "প্রদর্শন নাম",
  "billing.resourceLimits": "সম্পদ সীমা",
  "billing.maxProperties": "সর্বোচ্চ সম্পত্তি",
  "billing.maxUsers": "সর্বোচ্চ ব্যবহারকারী",
  "billing.maxRooms": "সর্বোচ্চ কক্ষ",
  "billing.billingCycle": "বিলিং চক্র",
  "billing.monthlyRevenueLabel": "মাসিক আয়",
  "billing.trialEnds": "ট্রায়াল শেষ",
  "billing.usageAndLimits": "ব্যবহার ও সীমা",
  "billing.changePlan": "প্ল্যান পরিবর্তন",
  "billing.newPlan": "নতুন প্ল্যান",
  "billing.effectiveDate": "কার্যকর তারিখ",
  "billing.reasonOptional": "কারণ (ঐচ্ছিক)",
  "billing.newPlanLabel": "নতুন প্ল্যান",
  "billing.priceChange": "মূল্য পরিবর্তন",
  "billing.usageBillingTitle": "ব্যবহার বিলিং",
  "billing.basePlan": "বেস প্ল্যান",
  "billing.usageCharges": "ব্যবহার চার্জ",
  "billing.overageCharges": "অতিরিক্ত ব্যবহার চার্জ",
  "billing.usageAlerts": "ব্যবহার সতর্কতা",
  "billing.rateCard": "রেট কার্ড",
  "billing.dailyUsage": "দৈনিক ব্যবহার",
  "billing.dailyUsageTrends": "দৈনিক ব্যবহার প্রবণতা",
  "billing.paymentPlansTitle": "পেমেন্ট প্ল্যান",
  "billing.planName": "প্ল্যানের নাম",
  "billing.depositPercent": "জমা %",
  "billing.schedulePreview": "সূচি প্রিভিউ",
  "billing.installmentTimeline": "কিস্তির টাইমলাইন",
  "billing.folioTransferTitle": "ফোলিও স্থানান্তর",
  "billing.settledFolios": "নিষ্পত্তিকৃত ফোলিও",
  "billing.transferMode": "স্থানান্তর মোড",
  "billing.transferAmountLabel": "স্থানান্তরের পরিমাণ",
  "billing.transferReason": "কারণ *",
  "billing.transferDescription": "বিবরণ (ঐচ্ছিক)",
  "billing.transferPreview": "স্থানান্তর প্রিভিউ",
  "billing.confirmTransfer": "স্থানান্তর নিশ্চিত",
  "billing.multiCurrencyTitle": "বহু-মুদ্রা",
  "billing.converterTitle": "মুদ্রা রূপান্তরকারী",
  "billing.fromCurrency": "থেকে মুদ্রা",
  "billing.toCurrency": "থেকে মুদ্রা",
  "billing.validFromLabel": "প্রযোজ্য হতে",
  "billing.validUntilLabel": "প্রযোজ্য পর্যন্ত",
  "billing.validUntilOptional": "প্রযোজ্য পর্যন্ত (ঐচ্ছিক)",
  "billing.cancellationPoliciesTitle": "বাতিলকরণ নীতি",
  "billing.avgFreeWindow": "গড় মুক্ত সময়",
  "billing.ratePlan": "রেট প্ল্যান",
  "billing.penaltyType": "জরিমানার ধরন",
  "billing.penaltyPercent": "জরিমানা শতাংশ",
  "billing.fixedPenaltyAmount": "নির্দিষ্ট জরিমানার পরিমাণ",
  "billing.noShowPenalty": "নো-শো জরিমানা",
  "billing.exemptGoldLoyalty": "গোল্ড+ অনুগত্ব টায়ার থেকে অব্যাহতি",
  "billing.exemptCorporate": "কর্পোরেট সেগমেন্ট থেকে অব্যাহতি",
  "billing.customExemptions": "কাস্টম অব্যাহতি",
  "billing.policyName": "নীতির নাম",
  "billing.freeWindow": "মুক্ত সময়",
  "billing.noShowLabel": "নো-শো",
  "pos.newOrder": "নতুন অর্ডার",
  "pos.todaysOrders": "আজকের অর্ডার",
  "pos.inKitchen": "রান্নাঘরে",
  "pos.menuItems": "মেনু আইটেম",
  "pos.selectedItems": "নির্বাচিত আইটেম",
  "pos.guestNameOptional": "অতিথির নাম (ঐচ্ছিক)",
  "pos.noPropertySelected": "কোনো সম্পত্তি নির্বাচিত নয়",
  "pos.cancelOrder": "অর্ডার বাতিল",
  "pos.keepOrder": "অর্ডার রাখুন",
  "pos.startPreparing": "প্রস্তুতি শুরু",
  "pos.dineIn": "রেস্তোরাঁয় খাওয়া",
  "pos.roomService": "রুম সার্ভিস",
  "pos.kitchenDisplay": "রান্নাঘর ডিসপ্লে সিস্টেম",
  "pos.noPropertyKitchen": "কোনো সম্পত্তি নির্বাচিত নয়",
  "pos.tableNumber": "টেবিল নম্বর",
  "pos.tableNameOptional": "নাম (ঐচ্ছিক)",
  "pos.avgPrice": "গড় মূল্য",
  "pos.itemName": "নাম *",
  "pos.itemPrice": "মূল্য *",
  "pos.itemCategory": "বিভাগ *",
  "pos.prepTime": "প্রস্তুতির সময় (মিনিট)",
  "pos.kitchenStation": "রান্নাঘর স্টেশন",
  "pos.saladBar": "সালাদ বার",
  "pos.dietaryOptions": "খাদ্যাভ্যাস বিকল্প",
  "pos.categoryName": "বিভাগের নাম",
  "pos.billingTitle": "রেস্তোরাঁ বিলিং",
  "pos.avgOrder": "গড় অর্ডার",
  "pos.todaysReservations": "আজকের রিজার্ভেশন",
  "pos.seatedNow": "বর্তমানে বসানো",
  "pos.noShows": "নো-শো",
  "pos.newReservation": "নতুন রিজার্ভেশন",
  "pos.guestNameRequired": "অতিথির নাম *",
  "pos.guestPhoneRequired": "অতিথির ফোন *",
  "pos.guestEmail": "অতিথির ইমেইল",
  "pos.partySizeRequired": "পার্টির সাইজ *",
  "pos.dateRequired": "তারিখ *",
  "pos.timeRequired": "সময় *",
  "pos.tableOptional": "টেবিল (ঐচ্ছিক)",
  "pos.specialRequestsLabel": "বিশেষ অনুরোধ",
  "pos.guestPhonePlaceholder": "+1 555 123 4567",
  "pos.guestNamePlaceholder": "জন ডো",
  "pos.lowStockAlerts": "নিম্ন স্টক সতর্কতা",
  "pos.inStock": "স্টকে আছে",
  "pos.lowStock": "নিম্ন স্টক",
  "pos.itemNameRequired": "আইটেমের নাম *",
  "pos.unitCost": "একক খরচ",
  "pos.lowThreshold": "নিম্ন সীমা",
  "pos.lastRestocked": "সর্বশেষ পুনরায় স্টক করা",
  "pos.adjustStock": "স্টক সামঞ্জস্য",
  "pos.roomServiceTitle": "রুম সার্ভিস",
  "pos.noRoomSelected": "কোনো কক্ষ নির্বাচিত নয়",
  "pos.orderSummary": "অর্ডার সারসংক্ষেপ",
  "pos.tableLayoutTitle": "টেবিল লেআউট",
  "pos.tableNumberRequired": "টেবিল নম্বর *",
  "pos.tableName": "টেবিলের নাম",
  "pos.widthPx": "প্রস্থ (px)",
  "pos.heightPx": "উচ্চতা (px)",
  "pos.noTableSelected": "কোনো টেবিল নির্বাচিত নয়",
  "pos.noTablesYet": "এখনো কোনো টেবিল নেই",
  "pos.resetZoom": "জুম রিসেট",
  "pos.zoomIn": "জুম ইন",
  "pos.zoomOut": "জুম আউট",
  "pos.toggleGridSnap": "গ্রিড স্ন্যাপ টগল",
  "pos.staffAssignmentTitle": "কর্মী বরাদ্দ",
  "pos.onDutyBadge": "দায়িত্বরত",
  "pos.staffMember": "কর্মী সদস্য",
  "pos.prepTimeLabel": "প্রস্তুতির সময় (মিনিট)",
  "pos.cookTime": "রান্নার সময় (মিনিট)",
  "pos.yieldServings": "ফলন (সার্ভিং)",
  "pos.sellingPrice": "বিক্রয় মূল্য:",
  "pos.foodCost": "খাদ্য খরচ:",
  "pos.restaurantReportsTitle": "রেস্তোরাঁ রিপোর্ট",
  "pos.avgOrderValue": "গড় অর্ডার মূল্য",
  "pos.tableOccupancy": "টেবিল দখল",
  "pos.revenueTrend": "আয়ের প্রবণতা",
  "pos.topSellingItems": "সর্বাধিক বিক্রিত আইটেম",
  "pos.salesSummary": "বিক্রয় সারসংক্ষেপ",
  "pos.categoryPerformance": "বিভাগ পারফরম্যান্স",
  "pos.ghostItems": "ভূত আইটেম (কখনো অর্ডার হয়নি)",
  "pos.avgDiningDuration": "গড় খাওয়ার সময়কাল",
  "pos.mostUsed": "সবচেয়ে বেশি ব্যবহৃত",
  "pos.leastUsed": "সবচেয়ে কম ব্যবহৃত",
  "pos.tableTurnover": "টেবিল টার্নওভার",
  "pos.receiptTemplatesTitle": "রিসিপ্ট টেমপ্লেট",
  "pos.printSample": "নমুনা প্রিন্ট",
  "pos.restaurantName": "রেস্তোরাঁর নাম",
  "pos.thankYouMessage": "ধন্যবাদ বার্তা",
  "pos.fontSize": "ফন্ট সাইজ",
  "pos.livePreview": "লাইভ প্রিভিউ",
  "pos.noActiveOrder": "কোনো সক্রিয় অর্ডার নেই",
  "pos.menuModifiersTitle": "মেনু মডিফায়ার",
  "pos.noModifierGroups": "কোনো মডিফায়ার গ্রুপ নেই",
  "pos.appliedTo": "প্রযোজ্য",
  "pos.groupNameRequired": "গ্রুপের নাম *",
  "pos.selectionTypeLabel": "নির্বাচনের ধরন",
  "pos.minSelections": "সর্বনিম্ন নির্বাচন",
  "pos.maxSelections": "সর্বোচ্চ নির্বাচন",
  "pos.appliesToMenuItems": "মেনু আইটেমে প্রযোজ্য",
  "pos.menuVariantsTitle": "মেনু ভ্যারিয়েন্ট / সাইজ",
  "pos.itemsWithVariants": "ভ্যারিয়েন্টসহ আইটেম",
  "pos.menuItemRequired": "মেনু আইটেম *",
  "pos.variantNameRequired": "ভ্যারিয়েন্টের নাম *",
  "pos.variantPriceRequired": "মূল্য *",
  "pos.sortOrder": "ক্রম অনুসারে সাজান",
  "pos.defaultVariant": "ডিফল্ট ভ্যারিয়েন্ট",
  "pos.bulkCreateVariants": "একসাথে ভ্যারিয়েন্ট তৈরি",
  "pos.menuItemImage": "মেনু আইটেমের ছবি",
  "pos.applyDiscount": "ছাড় প্রয়োগ",
  "pos.recentDiscounts": "সাম্প্রতিক ছাড়",
  "pos.specialInstructionsLabel": "বিশেষ নির্দেশনা",
  "pos.splitOrder": "অর্ডার বিভাজন",
  "pos.splitEqually": "সমানভাবে বিভাজন",
  "pos.tableMergeTitle": "টেবিল মার্জ / বিভাজন",
  "pos.availableTablesLabel": "উপলব্ধ টেবিল",
  "pos.mergeTables": "টেবিল মার্জ",
  "pos.partySizeLabel": "পার্টির সাইজ",
  "revenue.pricingRulesTitle": "মূল্য নির্ধারণ নিয়ম",
  "revenue.avgAdjustment": "গড় সামঞ্জস্য",
  "revenue.seasonalRules": "মৌসুমী নিয়ম",
  "revenue.ruleName": "নিয়মের নাম",
  "revenue.ruleType": "নিয়মের ধরন",
  "revenue.priceIncrease": "মূল্য বৃদ্ধি",
  "revenue.priceDecrease": "মূল্য হ্রাস",
  "revenue.dynamicPricing": "ডায়নামিক প্রাইসিং",
  "revenue.seasonalRate": "মৌসুমী হার",
  "revenue.valueType": "মানের ধরন",
  "revenue.fixedAmount": "নির্দিষ্ট পরিমাণ",
  "revenue.adjustmentValue": "সামঞ্জস্যের মান",
  "revenue.effectiveFrom": "কার্যকর হতে",
  "revenue.effectiveTo": "কার্যকর পর্যন্ত (ঐচ্ছিক)",
  "revenue.demandForecastingTitle": "চাহিদা পূর্বাভাস",
  "revenue.noForecastData": "কোনো পূর্বাভাস ডেটা উপলব্ধ নেই",
  "revenue.predictedOccupancy": "পূর্বাভাসিত দখল",
  "revenue.forecastAccuracy": "পূর্বাভাসের নির্ভুলতা",
  "revenue.peakDemandDays": "সর্বোচ্চ চাহিদার দিন",
  "revenue.bookingPace": "বুকিং গতি",
  "revenue.seasonalFactor": "মৌসুমী ফ্যাক্টর",
  "revenue.forecastChart": "পূর্বাভাস চার্ট",
  "revenue.seasonalTrends": "মৌসুমী প্রবণতা",
  "revenue.eventImpact": "ইভেন্ট প্রভাব",
  "revenue.demandForecast": "চাহিদা পূর্বাভাস",
  "revenue.confidenceInterval": "আত্মবিশ্বাস ব্যবধান",
  "revenue.dailyForecastBreakdown": "দৈনিক পূর্বাভাস বিবরণ",
  "revenue.seasonalOccupancy": "মৌসুমী দখল প্যাটার্ন",
  "revenue.dailyForecast": "দৈনিক পূর্বাভাস",
  "revenue.competitorPricingTitle": "প্রতিযোগী মূল্য",
  "revenue.ourPrice": "আমাদের মূল্য",
  "revenue.marketAverage": "বাজারের গড়",
  "revenue.competitorsTracked": "ট্র্যাক করা প্রতিযোগী",
  "revenue.marketPosition": "বাজারের অবস্থান",
  "revenue.priceHistoryComparison": "মূল্য ইতিহাস তুলনা",
  "revenue.competitorRates": "প্রতিযোগীর হার",
  "revenue.pricePositionAnalysis": "মূল্য অবস্থান বিশ্লেষণ",
  "revenue.marketLow": "বাজারের সর্বনিম্ন",
  "revenue.marketHigh": "বাজারের সর্বোচ্চ",
  "revenue.marketAvg": "বাজারের গড়",
  "revenue.competitorNameRequired": "প্রতিযোগীর নাম *",
  "revenue.potentialRevenue": "সম্ভাব্য আয়",
  "revenue.avgConfidence": "গড় আত্মবিশ্বাস",
  "revenue.appliedThisMonth": "এই মাসে প্রয়োগ করা",
  "revenue.appliedSuggestions": "প্রয়োগ করা পরামর্শ",
  "reports.staffPerformanceTitle": "কর্মী পারফরম্যান্স",
  "reports.avgRating": "গড় রেটিং",
  "reports.tasksCompleted": "সম্পন্ন কাজ",
  "reports.avgResponse": "গড় প্রতিক্রিয়া",
  "reports.weeklyTaskTrend": "সাপ্তাহিক কাজ প্রবণতা",
  "reports.departmentPerformance": "বিভাগীয় পারফরম্যান্স",
  "reports.topPerformers": "শীর্ষ পারফরমার",
  "reports.avgTime": "গড় সময়",
  "reports.guestAnalyticsTitle": "অতিথি বিশ্লেষণ রিপোর্ট",
  "reports.bookingPatternsTab": "বুকিং প্যাটার্ন",
  "reports.returningRate": "পুনরায় আসার হার",
  "reports.monthlyBookingTrend": "মাসিক বুকিং প্রবণতা",
  "reports.topMarkets": "শীর্ষ বাজার",
  "reports.loyaltyProgram": "অনুগত্ব প্রোগ্রাম",
  "reports.ageGroups": "বয়স গ্রুপ",
  "reports.topNationalities": "শীর্ষ জাতীয়তা",
  "reports.scheduledReportsTitle": "নির্ধারিত রিপোর্ট",
  "reports.reportName": "রিপোর্টের নাম",
  "reports.reportType": "রিপোর্টের ধরন",
  "reports.revenueReport": "আয় রিপোর্ট",
  "reports.occupancyReport": "দখল রিপোর্ট",
  "reports.staffPerformanceReport": "কর্মী পারফরম্যান্স",
  "reports.customReport": "কাস্টম রিপোর্ট",
  "reports.performanceSummary": "পারফরম্যান্স সারসংক্ষেপ",
  "reports.revenueReportsTitle": "আয় রিপোর্ট",
  "reports.paymentsCollected": "সংগৃহীত পেমেন্ট",
  "reports.avgBookingValue": "গড় বুকিং মূল্য",
  "reports.occupancyReportsTitle": "দখল রিপোর্ট",
  "reports.avgOccupancy": "গড় দখল",
  "reports.peakOccupancy": "সর্বোচ্চ দখল",
  "reports.lowOccupancy": "সর্বনিম্ন দখল",
  "reports.occupancyTrend": "দখল প্রবণতা",
  "reports.roomStatusDistribution": "কক্ষ অবস্থা বণ্টন",
  "reports.peakDays": "সর্বোচ্চ দিন",
  "reports.lowOccupancyDays": "নিম্ন দখলের দিন",
  "admin.monthlyRecurringRevenue": "মাসিক পুনরাবৃত্ত আয়",
  "admin.annualRecurringRevenue": "বার্ষিক পুনরাবৃত্ত আয়",
  "admin.revenueGrowth": "আয় প্রবৃদ্ধি",
  "admin.churnRate": "চার্ন হার",
  "admin.customerLifetimeValue": "গ্রাহক আজীবন মূল্য",
  "admin.customerAcquisitionCost": "গ্রাহক অর্জন খরচ",
  "admin.monthlyRevenueTrend": "মাসিক আয় প্রবণতা",
  "admin.systemRoles": "সিস্টেম ভূমিকা",
  "admin.customRoles": "কাস্টম ভূমিকা",
  "admin.testPermissions": "অনুমতি পরীক্ষা",
  "admin.adminRoleProtected": "অ্যাডমিন ভূমিকা সুরক্ষিত",
  "admin.permissionTester": "অনুমতি পরীক্ষক",
  "admin.roleComparison": "ভূমিকা তুলনা",
  "admin.commonPermissions": "সাধারণ অনুমতি",
  "admin.permissionComparisonMatrix": "অনুমতি তুলনা ম্যাট্রিক্স",
  "admin.bothGranted": "উভয় প্রদত্ত",
  "admin.rolePermissionAuditLog": "ভূমিকা ও অনুমতি অডিট লগ",
  "admin.auditTrail": "অডিট ট্রেইল",
  "admin.rolesPermissions": "ভূমিকা ও অনুমতি",
  "admin.permissionMatrix": "অনুমতি ম্যাট্রিক্স",
  "admin.auditLog": "অডিট লগ",
  "admin.displayName": "প্রদর্শন নাম",
  "admin.quickPermissions": "দ্রুত অনুমতি",
  "admin.noAccess": "প্রবেশ নেই",
  "admin.fullAccess": "সম্পূর্ণ প্রবেশ",
  "admin.manageRolesAndTheirPermissionAssignmentsAcrossTotalmodulesModulesAndTotalpermissionsPermissions": "{totalModules} মডিউল এবং {totalPermissions} অনুমতি জুড়ে ভূমিকা ও তাদের অনুমতি বরাদ্দ পরিচালনা করুন",
  "admin.effectivepermssizeEffectivePermissionsIncludingWildcards": "{effectivePerms.size}টি কার্যকর অনুমতি (ওয়াইল্ডকার্ড সহ)",
  "admin.permissionsSavedForRoledisplayname": "${role.displayName} এর জন্য অনুমতি সংরক্ষিত",
  "admin.role1": "ভূমিকা ১",
  "admin.role2": "ভূমিকা ২",
  "admin.roleName": "ভূমিকার নাম *",
  "admin.displayName_1": "প্রদর্শন নাম *",
  "admin.systemHealth": "সিস্টেমের স্বাস্থ্য",
  "admin.memoryUsage": "মেমরি ব্যবহার",
  "admin.systemUptime": "সিস্টেম আপটাইম",
  "admin.serviceStatus": "সেবার অবস্থা",
  "admin.databaseMetrics": "ডেটাবেস মেট্রিক্স",
  "admin.avgLatency": "গড় লেটেন্সি",
  "admin.connectionPool": "কনেকশন পুল",
  "admin.storageUsed": "ব্যবহৃত স্টোরেজ",
  "admin.diskUsage": "ডিস্ক ব্যবহার",
  "admin.recentAlerts": "সাম্প্রতিক সতর্কতা",
  "admin.onTrial": "ট্রায়ালে",
  "admin.trialsExpiringSoon": "শীঘ্রই মেয়াদোত্তীর্ণ হচ্ছে এমন ট্রায়াল",
  "admin.tenantSubscriptions": "টেন্যান্ট সাবস্ক্রিপশন",
  "admin.planChangeSummary": "প্ল্যান পরিবর্তন সারসংক্ষেপ",
  "admin.confirmStatusChange": "অবস্থা পরিবর্তন নিশ্চিত করুন",
  "admin.downgradePlan": "প্ল্যান ডাউনগ্রেড",
  "admin.upgradePlan": "প্ল্যান আপগ্রেড",
  "admin.tenantStatusChangedToNewstatus": "টেন্যান্টের অবস্থা ${newStatus} এ পরিবর্তিত",
  "admin.maxProperties": "সর্বোচ্চ সম্পত্তি",
  "admin.maxUsers": "সর্বোচ্চ ব্যবহারকারী",
  "admin.maxRooms": "সর্বোচ্চ কক্ষ",
  "admin.onTrial_1": "ট্রায়ালে",
  "admin.monthlyRevenue": "মাসিক আয়",
  "admin.usageTracking": "ব্যবহার ট্র্যাকিং",
  "admin.accountLimits": "অ্যাকাউন্ট সীমা",
  "admin.usageAlerts": "ব্যবহার সতর্কতা",
  "admin.loadingUserManagement": "ব্যবহারকারী পরিচালনা লোড হচ্ছে...",
  "admin.noRole": "কোনো ভূমিকা নেই",
  "admin.lastLogin": "সর্বশেষ লগইন",
  "admin.platformAdmin": "প্ল্যাটফর্ম অ্যাডমিন",
  "admin.resetPassword": "পাসওয়ার্ড রিসেট",
  "admin.jobTitle": "পদবি",
  "admin.frontDesk": "ফ্রন্ট ডেস্ক",
  "admin.isplatformadminAListOfAllUsersAcrossTenantsAListOfAllUsersInYourOrganization": "{isPlatformAdmin\n              ? 'সকল টেন্যান্ট জুড়ে সকল ব্যবহারকারীর তালিকা'\n              : 'আপনার সংস্থার সকল ব্যবহারকারীর তালিকা'\n            }",
  "admin.tenant_4": "টেন্যান্ট *",
  "admin.firstName": "প্রথম নাম *",
  "admin.lastName": "শেষ নাম *",
  "admin.email_1": "ইমেইল *",
  "admin.newPassword": "নতুন পাসওয়ার্ড *",
  "channels.bookingSync": "বুকিং সিঙ্ক",
  "channels.roomType": "কক্ষের ধরন",
  "channels.centralReservationSystem": "কেন্দ্রীয় রিজার্ভেশন সিস্টেম",
  "channels.bookingSources": "বুকিং উৎস",
  "channels.lastSync": "সর্বশেষ সিঙ্ক",
  "channels.syncInterval": "সিঙ্ক বিরতি",
  "channels.autoSync": "স্বয়ংক্রিয় সিঙ্ক",
  "channels.connectionName": "কনেকশনের নাম",
  "channels.apiKey": "API কী",
  "channels.syncIntervalMinutes": "সিঙ্ক বিরতি (মিনিট)",
  "channels.inventorySync": "ইনভেন্টরি সিঙ্ক",
  "channels.syncRate": "সিঙ্ক হার",
  "channels.syncProgress": "সিঙ্ক অগ্রগতি",
  "channels.roomType_1": "কক্ষের ধরন",
  "channels.lastSync_1": "সর্বশেষ সিঙ্ক",
  "channels.syncingInventoryForChannelname": "${channelName} এর জন্য ইনভেন্টরি সিঙ্ক হচ্ছে",
  "channels.channelMapping": "চ্যানেল ম্যাপিং",
  "channels.roomType_2": "কক্ষের ধরন",
  "channels.ratePlanOptional": "রেট প্ল্যান (ঐচ্ছিক)",
  "channels.externalRoomName": "বাহ্যিক কক্ষের নাম",
  "channels.externalRateName": "বাহ্যিক হারের নাম",
  "channels.syncInventory": "ইনভেন্টরি সিঙ্ক",
  "channels.syncRates": "হার সিঙ্ক",
  "channels.syncRestrictions": "সীমাবদ্ধতা সিঙ্ক",
  "channels.inventorySync_1": "ইনভেন্টরি সিঙ্ক",
  "channels.rateSync": "হার সিঙ্ক",
  "channels.ratePlan": "রেট প্ল্যান",
  "channels.externalRoom": "বাহ্যিক কক্ষ",
  "channels.externalRate": "বাহ্যিক হার",
  "channels.syncInv": "সিঙ্ক ইনভেন্টরি",
  "channels.syncRest": "সিঙ্ক সীমাবদ্ধতা",
  "channels.itemslengthMappingsConfigured": "{items.length}টি ম্যাপিং কনফিগার করা",
  "channels.asiaPacific": "এশিয়া প্যাসিফিক",
  "channels.middleEast": "মধ্যপ্রাচ্য",
  "channels.displayName": "প্রদর্শন নাম",
  "channels.autoSync_1": "স্বয়ংক্রিয় সিঙ্ক",
  "channels.syncInterval_1": "সিঙ্ক বিরতি",
  "channels.integrationProgress": "ইন্টিগ্রেশন অগ্রগতি",
  "channels.noChannelConnections": "কোনো চ্যানেল কনেকশন নেই",
  "channels.testConnection": "কনেকশন পরীক্ষা",
  "channels.syncNow": "এখন সিঙ্ক",
  "channels.criticalPriority": "সর্বোচ্চ অগ্রাধিকার",
  "channels.rateSync_1": "হার সিঙ্ক",
  "channels.avgRate": "গড় হার",
  "channels.roomType_3": "কক্ষের ধরন",
  "channels.ratePlan_1": "রেট প্ল্যান",
  "channels.basePrice": "ভিত্তি মূল্য",
  "channels.channelPrice": "চ্যানেল মূল্য",
  "channels.autoAdjust": "স্বয়ংক্রিয় সামঞ্জস্য",
  "channels.lastSync_2": "সর্বশেষ সিঙ্ক",
  "channels.basePriceReference": "ভিত্তি মূল্য (রেফারেন্স)",
  "channels.saveChanges": "পরিবর্তনগুলো সংরক্ষণ করুন",
  "channels.channelRestrictions": "চ্যানেল সীমাবদ্ধতা",
  "channels.stopSell": "বিক্রয় বন্ধ",
  "channels.minStay": "সর্বনিম্ন অবস্থান",
  "channels.maxStay": "সর্বোচ্চ অবস্থান",
  "channels.roomType_4": "কক্ষের ধরন",
  "channels.minimumStayNights": "সর্বনিম্ন অবস্থান (রাত)",
  "channels.maximumStayNights": "সর্বোচ্চ অবস্থান (রাত)",
  "channels.saveChanges_1": "পরিবর্তনগুলো সংরক্ষণ করুন",
  "channels.itemslengthRestrictionRulesConfigured": "{items.length}টি সীমাবদ্ধতা নিয়ম কনফিগার করা",
  "channels.successRate": "সফলতার হার",
  "crm.marketingCampaigns": "মার্কেটিং ক্যাম্পেইন",
  "crm.avgOpenRate": "গড় ওপেন হার",
  "crm.avgClickRate": "গড় ক্লিক হার",
  "crm.newCampaign": "নতুন ক্যাম্পেইন",
  "crm.campaignName": "ক্যাম্পেইনের নাম",
  "crm.subjectLine": "বিষয় লাইন",
  "crm.targetSegments": "লক্ষ্য সেগমেন্ট",
  "crm.scheduleOptional": "সূচি (ঐচ্ছিক)",
  "crm.scheduleCampaign": "ক্যাম্পেইন নির্ধারণ",
  "crm.deliveryProgress": "বিতরণ অগ্রগতি",
  "crm.feedbackReviews": "মতামত ও পর্যালোচনা",
  "crm.avgRating": "গড় রেটিং",
  "crm.responseRate": "প্রতিক্রিয়া হার",
  "crm.positiveSentiment": "সকারাত্মক সেন্টিমেন্ট",
  "crm.openFeedback": "খোলা মতামত",
  "crm.guestFeedback": "অতিথি মতামত",
  "crm.reviewResponse": "পর্যালোচনা প্রতিক্রিয়া",
  "crm.yourResponse": "আপনার প্রতিক্রিয়া",
  "crm.resolveFeedback": "মতামত সমাধান",
  "crm.guestSegments": "অতিথি সেগমেন্ট",
  "crm.avgMemberssegment": "গড় সদস্য/সেগমেন্ট",
  "crm.segmentName": "সেগমেন্টের নাম",
  "crm.segmentationRules": "সেগমেন্টেশন নিয়ম",
  "crm.loyaltyPrograms": "অনুগত্ব প্রোগ্রাম",
  "crm.pointsEarnedMonth": "অর্জিত পয়েন্ট (মাস)",
  "crm.pointsRedeemedMonth": "খরচ করা পয়েন্ট (মাস)",
  "crm.avgPointsmember": "গড় পয়েন্ট/সদস্য",
  "crm.tierLevels": "টায়ার স্তর",
  "crm.redemptionOptions": "রিডেম্পশন বিকল্প",
  "crm.topMembers": "শীর্ষ সদস্য",
  "crm.memberDistribution": "সদস্য বণ্টন",
  "crm.pointsRedemptionOptions": "পয়েন্ট রিডেম্পশন বিকল্প",
  "crm.pointsValue": "পয়েন্টের মান",
  "crm.perPointValue": "প্রতি পয়েন্টের মান",
  "crm.topLoyaltyMembers": "শীর্ষ অনুগত সদস্য",
  "crm.tierminpointstolocalestringTiermaxpoints999999TiermaxpointstolocalestringPoints": "{tier.minPoints.toLocaleString()} - {tier.maxPoints === 999999 ? '∞' : tier.maxPoints.toLocaleString()} পয়েন্ট",
  "crm.cohortAnalysis": "কোহর্ট বিশ্লেষণ",
  "crm.atriskGuests": "ঝুঁকিপূর্ণ অতিথি",
  "crm.lifetimeValue": "আজীবন মূল্য",
  "crm.guestJourneyFunnel": "অতিথি যাত্রা ফানেল",
  "crm.retentionInsights": "ধারণ অন্তর্দৃষ্টি",
  "crm.retentionActivity": "ধারণ কার্যকলাপ",
  "crm.cohortRetentionAnalysis": "কোহর্ট ধারণ বিশ্লেষণ",
  "crm.averageLifetimeValue": "গড় আজীবন মূল্য",
  "crm.avgStays": "গড় অবস্থান",
  "crm.avgSpend": "গড় খরচ",
  "marketing.directBookingEngine": "সরাসরি বুকিং ইঞ্জিন",
  "marketing.directBookings": "সরাসরি বুকিং",
  "marketing.conversionRate": "রূপান্তর হার",
  "marketing.bookingSources": "বুকিং উৎস",
  "marketing.directBooking": "সরাসরি বুকিং",
  "marketing.recentPerformance": "সাম্প্রতিক পারফরম্যান্স",
  "marketing.pageViews": "পেজ ভিউ",
  "marketing.bookingAttempts": "বুকিং প্রচেষ্টা",
  "marketing.completedBookings": "সম্পন্ন বুকিং",
  "marketing.abandonmentRate": "পরিত্যাগের হার",
  "marketing.commissionComparison": "কমিশন তুলনা",
  "marketing.directBookingSavings": "সরাসরি বুকিং সঞ্চয়",
  "marketing.enableBookingEngine": "বুকিং ইঞ্জিন সক্রিয়",
  "marketing.customDomainOptional": "কাস্টম ডোমেইন (ঐচ্ছিক)",
  "marketing.requirePayment": "পেমেন্ট প্রয়োজন",
  "marketing.depositPercentage": "জমা শতাংশ",
  "marketing.cancellationPolicy": "বাতিলকরণ নীতি",
  "marketing.brandingAppearance": "ব্র্যান্ডিং ও চেহারা",
  "marketing.primaryColor": "প্রাথমিক রং",
  "marketing.secondaryColor": "গৌণ রং",
  "marketing.uploadLogo": "লোগো আপলোড",
  "marketing.bookNow": "এখন বুক করুন",
  "marketing.embedWidget": "উইজেট এম্বেড",
  "marketing.analyticsIntegration": "অ্যানালিটিক্স ইন্টিগ্রেশন",
  "marketing.bookyourhotelcom": "book.yourhotel.com",
  "marketing.promotionsAmpOffers": "প্রচার ও অফার",
  "marketing.expiringSoon": "শীঘ্রই মেয়াদোত্তীর্ণ",
  "marketing.fixedAmount": "নির্দিষ্ট পরিমাণ",
  "marketing.freeNight": "বিনামূল্য রাত",
  "marketing.basicInfo": "প্রাথমিক তথ্য",
  "marketing.minNights": "সর্বনিম্ন রাত",
  "marketing.applicableRoomTypes": "প্রযোজ্য কক্ষের ধরন",
  "marketing.usageLimits": "ব্যবহার সীমা",
  "marketing.maxTotalUses": "সর্বোচ্চ মোট ব্যবহার",
  "marketing.maxUsesPerUser": "প্রতি ব্যবহারকারী সর্বোচ্চ ব্যবহার",
  "marketing.promoCode": "প্রোমো কোড *",
  "marketing.discountType": "ছাড়ের ধরন *",
  "marketing.discountValue": "ছাড়ের মান *",
  "marketing.startDate": "শুরুর তারিখ *",
  "marketing.endDate": "শেষ তারিখ *",
  "marketing.averageRating": "গড় রেটিং",
  "marketing.responseRate": "প্রতিক্রিয়া হার",
  "marketing.sentimentScore": "সেন্টিমেন্ট স্কোর",
  "marketing.ratingDistribution": "রেটিং বণ্টন",
  "marketing.categoryScores": "বিভাগ স্কোর",
  "marketing.recentReviews": "সাম্প্রতিক পর্যালোচনা",
  "marketing.propertyResponse": "সম্পত্তির প্রতিক্রিয়া",
  "marketing.yourResponse": "আপনার প্রতিক্রিয়া",
  "marketing.showingDatareviewslengthOfDatapaginationtotalReviews": "মোট {data.pagination.total}টি পর্যালোচনার মধ্যে {data.reviews.length}টি দেখানো হচ্ছে",
  "marketing.reviewSources": "পর্যালোচনা উৎস",
  "marketing.connectedSources": "সংযুক্ত উৎস",
  "marketing.avgRating": "গড় রেটিং",
  "marketing.syncStatus": "সিঙ্ক অবস্থা",
  "marketing.lastSync": "সর্বশেষ সিঙ্ক",
  "marketing.autoSync": "স্বয়ংক্রিয় সিঙ্ক",
  "marketing.availablePlatforms": "উপলব্ধ প্ল্যাটফর্ম",
  "marketing.connectReviewSource": "পর্যালোচনা উৎস সংযুক্ত করুন",
  "marketing.connectionName": "কনেকশনের নাম",
  "marketing.apiKey": "API কী",
  "marketing.syncNow": "এখন সিঙ্ক",
  "marketing.startingSyncForSourcename": "${source.name} এর জন্য সিঙ্ক শুরু হচ্ছে...",
  "automation.successRate": "সফলতার হার",
  "automation.thisWeek": "এই সপ্তাহে",
  "automation.thisMonth": "এই মাসে",
  "automation.triggerData": "ট্রিগার ডেটা",
  "automation.actionsResult": "ক্রিয়ার ফলাফল",
  "automation.showingLogslengthOfStatstotalexecutionsTotalExecutions": "মোট {stats.totalExecutions}টি এক্সিকিউশনের মধ্যে {logs.length}টি দেখানো হচ্ছে",
  "automation.rulesEngine": "নিয়ম ইঞ্জিন",
  "automation.successRate_1": "সফলতার হার",
  "automation.ruleName": "নিয়মের নাম",
  "automation.triggerEvent": "ট্রিগার ইভেন্ট",
  "automation.triggerConditions": "ট্রিগার শর্ত",
  "automation.sendEmail": "ইমেইল পাঠান",
  "automation.pushNotification": "পুশ বিজ্ঞপ্তি",
  "automation.automationTemplates": "অটোমেশন টেমপ্লেট",
  "automation.useTemplate": "টেমপ্লেট ব্যবহার",
  "automation.customizeTemplate": "টেমপ্লেট কাস্টমাইজ",
  "automation.workflowBuilder": "ওয়ার্কফ্লো বিল্ডার",
  "automation.savedWorkflows": "সংরক্ষিত ওয়ার্কফ্লো",
  "automation.startBuildingYourWorkflow": "আপনার ওয়ার্কফ্লো তৈরি শুরু করুন",
  "automation.emailTemplate": "ইমেইল টেমপ্লেট",
  "automation.welcomeEmail": "স্বাগতম ইমেইল",
  "automation.bookingConfirmation": "বুকিং নিশ্চিতকরণ",
  "automation.feedbackRequest": "মতামত অনুরোধ",
  "automation.messageTemplate": "বার্তা টেমপ্লেট",
  "automation.workflowName": "ওয়ার্কফ্লোর নাম",
  "automation.descriptionOptional": "বিবরণ (ঐচ্ছিক)",
  "inventory.netMovement": "নিট চলাচল",
  "inventory.consumedToday": "আজ খরচ করা",
  "inventory.logEntry": "লগ এন্ট্রি",
  "inventory.logStockMovement": "স্টক চলাচল লগ",
  "inventory.stockItem": "স্টক আইটেম *",
  "inventory.type_1": "ধরন *",
  "inventory.quantity_1": "পরিমাণ *",
  "inventory.lowStock": "নিম্ন স্টক",
  "inventory.stockLevel": "স্টক স্তর",
  "inventory.quickReorder": "দ্রুত পুনরায় অর্ডার",
  "inventory.minimumLevel": "সর্বনিম্ন স্তর:",
  "inventory.unitCost": "একক খরচ:",
  "inventory.estimatedCost": "আনুমানিক খরচ:",
  "inventory.vendor": "ভেন্ডর *",
  "inventory.orderQuantity": "অর্ডারের পরিমাণ *",
  "inventory.newOrder": "নতুন অর্ডার",
  "inventory.purchaseOrders": "ক্রয় অর্ডার",
  "inventory.orderDate": "অর্ডারের তারিখ",
  "inventory.expectedDate": "প্রত্যাশিত তারিখ",
  "inventory.orderItems": "অর্ডার আইটেম",
  "inventory.unitPrice": "একক মূল্য",
  "inventory.receiveOrder": "অর্ডার গ্রহণ",
  "inventory.cancelOrder": "অর্ডার বাতিল",
  "inventory.noKeepOrder": "না, অর্ডার রাখুন",
  "inventory.orderNewstatus": "অর্ডার ${newStatus}",
  "inventory.order": "অর্ডার #",
  "inventory.vendor_2": "ভেন্ডর *",
  "inventory.lowStockItems": "নিম্ন স্টক আইটেম",
  "inventory.lowStock_1": "নিম্ন স্টক",
  "inventory.stockItems": "স্টক আইটেম",
  "inventory.stockLevel_1": "স্টক স্তর",
  "inventory.unitCost_1": "একক খরচ",
  "inventory.minQuantity": "সর্বনিম্ন পরিমাণ",
  "inventory.maxQuantity": "সর্বোচ্চ পরিমাণ",
  "inventory.reorderPoint": "পুনরায় অর্ডার পয়েন্ট",
  "inventory.serviceProviders": "সেবা প্রদানকারী",
  "inventory.paymentTerms": "পেমেন্টের শর্ত",
  "inventory.contactPerson": "যোগাযোগের ব্যক্তি",
  "inventory.deactivateVendor": "ভেন্ডর নিষ্ক্রিয়",
  "inventory.companyName_1": "কোম্পানির নাম *",
  "inventory.type_3": "ধরন *",
  "events.eventBookings": "ইভেন্ট বুকিং",
  "events.newEvent": "নতুন ইভেন্ট",
  "events.inProgress": "চলমান",
  "events.productLaunch": "পণ্য উন্মোচন",
  "events.teamBuilding": "টিম বিল্ডিং",
  "events.propertySpace": "সম্পত্তি / স্থান",
  "events.newEventBooking": "নতুন ইভেন্ট বুকিং",
  "events.eventSpace": "ইভেন্ট স্থান",
  "events.eventType": "ইভেন্টের ধরন",
  "events.expectedGuests": "প্রত্যাশিত অতিথি",
  "events.dateTime": "তারিখ ও সময়",
  "events.startTime": "শুরুর সময়",
  "events.endTime": "শেষ সময়",
  "events.eventName": "ইভেন্টের নাম",
  "events.startDate": "শুরুর তারিখ",
  "events.endDate": "শেষ তারিখ",
  "events.johnDoe": "জন ডো",
  "events.eventStatusUpdatedToNewstatus": "ইভেন্টের অবস্থা ${newStatus} এ আপডেট হয়েছে",
  "events.property_1": "সম্পত্তি *",
  "events.eventName_1": "ইভেন্টের নাম *",
  "events.name_1": "নাম *",
  "events.startDate_1": "শুরুর তারিখ *",
  "events.endDate_1": "শেষ তারিখ *",
  "events.eventCalendar": "ইভেন্ট ক্যালেন্ডার",
  "events.inProgress_1": "চলমান",
  "events.spaceCharge": "স্থান ভাড়া",
  "events.cateringCharge": "ক্যাটারিং চার্জ",
  "events.otherCharges": "অন্যান্য চার্জ",
  "events.eventResources": "ইভেন্ট সম্পদ",
  "events.inUse": "ব্যবহৃত",
  "events.categorySummary": "বিভাগ সারসংক্ষেপ",
  "events.unitPrice": "একক মূল্য",
  "events.vendorName": "ভেন্ডরের নাম",
  "events.staffName": "কর্মীর নাম",
  "events.setupTime": "সেটআপের সময়",
  "events.teardownTime": "প্যাকিংয়ের সময়",
  "events.resourceName": "সম্পদের নাম",
  "events.projectorMicrophoneCatering": "প্রজেক্টর, মাইক্রোফোন, ক্যাটারিং...",
  "events.resourceName_1": "সম্পদের নাম *",
  "events.eventSpaces": "ইভেন্ট স্থান",
  "events.minCapacity": "সর্বনিম্ন ধারণক্ষমতা",
  "events.maxCapacity": "সর্বোচ্চ ধারণক্ষমতা",
  "events.grandBallroom": "গ্র্যান্ড বলরুম",
  "events.property_2": "সম্পত্তি *",
  "events.name_2": "নাম *",
  "ai.newChat": "নতুন চ্যাট",
  "ai.potentialRevenue": "সম্ভাব্য আয়",
  "ai.saveChanges": "পরিবর্তনগুলো সংরক্ষণ করুন",
  "ai.smartRecommendations": "স্মার্ট সুপারিশ",
  "ai.autoTagging": "স্বয়ংক্রিয় ট্যাগিং",
  "ai.sentimentAnalysis": "সেন্টিমেন্ট বিশ্লেষণ",
  "ai.apiKey": "API কী",
  "ai.maxTokens": "সর্বোচ্চ টোকেন",
  "ai.usageThisMonth": "এই মাসের ব্যবহার",
  "ai.defaultProvider": "ডিফল্ট প্রদানকারী",
  "notifications.deliveryRate": "বিতরণ হার",
  "notifications.sentAt": "প্রেরণের সময়",
  "notifications.deliveredAt": "বিতরণের সময়",
  "notifications.markAllRead": "সব পঠিত হিসেবে চিহ্নিত",
  "notifications.saveChanges": "পরিবর্তনগুলো সংরক্ষণ করুন",
  "notifications.enableEmailNotifications": "ইমেইল বিজ্ঞপ্তি সক্রিয়",
  "notifications.fromAddress": "প্রেরকের ঠিকানা",
  "notifications.trackOpens": "ওপেন ট্র্যাক",
  "notifications.fromNumber": "প্রেরকের নম্বর",
  "notifications.pushNotifications": "পুশ বিজ্ঞপ্তি",
  "notifications.enablePushNotifications": "পুশ বিজ্ঞপ্তি সক্রিয়",
  "notifications.quietHours": "শান্ত সময়",
  "notifications.enableQuietHours": "শান্ত সময় সক্রিয়",
  "notifications.startTime": "শুরুর সময়",
  "notifications.endTime": "শেষ সময়",
  "notifications.notificationTriggers": "বিজ্ঞপ্তি ট্রিগার",
  "notifications.notificationTemplates": "বিজ্ঞপ্তি টেমপ্লেট",
  "notifications.templateName": "টেমপ্লেটের নাম",
  "notifications.pushNotification": "পুশ বিজ্ঞপ্তি",
  "notifications.inapp": "ইন-অ্যাপ",
  "notifications.subjectLine": "বিষয় লাইন",
  "notifications.messageBody": "বার্তার মূল অংশ",
  "notifications.availableVariables": "উপলব্ধ ভ্যারিয়েবল:",
  "notifications.saveTemplate": "টেমপ্লেট সংরক্ষণ",
  "notifications.emailTemplates": "ইমেইল টেমপ্লেট",
  "notifications.lastModified": "সর্বশেষ পরিবর্তিত",
  "notifications.templatePreview": "টেমপ্লেট প্রিভিউ",
  "notifications.useVariablenameForDynamicContent": "ডায়নামিক কন্টেন্টের জন্য {{variable_name}} ব্যবহার করুন",
  "staff.attendanceTracking": "উপস্থিতি ট্র্যাকিং",
  "staff.presentToday": "আজ উপস্থিত",
  "staff.absentToday": "আজ অনুপস্থিত",
  "staff.lateToday": "আজ বিলম্বিত",
  "staff.attendanceRate": "উপস্থিতির হার",
  "staff.todaysAttendance": "আজকের উপস্থিতি",
  "staff.checkIn": "চেক ইন",
  "staff.checkOut": "চেক আউট",
  "staff.notClocked": "ক্লক করা হয়নি",
  "staff.clockIn": "ক্লক ইন",
  "staff.clockOut": "ক্লক আউট",
  "staff.startDate": "শুরুর তারিখ",
  "staff.endDate": "শেষ তারিখ",
  "staff.staffMember": "কর্মী সদস্য",
  "staff.lateMin": "বিলম্ব (মিনিট)",
  "staff.earlyLeaveMin": "আগে চলে যাওয়া (মিনিট)",
  "staff.notesOptional": "নোট (ঐচ্ছিক)",
  "staff.clockedClockactionSuccessfullyForSelectedstaffforclockfirstname": "${selectedStaffForClock.firstName} এর জন্য ${clockAction} সফলভাবে ক্লক করা হয়েছে",
  "staff.exportedAttendanceAsFormattouppercase": "উপস্থিতি ${format.toUpperCase()} হিসেবে এক্সপোর্ট করা হয়েছে",
  "staff.internalCommunication": "অভ্যন্তরীণ যোগাযোগ",
  "staff.newChannel": "নতুন চ্যানেল",
  "staff.channelName": "চ্যানেলের নাম",
  "staff.activechannelmemberslengthMembers": "{activeChannel.members.length} সদস্য",
  "staff.staffScheduling": "কর্মী শিডিউলিং",
  "staff.scheduledToday": "আজ শিডিউল করা",
  "staff.startTime": "শুরুর সময়",
  "staff.endTime": "শেষ সময়",
  "staff.todaysAttendance_1": "আজকের উপস্থিতি",
  "staff.checkIn_1": "চেক ইন",
  "staff.checkOut_1": "চেক আউট",
  "staff.checkedOut": "চেক আউট হয়েছে",
  "staff.checkedIn": "চেক ইন হয়েছে",
  "staff.notCheckedIn": "চেক ইন হয়নি",
  "staff.clockIn_1": "ক্লক ইন",
  "staff.clockOut_1": "ক্লক আউট",
  "staff.staffMember_1": "কর্মী সদস্য",
  "staff.shiftslengthShiftsScheduled": "{shifts.length}টি শিফট শিডিউল করা",
  "staff.staffSkills": "কর্মী দক্ষতা",
  "staff.staffMembers": "কর্মী সদস্য",
  "staff.avgProficiency": "গড় দক্ষতা",
  "staff.staffMember_2": "কর্মী সদস্য",
  "staff.certifiedOnly": "শুধুমাত্র সার্টিফাইড",
  "staff.skill": "দক্ষতা",
  "staff.skillsOverviewByCategory": "বিভাগ অনুসারে দক্ষতা সারসংক্ষেপ",
  "staff.proficiencyLevel": "দক্ষতার স্তর",
  "staff.certificationDate": "সার্টিফিকেশনের তারিখ",
  "staff.staffMember_3": "কর্মী সদস্য *",
  "staff.skillName": "দক্ষতার নাম *",
  "staff.taskAssignment": "কাজ বরাদ্দ",
  "staff.newTask": "নতুন কাজ",
  "staff.inProgress": "চলমান",
  "staff.myTasks": "আমার কাজ",
  "staff.assignedTo": "যাকে বরাদ্দ",
  "staff.dueDate": "নির্ধারিত তারিখ",
  "staff.assignTo": "বরাদ্দ করুন",
  "staff.scheduledDate": "নির্ধারিত তারিখ",
  "staff.title": "শিরোনাম *",
  "integrations.paymentGateways": "পেমেন্ট গেটওয়ে",
  "integrations.feesLimits": "ফি ও সীমা",
  "integrations.gatewayName": "গেটওয়ের নাম",
  "integrations.apiKeyClientId": "API কী / ক্লায়েন্ট আইডি",
  "integrations.secretKey": "গোপন কী",
  "integrations.webhookSecret": "ওয়েবহুক গোপন কী",
  "integrations.processingFee": "প্রসেসিং ফি",
  "integrations.setPrimary": "প্রাথমিক হিসেবে সেট",
  "integrations.failoverProtection": "ফেইলওভার সুরক্ষা",
  "integrations.myPaymentGateway": "আমার পেমেন্ট গেটওয়ে",
  "integrations.usdEurGbp": "USD, EUR, GBP",
  "integrations.gatewaynameConnectionTestInitiatedVerifyInGatewayDashboard": "${gateway.name} কনেকশন পরীক্ষা শুরু হয়েছে। গেটওয়ে ড্যাশবোর্ডে যাচাই করুন।",
  "integrations.paymentGateways_1": "পেমেন্ট গেটওয়ে",
  "integrations.gatewayName_1": "গেটওয়ের নাম",
  "integrations.apiKey": "API কী",
  "integrations.secretKey_1": "গোপন কী",
  "integrations.webhookSecret_1": "ওয়েবহুক গোপন কী",
  "integrations.saveGateway": "গেটওয়ে সংরক্ষণ",
  "integrations.successRate": "সফলতার হার",
  "integrations.processingFee_1": "প্রসেসিং ফি",
  "integrations.testConnection": "কনেকশন পরীক্ষা",
  "integrations.apiKey_1": "API কী:",
  "integrations.myPaymentGateway_1": "আমার পেমেন্ট গেটওয়ে",
  "integrations.pkxxxxx": "pk_xxxxx",
  "integrations.skxxxxx": "sk_xxxxx",
  "integrations.connectionTestInitiatedForTestgatewaynameVerifyInGatewayDashboard": "${testGateway.name} এর জন্য কনেকশন পরীক্ষা শুরু হয়েছে। গেটওয়ে ড্যাশবোর্ডে যাচাই করুন।",
  "integrations.paymentGateways_2": "পেমেন্ট গেটওয়ে",
  "integrations.gatewayName_2": "গেটওয়ের নাম",
  "integrations.apiKey_2": "API কী",
  "integrations.secretKey_2": "গোপন কী",
  "integrations.saveGateway_1": "গেটওয়ে সংরক্ষণ",
  "integrations.processingFee_2": "প্রসেসিং ফি",
  "integrations.myPaymentGateway_2": "আমার পেমেন্ট গেটওয়ে",
  "integrations.pkxxxxx_1": "pk_xxxxx",
  "integrations.skxxxxx_1": "sk_xxxxx",
  "integrations.systemName": "সিস্টেমের নাম",
  "integrations.apiKey_3": "API কী",
  "integrations.syncMenu": "মেনু সিঙ্ক",
  "integrations.syncOrders": "অর্ডার সিঙ্ক",
  "integrations.syncPayments": "পেমেন্ট সিঙ্ক",
  "integrations.syncGuests": "অতিথি সিঙ্ক",
  "integrations.saveSystem": "সিস্টেম সংরক্ষণ",
  "integrations.connectedSystems": "সংযুক্ত সিস্টেম",
  "integrations.menuItems": "মেনু আইটেম",
  "integrations.lastSync": "সর্বশেষ সিঙ্ক",
  "integrations.syncNow": "এখন সিঙ্ক",
  "integrations.thirdpartyApis": "তৃতীয় পক্ষের API",
  "integrations.apiKey_4": "API কী",
  "integrations.rateLimit": "হার সীমা",
  "integrations.perMinute": "প্রতি মিনিটে",
  "integrations.perHour": "প্রতি ঘণ্টায়",
  "integrations.perDay": "প্রতিদিন",
  "integrations.perMonth": "প্রতি মাসে",
  "integrations.apiKeyCopiedToClipboard": "API কী ক্লিপবোর্ডে কপি হয়েছে",
  "integrations.wifiGateways": "WiFi গেটওয়ে",
  "integrations.gatewayName_3": "গেটওয়ের নাম",
  "integrations.controllerType": "কন্ট্রোলারের ধরন",
  "integrations.apiKey_5": "API কী",
  "integrations.syncIntervalMin": "সিঙ্ক বিরতি (মিনিট)",
  "integrations.autoSync": "স্বয়ংক্রিয় সিঙ্ক",
  "integrations.saveGateway_2": "গেটওয়ে সংরক্ষণ",
  "integrations.connectedGateways": "সংযুক্ত গেটওয়ে",
  "integrations.bandwidthUsage": "ব্যান্ডউইথ ব্যবহার",
  "integrations.accessPoints": "অ্যাক্সেস পয়েন্ট",
  "integrations.syncNow_1": "এখন সিঙ্ক",
  "integrations.myWifiController": "আমার WiFi কন্ট্রোলার",
  "integrations.serverRoomBuildingA": "সার্ভার রুম, বিল্ডিং এ",
  "parking.noPropertySelected": "কোনো সম্পত্তি নির্বাচিত নয়",
  "parking.parkingBilling": "পার্কিং বিলিং",
  "parking.checkin": "চেক-ইন",
  "parking.averageFee": "গড় ফি",
  "parking.thisMonth": "এই মাসে",
  "parking.clearFilters": "ফিল্টার মুছুন",
  "parking.checkInVehicle": "যানবাহন চেক ইন",
  "parking.entryTime": "প্রবেশের সময়",
  "parking.exitTime": "বের হওয়ার সময়",
  "parking.parkingFee": "পার্কিং ফি",
  "parking.hourlyRate": "প্রতি ঘণ্টার হার",
  "parking.dailyMax": "দৈনিক সর্বোচ্চ",
  "parking.paymentPending": "পেমেন্ট অপেক্ষমান",
  "parking.paymentComplete": "পেমেন্ট সম্পন্ন",
  "parking.recordPayment": "পেমেন্ট রেকর্ড",
  "parking.amountDue": "দেনার পরিমাণ",
  "parking.paymentMethod": "পেমেন্ট পদ্ধতি",
  "parking.newVehicleCheckin": "নতুন যানবাহন চেক-ইন",
  "parking.parkingSlotOptional": "পার্কিং স্লট (ঐচ্ছিক)",
  "parking.dailyMaxRate": "দৈনিক সর্বোচ্চ হার",
  "parking.recordExit": "বের হওয়া রেকর্ড",
  "parking.licensePlate": "লাইসেন্স প্লেট *",
  "parking.noPropertySelected_1": "কোনো সম্পত্তি নির্বাচিত নয়",
  "parking.parkingSlots": "পার্কিং স্লট",
  "parking.slotNumber": "স্লট নম্বর",
  "parking.slotType": "স্লটের ধরন",
  "parking.vehicleType": "যানবাহনের ধরন",
  "parking.chargerType": "চার্জারের ধরন",
  "parking.parkedVehicle": "পার্ক করা যানবাহন",
  "parking.setAvailable": "উপলব্ধ হিসেবে সেট",
  "parking.noPropertySelected_2": "কোনো সম্পত্তি নির্বাচিত নয়",
  "parking.vehicleTracking": "যানবাহন ট্র্যাকিং",
  "parking.logEntry": "লগ এন্ট্রি",
  "parking.currentlyParked": "বর্তমানে পার্ক করা",
  "parking.exitedToday": "আজ বের হয়েছে",
  "parking.entryTime_1": "প্রবেশের সময়",
  "parking.logVehicleEntry": "যানবাহন প্রবেশ লগ",
  "parking.exitTime_1": "বের হওয়ার সময়",
  "parking.parkingFee_1": "পার্কিং ফি",
  "parking.paymentPending_1": "পেমেন্ট অপেক্ষমান",
  "parking.licensePlate_1": "লাইসেন্স প্লেট *",
  "bookings.bookingsTitle": "বুকিং",
  "bookings.validationError": "অনুগ্রহ করে সকল প্রয়োজনীয় ক্ষেত্র পূরণ করুন",
  "bookings.specialRequests": "বিশেষ অনুরোধ বা নোট...",
  "bookings.changeStatus": "অবস্থা পরিবর্তন",
  "bookings.bookingDetailsCopied": "বুকিং বিবরণ কপি হয়েছে",
  "bookings.bookingDataCopied": "বুকিং ডেটা ক্লিপবোর্ডে কপি হয়েছে।",
  "bookings.noBookingsToExport": "বর্তমান ভিউয়ে এক্সপোর্ট করার মতো কোনো বুকিং নেই।",
  "bookings.printView": "প্রিন্ট ভিউ",
  "bookings.openingPrintDialog": "প্রিন্ট ডায়ালগ খোলা হচ্ছে...",
  "bookings.useCalendarForDates": "এই বুকিংয়ের জন্য নতুন চেক-ইন/চেক-আউট তারিখ নির্বাচন করতে ক্যালেন্ডার ব্যবহার করুন।",
  "bookings.calendarTitle": "বুকিং ক্যালেন্ডার",
  "bookings.wifiAccessCreated": "WiFi অ্যাক্সেস তৈরি হয়েছে",
  "bookings.wifiProvisioningSkipped": "WiFi প্রভিশনিং বাদ দেওয়া হয়েছে",
  "bookings.wifiUserExists": "WiFi ব্যবহারকারী বিদ্যমান",
  "bookings.calendarListTitle": "বুকিং ক্যালেন্ডার তালিকা",
  "bookings.conflictsTitle": "বুকিং সংঘাত",
  "bookings.resolveConflict": "এই বুকিং সংঘাত কীভাবে সমাধান করবেন তা নির্বাচন করুন",
  "bookings.pleaseSelectResolution": "অনুগ্রহ করে একটি সমাধান পদ্ধতি নির্বাচন করুন",
  "bookings.pleaseSelectTargetRoom": "অনুগ্রহ করে একটি লক্ষ্য কক্ষ নির্বাচন করুন",
  "bookings.groupBookingsTitle": "গ্রুপ বুকিং",
  "bookings.groupDetails": "গ্রুপ বুকিং বিবরণ এবং সম্পর্কিত রিজার্ভেশন",
  "bookings.groupName": "গ্রুপের নাম",
  "bookings.groupNamePlaceholder": "কর্পোরেট রিট্রিট ২০২৪",
  "bookings.groupDescription": "গ্রুপের বিবরণ...",
  "bookings.contactPerson": "যোগাযোগের ব্যক্তি",
  "bookings.contactEmail": "যোগাযোগের ইমেইল",
  "bookings.contactPhone": "যোগাযোগের ফোন",
  "bookings.pleaseEnterGuestName": "অনুগ্রহ করে অতিথির প্রথম ও শেষ নাম লিখুন",
  "bookings.pleaseFillRequired": "অনুগ্রহ করে সকল প্রয়োজনীয় ক্ষেত্র পূরণ করুন",
  "bookings.pleaseSelectGuest": "অনুগ্রহ করে বুকিংয়ের জন্য একজন অতিথি নির্বাচন করুন",
  "bookings.pleaseSelectRoom": "অনুগ্রহ করে বুক করতে কমপক্ষে একটি কক্ষ নির্বাচন করুন",
  "bookings.additionalNotes": "অতিরিক্ত নোট...",
  "bookings.moreActions": "আরও কার্যকলাপ",
  "bookings.waitlistTitle": "ওয়েটলিস্ট",
  "bookings.waitlistEntryRemoved": "ওয়েটলিস্ট এন্ট্রি সরানো হয়েছে",
  "bookings.guestNameRequired": "অতিথির প্রথম ও শেষ নাম আবশ্যক",
  "bookings.actionType": "ক্রিয়ার ধরন",
  "bookings.noShowTitle": "নো-শো অটোমেশন",
  "bookings.noShowConfirmDesc": "এটি চেক-ইন ডেডলাইন পার হওয়া সকল নিশ্চিত বুকিং স্ক্যান করবে এবং সেগুলোকে নো-শো হিসেবে প্রক্রিয়া করবে। এই ক্রিয়া পূর্বাবস্থায় ফেরানো যাবে না।",
  "iot.lastSeen": "সর্বশেষ দেখা",
  "iot.unlockDoor": "দরজা আনলক",
  "iot.deviceName": "ডিভাইসের নাম",
  "iot.deviceType": "ডিভাইসের ধরন",
  "iot.smartLock": "স্মার্ট লক",
  "iot.motorizedBlinds": "মোটরাইজড ব্লাইন্ডস",
  "iot.airConditioner": "এয়ার কন্ডিশনার",
  "iot.zwave": "Z-Wave",
  "iot.lockDoor": "দরজা লক",
  "iot.turnOff": "বন্ধ করুন",
  "iot.turnOn": "চালু করুন",
  "iot.energyDashboard": "শক্তি ড্যাশবোর্ড",
  "iot.carbonFootprint": "কার্বন ফুটপ্রিন্ট",
  "iot.costSavings": "খরচ সঞ্চয়",
  "iot.carbonReduction": "কার্বন হ্রাস",
  "iot.consumptionTrends": "খরচ প্রবণতা",
  "iot.costBreakdown": "খরচ বিবরণ",
  "iot.byProperty": "সম্পত্তি অনুসারে",
  "iot.dailyEnergyConsumption": "দৈনিক শক্তি খরচ",
  "iot.carbonFootprintTrend": "কার্বন ফুটপ্রিন্ট প্রবণতা",
  "iot.dailyCostTrend": "দৈনিক খরচ প্রবণতা",
  "iot.electricityKwh": "বিদ্যুৎ (kWh)",
  "iot.propertyComparison": "সম্পত্তি তুলনা",
  "iot.dailyAverages": "দৈনিক গড়",
  "iot.avgElectricity": "গড় বিদ্যুৎ",
  "iot.avgGas": "গড় গ্যাস",
  "iot.avgWater": "গড় পানি",
  "iot.avgDailyCost": "গড় দৈনিক খরচ",
  "iot.gasM": "গ্যাস (m³)",
  "iot.waterM": "পানি (m³)",
  "iot.fanSpeed": "ফ্যান স্পিড",
  "iot.roomControls": "কক্ষ নিয়ন্ত্রণ",
  "iot.sensorNoControls": "সেন্সর - নিয়ন্ত্রণ নেই",
  "iot.confirmDoorUnlock": "দরজা আনলক নিশ্চিত",
  "iot.unlockDoor_1": "দরজা আনলক",
  "iot.quickActions": "দ্রুত ক্রিয়া",
  "iot.morningMode": "সকালের মোড",
  "iot.nightMode": "রাতের মোড",
  "help.watchVideo": "ভিডিও দেখুন",
  "help.relatedArticles": "সম্পর্কিত নিবন্ধ",
  "help.contactSupport": "সহায়তার সাথে যোগাযোগ",
  "help.knowledgeBase": "জ্ঞানভাণ্ডার",
  "help.newArticle": "নতুন নিবন্ধ",
  "help.newestFirst": "নতুন আগে",
  "help.oldestFirst": "পুরনো আগে",
  "help.mostViewed": "সবচেয়ে বেশি দেখা",
  "help.mostHelpful": "সবচেয়ে সহায়ক",
  "help.clearFilters": "ফিল্টার মুছুন",
  "help.gettingStarted": "শুরু করা",
  "help.knowledgeBase_1": "জ্ঞানভাণ্ডার",
  "help.helpCenter": "সাহায্য কেন্দ্র",
  "help.popularArticles": "জনপ্রিয় নিবন্ধ",
  "help.frequentlyAskedQuestions": "সচরাচর জিজ্ঞাসা",
  "help.stillNeedHelp": "এখনও সাহায্য প্রয়োজন?",
  "help.contactSupport_1": "সহায়তার সাথে যোগাযোগ",
  "help.submitARequest": "একটি অনুরোধ জমা দিন",
  "help.submitRequest": "অনুরোধ জমা",
  "help.helpCenter_1": "সাহায্য কেন্দ্র",
  "help.newArticle_1": "নতুন নিবন্ধ",
  "help.contentMarkdown": "কন্টেন্ট (Markdown)",
  "help.articleurlslug_1": "article-url-slug",
  "help.restartTutorial": "টিউটোরিয়াল পুনরায় শুরু",
  "help.startTutorial": "টিউটোরিয়াল শুরু",
  "help.skipTutorial": "টিউটোরিয়াল এড়িয়ে যান",
  "help.tutorialProgress": "টিউটোরিয়াল অগ্রগতি",
  "help.yesReset": "হ্যাঁ, রিসেট",
  "help.resetAllProgress": "সকল অগ্রগতি রিসেট",
  "help.tutorialsAvailable": "টিউটোরিয়াল উপলব্ধ",
  "help.inProgress": "চলমান",
  "help.overallProgress": "সামগ্রিক অগ্রগতি",
  "help.availableTutorials": "উপলব্ধ টিউটোরিয়াল",
  "help.startTutorial_1": "টিউটোরিয়াল শুরু",
  "help.reviewTutorial": "টিউটোরিয়াল পুনরায় দেখুন",
  "portal.inProgress": "চলমান",
  "portal.uploadFirstDocument": "প্রথম ডকুমেন্ট আপলোড",
  "portal.uploadAnotherDocument": "আরেকটি ডকুমেন্ট আপলোড",
  "portal.uploadDocument": "ডকুমেন্ট আপলোড",
  "portal.egPassportJohnDoe": "যেমন, পাসপোর্ট - জন ডো",
  "portal.documentType": "ডকুমেন্টের ধরন *",
  "portal.documentName": "ডকুমেন্টের নাম *",
  "portal.documentFile": "ডকুমেন্ট ফাইল *",
  "portal.termsSignature": "শর্তাবলী ও স্বাক্ষর",
  "portal.termsAccepted": "শর্তাবলী গৃহীত",
  "portal.yourSignature": "আপনার স্বাক্ষর",
  "portal.signAcceptTerms": "স্বাক্ষর ও শর্তাবলী গ্রহণ",
  "portal.alternatePhone": "বিকল্প ফোন",
  "portal.streetAddress": "রাস্তার ঠিকানা",
  "portal.postalCode": "পোস্টাল কোড",
  "portal.newYork": "নিউ ইয়র্ক",
  "portal.firstName": "প্রথম নাম *",
  "portal.lastName": "শেষ নাম *",
  "portal.phoneNumber": "ফোন নম্বর *",
  "portal.paymentSummary": "পেমেন্ট সারসংক্ষেপ",
  "portal.balanceDue": "বকেয়া",
  "portal.taxesFees": "কর ও ফি",
  "portal.amountPaid": "পরিশোধিত পরিমাণ",
  "portal.payNow": "এখন পরিশোধ",
  "portal.paymentComplete": "পেমেন্ট সম্পন্ন",
  "portal.floorPreference": "ফ্লোর পছন্দ",
  "portal.bedType": "বিছানার ধরন",
  "portal.pillowType": "বালিশের ধরন",
  "portal.additionalRoomPreferences": "অতিরিক্ত কক্ষ পছন্দ",
  "portal.dietaryRequirements": "খাদ্যাভ্যাস প্রয়োজনীয়তা",
  "portal.roomAmenities": "কক্ষ সুবিধা",
  "portal.preferredLanguage": "পছন্দের ভাষা",
  "portal.notificationPreferences": "বিজ্ঞপ্তি পছন্দ",
  "ads.adCampaigns": "বিজ্ঞাপন ক্যাম্পেইন",
  "ads.newCampaign": "নতুন ক্যাম্পেইন",
  "ads.budgetUsed": "ব্যবহৃত বাজেট",
  "ads.basicInformation": "প্রাথমিক তথ্য",
  "ads.campaignName": "ক্যাম্পেইনের নাম",
  "ads.campaignType": "ক্যাম্পেইনের ধরন",
  "ads.budgetBidding": "বাজেট ও বিডিং",
  "ads.budgetType": "বাজেটের ধরন",
  "ads.bidStrategy": "বিড কৌশল",
  "ads.bidAmountOptional": "বিডের পরিমাণ (ঐচ্ছিক)",
  "ads.startDate": "শুরুর তারিখ",
  "ads.endDate": "শেষ তারিখ",
  "ads.performanceTrend": "পারফরম্যান্স প্রবণতা",
  "ads.bidStrategy_1": "বিড কৌশল",
  "ads.autoBidding": "স্বয়ংক্রিয় বিডিং",
  "ads.baseBidModifier": "বেস বিড মডিফায়ার",
  "ads.lastPriceFeed": "সর্বশেষ মূল্য ফিড",
  "ads.lastBookingFeed": "সর্বশেষ বুকিং ফিড",
  "ads.feedFormat": "ফিড ফরম্যাট",
  "ads.connectionMode": "কনেকশন মোড",
  "ads.performanceTracking": "পারফরম্যান্স ট্র্যাকিং",
  "ads.convRate": "রূপান্তর হার",
  "ads.performanceTrend_1": "পারফরম্যান্স প্রবণতা",
  "ads.conversionTrend": "রূপান্তর প্রবণতা",
  "ads.dailyBreakdown": "দৈনিক বিবরণ",
  "ads.netProfit": "নিট লাভ",
  "ads.channelComparison": "চ্যানেল তুলনা",
  "ads.trendInsights": "প্রবণতা অন্তর্দৃষ্টি",
  "ads.profitTrend": "লাভ প্রবণতা",
  "chain.primaryColor": "প্রাথমিক রং",
  "chain.secondaryColor": "গৌণ রং",
  "chain.grandHotels": "গ্র্যান্ড হোটেলস",
  "chain.brandName": "ব্র্যান্ডের নাম *",
  "chain.brandCode": "ব্র্যান্ড কোড *",
  "chain.chainDashboard": "চেইন ড্যাশবোর্ড",
  "chain.occupancyRate": "দখল হার",
  "chain.monthlyBookings": "মাসিক বুকিং",
  "chain.monthlyRevenue": "মাসিক আয়",
  "chain.todayapossArrivals": "আজকের আগমন",
  "chain.todayapossDepartures": "আজকের প্রস্থান",
  "chain.propertyPerformance": "সম্পত্তি পারফরম্যান্স",
  "chain.brandDistribution": "ব্র্যান্ড বণ্টন",
  "chain.propertiesPerformance": "সম্পত্তি পারফরম্যান্স",
  "chain.thisWeek": "এই সপ্তাহে",
  "chain.thisMonth": "এই মাসে",
  "chain.thisYear": "এই বছরে",
  "chain.avgOccupancy": "গড় দখল",
  "chain.byProperty": "সম্পত্তি অনুসারে",
  "chain.byBrand": "ব্র্যান্ড অনুসারে",
  "chain.bookingSources": "বুকিং উৎস",
  "chain.guestDemographics": "অতিথি জনসংখ্যাতাত্ত্বিক",
  "chain.propertyPerformanceComparison": "সম্পত্তি পারফরম্যান্স তুলনা",
  "chain.revenueTrend": "আয় প্রবণতা",
  "chain.propertyComparison": "সম্পত্তি তুলনা",
  "gdpr.privacyNotice": "গোপনীয়তা বিজ্ঞপ্তি",
  "gdpr.acceptAll": "সব গ্রহণ",
  "gdpr.rejectOptional": "ঐচ্ছিক প্রত্যাখ্যান",
  "gdpr.privacyPolicy": "গোপনীয়তা নীতি",
  "gdpr.declineOptional": "ঐচ্ছিক প্রত্যাখ্যান",
  "gdpr.requestTypes": "অনুরোধের ধরন",
  "gdpr.exportData": "ডেটা এক্সপোর্ট",
  "gdpr.exportGuestData": "অতিথি ডেটা এক্সপোর্ট করবেন?",
  "gdpr.confirmExport": "এক্সপোর্ট নিশ্চিত",
  "gdpr.anonymizeData": "ডেটা বেনামীকরণ",
  "gdpr.anonymizeGuestData": "অতিথি ডেটা বেনামীকরণ করবেন?",
  "gdpr.confirmAnonymization": "বেনামীকরণ নিশ্চিত",
  "gdpr.softDelete": "সফট ডিলিট",
  "gdpr.softDeleteGuestData": "অতিথি ডেটা সফট ডিলিট করবেন?",
  "gdpr.confirmSoftDelete": "সফট ডিলিট নিশ্চিত",
  "gdpr.hardDelete": "হার্ড ডিলিট",
  "gdpr.permanentlyDeleteGuestData": "অতিথি ডেটা স্থায়ীভাবে মুছবেন?",
  "gdpr.confirmPermanentDelete": "স্থায়ী মুছে ফেলা নিশ্চিত",
  "gdpr.recordConsent": "সম্মতি রেকর্ড",
  "webhooks.webhookDelivery": "ওয়েবহুক বিতরণ",
  "webhooks.deliveredAt": "বিতরণের সময়",
  "webhooks.webhookEndpoints": "ওয়েবহুক এন্ডপয়েন্ট",
  "webhooks.secretKey": "গোপন কী",
  "webhooks.saveEndpoint": "এন্ডপয়েন্ট সংরক্ষণ",
  "webhooks.avgSuccessRate": "গড় সফলতার হার",
  "webhooks.eventTypes": "ইভেন্টের ধরন",
  "webhooks.successRate": "সফলতার হার",
  "webhooks.lastTriggered": "সর্বশেষ ট্রিগার",
  "webhooks.secret": "গোপন",
  "webhooks.subscribedEvents": "সাবস্ক্রাইব করা ইভেন্ট",
  "webhooks.myWebhook": "আমার ওয়েবহুক",
  "webhooks.secretCopiedToClipboard": "গোপন কী ক্লিপবোর্ডে কপি হয়েছে",
  "webhooks.retryQueue": "পুনরায় চেষ্টার সারি",
  "webhooks.pendingRetry": "পুনরায় চেষ্টা অপেক্ষমান",
  "webhooks.failedMaxAttempts": "ব্যর্থ (সর্বোচ্চ প্রচেষ্টা)",
  "webhooks.nextRetry": "পরবর্তী পুনরায় চেষ্টা",
  "webhooks.lastError": "সর্বশেষ ত্রুটি",
  "profile.personalInformation": "ব্যক্তিগত তথ্য",
  "profile.firstName": "প্রথম নাম",
  "profile.lastName": "শেষ নাম",
  "profile.jobTitle": "পদবি",
  "profile.newPassword": "নতুন পাসওয়ার্ড",
  "profile.confirmPassword": "পাসওয়ার্ড নিশ্চিত",
  "profile.twofactorAuthentication": "দুই-ফ্যাক্টর প্রমাণীকরণ",
  "profile.authenticatorApp": "অথেনটিকেটর অ্যাপ",
  "profile.emailNotifications": "ইমেইল বিজ্ঞপ্তি",
  "profile.pushNotifications": "পুশ বিজ্ঞপ্তি",
  "profile.marketingEmails": "মার্কেটিং ইমেইল",
  "profile.darkMode": "ডার্ক মোড",
  "profile.compactMode": "কমপ্যাক্ট মোড",
  "profile.dateFormat": "তারিখ ফরম্যাট",
  "communication.changeStatus": "অবস্থা পরিবর্তন",
  "communication.assignTo": "বরাদ্দ করুন",
  "communication.quickReplies": "দ্রুত উত্তর:",
  "communication.messageTemplates": "বার্তা টেমপ্লেট",
  "communication.insertLink": "লিংক সন্নিবেশ",
  "communication.bulletList": "বুলেট তালিকা",
  "communication.numberedList": "সংখ্যাযুক্ত তালিকা",
  "communication.attachFile": "ফাইল সংযুক্ত",
  "audit.securityEvents": "নিরাপত্তা ইভেন্ট",
  "audit.failedLogins": "ব্যর্থ লগইন",
  "audit.activityLog": "কার্যকলাপ লগ",
  "audit.entityType": "এনটিটির ধরন",
  "audit.userAgent": "ইউজার এজেন্ট",
  "audit.oldValue": "পুরনো মান",
  "audit.newValue": "নতুন মান",
  "pms.propertyName": "সম্পত্তির নাম",
  "pms.propertyNamePlaceholder": "গ্র্যান্ড হোটেল",
  "pms.phonePlaceholder": "+91 98765 43210",
  "pms.taxComponent": "কর উপাদান",
  "pms.taxId": "কর আইডি",
  "pms.taxIdPlaceholder": "GSTIN বা কর আইডি",
  "pms.taxRate": "হার (%)",
  "pms.generalInfo": "সাধারণ তথ্য",
  "pms.contactInfo": "যোগাযোগের তথ্য",
  "pms.validationError": "যাচাইকরণ ত্রুটি",
  "pms.requiredFields": "নাম, স্লাগ, ঠিকানা, শহর এবং দেশ আবশ্যক।",
  "pms.copySlug": "স্লাগ কপি",
  "pms.moreOptions": "আরও বিকল্প",
  "pms.exportComplete": "এক্সপোর্ট সম্পন্ন",
  "pms.importFailed": "ইমপোর্ট ব্যর্থ",
  "pms.invalidFileFormat": "অবৈধ ফাইল ফরম্যাট। অনুগ্রহ করে ফাইলের কাঠামো পরীক্ষা করুন।",
  "pms.roomsTitle": "কক্ষসমূহ",
  "pms.roomNumber": "কক্ষ নম্বর",
  "pms.roomName": "কক্ষের নাম",
  "pms.roomNamePlaceholder": "হানিমুন স্যুট",
  "pms.importRooms": "CSV ফাইল থেকে একাধিক কক্ষ ইমপোর্ট করুন",
  "pms.roomStatusUpdated": "কক্ষের অবস্থা আপডেট হয়েছে",
  "pms.pleaseFillRequired": "অনুগ্রহ করে সকল প্রয়োজনীয় ক্ষেত্র পূরণ করুন",
  "pms.pleaseSelectFileAndProperty": "অনুগ্রহ করে একটি ফাইল এবং সম্পত্তি নির্বাচন করুন",
  "pms.gridView": "গ্রিড ভিউ",
  "pms.listView": "লিস্ট ভিউ",
  "pms.roomTypesTitle": "কক্ষের ধরন",
  "pms.typeName": "ধরনের নাম",
  "pms.typeNamePlaceholder": "ডিলাক্স রুম",
  "pms.basePrice": "ভিত্তি মূল্য",
  "pms.maxOccupancy": "সর্বোচ্চ দখলক্ষমতা",
  "pms.defaultProperty": "ডিফল্ট (AAA সেটিং থেকে)",
  "pms.roomDescription": "কক্ষের বিবরণ...",
  "pms.amenities": "সুবিধাসমূহ",
  "pms.amenityName": "সুবিধার নাম",
  "pms.amenityCreated": "সুবিধা তৈরি হয়েছে",
  "pms.pleaseUseCsvOrJson": "অনুগ্রহ করে CSV বা JSON ফাইল ব্যবহার করুন।",
  "pms.propertyRequired": "সম্পত্তি, নাম, কোড এবং ভিত্তি মূল্য আবশ্যক।",
  "pms.validationPriceError": "সর্বোচ্চ প্রাপ্তবয়স্ক >= ১ হতে হবে এবং ভিত্তি মূল্য > 0 হতে হবে।",
  "pms.inventoryTitle": "ইনভেন্টরি ক্যালেন্ডার",
  "pms.availableCount": "উপলব্ধ",
  "pms.closed": "বন্ধ",
  "pms.availabilityClosed": "এই তারিখের জন্য প্রাপ্যতা বন্ধ",
  "pms.previousMonth": "আগের মাস",
  "pms.nextMonth": "পরের মাস",
  "pms.availabilityTitle": "প্রাপ্যতা নিয়ন্ত্রণ",
  "pms.adjustAvailable": "এই তারিখের জন্য উপলব্ধ কক্ষের সংখ্যা সামঞ্জস্য করুন",
  "pms.availabilityExported": "প্রাপ্যতা CSV তে এক্সপোর্ট হয়েছে",
  "pms.lockingTitle": "ইনভেন্টরি লকিং",
  "pms.createLock": "একটি নির্দিষ্ট সময়ের জন্য কক্ষ প্রাপ্যতা ব্লক করুন",
  "pms.lockType": "লকের ধরন",
  "pms.reason": "কারণ",
  "pms.reasonPlaceholder": "সমস্যা বা প্রয়োজনীয় কাজ বর্ণনা করুন...",
  "pms.pleaseSelectRoom": "অনুগ্রহ করে একটি কক্ষ বা কক্ষের ধরন নির্বাচন করুন",
  "pms.unlockInventory": "ইনভেন্টরি আনলক",
  "pms.refreshLocks": "লক রিফ্রেশ",
  "pms.unlock": "আনলক",
  "pms.enableOverbooking": "ওভারবুকিং সক্রিয়",
  "pms.pricingTitle": "প্রাইসিং ম্যানেজার",
  "pms.ratePlanName": "রেট প্ল্যানের নাম",
  "pms.ratePlanDesc": "এই রেট প্ল্যান বর্ণনা করুন",
  "pms.ratePlanCode": "কোড",
  "pms.maxPrice": "সর্বোচ্চ মূল্য",
  "pms.seasonalLabel": "মৌসুমী মূল্য, সপ্তাহান্তের হার ইত্যাদি",
  "pms.priceOverride": "মূল্য ওভাররাইড",
  "pms.customPrice": "একটি নির্দিষ্ট তারিখের জন্য কাস্টম মূল্য সেট করুন",
  "pms.overrideLabel": "ছুটির হার, সপ্তাহান্তের মূল্য ইত্যাদি",
  "pms.noLimit": "কোনো সীমা নেই",
  "pms.roomType": "কক্ষের ধরন",
  "pms.property": "সম্পত্তি",
  "pms.configurePricing": "মূল্য এবং সীমাবদ্ধতা কনফিগার",
  "pms.ratePlanCreated": "রেট প্ল্যান তৈরি হয়েছে",
  "pms.ratePlanUpdated": "রেট প্ল্যান আপডেট হয়েছে",
  "pms.ratePlanDeleted": "রেট প্ল্যান মুছে ফেলা হয়েছে",
  "pms.priceOverrideRemoved": "মূল্য ওভাররাইড সরানো হয়েছে",
  "pms.revenueTitle": "আয় ড্যাশবোর্ড",
  "pms.avgOccupancy": "গড় দখল",
  "pms.avgDailyGuests": "প্রতিদিন গড় অতিথি",
  "pms.occupancyCardDesc": "গড় দখল শতাংশ",
  "pms.guestsCardDesc": "প্রতিদিন গড় অতিথি",
  "pms.bulkPriceTitle": "একসাথে মূল্য আপডেট",
  "pms.reviewChanges": "প্রয়োগ করার আগে মূল্য পরিবর্তনগুলো পর্যালোচনা করুন",
  "pms.adjustment": "সামঞ্জস্য (%)",
  "pms.adjustmentPlaceholder": "10 বা -10",
  "pms.minPrice": "সর্বনিম্ন মূল্য",
  "pms.bulkUpdateComplete": "একসাথে আপডেট সম্পন্ন",
  "pms.floorPlansTitle": "ফ্লোর প্ল্যান",
  "pms.floorPlanName": "ফ্লোর প্ল্যানের নাম",
  "pms.floorPlanNamePlaceholder": "যেমন, প্রথম তলার প্ল্যান",
  "pms.roomAlreadyOnPlan": "এই কক্ষটি ইতোমধ্যে ফ্লোর প্ল্যানে আছে",
  "pms.autoArranged": "স্বয়ংক্রিয়ভাবে সাজানো",
  "pms.exported": "এক্সপোর্ট হয়েছে",
  "pms.noFreePosition": "ক্যানভাসে কোনো ফাঁকা অবস্থান পাওয়া যায়নি",
  "pms.shifted": "স্থানান্তরিত",
  "pms.resetView": "ভিউ রিসেট",
  "pms.toggleGrid": "গ্রিড টগল",
  "pms.undo": "আনডু",
  "pms.redo": "রিডু",
  "pms.zoomIn": "জুম ইন",
  "pms.zoomOut": "জুম আউট",
  "pms.floorPlanExported": "ফ্লোর প্ল্যান PNG ছবি হিসেবে এক্সপোর্ট হয়েছে",
  "pms.alignLeft": "বামে সারিবদ্ধ",
  "pms.alignCenterH": "অনুভূমিকে কেন্দ্রে সারিবদ্ধ",
  "pms.alignTop": "উপরে সারিবদ্ধ",
  "pms.noSpaceOnCanvas": "ক্যানভাসে কোনো জায়গা নেই",
  "pms.confirmRemoval": "অপসারণ নিশ্চিত",
  "pms.floorPlanViewer": "ফ্লোর প্ল্যান ভিউয়ার",
  "pms.pricingRulesTitle": "রেট প্ল্যান ও মূল্য নির্ধারণ নিয়ম",
  "pms.addPricingRule": "একটি স্বয়ংক্রিয় মূল্য সামঞ্জস্য নিয়ম সেটআপ করুন",
  "pms.ratePlanCodePlaceholder": "যেমন, BAR",
  "pms.ratePlanNamePlaceholder": "যেমন, সর্বোত্তম প্রাপ্য হার",
  "pms.pricingRuleDesc": "এই মূল্য নিয়মটি বর্ণনা করুন",
  "pms.seasonLabel": "যেমন, ছুটি, ইভেন্ট, পিক সিজন",
  "pms.ruleNameLabel": "যেমন, সপ্তাহান্তের প্রিমিয়াম",
  "pms.enterPrice": "মূল্য লিখুন",
  "pms.enterValue": "মান লিখুন",
  "pms.unlimited": "আনলিমিটেড",
  "pms.noActiveRatePlan": "এই কক্ষের ধরনের জন্য কোনো সক্রিয় রেট প্ল্যান পাওয়া যায়নি",
  "pms.ruleCreated": "মূল্য নিয়ম তৈরি হয়েছে",
  "pms.ruleUpdated": "মূল্য নিয়ম আপডেট হয়েছে",
  "pms.ruleDeleted": "নিয়ম মুছে ফেলা হয়েছে",
  "pms.ruleDuplicated": "নিয়ম ডুপ্লিকেট হয়েছে",
  "pms.ruleStatusUpdated": "নিয়মের অবস্থা আপডেট হয়েছে",
  "pms.ruleActions": "নিয়ম কার্যকলাপ",
  "pms.ratePlanActions": "রেট প্ল্যান কার্যকলাপ",
  "pms.roomRateCalendarTitle": "কক্ষ হার ক্যালেন্ডার",
  "pms.setFixedRate": "একটি তারিখ পরিসরের জন্য নির্দিষ্ট হার সেট করুন",
  "pms.enterRateAmount": "হারের পরিমাণ লিখুন",
  "pms.rateUpdated": "হার আপডেট হয়েছে",
  "pms.invalidNumber": "অবৈধ সংখ্যা",
  "pms.startDateBeforeEnd": "শুরুর তারিখ শেষ তারিখের আগে হতে হবে",
  "pms.cancelEdit": "সম্পাদনা বাতিল",
  "pms.saveRate": "হার সংরক্ষণ",
  "pms.outOfOrderTitle": "কক্ষ বাইরে-অর্ডার",
  "pms.blockRoom": "রক্ষণাবেক্ষণের জন্য একটি কক্ষ সেবা থেকে বাইরে রাখুন",
  "pms.reasonLabel": "কারণ",
  "pms.blockCompleted": "ব্লক সম্পন্ন",
  "pms.blockCancelled": "ব্লক বাতিল",
  "pms.endDateAfterStart": "শেষ তারিখ শুরুর তারিখের পরে হতে হবে।",
  "pms.fillRequired": "সকল প্রয়োজনীয় ক্ষেত্র পূরণ করুন",
  "pms.failed": "ব্যর্থ",
  "pms.filterStatus": "অবস্থা ফিল্টার",
  "pms.costEstimate": "খরচ অনুমান",
  "pms.galleryTitle": "কক্ষ ইমেজ গ্যালারি",
  "pms.uploadPhotos": "কক্ষের ছবি আপলোড ও পরিচালনা করুন। পুনরায় সাজাতে টেনে আনুন। প্রথম ছবিটি প্রাথমিক ছবি।",
  "pms.setImagePrimary": "ছবি প্রাথমিক হিসেবে সেট হয়েছে (গ্যালারিতে প্রথম)",
  "pms.imageRemoved": "ছবি গ্যালারি থেকে সরানো হয়েছে",
  "pms.primaryUpdated": "প্রাথমিক ছবি আপডেট হয়েছে",
  "pms.imagesUploaded": "ছবি আপলোড হয়েছে",
  "pms.limitReached": "সীমায় পৌঁছেছে",
  "pms.someUploadsFailed": "কিছু আপলোড ব্যর্থ",
  "pms.uploadFailed": "আপলোড ব্যর্থ",
  "pms.pleaseTryDifferentFiles": "অনুগ্রহ করে ভিন্ন ফাইল দিয়ে আবার চেষ্টা করুন",
  "pms.fileTooLarge": "ফাইল খুব বড়",
  "pms.pleaseSelectSmallFile": "অনুগ্রহ করে 10MB এর নিচে একটি ফাইল নির্বাচন করুন।",
  "pms.closeLightbox": "লাইটবক্স বন্ধ",
  "pms.setAsPrimary": "প্রাথমিক ফটো হিসেবে সেট",
  "frontdesk.todaysArrivalsCount": "আজকের আগমন",
  "frontdesk.checkedIn": "চেক ইন হয়েছে",
  "frontdesk.checkInBtn": "চেক ইন",
  "frontdesk.roomType": "কক্ষের ধরন",
  "frontdesk.assignedRoom": "বরাদ্দকৃত কক্ষ",
  "frontdesk.roomsAvailable": "{count}টি কক্ষ উপলব্ধ",
  "frontdesk.driverLicense": "ড্রাইভার লাইসেন্স",
  "frontdesk.wifiCredentials": "WiFi প্রমাণপত্র",
  "frontdesk.validUntil": "প্রযোজ্য পর্যন্ত",
  "frontdesk.specialRequests": "বিশেষ অনুরোধ",
  "frontdesk.specialRequestsLabel": "বিশেষ অনুরোধ",
  "frontdesk.copiedToClipboard": "{label} ক্লিপবোর্ডে কপি হয়েছে",
  "frontdesk.couldNotCopy": "{label} কপি করা যায়নি",
  "frontdesk.validationError": "যাচাইকরণ ত্রুটি",
  "frontdesk.checkInSuccessMsg": "অতিথি কক্ষ {room}-এ চেক ইন করেছেন। WiFi প্রমাণপত্র প্রস্তুত।",
  "frontdesk.seaView": "সমুদ্রের দৃশ্য",
  "frontdesk.mountainView": "পাহাড়ের দৃশ্য",
  "frontdesk.markClean": "পরিষ্কার হিসেবে চিহ্নিত",
  "frontdesk.markAvailable": "উপলব্ধ হিসেবে চিহ্নিত",
  "frontdesk.checkOut": "চেক আউট",
  "frontdesk.quickActions": "দ্রুত ক্রিয়া",
  "frontdesk.todaysDeparturesCount": "আজকের প্রস্থান",
  "frontdesk.checkingOut": "চেক আউট হচ্ছে",
  "frontdesk.outstandingBalance": "বকেয়া",
  "frontdesk.outstandingBalanceAmount": "বকেয়া: {amount}",
  "frontdesk.checkOutBtn": "চেক আউট",
  "frontdesk.stayDuration": "অবস্থানের সময়কাল",
  "frontdesk.takePayment": "পেমেন্ট গ্রহণ",
  "frontdesk.paymentRecorded": "পেমেন্ট রেকর্ড হয়েছে",
  "frontdesk.paymentOf": "{amount} পেমেন্ট প্রক্রিয়া হয়েছে",
  "frontdesk.outstandingBalanceLabel": "বকেয়া",
  "frontdesk.paymentMethod": "পেমেন্ট পদ্ধতি",
  "frontdesk.referenceOptional": "রেফারেন্স (ঐচ্ছিক)",
  "frontdesk.recordPayment": "পেমেন্ট রেকর্ড",
  "frontdesk.guestCheckedOut": "অতিথি কক্ষ {room} থেকে চেক আউট করেছেন",
  "frontdesk.creditDebitCard": "ক্রেডিট/ডেবিট কার্ড",
  "frontdesk.bankTransfer": "ব্যাংক স্থানান্তর",
  "frontdesk.digitalWallet": "ডিজিটাল ওয়ালেট",
  "frontdesk.nightsLabel": "{count} রাত",
  "frontdesk.propertyAndRoom": "সম্পত্তি ও কক্ষ",
  "frontdesk.assignRoom": "কক্ষ বরাদ্দ",
  "frontdesk.guestInformation": "অতিথির তথ্য",
  "frontdesk.existingGuest": "বিদ্যমান অতিথি",
  "frontdesk.stateProvince": "রাজ্য / প্রদেশ / অঞ্চল",
  "frontdesk.guestName": "অতিথির নাম",
  "frontdesk.bookingSummary": "বুকিং সারসংক্ষেপ",
  "frontdesk.taxBreakdown": "কর বিবরণ",
  "frontdesk.serviceCharge": "সেবা চার্জ",
  "frontdesk.grandTotal": "সর্বমোট",
  "frontdesk.guestCreationFailed": "অতিথি তৈরি ব্যর্থ",
  "frontdesk.bookingCreated": "বুকিং তৈরি হয়েছে",
  "frontdesk.bookingFailed": "বুকিং ব্যর্থ",
  "frontdesk.roomGridTitle": "কক্ষ গ্রিড",
  "frontdesk.seaViewLegend": "সমুদ্রের দৃশ্য",
  "frontdesk.liveUpdate": "লাইভ আপডেট",
  "frontdesk.roomFeatures": "কক্ষের বৈশিষ্ট্য",
  "frontdesk.roomBookingInfo": "কক্ষ বুকিং তথ্য",
  "frontdesk.connectionError": "কনেকশন ত্রুটি",
  "frontdesk.roomStatusUpdated": "কক্ষের অবস্থা আপডেট হয়েছে",
  "frontdesk.roomStatusUpdatedMsg": "কক্ষ {id} এখন {status}",
  "frontdesk.roomAssignmentTitle": "কক্ষ বরাদ্দ",
  "frontdesk.unassignedBookings": "বরাদ্ধহীন বুকিং",
  "frontdesk.availableRooms": "উপলব্ধ কক্ষ",
  "frontdesk.arrivingToday": "আজ আসছেন",
  "frontdesk.compatibleRooms": "{count}টি সামঞ্জস্যপূর্ণ কক্ষ",
  "frontdesk.assignRoomTitle": "কক্ষ বরাদ্দ",
  "frontdesk.bookingInfo": "বুকিং তথ্য",
  "frontdesk.roomPreview": "কক্ষ প্রিভিউ",
  "frontdesk.roomAssignmentSuccess": "কক্ষ বরাদ্দ হয়েছে",
  "frontdesk.roomAssignmentSuccessMsg": "কক্ষ {room} বুকিং {code}-এ বরাদ্ধ হয়েছে",
  "frontdesk.allBookingsTab": "বরাদ্ধহীন বুকিং",
  "frontdesk.availableRoomsTab": "উপলব্ধ কক্ষ",
  "frontdesk.roomMoveTitle": "কক্ষ স্থানান্তর",
  "frontdesk.moveToRoom": "এই কক্ষে স্থানান্তর",
  "frontdesk.roomComparison": "কক্ষ তুলনা",
  "frontdesk.sameRate": "একই হার",
  "frontdesk.notesOptional": "নোট (ঐচ্ছিক)",
  "frontdesk.moveToRoomBtn": "কক্ষ {room}-এ স্থানান্তর",
  "frontdesk.moveHistoryTable.rateChange": "হার Δ",
  "frontdesk.confirmRoomMove": "কক্ষ স্থানান্তর নিশ্চিত",
  "frontdesk.rateChange": "হার পরিবর্তন",
  "frontdesk.roomMovedMsg": "অতিথি কক্ষ {room} ({roomType})-এ স্থানান্তরিত",
  "frontdesk.moveFailed": "স্থানান্তর ব্যর্থ",
  "frontdesk.confirmMove": "স্থানান্তর নিশ্চিত",
  "frontdesk.guestRequest": "অতিথি অনুরোধ",
  "frontdesk.maintenanceIssue": "রক্ষণাবেক্ষণ সমস্যা",
  "frontdesk.complimentaryUpgrade": "বিনামূল্যে আপগ্রেড",
  "frontdesk.availabilityIssue": "প্রাপ্যতা সমস্যা",
  "frontdesk.targetRoomStatus": "লক্ষ্য কক্ষের অবস্থা: {status}। হাউসকিপিং প্রয়োজন হতে পারে।",
  "frontdesk.registrationCardTitle": "রেজিস্ট্রেশন কার্ড",
  "frontdesk.fullName": "পূর্ণ নাম",
  "frontdesk.roomNumber": "কক্ষ নম্বর",
  "frontdesk.roomTypeLabel": "কক্ষের ধরন",
  "frontdesk.accompanyingGuests": "সাথী অতিথি",
  "frontdesk.vehicleInformation": "যানবাহনের তথ্য",
  "frontdesk.existingCard": "বিদ্যমান কার্ড",
  "frontdesk.cardNo": "কার্ড নম্বর",
  "frontdesk.termsAndConditions": "শর্তাবলী",
  "frontdesk.regeneratePrint": "পুনরায় তৈরি ও প্রিন্ট",
  "frontdesk.generatePrint": "তৈরি ও প্রিন্ট",
  "frontdesk.leisure": "অবকাশ / ছুটি",
  "frontdesk.business": "ব্যবসায়িক ভ্রমণ",
  "frontdesk.conference": "সম্মেলন / সভা",
  "frontdesk.medical": "চিকিৎসা সেবা",
  "frontdesk.transit": "ট্রানজিট / স্টপওভার",
  "frontdesk.termsRequired": "শর্তাবলী আবশ্যক",
  "frontdesk.registrationCardGenerated": "রেজিস্ট্রেশন কার্ড তৈরি হয়েছে",
  "frontdesk.expressCheckIn": "এক্সপ্রেস চেক-ইন",
  "frontdesk.findYourBooking": "আপনার বুকিং খুঁজুন",
  "frontdesk.findBooking": "বুকিং খুঁজুন",
  "frontdesk.confirmCheckIn": "নিশ্চিত ও চেক ইন",
  "frontdesk.detailsCorrect": "বিবরণ সঠিক",
  "frontdesk.checkingIn": "চেক ইন হচ্ছে...",
  "frontdesk.checkInNow": "এখন চেক ইন",
  "frontdesk.yourRoom": "আপনার কক্ষ",
  "frontdesk.wifiCredentialsTitle": "WiFi প্রমাণপত্র",
  "frontdesk.validUntilDate": "{date} পর্যন্ত বৈধ",
  "frontdesk.tryAgain": "পুনরায় চেষ্টা করুন",
  "frontdesk.startOver": "পুনরায় শুরু",
  "frontdesk.paymentComplete": "পেমেন্ট সম্পন্ন",
  "frontdesk.paymentIssue": "পেমেন্ট সমস্যা",
  "frontdesk.cardPayment": "কার্ড পেমেন্ট",
  "frontdesk.cashPayment": "নগদ পেমেন্ট",
  "frontdesk.cardNumber": "কার্ড নম্বর",
  "frontdesk.expiryDate": "মেয়াদ উত্তীর্ণের তারিখ",
  "frontdesk.pay": "{amount} পরিশোধ",
  "frontdesk.upiIdPlaceholder": "yourname@upi",
  "frontdesk.amountDue": "দেনার পরিমাণ",
  "frontdesk.confirmCashPayment": "নগদ পেমেন্ট নিশ্চিত",
  "frontdesk.processingPayment": "পেমেন্ট প্রক্রিয়া হচ্ছে...",
  "frontdesk.paymentSuccessful": "পেমেন্ট সফল!",
  "frontdesk.receiptNo": "রিসিপ্ট নম্বর",
  "frontdesk.remainingBalance": "অবশিষ্ট বকেয়া",
  "frontdesk.paymentFailed": "পেমেন্ট ব্যর্থ",
  "frontdesk.hotelName": "হোটেলের নাম",
  "frontdesk.welcomeMessage": "স্বাগতম বার্তা",
  "frontdesk.primaryColor": "প্রাথমিক রং",
  "frontdesk.backgroundStyle": "ব্যাকগ্রাউন্ড স্টাইল",
  "frontdesk.idleTimeout": "অলস টাইমআউট",
  "frontdesk.enableCheckIn": "চেক-ইন সক্রিয়",
  "frontdesk.enableCheckOut": "চেক-আউট সক্রিয়",
  "frontdesk.enablePayment": "পেমেন্ট সক্রিয়",
  "frontdesk.kioskAddress": "কিয়স্ক ঠিকানা",
  "frontdesk.saveChanges": "পরিবর্তনগুলো সংরক্ষণ করুন",
  "guests.guestsTitle": "অতিথি",
  "guests.guestProfiles": "অতিথি প্রোফাইল",
  "guests.firstName": "প্রথম নাম",
  "guests.lastName": "শেষ নাম",
  "guests.firstNamePlaceholder": "জন",
  "guests.lastNamePlaceholder": "স্মিথ",
  "guests.phonePlaceholder": "+1 555 123 4567",
  "guests.cityPlaceholder": "নিউ ইয়র্ক",
  "guests.countryPlaceholder": "মার্কিন যুক্তরাষ্ট্র",
  "guests.specialRequests": "বিশেষ পছন্দ, অতিথি সম্পর্কে নোট...",
  "guests.loyaltyTier": "অনুগত্ব টায়ার",
  "guests.vipStatus": "VIP অবস্থা",
  "guests.nameRequired": "প্রথম নাম এবং শেষ নাম আবশ্যক",
  "guests.validationError": "যাচাইকরণ ত্রুটি",
  "guests.reviewDocuments": "অতিথি পরিচয়পত্র পর্যালোচনা ও যাচাই করুন",
  "guests.reviewDocument": "এই ডকুমেন্ট পর্যালোচনা, যাচাই বা প্রত্যাখ্যান করুন",
  "guests.rejectReason": "প্রত্যাখ্যানের কারণ লিখুন...",
  "guests.kycStatus": "KYC অবস্থা",
  "guests.kycDocumentsTitle": "KYC ডকুমেন্ট",
  "guests.uploadDocument": "যাচাইয়ের জন্য একটি KYC ডকুমেন্ট আপলোড করুন",
  "guests.documentName": "ডকুমেন্টের নাম",
  "guests.documentNamePlaceholder": "যেমন, পাসপোর্ট - জন স্মিথ",
  "guests.documentTypeRequired": "ডকুমেন্টের ধরন এবং নাম আবশ্যক",
  "guests.fileTooLarge": "ফাইল খুব বড়",
  "guests.pleaseSelectSmallFile": "অনুগ্রহ করে 10MB এর নিচে একটি ফাইল নির্বাচন করুন।",
  "guests.guestPreferencesTitle": "অতিথি পছন্দ",
  "guests.dietaryRequirements": "অন্য কোনো খাদ্যাভ্যাস প্রয়োজনীয়তা বা সীমাবদ্ধতা...",
  "guests.additionalPreferences": "অন্য কোনো পছন্দ বা বিশেষ অনুরোধ...",
  "guests.managePreferences": "অতিথি পছন্দ এবং বিশেষ অনুরোধ পরিচালনা",
  "guests.loyaltyTitle": "অনুগত্ব প্রোগ্রাম",
  "guests.adjustPoints": "পয়েন্ট সামঞ্জস্য",
  "guests.pointsPlaceholder": "পয়েন্ট লিখুন",
  "guests.tier": "টায়ার",
  "guests.reasonPlaceholder": "যেমন, সেবা সমস্যার জন্য ক্ষতিপূরণ",
  "guests.pleaseEnterValidPoints": "অনুগ্রহ করে একটি বৈধ পয়েন্ট পরিমাণ লিখুন",
  "guests.loyaltyPointsTitle": "অনুগত্ব পয়েন্ট",
  "guests.redemptionOptions": "রিডেম্পশন বিকল্প",
  "guests.insufficientPoints": "অপর্যাপ্ত পয়েন্ট",
  "guests.pleaseSelectRedemption": "অনুগ্রহ করে একটি রিডেম্পশন বিকল্প নির্বাচন করুন",
  "guests.completeStayInfo": "এই অবস্থান সম্পর্কে সম্পূর্ণ তথ্য",
  "guests.exportComplete": "এক্সপোর্ট সম্পন্ন",
  "guests.guestProfileTitle": "অতিথি প্রোফাইল",
  "guests.backToList": "তালিকায় ফিরে যান",
  "guests.guestJourneyTitle": "অতিথি যাত্রা",
  "guests.addJourneyEvent": "অতিথির যাত্রা টাইমলাইনে একটি নতুন ইভেন্ট রেকর্ড করুন",
  "guests.eventTitle": "ইভেন্টের শিরোনাম",
  "guests.eventType": "ইভেন্টের ধরন",
  "guests.eventTitlePlaceholder": "যেমন, website_visit, booking_created, check_in",
  "guests.eventDescription": "কী ঘটেছে তা বর্ণনা করুন...",
  "guests.journeyEventAdded": "যাত্রা ইভেন্ট যোগ হয়েছে",
  "guests.titleAndTypeRequired": "শিরোনাম এবং ইভেন্টের ধরন আবশ্যক",
  "guests.preStay": "পূর্ব-অবস্থান যোগাযোগ এবং প্রস্তুতি",
  "guests.inStay": "অবস্থানকালীন অভিজ্ঞতা এবং সেবা",
  "guests.postStay": "মতামত, পর্যালোচনা এবং ফলো-আপ",
  "guests.loyaltyReEngagement": "অনুগত্ব প্রোগ্রাম এবং পুনঃসম্পৃক্ততা",
  "guests.howFoundProperty": "অতিথি কীভাবে সম্পত্তি খুঁজে পেয়েছেন"
};

const bnPath = path.join(process.cwd(), 'src/messages/bn.json');
console.log('Reading:', bnPath);
const locale = JSON.parse(fs.readFileSync(bnPath, 'utf-8'));
console.log('Applying', Object.keys(translations).length, 'Bengali translations...');

for (const [key, value] of Object.entries(translations)) {
  deepSet(locale, key, value);
}

console.log('Writing updated bn.json...');
fs.writeFileSync(bnPath, JSON.stringify(locale, null, 2) + '\n');
console.log('Done! Bengali translations applied successfully.');
