import fs from 'fs';

const T = JSON.parse(fs.readFileSync('/tmp/de_translations_all.json','utf8'));
const src = JSON.parse(fs.readFileSync('/tmp/de_keys.json','utf8'));
const remaining = Object.keys(src).filter(k => !(k in T));

// Massive phrase-level German translation dictionary
// Maps English phrases to German translations
const PH = {
// ===== staff (141) =====
'Attendance Tracking':'Anwesenheitsverfolgung',
'Monitor staff attendance and clock in/out times':'Personalanwesenheit und Stempeluhrzeiten überwachen',
'Export as CSV':'Als CSV exportieren','Export as JSON':'Als JSON exportieren',
'Present Today':'Heute anwesend','Absent Today':'Heute abwesend','Late Today':'Heute verspätet',
'Attendance Rate':'Anwesenheitsquote',"Today's Attendance":"Heutige Anwesenheit",
'History':'Verlauf','Clock In':'Einstempeln','Clock Out':'Ausstempeln',
'Not Clocked':'Nicht eingestempelt','Select Staff':'Personal auswählen',
'No staff selected':'Kein Personal ausgewählt','Clock-in time':'Einstempelzeit',
'Clock-out time':'Ausstempelzeit','Duration':'Dauer','Total Hours':'Gesamtstunden',
'Overtime':'Überstunden','Regular Hours':'Reguläre Stunden',
'Shift Management':'Schichtverwaltung',
'Manage staff shifts and schedules':'Personal- und Schichtpläne verwalten',
'Shift':'Schicht','Shifts':'Schichten','Schedule':'Zeitplan',
'Create Shift':'Schicht erstellen','Edit Shift':'Schicht bearbeiten',
'Delete Shift':'Schicht löschen','Shift Template':'Schichtvorlage',
'Morning Shift':'Frühschicht','Afternoon Shift':'Nachmittagschicht',
'Night Shift':'Nachtschicht','Split Shift':'Geteilte Schicht',
'On-call Shift':'Bereitschaftsschicht','Shift Swap':'Schichttausch',
'Staff Member':'Mitarbeiter','Assigned Staff':'Zugewiesenes Personal',
'Shift Coverage':'Schichtabdeckage','Understaffed':'Unterbesetzt',
'Overstaffed':'Überbesetzt','Optimal Staffing':'Optimale Besetzung',
'Skills & Certifications':'Fähigkeiten & Zertifizierungen',
'Track staff qualifications and certifications':'Personalqualifikationen und -zertifizierungen verfolgen',
'Skill':'Fähigkeit','Skills':'Fähigkeiten','Certification':'Zertifizierung',
'Certifications':'Zertifizierungen','Add Skill':'Fähigkeit hinzufügen',
'Add Certification':'Zertifizierung hinzufügen','Expiry Date':'Ablaufdatum',
'Certified':'Zertifiziert','Expired':'Abgelaufen','Renewal Due':'Erneuerung fällig',
'Valid Until':'Gültig bis','Issued By':'Ausgestellt von','Certificate Number':'Zertifikatsnummer',
'Staff Communication':'Interne Kommunikation',
'Internal messaging and announcements':'Interne Nachrichten und Ankündigungen',
'Announcement':'Ankündigung','Announcements':'Ankündigungen',
'New Announcement':'Neue Ankündigung','Priority Level':'Prioritätsstufe',
'Target Audience':'Zielgruppe','All Staff':'Gesamtes Personal',
'Specific Department':'Bestimmte Abteilung','Message':'Nachricht',
'Send Announcement':'Ankündigung senden','Broadcast':'Rundsendung',
'Direct Message':'Direktnachricht','Reply':'Antworten',
'Staff Directory':'Personalverzeichnis','Contact Information':'Kontaktinformationen',
'Emergency Contact':'Notfallkontakt','Next of Kin':'Nächster Angehöriger',
'Leave blank to use today\'s date. Certification validity is 1 year from this date.':'Leer lassen für heutiges Datum. Zertifizierungsgültigkeit beträgt 1 Jahr ab diesem Datum.',
'Staff Performance':'Leistungskennzahlen',
'Detailed performance metrics and evaluations':'Detaillierte Leistungskennzahlen und Bewertungen',
'Performance Review':'Leistungsbewertung','Evaluation Period':'Bewertungszeitraum',
'Rating':'Bewertung','Goals':'Ziele','Achievements':'Errungenschaften',
'Areas for Improvement':'Verbesserungsbereiche','Feedback':'Feedback',
'Performance Score':'Leistungspunktzahl','Peer Review':'Kollegenbewertung',
'Self Assessment':'Selbstbewertung','Manager Review':'Vorgesetztenbewertung',
'Clock-in':'Einstempeln','Clock-out':'Ausstempeln',
'Clocked ${clockAction} successfully for ${selectedStaffForClock.firstName}':'${clockAction} erfolgreich für ${selectedStaffForClock.firstName} eingestempelt',
'Training':'Schulung','Trainings':'Schulungen',
'Training & Development':'Schulung & Weiterbildung',
'Manage training programs and staff development':'Schulungsprogramme und Personalentwicklung verwalten',
'Training Program':'Schulungsprogramm','Course':'Kurs','Courses':'Kurse',
'Module':'Modul','Modules':'Module','Completion Date':'Abschlussdatum',
'Training Status':'Schulungsstatus','In Progress':'In Bearbeitung',
'Not Started':'Nicht gestarted','Completed':'Abgeschlossen',
'Training Certificate':'Schulungszertifikat','Mandatory':'Verpflichtend',
'Optional Training':'Freiwillige Schulung','Training Calendar':'Schulungskalender',
'Upcoming Trainings':'Anstehende Schulungen','Training History':'Schulungsverlauf',

// ===== ads (131) =====
'Ad Campaigns':'Werbekampagnen','New Campaign':'Neue Kampagne',
'Paused':'Pausiert','Budget':'Budget','Spent':'Ausgegeben','Draft':'Entwurf',
'Impressions':'Impressionen','Clicks':'Klicks','Conversions':'Konversionen',
'Revenue':'Umsatz','Cost':'Kosten','ROAS':'ROAS','ROI':'ROI',
'CTR':'KTR','CPC':'KPK','CPM':'KPT','CPA':'KPA',
'Campaign Name':'Kampagnenname','Campaign Type':'Kampagnentyp',
'Search Ads':'Suchanzeigen','Display Ads':'Banneranzeigen',
'Social Ads':'Soziale-Medien-Anzeigen','Retargeting':'Retargeting',
'Google Hotel Ads':'Google Hotel Ads',
'Google Ads':'Google Ads','Facebook Ads':'Facebook Ads',
'Instagram Ads':'Instagram Ads','Meta Ads':'Meta Ads',
'Create Campaign':'Kampagne erstellen','Edit Campaign':'Kampagne bearbeiten',
'Delete Campaign':'Kampagne löschen','Duplicate Campaign':'Kampagne duplizieren',
'Pause Campaign':'Kampagne pausieren','Resume Campaign':'Kampagne fortsetzen',
'Campaign Budget':'Kampagnenbudget','Daily Budget':'Tägliches Budget',
'Total Budget':'Gesamtbudget','Budget Spent':'Budget ausgegeben',
'Budget Remaining':'Verbleibendes Budget','Start Date':'Startdatum',
'End Date':'Enddatum','Campaign Duration':'Kampagnendauer',
'Target Audience':'Zielgruppe','Geographic Targeting':'Geografische Ausrichtung',
'Language Targeting':'Sprachausrichtung','Device Targeting':'Geräteausrichtung',
'Demographic Targeting':'Demografische Ausrichtung','Interest Targeting':'Interessenausrichtung',
'Ad Creative':'Anzeigengestaltung','Ad Copy':'Anzeigentext',
'Headline':'Überschrift','Description':'Beschreibung','Call to Action':'Handlungsaufruf',
'Book Now':'Jetzt buchen','Learn More':'Mehr erfahren','View Rates':'Tarife ansehen',
'Special Offer':'Sonderangebot','Limited Time':'Zeitlich begrenzt',
'Ad Group':'Anzeigengruppe','Keywords':'Schlüsselwörter',
'Negative Keywords':'Negative Schlüsselwörter','Bid Strategy':'Gebotsstrategie',
'Manual Bidding':'Manuelles Bieten','Automatic Bidding':'Automatisches Bieten',
'Maximize Clicks':'Klicks maximieren','Maximize Conversions':'Konversionen maximieren',
'Target CPA':'Ziel-CPA','Target ROAS':'Ziel-ROAS',
'Ad Performance':'Anzeigenleistung','Campaign Performance':'Kampagnenleistung',
'Ad Group Performance':'Anzeigengruppenleistung','Keyword Performance':'Schlüsselwortleistung',
'Performance Metrics':'Leistungskennzahlen','Performance Trends':'Leistungstrends',
'Top Performing Ads':'Top-Anzeigen','Underperforming Ads':'Schwache Anzeigen',
'A/B Test':'A/B-Test','Variant A':'Variante A','Variant B':'Variante B',
'Test Winner':'Test-Gewinner','No Winner Yet':'Noch kein Gewinner',
'Conversion Tracking':'Konversionsverfolgung','Tracking Pixel':'Tracking-Pixel',
'Conversion Code':'Konversionscode','Event Tracking':'Ereignisverfolgung',
'Bookings':'Buchungen','Phone Calls':'Telefonanrufe','Directions':'Wegbeschreibungen',
'Website Clicks':'Website-Klicks','Google Analytics':'Google Analytics',
'No profit trend data available':'Keine Gewinn-Trenddaten verfügbar',
'No performance data available':'Keine Leistungsdaten verfügbar',
'Detailed metrics for each day':'Detaillierte Kennzahlen für jeden Tag',
'Profit Trend':'Gewinntrend','Ad Spend':'Werbeausgaben',
'Net Profit':'Nettogewinn','Profit Margin':'Gewinnmarge',
'Google Hotels Performance':'Google Hotels Leistung',
'Google Ads Performance':'Google Ads Leistung',
'Campaign Settings':'Kampagneneinstellungen',
'Bidding Strategy':'Gebotsstrategie','Ad Schedule':'Anzeigenzeitplan',
'Ad Extensions':'Anzeigenerweiterungen','Sitelinks':'Sitelinks',
'Callouts':'Hervorhebungen','Structured Snippets':'Strukturierte Snippets',
'Location Extensions':'Standorterweiterungen','Affiliate Extensions':'Partnererweiterungen',

// ===== events (118) =====
'Event Bookings':'Veranstaltungsbuchungen',
'Manage event inquiries and bookings':'Veranstaltungsanfragen und -buchungen verwalten',
'New Event':'Neue Veranstaltung','Event Name':'Veranstaltungsname',
'Event Type':'Veranstaltungsart','Event Date':'Veranstaltungsdatum',
'Start Time':'Startzeit','End Time':'Endzeit',
'Event Space':'Veranstaltungsraum','Event Details':'Veranstaltungsdetails',
'Number of Guests':'Anzahl der Gäste','Expected Attendance':'Erwartete Teilnehmerzahl',
'Actual Attendance':'Tatsächliche Teilnehmerzahl',
'Event Status':'Veranstaltungsstatus','Inquiry':'Anfrage',
'Confirmed':'Bestätigt','Tentative':'Vorläufig','Cancelled':'Storniert',
'Completed':'Abgeschlossen','Event Organizer':'Veranstalter',
'Contact Name':'Kontaktname','Contact Email':'Kontakt-E-Mail',
'Contact Phone':'Kontakttelefon','Company Name':'Unternehmensname',
'Event Requirements':'Veranstaltungsanforderungen',
'Catering':'Verpflegung','Audio/Visual':'Audio/Visuell',
'Setup Style':'Aufbaustil','Theater Style':'Theaterstil',
'Classroom Style':'Klassenraumstil','Banquet Style':'Bankettstil',
'U-Shape Style':'U-Form','Boardroom Style':'Konferenzraumstil',
'Cocktail Style':'Cocktailstil','Equipment':'Ausrüstung',
'Projector':'Beamer','Microphone':'Mikrofon','Speakers':'Lautsprecher',
'Screen':'Leinwand','Whiteboard':'Whiteboard','Flipchart':'Flipchart',
'Dance Floor':'Tanzfläche','Stage':'Bühne','Lighting':'Beleuchtung',
'Sound System':'Beschallungsanlage','WiFi Access':'WiFi-Zugang',
'Event Budget':'Veranstaltungsbudget','Estimated Cost':'Geschätzte Kosten',
'Actual Cost':'Tatsächliche Kosten','Budget Variance':'Budgetabweichung',
'Deposit Required':'Anzahlung erforderlich','Deposit Amount':'Anzahlungsbetrag',
'Deposit Paid':'Anzahlung bezahlt','Balance Due':'Zahlungsfällig',
'Payment Status':'Zahlungsstatus','Fully Paid':'Vollständig bezahlt',
'Partially Paid':'Teilweise bezahlt','Outstanding':'Offen',
'Event Spaces':'Veranstaltungsräume',
'Manage your event venues and spaces':'Veranstaltungsorte und -räume verwalten',
'Space Name':'Raumname','Space Type':'Raumtyp',
'Maximum Capacity':'Maximale Kapazität','Minimum Capacity':'Minimale Kapazität',
'Day Rate':'Tagespreis','Half Day Rate':'Halbtagespreis','Hourly Rate':'Stundenpreis',
'Availability':'Verfügbarkeit','Amenities':'Ausstattung',
'Natural Light':'Tageslicht','Soundproof':'Schalldicht',
'Wheelchair Access':'Rollstuhlgerecht','Built-in AV':'Integrierte AV-Technik',
'Floor Level':'Etagenstock','Dimensions':'Abmessungen',
'Event Calendar':'Veranstaltungskalender',
'Month View':'Monatsansicht','Week View':'Wochenansicht','Day View':'Tagesansicht',
'List View':'Listenansicht','Event Resources':'Veranstaltungsressourcen',
'Manage shared resources for events':'Gemeinsame Ressourcen für Veranstaltungen verwalten',
'Resource Name':'Ressourcenname','Resource Type':'Ressourcentyp',
'Quantity Available':'Verfügbare Menge','Quantity Assigned':'Zugewiesene Menge',
'Booking Status':'Buchungsstatus','Event Type Filter':'Veranstaltungstyp-Filter',
'All Types':'Alle Typen','Conference':'Konferenz',
'Wedding':'Hochzeit','Meeting':'Besprechung','Banquet':'Bankett',
'Workshop':'Workshop','Exhibition':'Ausstellung','Seminar':'Seminar',
'Corporate Event':'Unternehmensveranstaltung','Social Event':'Gesellschaftsveranstaltung',
'Private Event':'Private Veranstaltung','Non-Profit Event':'Non-Profit-Veranstaltung',
'Event details and information':'Veranstaltungsdetails und -informationen',

// ===== crm (115) =====
'Guest Segments':'Gästesegmente',
'Manage guest segmentation rules':'Gästesegmentierungsregeln verwalten',
'Create Segment':'Segment erstellen','Edit Segment':'Segment bearbeiten',
'Delete Segment':'Segment löschen','Segment Name':'Segmentname',
'Segment Description':'Segmentbeschreibung','Segment Type':'Segmenttyp',
'Manual Segment':'Manuelles Segment','Automatic Segment':'Automatisches Segment',
'Dynamic Segment':'Dynamisches Segment','Static Segment':'Statisches Segment',
'Segment Rules':'Segmentregeln','Conditions':'Bedingungen',
'Add Condition':'Bedingung hinzufügen','Remove Condition':'Bedingung entfernen',
'Guest Count':'Gästeanzahl','Guests in Segment':'Gäste im Segment',
'Define rules to automatically group guests based on their attributes and behavior':'Regeln definieren, um Gäste automatisch basierend auf ihren Attributen und Verhalten zu gruppieren',
'Guest Type':'Gasttyp','Stay Frequency':'Aufenthaltsfrequenz',
'Spending Level':'Ausgabenniveau','Loyalty Tier':'Treuestufe',
'Geographic Location':'Geografischer Standort','Demographics':'Demografie',
'Booking Channel':'Buchungskanal','Room Type Preference':'Zimmertyp-Präferenz',
'Guest Campaigns':'Gästekampagnen',
'Create and manage marketing campaigns':'Marketingkampagnen erstellen und verwalten',
'New Campaign':'Neue Kampagne','Campaign Name':'Kampagnenname',
'Campaign Type':'Kampagnentyp','Email Campaign':'E-Mail-Kampagne',
'SMS Campaign':'SMS-Kampagne','Push Campaign':'Push-Kampagne',
'Target Segment':'Zielsegment','Target Audience':'Zielgruppe',
'Campaign Content':'Kampagneninhalt','Subject Line':'Betreffzeile',
'Preview':'Vorschau','Schedule':'Zeitplan','Send Now':'Jetzt senden',
'Scheduled':'Geplant','Sent':'Gesendet','Delivered':'Zugestellt',
'Opened':'Geöffnet','Clicked':'Geklickt','Bounced':'Zurückgewiesen',
'Unsubscribed':'Abgemeldet','Complained':'Beschwert',
'Open Rate':'Öffnungsrate','Click Rate':'Klickrate',
'Conversion Rate':'Konversionsrate','Delivery Rate':'Zustellungsrate',
'Bounce Rate':'Bounce-Rate','Unsubscribe Rate':'Abmelderate',
'Campaign Analytics':'Kampagnenanalysen','Campaign Results':'Kampagnenergebnisse',
'Best Performing':'Beste Leistung','Worst Performing':'Schwächste Leistung',
'Loyalty Program':'Treueprogramm',
'Manage loyalty tiers, points, and rewards':'Treuestufen, Punkte und Prämien verwalten',
'Program Name':'Programmname','Program Type':'Programmtyp',
'Points-Based':'Punktebasiert','Tier-Based':'Stufenbasiert',
'Hybrid':'Hybrid','Earn Rate':'Punkte-Satz',
'Redemption Rate':'Einlösungsrate','Point Value':'Punktwert',
'Minimum Points':'Mindestpunkte','Maximum Points':'Höchstpunkte',
'Tier Name':'Stufenname','Tier Benefits':'Stufenvorteile',
'Tier Threshold':'Stufenschwelle','Points Required':'Erforderliche Punkte',
'Bronze':'Bronze','Silver':'Silber','Gold':'Gold',
'Platinum':'Platin','Diamond':'Diamant',
'Member Enrollment':'Mitgliedsanmeldung','Member Activity':'Mitgliedsaktivität',
'Points Balance':'Punktestand','Points History':'Punkteverlauf',
'Rewards':'Prämien','Available Rewards':'Verfügbare Prämien',
'Redeem Points':'Punkte einlösen','Point Expiration':'Punktablauf',
'Monitor guest retention, lifetime value, and identify at-risk guests':'Gastbindung, Lebenszeitwert überwachen und gefährdete Gäste identifizieren',
'Churn Risk':'Abwanderungsrisiko','Retention Rate':'Bindungsrate',
'Guest Lifetime Value':'Gast-Lebenszeitwert','Repeat Guest Rate':'Wiederkehrgäste-Rate',
'Average Stay Length':'Durchschn. Aufenthaltsdauer',
'Guests at Risk':'Gefährdete Gäste','Re-engagement Opportunities':'Wiederbindungsmöglichkeiten',
'Top Guests':'Top-Gäste','VIP Guests':'VIP-Gäste',
'Guest Feedback':'Gästefeedback','Reviews':'Bewertungen',
'Average Rating':'Durchschn. Bewertung','Response Rate':'Antwortrate',
'Review Trend':'Bewertungstrend','Sentiment Analysis':'Stimmungsanalyse',
'Guests with multiple stays across different months are needed to calculate cohort metrics.':'Gäste mit mehreren Aufenthalten in verschiedenen Monaten werden für Kohortenmetriken benötigt.',
'Name and content are required':'Name und Inhalt sind erforderlich',
'Leave empty to save as draft':'Leer lassen, um als Entwurf zu speichern',
'Points per unit currency spent':'Punkte pro ausgegebener Währungseinheit',
'{tier.minPoints.toLocaleString()} - {tier.maxPoints === 999999 ? \'∞\' : tier.maxPoints.toLocaleString()}':'{tier.minPoints.toLocaleString()} - {tier.maxPoints === 999999 ? \'∞\' : tier.maxPoints.toLocaleString()}',

// ===== inventory (113) =====
'Inventory':'Bestand','Stock':'Bestand','Stock Items':'Bestandsartikel',
'Manage inventory items and stock levels':'Bestandsartikel und Bestandsstände verwalten',
'Item Name':'Artikelname','Item Description':'Artikelbeschreibung',
'Category':'Kategorie','Unit':'Einheit','Unit Cost':'Stückpreis',
'Current Stock':'Aktueller Bestand','Minimum Stock':'Mindestbestand',
'Maximum Stock':'Höchstbestand','Reorder Level':'Bestellpunkt',
'Reorder Quantity':'Bestellmenge','Supplier':'Lieferant',
'Supplier Name':'Lieferantenname','Supplier Contact':'Lieferantenkontakt',
'Stock Status':'Bestandsstatus','In Stock':'Auf Lager',
'Low Stock':'Niedriger Bestand','Out of Stock':'Nicht auf Lager',
'Discontinued':'Eingestellt','On Order':'Bestellt',
'Consumption Logs':'Verbrauchsprotokolle',
'Track item consumption and usage':'Artikelverbrauch und -nutzung verfolgen',
'Consumption Date':'Verbrauchsdatum','Quantity Used':'Verbrauchte Menge',
'Used By':'Verwendet von','Department':'Abteilung',
'Cost of Goods':'Warenkosten','Consumption Trend':'Verbrauchstrend',
'Low Stock Alerts':'Meldebestandswarnungen',
'Configure alerts for low stock items':'Warnungen für Niedrig-Bestand konfigurieren',
'Alert Threshold':'Warngrenze','Alert Recipient':'Warnungsempfänger',
'Notification Method':'Benachrichtigungsmethode',
'Vendors':'Lieferanten',
'Manage supplier information and orders':'Lieferanteninformationen und -bestellungen verwalten',
'Vendor Name':'Lieferantenname','Vendor Type':'Lieferantentyp',
'Contact Person':'Kontaktperson','Payment Terms':'Zahlungsbedingungen',
'Delivery Terms':'Lieferbedingungen','Lead Time':'Vorlaufzeit',
'Minimum Order':'Mindestbestellung','Credit Limit':'Kreditlimit',
'Purchase Orders':'Bestellungen',
'Create and manage purchase orders':'Bestellungen erstellen und verwalten',
'PO Number':'Bestellnummer','Order Date':'Bestelldatum',
'Expected Delivery':'Erwartete Lieferung','Actual Delivery':'Tatsächliche Lieferung',
'Order Status':'Bestellstatus','Pending':'Ausstehend',
'Approved':'Genehmigt','Received':'Empfangen','Partial':'Teilweise',
'Order Total':'Bestellsumme','Items Ordered':'Bestellte Artikel',
'Items Received':'Empfangene Artikel','Items Pending':'Ausstehende Artikel',
'Inventory Reports':'Bestandsberichte','Stock Value':'Bestandswert',
'Turnover Rate':'Umschlagshäufigkeit','Dead Stock':'Toter Bestand',
'Most Consumed':'Am meisten verbraucht','Least Consumed':'Am wenigsten verbraucht',
'Inventory Audit':'Bestandsprüfung','Count':'Zählung',
'System Count':'Systemzählung','Physical Count':'Ist-Bestand',
'Variance':'Abweichung','Adjusted Count':'Angepasste Zählung',
'Adjustment Reason':'Anpassungsgrund','Last Audit':'Letzte Prüfung',

// ===== parking (111) =====
'Parking Management':'Parkverwaltung',
'Manage parking slots and vehicle tracking':'Parkplätze und Fahrzeugverfolgung verwalten',
'Parking Slots':'Parkplätze','Total Slots':'Gesamtplätze',
'Available Slots':'Verfügbare Plätze','Occupied Slots':'Belegte Plätze',
'Reserved Slots':'Reservierte Plätze','Disabled Slots':'Behindertenplätze',
'Slot Number':'Platznummer','Slot Type':'Platztyp',
'Regular':'Standard','Compact':'Kompakt','Motorcycle':'Motorrad',
'EV Charging':'E-Ladestation','Handicap':'Behindert',
'Valet':'Valet','VIP':'VIP','Staff':'Personal',
'Floor Level':'Etagenstock','Zone':'Zone','Section':'Abschnitt',
'Parking Rate':'Parkgebühr','Hourly Rate':'Stundenpreis',
'Daily Rate':'Tagespreis','Monthly Rate':'Monatspreis',
'Weekly Rate':'Wochenpreis','Event Rate':'Eventpreis',
'Vehicle Tracking':'Fahrzeugverfolgung',
'Track vehicles entering and exiting':'Fahrzeuge bei Ein- und Ausfahrt verfolgen',
'License Plate':'Kennzeichen','Vehicle Type':'Fahrzeugtyp',
'Car':'PKW','Truck':'LKW','Motorcycle':'Motorrad',
'Van':'Transporter','SUV':'SUV','Bus':'Bus',
'Entry Time':'Einfahrtzeit','Exit Time':'Ausfahrtzeit',
'Duration':'Dauer','Parking Fee':'Parkgebühr',
'Payment Status':'Zahlungsstatus','Overstayed':'Überzogen',
'Expected Exit':'Erwartete Ausfahrt','Alert':'Warnung',
'Parking Billing':'Parkgebührenabrechnung',
'Manage parking fees and payments':'Parkgebühren und -zahlungen verwalten',
'Billing Method':'Abrechnungsmethode','Per Hour':'Pro Stunde',
'Per Day':'Pro Tag','Flat Rate':'Pauschalpreis',
'Monthly Pass':'Monatskarte','Annual Pass':'Jahreskarte',
'Payment History':'Zahlungsverlauf','Outstanding Balance':'Offener Saldo',
'Parking Reports':'Parkberichte','Occupancy Trends':'Belegungstrends',
'Revenue by Zone':'Umsatz nach Zone','Peak Hours':'Spitzenzeiten',
'Average Duration':'Durchschn. Dauer','Frequent Users':'Häufige Nutzer',
'Parking Reservation':'Parkplatzreservierung',
'Reserve a parking slot':'Parkplatz reservieren',
'Reservation Date':'Reservierungsdatum','Expected Arrival':'Erwartete Ankunft',
'Expected Departure':'Erwartete Abreise','Guest Name':'Gastname',
'Room Number':'Zimmernummer','Confirmation':'Bestätigung',
'Camera Integration':'Kamera-Integration','License Plate Recognition':'Kennzeichenerkennung',
'ANPR':'ANPR','Barrier Control':'Schrankensteuerung',
'Parking Map':'Parkkarte','Slot Status':'Platzstatus',
'Current Occupancy':'Aktuelle Belegung','Parking History':'Parkverlauf',

// ===== help (110) =====
'Help Center':'Hilfecenter','Knowledge Base':'Wissensdatenbank',
'Articles':'Artikel','Tutorials':'Tutorials','FAQ':'FAQ',
'Documentation':'Dokumentation','Getting Started':'Erste Schritte',
'Quick Start Guide':'Schnellstartanleitung','User Guide':'Benutzerhandbuch',
'Admin Guide':'Administratorenhandbuch','API Reference':'API-Referenz',
'Video Tutorials':'Videotutorials','Webinars':'Webinare',
'Search Help':'Hilfe suchen','Search articles...':'Artikel suchen...',
'Popular Articles':'Beliebte Artikel','Recent Articles':'Aktuelle Artikel',
'Categories':'Kategorien','General':'Allgemein',
'Account Management':'Kontoverwaltung','Billing':'Abrechnung',
'Integrations':'Integrationen','PMS':'PMS','POS':'POS',
'Channel Manager':'Kanalmanager','Revenue Management':'Umsatzmanagement',
'Housekeeping':'Housekeeping','Guest Experience':'Gästeerlebnis',
'Security':'Sicherheit','Troubleshooting':'Fehlerbehebung',
'Article':'Artikel','Last Updated':'Zuletzt aktualisiert',
'Reading Time':'Lesezeit','Helpful':'Hilfreich',
'Yes':'Ja','No':'Nein','Was this helpful?':'War dies hilfreich?',
'Report an issue':'Problem melden','Contact Support':'Support kontaktieren',
'Our support team is here to assist you. Reach out through any of the channels below.':'Unser Support-Team steht Ihnen zur Verfügung. Kontaktieren Sie uns über einen der unten stehenden Kanäle.',
"Can't find what you're looking for? Our support team is here to help.":'Konnten Sie nicht finden, wonach Sie suchen? Unser Support-Team hilft Ihnen gerne.',
'Live Chat':'Live-Chat','Email Support':'E-Mail-Support',
'Phone Support':'Telefon-Support','Ticket':'Ticket',
'Create Ticket':'Ticket erstellen','Ticket Status':'Ticketstatus',
'Open':'Offen','In Progress':'In Bearbeitung','Resolved':'Gelöst',
'Closed':'Geschlossen','Ticket Priority':'Ticketpriorität',
'Ticket Description':'Ticketbeschreibung','Attachments':'Anhänge',
'Ticket History':'Ticketverlauf',
'Describe your issue, attach screenshots, and track your request status':'Beschreiben Sie Ihr Problem, hängen Sie Screenshots an und verfolgen Sie Ihren Anfragestatus',
'Tutorial Progress':'Tutorial-Fortschritt','Tutorial':'Tutorial',
'Completed Tutorials':'Abgeschlossene Tutorials','In Progress':'In Bearbeitung',
'Not Started':'Nicht gestartet','Estimated Time':'Geschätzte Dauer',
'Tutorial Categories':'Tutorial-Kategorien',
'What would you like to learn?':'Was möchten Sie lernen?',
'Recommended for you':'Empfohlen für Sie','Continue Learning':'Weiterlernen',

// ===== iot (92) =====
'Smart Hotel / IoT':'Smart Hotel / IoT',
'Device Management':'Geräteverwaltung',
'Manage connected devices and sensors':'Verbundene Geräte und Sensoren verwalten',
'Device Name':'Gerätename','Device Type':'Gerätetyp',
'Thermostat':'Thermostat','Light Switch':'Lichtschalter',
'Door Lock':'Türschloss','Motion Sensor':'Bewegungsmelder',
'Temperature Sensor':'Temperatursensor','Humidity Sensor':'Feuchtigkeitssensor',
'Energy Monitor':'Energiemonitor','Smart Plug':'Smart-Steckdose',
'Air Quality Monitor':'Luftqualitätsmonitor','Water Sensor':'Wassersensor',
'Smoke Detector':'Rauchmelder','CO₂ Detector':'CO₂-Melder',
'Device Status':'Gerätestatus','Online':'Online','Offline':'Offline',
'Connected':'Verbunden','Disconnected':'Getrennt',
'Low Battery':'Niedriger Akkustand','Error':'Fehler',
'Last Seen':'Zuletzt gesehen','Signal Strength':'Signalstärke',
'Firmware Version':'Firmware-Version','Battery Level':'Akkustand',
'Protocol':'Protokoll','WiFi':'WiFi','Bluetooth':'Bluetooth',
'Zigbee':'Zigbee','Z-Wave':'Z-Wave','Thread':'Thread',
'Matter':'Matter','Room Control':'Zimmersteuerung',
'Control room devices remotely':'Zimmergeräte fernsteuern',
'Temperature':'Temperatur','Humidity':'Feuchtigkeit',
'Lighting':'Beleuchtung','Brightness':'Helligkeit',
'Color':'Farbe','Color Temperature':'Farbtemperatur',
'Cool Mode':'Kühlmodus','Heat Mode':'Heizmodus','Auto Mode':'Automatik',
'Fan Speed':'Lüfterstufe','Low':'Niedrig','Medium':'Mittel',
'High':'Hoch','Auto':'Automatisch',
'Energy Dashboard':'Energie-Dashboard',
'Monitor energy consumption and optimize usage':'Energieverbrauch überwachen und Nutzung optimieren',
'Total Energy':'Gesamtenergie','Energy by Room':'Energie nach Zimmer',
'Energy by Floor':'Energie nach Etage','Energy by Device Type':'Energie nach Gerätetyp',
'Energy Cost':'Energiekosten','Energy Savings':'Energieeinsparungen',
'Carbon Footprint':'CO₂-Fußabdruck','Green Score':'Umweltpunktzahl',
'Peak Usage':'Spitzenverbrauch','Off-Peak Usage':'Niedrigverbrauch',
'Daily Trend':'Täglicher Trend','Weekly Trend':'Wöchentlicher Trend',
'Monthly Trend':'Monatlicher Trend',
'Energy Optimization':'Energieoptimierung',
'Automated Energy Rules':'Automatische Energiergeln',
'Auto-off when room empty':'Automatisch ausschalten bei leerem Zimmer',
'Night setback':'Nachtabsenkung','Temperature limits':'Temperaturgrenzen',
'Lighting schedules':'Beleuchtungszeitpläne',
'Are you sure you want to unlock this door? This will allow access to the room.':'Sind Sie sicher, dass Sie diese Tür entriegeln möchten? Dies gewährt Zugang zum Zimmer.',
'Lock':'Sperren','Unlock':'Entriegeln',
'Device Health':'Gerätezustand','Maintenance Needed':'Wartung erforderlich',
'Replace Battery':'Batterie wechseln','Update Firmware':'Firmware aktualisieren',
'Reboot Device':'Gerät neu starten','Remove Device':'Gerät entfernen',
'Device Groups':'Gerätegruppen','All Devices':'Alle Geräte',
'By Room':'Nach Zimmer','By Type':'Nach Typ','By Floor':'Nach Etage',
'By Protocol':'Nach Protokoll','By Status':'Nach Status',

// ===== chain (91) =====
'Chain Management':'Kettenverwaltung',
'Manage multi-property operations':'Betrieb über mehrere Immobilien verwalten',
'Brand Management':'Markenverwaltung',
'Manage brand standards and guidelines':'Markenstandards und -richtlinien verwalten',
'Brand Name':'Markenname','Brand Logo':'Markenlogo',
'Brand Colors':'Markenfarben','Brand Guidelines':'Markenrichtlinien',
'Brand Standards':'Markenstandards',
'JSON object defining brand standards (check-in/out times, amenities, etc.)':'JSON-Objekt mit Markenstandards (Check-in/Check-out-Zeiten, Ausstattung usw.)',
'Chain Dashboard':'Ketten-Dashboard',
'Overview of all properties':'Übersicht aller Immobilien',
'Total Properties':'Gesamtimmobilien','Active Properties':'Aktive Immobilien',
'Inactive Properties':'Inaktive Immobilien',
'Chain Revenue':'Kettenumsatz','Total Revenue':'Gesamtumsatz',
'Average RevPAR':'Durchschn. RevPAR','Average Occupancy':'Durchschn. Auslastung',
'Average ADR':'Durchschn. ADR','Guest Satisfaction':'Gastzufriedenheit',
'Property Comparison':'Immobilienvergleich','Top Performing':'Beste Leistung',
'Underperforming':'Schwache Leistung','Improvement Needed':'Verbesserungsbedarf',
'Cross-Property Analytics':'Übergreifende Immobilienanalysen',
'Revenue by Property':'Umsatz nach Immobilie',
'Occupancy by Property':'Auslastung nach Immobilie',
'Guest Satisfaction by Property':'Gastzufriedenheit nach Immobilie',
'Staff Performance by Property':'Mitarbeiterleistung nach Immobilie',
'Chain Reports':'Kettenberichte','Consolidated Reports':'Konsolidierte Berichte',
'Property Comparison Reports':'Immobilienvergleichsberichte',
'Brand Performance Reports':'Markenleistungsberichte',
'Chain Settings':'Ketten-Einstellungen',
'Centralized Policies':'Zentralisierte Richtlinien',
'Brand Configuration':'Markenkonfiguration',
'Property Templates':'Immobilienvorlagen',
'No demographic data available':'Keine demografische Daten verfügbar',

// ===== portal (78) =====
'Guest Portal':'Gästeportal','Portal Settings':'Portal-Einstellungen',
'Customize your stay experience':'Passen Sie Ihr Aufenthaltserlebnis an',
'Welcome Message':'Willkommensnachricht','Portal Theme':'Portal-Design',
'Primary Color':'Primärfarbe','Secondary Color':'Sekundärfarbe',
'Font Family':'Schriftart','Logo Upload':'Logo hochladen',
'Background Image':'Hintergrundbild','Portal Features':'Portal-Funktionen',
'Room Service':'Zimmerservice','Housekeeping Requests':'Housekeeping-Anfragen',
'Service Requests':'Serviceanfragen','Local Guide':'Lokalführer',
'Feedback':'Feedback','Express Check-out':'Express Check-out',
'Digital Key':'Digitaler Schlüssel','In-Room Dining':'Zimmerservice',
'Spa Booking':'Spa-Buchung','Activity Booking':'Aktivitätenbuchung',
'Airport Transfer':'Flughafentransfer','Late Check-out':'Später Check-out',
'Room Upgrade':'Zimmer-Upgrade','Extra Bed':'Zusatzbett',
'Baby Crib':'Babybett','Welcome Amenity':'Willkommens-Geschenk',
'Portal Configuration':'Portal-Konfiguration',
'Enable/Disable portal features':'Portalfunktionen aktivieren/deaktivieren',
'Mobile Responsive':'Mobil-optimiert','Multi-language Support':'Mehrsprachenunterstützung',
'Custom Domain':'Benutzerdefinierte Domain','Portal Analytics':'Portal-Analysen',
'Portal Usage':'Portal-Nutzung','Feature Usage':'Funktionsnutzung',
'User Satisfaction':'Benutzerzufriedenheit','Popular Features':'Beliebte Funktionen',
'Conversion Rate':'Konversionsrate','Portal Access':'Portal-Zugang',
'Access Method':'Zugangsmethode','QR Code':'QR-Code',
'Email Link':'E-Mail-Link','SMS Link':'SMS-Link',
'Direct URL':'Direkte URL','Portal Branding':'Portal-Branding',
'By signing below, you agree to the property\'s terms and conditions, ':'Mit Ihrer Unterschrift unten stimmen Sie den Bedingungen und Konditionen der Immobilie zu,',
'Terms and Conditions':'AGB','Privacy Policy':'Datenschutzerklärung',
'Digital Signature':'Digitale Unterschrift','Sign Here':'Hier unterschreiben',
'Guest-facing portal configuration':'Gästeportal-Konfiguration',

// ===== automation (75) =====
'Automation':'Automatisierung','Workflow Builder':'Workflow-Builder',
'Create automated workflows':'Automatisierte Workflows erstellen',
'Workflow Name':'Workflowname','Workflow Description':'Workflowbeschreibung',
'Trigger':'Auslöser','Trigger Type':'Auslösertyp',
'Event Trigger':'Ereignis-Auslöser','Schedule Trigger':'Zeitplan-Auslöser',
'Manual Trigger':'Manueller Auslöser','Condition':'Bedingung',
'Conditions':'Bedingungen','Action':'Aktion','Actions':'Aktionen',
'Add Action':'Aktion hinzufügen','Remove Action':'Aktion entfernen',
'Workflow Status':'Workflow-Status','Active':'Aktiv','Inactive':'Inaktiv',
'Paused':'Pausiert','Draft':'Entwurf',
'Execution Logs':'Ausführungsprotokolle','Execution History':'Ausführungsverlauf',
'Last Run':'Letzte Ausführung','Next Run':'Nächste Ausführung',
'Success Count':'Erfolgsanzahl','Failure Count':'Fehleranzahl',
'Average Duration':'Durchschn. Dauer','Run Now':'Jetzt ausführen',
'Test Workflow':'Workflow testen','Enable':'Aktivieren',
'Disable':'Deaktivieren','Clone':'Klonen','Delete':'Löschen',
'Rules Engine':'Regel-Engine',
'Create business rules for automation':'Geschäftsregeln für Automatisierung erstellen',
'Rule Name':'Regelname','Rule Description':'Regelbeschreibung',
'Rule Type':'Regeltyp','Priority':'Priorität',
'Rule Status':'Regelstatus','Evaluation':'Auswertung',
'JSON array of conditions that must be met for this rule to trigger':'JSON-Array von Bedingungen, die erfüllt sein müssen, damit diese Regel ausgelöst wird',
'Templates':'Vorlagen','Workflow Templates':'Workflow-Vorlagen',
'Use Template':'Vorlage verwenden','Template Library':'Vorlagenbibliothek',
'Custom Templates':'Benutzerdefinierte Vorlagen','Built-in Templates':'Integrierte Vorlagen',
'Import Template':'Vorlage importieren','Export Template':'Vorlage exportieren',

// ===== notifications (75) =====
'Notification Templates':'Benachrichtigungsvorlagen',
'Manage notification templates':'Benachrichtigungsvorlagen verwalten',
'Template Name':'Vorlagenname','Template Type':'Vorlagentyp',
'Email Template':'E-Mail-Vorlage','SMS Template':'SMS-Vorlage',
'Push Template':'Push-Vorlage','Notification Template':'Benachrichtigungsvorlage',
'Subject':'Betreff','Body':'Text','HTML Body':'HTML-Text',
'Plain Text':'Klartext','Variables':'Variablen',
'Available Variables':'Verfügbare Variablen','Insert Variable':'Variable einfügen',
'Preview':'Vorschau','Test Template':'Vorlage testen',
'Send Test':'Test senden','Test Recipient':'Testempfänger',
'Template Categories':'Vorlagenkategorien',
'Booking':'Buchung','Check-in':'Check-in','Check-out':'Check-out',
'Cancellation':'Stornierung','Payment':'Zahlung','Feedback':'Feedback',
'Promotional':'Aktionsangebot','Informational':'Information',
'Emergency':'Notfall','System':'System',
'Delivery Logs':'Zustellungsprotokolle',
'Track notification delivery status':'Zustellungsstatus verfolgen',
'Recipient':'Empfänger','Channel':'Kanal','Status':'Status',
'Delivered':'Zugestellt','Failed':'Fehlgeschlagen','Pending':'Ausstehend',
'Queued':'In Warteschlange','Bounced':'Zurückgewiesen',
'Delivery Time':'Zustellungszeit','Open Time':'Öffnungszeit',
'Click Time':'Klickzeit','Retry':'Wiederholen','Retry All':'Alle wiederholen',
'Delivery Analytics':'Zustellungsanalysen','Delivery Rate':'Zustellungsrate',
'Open Rate':'Öffnungsrate','Click Rate':'Klickrate',
'Channel Performance':'Kanalperformance','Bounce Rate':'Bounce-Rate',
'Notification Settings':'Benachrichtigungseinstellungen',
'Configure notification channels':'Benachrichtigungskanäle konfigurieren',
'Email Settings':'E-Mail-Einstellungen','SMS Settings':'SMS-Einstellungen',
'Push Settings':'Push-Einstellungen','In-App Settings':'In-App-Einstellungen',
'SMTP Configuration':'SMTP-Konfiguration','SMTP Host':'SMTP-Host',
'SMTP Port':'SMTP-Port','SMTP Username':'SMTP-Benutzername',
'SMTP Password':'SMTP-Passwort','Encryption':'Verschlüsselung',
'SMS Provider':'SMS-Anbieter','SMS Gateway':'SMS-Gateway',
'API Key':'API-Schlüssel','From Number':'Absendernummer',
'Push Provider':'Push-Anbieter','FCM':'FCM','APNS':'APNS',
'Server Key':'Server-Schlüssel','Bundle ID':'Bundle-ID',

// ===== guests (57) =====
'Guest Profile':'Gästeprofil','Guest Profiles':'Gästeprofile',
'Manage guest profiles and information':'Gästeprofile und -informationen verwalten',
'Profile':'Profil','Basic Information':'Grundinformationen',
'Personal Details':'Persönliche Daten','Contact Information':'Kontaktinformationen',
'ID Documents':'Ausweisdokumente','Preferences':'Präferenzen',
'Stay History':'Aufenthaltsverlauf','Loyalty Information':'Treueinformationen',
'Communication History':'Kommunikationsverlauf','Special Notes':'Besondere Notizen',
'VIP Status':'VIP-Status','Guest Tags':'Gast-Tags',
'Guest Source':'Gastquelle','Referral Source':'Empfehlungsquelle',
'GDPR Consent':'DSGVO-Einwilligung','Marketing Consent':'Marketing-Einwilligung',
'Data Processing Consent':'Datenverarbeitungseinwilligung',
'Create Guest':'Gast erstellen','Edit Profile':'Profil bearbeiten',
'Merge Profiles':'Profile zusammenführen','Delete Profile':'Profil löschen',
'Search Guests':'Gäste suchen','Advanced Search':'Erweiterte Suche',
'Filter':'Filtern','Sort':'Sortieren','Export':'Exportieren',
'Guest List':'Gästeliste','Recent Guests':'Aktuelle Gäste',
'VIP Guests':'VIP-Gäste','Returning Guests':'Wiederkehrgäste',
'New Guests':'Neue Gäste','All Guests':'Alle Gäste',
'Date of Birth':'Geburtsdatum','Gender':'Geschlecht',
'Nationality':'Nationalität','Passport Number':'Reisepassnummer',
'ID Expiry':'Ausweisablauf','Visa Information':'Visainformationen',
'Phone':'Telefon','Email':'E-Mail',
'Secondary Email':'Sekundäre E-Mail','Work Email':'Geschäfts-E-Mail',
'Address':'Adresse','City':'Stadt','State':'Bundesland',
'Postal Code':'Postleitzahl','Country':'Land',
'Company':'Unternehmen','Job Title':'Position',
'Loyalty Number':'Treuenummer','Loyalty Tier':'Treuestufe',
'Points Balance':'Punktestand','Member Since':'Mitglied seit',
'Room Preferences':'Zimmerpräferenzen','Dietary Preferences':'Ernährungspräferenzen',
'Pillow Type':'Kissensorte','Extra Pillows':'Zusatzkissen',
'Hypoallergenic':'Hypoallergen','Bed Type':'Bettenart',
'Floor Preference':'Etagenpräferenz','High Floor':'Obere Etage',
'Low Floor':'Untere Etage','Quiet Room':'Ruhiges Zimmer',
'Special Requirements':'Besondere Anforderungen',
'Pre-stay communications and preparation':'Vor-Aufenthalts-Kommunikation und Vorbereitung',
'In-stay experiences and services':'Aufenthalts-Erlebnisse und -dienstleistungen',
'Feedback, reviews, and follow-up':'Feedback, Bewertungen und Nachbereitung',
'Loyalty programs and re-engagement':'Treueprogramme und Wiederbindung',
'How the guest found the property':'Wie der Gast die Immobilie gefunden hat',
'Enter reason for rejection...':'Ablehnungsgrund eingeben...',
'Event Type':'Ereignistyp',
'e.g., website_visit, booking_created, check_in':'z.B., website_besuch, buchung_erstellt, check_in',
'Describe what happened...':'Beschreiben Sie, was passiert ist...',
'Journey event added':'Reiseereignis hinzugefügt',
'Title and event type are required':'Titel und Ereignistyp sind erforderlich',

// ===== webhooks (50) =====
'Webhooks':'Webhooks','Webhook Events':'Webhook-Ereignisse',
'Manage webhook endpoints and events':'Webhook-Endpunkte und -ereignisse verwalten',
'Webhook URL':'Webhook-URL','Secret':'Geheimnis',
'Events':'Ereignisse','Subscribe to Events':'Für Ereignisse abonnieren',
'All Events':'Alle Ereignisse','Selected Events':'Ausgewählte Ereignisse',
'Add Event':'Ereignis hinzufügen','Webhook Status':'Webhook-Status',
'Active':'Aktiv','Inactive':'Inaktiv','Paused':'Pausiert',
'Last Delivery':'Letzte Zustellung','Delivery Status':'Zustellungsstatus',
'Success':'Erfolg','Failure':'Fehler','Retry':'Wiederholen',
'Retry Queue':'Warteschlange','Pending Retries':'Ausstehende Wiederholungen',
'Max Retries':'Max. Wiederholungen','Retry Interval':'Wiederholungsintervall',
'Delivery Logs':'Zustellungsprotokolle','Request':'Anfrage',
'Response':'Antwort','Headers':'Header','Payload':'Nutzdaten',
'Response Code':'Antwortcode','Response Time':'Antwortzeit',
'Signature':'Signatur','Signature Verification':'Signaturprüfung',
'HMAC':'HMAC','SHA256':'SHA256',
'Webhook Delivery':'Webhook-Zustellung','Delivery History':'Zustellungsverlauf',
'Successful Deliveries':'Erfolgreiche Zustellungen','Failed Deliveries':'Fehlgeschlagene Zustellungen',
'Retry Queue':'Warteschlange','Manual Retry':'Manuelle Wiederholung',
'Retry All':'Alle wiederholen','Clear Queue':'Warteschlange leeren',
'Webhook Settings':'Webhook-Einstellungen',
'Security Settings':'Sicherheitseinstellungen',
'IP Whitelist':'IP-Whitelist','Rate Limiting':'Ratenbegrenzung',
'Timeout':'Timeout','Connection Timeout':'Verbindungstimeout',

// ===== profile (49) =====
'Profile':'Profil','Account Settings':'Kontoeinstellungen',
'Personal Information':'Persönliche Informationen',
'Update your personal details':'Ihre persönlichen Daten aktualisieren',
'First Name':'Vorname','Last Name':'Nachname',
'Email Address':'E-Mail-Adresse','Phone Number':'Telefonnummer',
'Timezone':'Zeitzone','Language':'Sprache',
'Date Format':'Datumsformat','Time Format':'Zeitformat',
'Currency':'Währung','Avatar':'Avatar','Profile Picture':'Profilbild',
'Change Password':'Passwort ändern','Current Password':'Aktuelles Passwort',
'New Password':'Neues Passwort','Confirm Password':'Passwort bestätigen',
'Password Requirements':'Passwortanforderungen',
'Two-Factor Authentication':'Zwei-Faktor-Authentifizierung',
'Enable 2FA':'2FA aktivieren','Disable 2FA':'2FA deaktivieren',
'Authenticator App':'Authenticator-App','Backup Codes':'Backup-Codes',
'Active Sessions':'Aktive Sitzungen','Session Management':'Sitzungsverwaltung',
'Device':'Gerät','Browser':'Browser','IP Address':'IP-Adresse',
'Location':'Standort','Last Activity':'Letzte Aktivität',
'Revoke Session':'Sitzung widerrufen','Revoke All':'Alle widerrufen',
'Login History':'Anmeldeverlauf','Security Log':'Sicherheitsprotokoll',
'Notification Preferences':'Benachrichtigungseinstellungen',
'Email Notifications':'E-Mail-Benachrichtigungen',
'Push Notifications':'Push-Benachrichtigungen',
'SMS Notifications':'SMS-Benachrichtigungen',
'In-App Notifications':'In-App-Benachrichtigungen',
'Marketing Emails':'Marketing-E-Mails',
'Product Updates':'Produktaktualisierungen',
'Security Alerts':'Sicherheitswarnungen',
'Weekly Digest':'Wöchentliche Zusammenfassung',
'Delete Account':'Konto löschen',
'Export Data':'Daten exportieren',
'Download My Data':'Meine Daten herunterladen',
'If you notice any suspicious activity, revoke the session immediately and change your password.':'Wenn Sie verdächtige Aktivitäten bemerken, widerrufen Sie die Sitzung sofort und ändern Sie Ihr Passwort.',
'Preferences':'Präferenzen',

// ===== gdpr (42) =====
'GDPR Compliance':'DSGVO-Konformität',
'Data Protection':'Datenschutz','Guest Privacy':'Gastdatenschutz',
'Privacy Policy':'Datenschutzerklärung','Cookie Policy':'Cookie-Richtlinie',
'Consent Management':'Einwilligungsverwaltung',
'Manage guest data consent':'Gastdateneinwilligung verwalten',
'Consent Type':'Einwilligungstyp','Consent Status':'Einwilligungsstatus',
'Granted':'Gewährt','Denied':'Verweigert','Revoked':'Widerrufen',
'Consent Date':'Einwilligungsdatum','Revocation Date':'Widerrufsdatum',
'Data Access Requests':'Datenauskunftsersuchen',
'Process guest data access requests':'Gast-Datenauskunftsersuchen verarbeiten',
'Request ID':'Anfrage-ID','Request Type':'Antragstyp',
'Request Date':'Anfragedatum','Request Status':'Antragstatus',
'Pending':'Ausstehend','Processing':'In Bearbeitung',
'Completed':'Abgeschlossen','Expired':'Abgelaufen',
'Respond to Request':'Auf Antrag antworten','Download Data':'Daten herunterladen',
'Data Deletion':'Datenlöschung',
'Delete guest data in compliance with GDPR':'Gastdaten DSGVO-konform löschen',
'Permanently Delete Guest Data?':'Gastdaten dauerhaft löschen?',
'This action cannot be undone. All guest data will be permanently':'Diese Aktion kann nicht rückgängig gemacht werden. Alle Gastdaten werden dauerhaft',
'Deletion Request':'Löschungsantrag','Soft Delete':'Logisches Löschen',
'Hard Delete':'Physisches Löschen','Anonymize':'Anonymisieren',
'This will mark the guest record as deleted but preserve the data.':'Dies markiert den Gastdatensatz als gelöscht, bewahrt aber die Daten.',
'Data Retention':'Datenaufbewahrung',
'Configure data retention policies':'Datenaufbewahrungsrichtlinien konfigurieren',
'Retention Period':'Aufbewahrungsfrist','Auto-Delete':'Automatische Löschung',
'Auto-Anonymize':'Automatische Anonymisierung',
'Retention Policy':'Aufbewahrungsrichtlinie','Policy Name':'Richtlinienname',
'Data Category':'Datenkategorie','Guest Profile Data':'Gästeprofil-Daten',
'Booking Data':'Buchungsdaten','Payment Data':'Zahlungsdaten',
'Communication Data':'Kommunikationsdaten','Feedback Data':'Feedback-Daten',
'Stay History':'Aufenthaltsverlauf','Consent Records':'Einwilligungsprotokolle',
'Privacy Impact Assessment':'Datenschutz-Folgenabschätzung',
'Data Processing Agreement':'Auftragsverarbeitungsvertrag',
'Data Protection Officer':'Datenschutzbeauftragter',
'DPO Contact':'DSB-Kontakt','DPO Name':'DSB-Name',
'DPO Email':'DSB-E-Mail','DPO Phone':'DSB-Telefon',

// ===== bookings (40) =====
'Booking Management':'Buchungsverwaltung',
'Manage all bookings across channels':'Alle Buchungen kanalübergreifend verwalten',
'All Bookings':'Alle Buchungen','New Booking':'Neue Buchung',
'Booking ID':'Buchungs-ID','Confirmation Code':'Bestätigungscode',
'Booking Status':'Buchungsstatus','Guest Name':'Gastname',
'Room Type':'Zimmertyp','Room Number':'Zimmernummer',
'Check-in Date':'Check-in-Datum','Check-out Date':'Check-out-Datum',
'Number of Nights':'Anzahl der Nächte','Total Amount':'Gesamtbetrag',
'Outstanding Balance':'Offener Saldo','Booking Source':'Buchungsquelle',
'Booking Channel':'Buchungskanal','Created Date':'Erstelldatum',
'Modified Date':'Änderungsdatum','Created By':'Erstellt von',
'Modified By':'Geändert von','Internal Notes':'Interne Notizen',
'Guest Notes':'Gastnotizen','Special Requests':'Sonderwünsche',
'Booking Actions':'Buchungsaktionen','Modify Booking':'Buchung ändern',
'Cancel Booking':'Buchung stornieren','Check-in Guest':'Gast einchecken',
'Check-out Guest':'Gast auschecken','Assign Room':'Zimmer zuweisen',
'Reassign Room':'Zimmer neu zuweisen','Send Confirmation':'Bestätigung senden',
'Send Reminder':'Erinnerung senden','Add Note':'Notiz hinzufügen',
'Group Bookings':'Gruppenbuchungen',
'Manage group reservations':'Gruppenreservierungen verwalten',
'Group Name':'Gruppenname','Group Type':'Gruppentyp',
'Corporate':'Geschäftlich','Tour Group':'Reisegruppe',
'Wedding Party':'Hochzeitsgesellschaft','Conference':'Konferenz',
'Sports Team':'Sportmannschaft','Number of Rooms':'Anzahl der Zimmer',
'Block Rooms':'Zimmer blockieren','Release Rooms':'Zimmer freigeben',
'Group Rate':'Gruppentarif','Cut-off Date':'Stichtag',
'Sub-blocks':'Unterblöcke','Rooming List':'Belegungsliste',
'Waitlist Management':'Wartelistenverwaltung',
'Manage waitlisted bookings':'Wartelistenbuchungen verwalten',
'Waitlist Position':'Wartelistenposition',
'Add to Waitlist':'Zur Warteliste hinzufügen',
'Remove from Waitlist':'Von Warteliste entfernen',
'Auto-assign when available':'Automatisch zuweisen bei Verfügbarkeit',
'Booking Conflicts':'Buchungskonflikte',
'Detect and resolve booking conflicts':'Buchungskonflikte erkennen und lösen',
'Conflict Type':'Konflikttyp','Double Booking':'Doppelbuchung',
'Rate Conflict':'Tarifkonflikt','Room Conflict':'Zimmerkonflikt',
'Resolution':'Lösung','Auto-resolve':'Automatisch lösen',
'Manual Resolution':'Manuelle Lösung',
'No-Show Automation':'No-Show-Automatisierung',
'Automate no-show processing':'No-Show-Verarbeitung automatisieren',
'This will scan all confirmed bookings past their check-in deadline and process t...':'Dies scannt alle bestätigten Buchungen, deren Check-in-Frist abgelaufen ist, und verarbeitet diese.',
'No-Show Threshold':'No-Show-Schwelle',
'Auto-Mark as No-Show':'Automatisch als No-Show markieren',
'Apply Penalty':'Strafe anwenden','Release Room':'Zimmer freigeben',
'Cancel Booking':'Buchung stornieren','Send Notification':'Benachrichtigung senden',
'Use the calendar to pick new check-in/check-out dates for this booking.':'Verwenden Sie den Kalender, um neue Check-in/Check-out-Daten für diese Buchung auszuwählen.',

// ===== ai (37) =====
'AI Assistant':'KI-Assistent','AI Provider Settings':'KI-Anbietereinstellungen',
'Configure AI model providers':'KI-Modellanbieter konfigurieren',
'Provider Name':'Anbietername','Provider Type':'Anbietertyp',
'OpenAI':'OpenAI','Anthropic':'Anthropic','Google AI':'Google KI',
'Hugging Face':'Hugging Face','Local Model':'Lokales Modell',
'API Key':'API-Schlüssel','API Endpoint':'API-Endpunkt',
'Model Name':'Modellname','Model Version':'Modellversion',
'Token Limit':'Token-Limit','Temperature':'Temperatur',
'Max Tokens':'Max. Tokens','Top P':'Top P',
'Frequency Penalty':'Frequenz-Strafe','Presence Penalty':'Präsenz-Strafe',
'Test Connection':'Verbindung testen','Connection Status':'Verbindungsstatus',
'AI Copilot':'KI-Copilot',
'AI-powered assistant for your operations':'KI-gestützter Assistent für Ihren Betrieb',
'Ask AI':'KI fragen','Suggested Actions':'Vorgeschlagene Aktionen',
'AI Insights':'KI-Einblicke',
'Actionable insights powered by AI':'KI-gestützte handlungsorientierte Einblicke',
'Pricing and upsell suggestions':'Preis- und Upselling-Vorschläge',
'Guest sentiment analysis':'Gaststimmungsanalyse',
'Demand forecasting':'Nachfrageprognose',
'Revenue optimization recommendations':'Umsatzoptimierungsempfehlungen',
'Staff scheduling suggestions':'Personalplanungsvorschläge',
'Auto-categorize feedback':'Feedback automatisch kategorisieren',
'Smart room assignment':'Intelligente Zimmervergabe',
'Predictive maintenance':'Vorausschauende Wartung',
'AI Settings':'KI-Einstellungen',
'Default Provider':'Standardanbieter','Default Model':'Standardmodell',
'Fallback Provider':'Ersatzanbieter','Max Tokens per Request':'Max. Tokens pro Anfrage',
'Rate Limiting':'Ratenbegrenzung','Requests per Minute':'Anfragen pro Minute',
'Total Budget':'Gesamtbudget','Budget Period':'Budgetzeitraum',
'Monthly':'Monatlich','Usage Tracking':'Nutzungsverfolgung',
'Total Requests':'Gesamtanfragen','Total Tokens':'Gesamttokens',
'Estimated Cost':'Geschätzte Kosten','Actual Cost':'Tatsächliche Kosten',
'Usage by Module':'Nutzung nach Modul','Usage Trends':'Nutzungstrends',

// ===== communication (31) =====
'Guest Communication':'Gästekommunikation',
'Manage guest messaging':'Gastnachrichten verwalten',
'Inbox':'Posteingang','Sent':'Gesendet','Drafts':'Entwürfe',
'Archived':'Archiviert','Spam':'Spam','Trash':'Papierkorb',
'Compose':'Verfassen','New Message':'Neue Nachricht',
'To':'An','CC':'CC','BCC':'BCC',
'Subject':'Betreff','Body':'Text','Attachments':'Anhänge',
'Send':'Senden','Reply':'Antworten','Reply All':'Allen antworten',
'Forward':'Weiterleiten','Mark as Read':'Als gelesen markieren',
'Mark as Unread':'Als ungelesen markieren','Star':'Markieren',
'Archive':'Archivieren','Delete':'Löschen',
'Search':'Suchen','Filter':'Filtern','Sort':'Sortieren',
'Unread':'Ungelesen','Flagged':'Markiert','Has Attachment':'Hat Anhang',
'Unified Inbox':'Einheitlicher Posteingang',
'All channels in one place':'Alle Kanäle an einem Ort',
'Email':'E-Mail','SMS':'SMS','WhatsApp':'WhatsApp',
'Chat':'Chat','Voice':'Sprachnachricht','In-App':'In-App',
'Message Templates':'Nachrichtenvorlagen',
'Quick Responses':'Schnellantworten','Canned Responses':'Vordefinierte Antworten',
'Auto-Responses':'Automatische Antworten',
'Out of Office':'Abwesend','Auto-Reply':'Automatische Antwort',
'Communication Analytics':'Kommunikationsanalysen',
'Response Time':'Antwortzeit','First Response Time':'Erste Antwortzeit',
'Average Response Time':'Durchschn. Antwortzeit',
'Resolution Time':'Lösungszeit','Message Volume':'Nachrichtenvolumen',
'Channel Distribution':'Kanalverteilung','Sentiment Trend':'Stimmungstrend',

// ===== audit (26) =====
'Audit Logs':'Prüfprotokolle',
'Track all system activities and changes':'Alle Systemaktivitäten und -änderungen verfolgen',
'Log Entry':'Protokolleintrag','Timestamp':'Zeitstempel',
'User':'Benutzer','Action':'Aktion','Resource':'Ressource',
'Details':'Details','IP Address':'IP-Adresse',
'User Agent':'User-Agent','Session ID':'Sitzungs-ID',
'Filter by':'Filtern nach','Date Range':'Zeitraum',
'Action Type':'Aktionstyp','Create':'Erstellen','Read':'Lesen',
'Update':'Aktualisieren','Delete':'Löschen','Login':'Anmeldung',
'Logout':'Abmeldung','Export':'Exportieren','Download':'Herunterladen',
'Search':'Suchen','Clear Filters':'Filter löschen',
'Recent Activity':'Aktuelle Aktivität','All Activity':'Alle Aktivitäten',
'Critical Events':'Kritische Ereignisse','Security Events':'Sicherheitsereignisse',
'Data Events':'Datenereignisse','Configuration Changes':'Konfigurationsänderungen',
'Access Events':'Zugriffsereignisse',
};

// Apply translations
let newTranslations = 0;
for (const [eng, ger] of Object.entries(PH)) {
  // Find keys whose value matches this English phrase
  for (const [k, v] of Object.entries(src)) {
    if (T[k]) continue;
    if (v === eng || v.trim() === eng) {
      T[k] = ger;
      newTranslations++;
    }
  }
}

console.log('Phrase-based translations: ' + newTranslations);
console.log('Total translations: ' + Object.keys(T).length);

const remaining2 = Object.keys(src).filter(k => !(k in T));
console.log('Still remaining: ' + remaining2.length);

fs.writeFileSync('/tmp/de_translations_all2.json', JSON.stringify(T, null, 2));
fs.writeFileSync('/tmp/de_remaining_final.json', JSON.stringify(remaining));
