import fs from 'fs';

const T = JSON.parse(fs.readFileSync('/tmp/de_translations_final.json','utf8'));
const src = JSON.parse(fs.readFileSync('/tmp/de_keys.json','utf8'));
const remaining = Object.keys(src).filter(k => !(k in T));

// Massive comprehensive translation dictionary for remaining keys
const DICT = {
// admin
'admin.neither':'Weder','admin.rolePermissionAuditLog':'Rollen- & Berechtigungs-Prüfprotokoll',
'admin.recentChangesToRolesAndPermissionAssignments':'Aktuelle Änderungen an Rollen und Berechtigungszuweisungen',
'admin.entity':'Entität','admin.auditTrail':'Prüfpfad','admin.rolesPermissions':'Rollen & Berechtigungen',
'admin.manageAccessControlRolesAndPermissionAssignments':'Zugangskontrolle, Rollen und Berechtigungszuweisungen verwalten',
'admin.manageRolesFor':'Rollen verwalten für:','admin.permissionMatrix':'Berechtigungsmatrix',
'admin.matrix':'Matrix','admin.test':'Test','admin.compare':'Vergleichen',
'admin.auditLog':'Prüfprotokoll','admin.audit':'Prüfung',
'admin.lowercaseLettersNumbersAndUnderscoresOnly':'Nur Kleinbuchstaben, Zahlen und Unterstriche',
'admin.displayName':'Anzeigename','admin.quickPermissions':'Schnellberechtigungen',
'admin.noAccess':'Kein Zugriff','admin.adminPermissionsCannotBeModified':'Admin-Berechtigungen können nicht geändert werden',
'admin.fullAccess':'Vollzugriff','admin.openInMatrix':'In Matrix öffnen',
'admin.egBookingsviewGuestscreate':'z.B. bookings.view, guests.create',
'admin.egFrontdesklead':'z.B. front_desk_lead','admin.egFrontDeskLead':'z.B. Empfangsleiter',
'admin.optionalDescription':'Optionale Beschreibung',
'admin.nameAndDisplayNameAreRequired':'Name und Anzeigename sind erforderlich',
'admin.roleNameMustStartWithLowercaseLetterAndContainOnlyLowercaseLettersNumbersAndUnderscores':'Rollenname muss mit einem Kleinbuchstaben beginnen und nur Kleinbuchstaben, Zahlen und Unterstriche enthalten',
'admin.cannotModifyAdminRolePermissions':'Admin-Rollenberechtigungen können nicht geändert werden',
'admin.role1':'Rolle 1','admin.role2':'Rolle 2','admin.displayName_1':'Anzeigename *',
'admin.systemHealth':'Systemzustand','admin.monitorPlatformPerformanceAndServiceStatus':'Plattformleistung und Dienststatus überwachen',
'admin.systemUptime':'Systemverfügbarkeit','admin.realtimeStatusOfAllPlatformServices':'Echtzeit-Status aller Plattformdienste',
'admin.databaseMetrics':'Datenbank-Kennzahlen','admin.queriessec':'Abfragen/Sek.',
'admin.avgLatency':'Durchschn. Latenz','admin.connectionPool':'Verbindungspool',
'admin.storage':'Speicher','admin.storageUsed':'Speicher verwendet',
'admin.recentAlerts':'Aktuelle Warnungen','admin.noActiveAlerts':'Keine aktiven Warnungen',
'admin.manageTenantStatusSubscriptionsAndPlanChanges':'Mandantenstatus, Abonnements und Tarifänderungen verwalten',
'admin.onTrial':'In Testphase','admin.trialsExpiringSoon':'Testphasen laufen bald ab',
'admin.starter':'Starter','admin.professional':'Professional','admin.enterprise':'Enterprise',
'admin.tenantSubscriptions':'Mandantenabonnements',
'admin.manageTenantStatusTransitionsAndPlanChanges':'Mandantenstatusübergänge und Tarifänderungen verwalten',
'admin.plan':'Tarif','admin.usage':'Nutzung','admin.trialsubscription':'Testphase/Abonnement',
'admin.noTenantsFoundMatchingYourCriteria':'Keine Mandanten entsprechen Ihren Kriterien.',
'admin.planChangeSummary':'Tarifänderungs-Zusammenfassung','admin.from':'Von:','admin.to':'An:',
'admin.priceDifference':'Preisdifferenz:','admin.confirmStatusChange':'Statusänderung bestätigen',
'admin.youAreAboutToChangeTheStatusOf':'Sie sind dabei, den Status von folgendem zu ändern:',
'admin.downgradePlan':'Tarif herabstufen','admin.upgradePlan':'Tarif upgraden',
'admin.tenantStatusChangedToNewstatus':'Mandantenstatus geändert zu ${newStatus}',
'admin.manageAllHotelTenantsAndSubscriptions':'Alle Hotel-Mandanten und Abonnements verwalten',
'admin.configureTenantDetailsAndSubscription':'Mandantendetails und Abonnement konfigurieren',
'admin.name':'Name','admin.slug':'Slug','admin.plan_1':'Tarif',
'admin.starter_1':'Starter','admin.professional_1':'Professional','admin.enterprise_1':'Enterprise',
'admin.maxProperties':'Max. Immobilien','admin.maxUsers':'Max. Benutzer','admin.maxRooms':'Max. Zimmer',
'admin.onTrial_1':'In Testphase','admin.monthlyRevenue':'Monatsumsatz',
'admin.tenantStatusUpdated':'Mandantenstatus aktualisiert','admin.tenantDeleted':'Mandant gelöscht',
'admin.unableToLoadUsageData':'Nutzungsdaten können nicht geladen werden',
'admin.apiCalls':'API-Aufrufe','admin.storage_1':'Speicher','admin.messages':'Nachrichten',
'admin.accountLimits':'Kontolimits','admin.apiUsageBreakdown':'API-Nutzungsaufschlüsselung',
'admin.usageAlerts':'Nutzungswarnungen','admin.loadingUserManagement':'Benutzerverwaltung wird geladen...',
'admin.noRole':'Keine Rolle','admin.tenant_2':'Mandant:','admin.verified':'Verifiziert',
'admin.lastLogin':'Letzte Anmeldung','admin.deactivate':'Deaktivieren','admin.activate':'Aktivieren',
'admin.grantFullAccessToAllTenantsAndPlatformlevelFeatures':'Vollzugriff auf alle Mandanten und Plattformfunktionen gewähren',
'admin.minimum6Characters':'Mindestens 6 Zeichen','admin.manager':'Manager',
'admin.pleaseFillInAllRequiredFields':'Bitte füllen Sie alle Pflichtfelder aus',
'admin.pleaseEnterANewPassword':'Bitte geben Sie ein neues Passwort ein',
'admin.passwordMustBeAtLeast6Characters':'Passwort muss mindestens 6 Zeichen lang sein',
'admin.tenant_4':'Mandant *','admin.firstName':'Vorname *','admin.lastName':'Nachname *',
'admin.email_1':'E-Mail *','admin.newPassword':'Neues Passwort *',
// channels remaining
'channels.resolve':'Lösen','channels.sync':'Synchronisieren','channels.conflictResolved':'Konflikt gelöst',
'channels.manageYourCentralReservationSystemAndBookingSources':'Ihr zentrales Reservierungssystem und Ihre Buchungsquellen verwalten',
'channels.crsConnections':'CRS-Verbindungen','channels.bookingSources':'Buchungsquellen',
'channels.noCrsConnectionsConfigured':'Keine CRS-Verbindungen konfiguriert',
'channels.theInternalCrsIsAvailableByDefault':'Das interne CRS ist standardmäßig verfügbar',
'channels.autoSync':'Auto-Sync','channels.test':'Test','channels.features':'Funktionen:',
'channels.commission':'Provision','channels.connectionName':'Verbindungsname',
'channels.syncIntervalMinutes':'Sync-Intervall (Minuten)','channels.featuresToSync':'Zu synchronisierende Funktionen',
'channels.testingConnection':'Verbindung wird getestet...','channels.connectionUpdated':'Verbindung aktualisiert',
'channels.monitorRoomAvailabilityAcrossAllChannels':'Zimmerverfügbarkeit über alle Kanäle überwachen',
'channels.synced_1':'Synchronisiert','channels.errors':'Fehler','channels.syncRate':'Sync-Rate',
'channels.sync_1':'Synchronisieren','channels.syncProgress':'Sync-Fortschritt','channels.lastSync_1':'Letzte Sync.',
'channels.direction_1':'Richtung','channels.inventorySyncInitiatedForAllChannels':'Bestandssync für alle Kanäle gestartet',
'channels.syncingInventoryForChannelname':'Bestand wird für ${channelName} synchronisiert',
'channels.mapYourRoomTypesAndRatePlansToExternalChannels':'Ordnen Sie Ihre Zimmertypen und Tarifpläne externen Kanälen zu',
'channels.linkYourRoomTypesAndRatePlansToExternalChannelProducts':'Verknüpfen Sie Ihre Zimmertypen und Tarifpläne mit externen Kanalprodukten',
'channels.ratePlanOptional':'Tarifplan (optional)','channels.noRatePlan':'Kein Tarifplan',
'channels.externalRoomId':'Externe Zimmer-ID','channels.externalRoomName':'Externer Zimmername',
'channels.externalRateIdOptional':'Externe Tarif-ID (optional)','channels.externalRateName':'Externer Tarifname',
'channels.syncInventory':'Bestand synchronisieren','channels.syncRates':'Tarife synchronisieren',
'channels.syncRestrictions':'Einschränkungen synchronisieren','channels.inventorySync_1':'Bestandssync',
'channels.noChannelMappingsConfigured':'Keine Kanalzuordnungen konfiguriert','channels.ratePlan':'Tarifplan',
'channels.externalRoom':'Externes Zimmer','channels.externalRate':'Externer Tarif',
'channels.syncInv':'Bestand sync.','channels.syncRest':'Einschränkungen sync.',
'channels.egBcstd001':'z.B., BC_STD_001','channels.egStandardDoubleRoom':'z.B., Standard Doppelzimmer',
'channels.egBcbar':'z.B., BC_BAR','channels.egBestAvailableRate':'z.B., Bester verfügbarer Tarif',
'channels.itemslengthMappingsConfigured':'{items.length} Zuordnungen konfiguriert',
'channels.mappingUpdated':'Zuordnung aktualisiert','channels.mappingDeleted':'Zuordnung gelöscht',
'channels.mappingCreated':'Zuordnung erstellt','channels.global':'Global','channels.india':'Indien',
'channels.asiaPacific':'Asien-Pazifik','channels.europe':'Europa','channels.middleEast':'Naher Osten',
'channels.africa':'Afrika','channels.apiCredentials':'API-Zugangsdaten','channels.displayName':'Anzeigename',
'channels.autoSync_1':'Auto-Sync','channels.automaticallySyncInventoryAndRates':'Bestand und Tarife automatisch synchronisieren',
'channels.syncInterval_1':'Sync-Intervall','channels.docs':'Dokumentation','channels.errors_1':'Fehler',
'channels.integrationProgress':'Integrationsfortschritt','channels.noChannelConnections':'Keine Kanalverbindungen',
'channels.connect':'Verbinden','channels.successful':'Erfolgreich','channels.autosync':'Auto-Sync',
'channels.criticalPriority':'Kritische Priorität','channels.realtime':'Echtzeit','channels.region':'Region',
'channels.connectionTestSuccessful':'Verbindungstest erfolgreich!','channels.connectionTestFailed':'Verbindungstest fehlgeschlagen',
'channels.pleaseSelectAChannel':'Bitte wählen Sie einen Kanal',
'channels.channelConnectionCreatedSuccessfully':'Kanalverbindung erfolgreich erstellt!',
'channels.every2Hours':'Alle 2 Stunden','channels.every6Hours':'Alle 6 Stunden',
'channels.synced_2':'Synchronisiert','channels.higher':'Höher','channels.lower':'Niedriger',
'channels.unknown_1':'Unbekannt','channels.rateSync_1':'Tarifsync',
'channels.manageRatesAcrossAllDistributionChannels':'Tarife über alle Vertriebskanäle verwalten',
'channels.outOfSync':'Nicht synchronisiert','channels.errors_2':'Fehler','channels.avgRate':'Durchschn. Tarif',
'channels.noRateSyncDataAvailable':'Keine Tarif-Sync-Daten verfügbar',
'channels.connectChannelsAndConfigureRatePlansToSeeSyncStatus':'Kanäle verbinden und Tarifpläne konfigurieren, um Sync-Status zu sehen',
'channels.ratePlan_1':'Tarifplan','channels.basePrice':'Basispreis','channels.channelPrice':'Kanalpreis',
'channels.diff':'Diff','channels.autoAdjust':'Auto-Anpassung','channels.lastSync_2':'Letzte Sync.',
'channels.basePriceReference':'Basispreis (Referenz)','channels.pleaseEnterAValidPrice':'Bitte geben Sie einen gültigen Preis ein',
'channels.channelRestrictions':'Kanaleinschränkungen',
'channels.manageMinStayCtaCtdAndStopsellAcrossChannels':'Mindestaufenthalt, CTA, CTD und Stop-Sell kanalübergreifend verwalten',
'channels.stopSell':'Stop-Sell','channels.noRestrictionsConfigured':'Keine Einschränkungen konfiguriert',
'channels.connectChannelsToConfigureRestrictions':'Kanäle verbinden, um Einschränkungen zu konfigurieren',
'channels.noLimit':'Kein Limit','channels.minimumStayNights':'Mindestaufenthalt (Nächte)',
'channels.maximumStayNights':'Maximalaufenthalt (Nächte)','channels.closedToArrivalCta':'Geschlossen für Ankunft (CTA)',
'channels.guestsCannotCheckInOnThisDate':'Gäste können an diesem Datum nicht einchecken',
'channels.closedToDepartureCtd':'Geschlossen für Abreise (CTD)',
'channels.guestsCannotCheckOutOnThisDate':'Gäste können an diesem Datum nicht auschecken',
'channels.itemslengthRestrictionRulesConfigured':'{items.length} Einschränkungsregeln konfiguriert',
'channels.invalidRestrictionId':'Ungültige Einschränkungs-ID','channels.successful_1':'Erfolgreich',
'channels.successRate':'Erfolgsquote','channels.direction_2':'Richtung','channels.httpCode':'HTTP-Code',
'channels.attempts':'Versuche','channels.correlationId':'Korrelations-ID',
'channels.inbound_1':'Eingehend','channels.outbound_1':'Ausgehend',
// crm remaining
'crm.marketingCampaigns':'Marketingkampagnen','crm.avgOpenRate':'Durchschn. Öffnungsrate',
'crm.avgClickRate':'Durchschn. Klickrate','crm.stats':'Statistik',
'crm.configureYourMarketingCampaignDetailsAndTargetAudience':'Marketingkampagnendetails und Zielgruppe konfigurieren',
'crm.content':'Inhalt','crm.targetSegments':'Zielsegmente',
'crm.noSegmentsAvailableCreateSegmentsFirst':'Keine Segmente verfügbar. Erstellen Sie zuerst Segmente.',
'crm.scheduleOptional':'Zeitplan (optional)','crm.scheduleCampaign':'Kampagne planen',
'crm.deliveryProgress':'Zustellungsfortschritt','crm.egSummerPromotion2024':'z.B., Sommeraktion 2024',
'crm.briefDescriptionOfTheCampaign':'Kurzbeschreibung der Kampagne',
'crm.emailSubjectLine':'E-Mail-Betreffzeile','crm.campaignStatusUpdated':'Kampagnenstatus aktualisiert',
'crm.feedbackReviews':'Feedback & Bewertungen',
'crm.monitorGuestReviewsAndManageFeedbackAcrossAllChannels':'Gastbewertungen überwachen und Feedback kanalübergreifend verwalten',
'crm.avgRating':'Durchschn. Bewertung','crm.positiveSentiment':'Positive Stimmung',
'crm.openFeedback':'Offenes Feedback','crm.cleanliness':'Sauberkeit:','crm.service':'Service:',
'crm.location':'Standort:','crm.complaints':'Beschwerden','crm.compliments':'Komplimente',
'crm.suggestions':'Vorschläge','crm.resolution':'Lösung:','crm.resolve':'Lösen',
'crm.reviewResponse':'Bewertungsantwort','crm.yourResponse':'Ihre Antwort',
'crm.resolveFeedback':'Feedback lösen','crm.writeYourResponse':'Schreiben Sie Ihre Antwort...',
'crm.describeHowThisWasResolved':'Beschreiben Sie, wie dies gelöst wurde...',
'crm.avgMemberssegment':'Durchschn. Mitglieder/Segment','crm.segmentationRules':'Segmentierungsregeln',
'crm.guestsMustMatchAllConditionsToBeIncluded':'Gäste müssen alle Bedingungen erfüllen, um eingeschlossen zu werden',
'crm.noConditionsAddedAddConditionsToDefineYourSegment':'Keine Bedingungen hinzugefügt. Fügen Sie Bedingungen hinzu, um Ihr Segment zu definieren.',
'crm.egVipGuestsFrequentTravelers':'z.B., VIP-Gäste, Häufige Reisende',
'crm.describeThePurposeOfThisSegment':'Beschreiben Sie den Zweck dieses Segments',
'crm.operator':'Operator','crm.segmentNameIsRequired':'Segmentname ist erforderlich',
'crm.loyaltyPrograms':'Treueprogramme',
'crm.manageGuestLoyaltyTiersRewardsAndBenefits':'Gast-Treuestufen, Prämien und Vorteile verwalten',
'crm.pointsEarnedMonth':'Verdiente Punkte (Monat)','crm.pointsRedeemedMonth':'Eingelöste Punkte (Monat)',
'crm.avgPointsmember':'Durchschn. Punkte/Mitglied','crm.tierLevels':'Stufenstufen',
'crm.redemptionOptions':'Einlösungsoptionen','crm.topMembers':'Top-Mitglieder','crm.benefits':'Vorteile:',
'crm.memberDistribution':'Mitgliederverteilung','crm.pointsRedemptionOptions':'Punkte-Einlösungsoptionen',
'crm.availableRewardsThatGuestsCanRedeemWithTheirPoints':'Verfügbare Prämien, die Gäste mit ihren Punkten einlösen können',
'crm.pointsValue':'Punktwert','crm.estimatedValueOfLoyaltyPoints':'Geschätzter Wert der Treuepunkte',
'crm.perPointValue':'Wert pro Punkt','crm.pointsForFreeNight':'Punkte für freie Nacht',
'crm.topLoyaltyMembers':'Top-Treuemitglieder','crm.highestPointEarnersAcrossAllTiers':'Höchste Punkteverdiener über alle Stufen',
'crm.tierminpointstolocalestringTiermaxpoints999999TiermaxpointstolocalestringPoints':'{tier.minPoints.toLocaleString()} - {tier.maxPoints === 999999 ? \'∞\' : tier.maxPoints.toLocaleString()} Punkte',
'crm.cohortAnalysis':'Kohortenanalyse','crm.atriskGuests':'Gefährdete Gäste','crm.lifetimeValue':'Lebenszeitwert',
'crm.guestJourneyFunnel':'Gäste-Reise-Funnel','crm.conversionThroughGuestLifecycleStages':'Konversion über Gastlebenszyklus-Phasen',
'crm.noGuestDataAvailableForFunnelAnalysis':'Keine Gastdaten für Funnel-Analyse verfügbar',
'crm.retentionInsights':'Bindungseinblicke','crm.keyMetricsDerivedFromGuestData':'Schlüsselkennzahlen aus Gastdaten',
'crm.insightsRequireGuestData':'Einblicke erfordern Gastdaten','crm.retentionActivity':'Bindungsaktivität',
'crm.overallRetentionRate':'Gesamtbindungsrate','crm.overallChurnRate':'Gesamt-Abwanderungsrate',
'crm.cohortRetentionAnalysis':'Kohorten-Bindungsanalyse',
'crm.trackGuestRetentionByAcquisitionMonth':'Gastbindung nach Akquisitionsmonat verfolgen',
'crm.cohortAnalysisRequiresHistoricalData':'Kohortenanalyse erfordert historische Daten',
'crm.cohort':'Kohorte','crm.guestsWithHighChurnProbabilityRequiringAttention':'Gäste mit hoher Abwanderungswahrscheinlichkeit, die Aufmerksamkeit erfordern',
'crm.noAtriskGuestsIdentified':'Keine gefährdeten Gäste identifiziert',
'crm.noLifetimeValueDataAvailable':'Keine Lebenszeitwertdaten verfügbar',
'crm.averageLifetimeValue':'Durchschn. Lebenszeitwert','crm.avgStays':'Durchschn. Aufenthalte',
'crm.avgSpend':'Durchschn. Ausgaben','crm.ltvByLoyaltyTier':'LTV nach Treuestufe',
'crm.comparisonOfAverageLifetimeValueAcrossTiers':'Vergleich des durchschn. Lebenszeitwerts über Stufen',
'crm.noLtvDataAvailable':'Keine LTV-Daten verfügbar',
'crm.guestsWithMultipleStaysAcrossDifferentMonthsAreNeededToCalculateCohortRetentionThisViewWillPopulateAsYourGuestDatabaseGrows':'Gäste mit mehreren Aufenthalten in verschiedenen Monaten sind erforderlich, um Kohortenbindung zu berechnen.\n                    Diese Ansicht wird sich füllen, wenn Ihre Gastdatenbank wächst.',
// marketing remaining
'marketing.appearance':'Erscheinungsbild','marketing.integration':'Integration',
'marketing.distributionOfBookingsBySource':'Buchungsverteilung nach Quelle',
'marketing.directBooking':'Direktbuchung','marketing.otaChannels':'OTA-Kanäle',
'marketing.recentPerformance':'Aktuelle Leistung','marketing.bookingAttempts':'Buchungsversuche',
'marketing.completedBookings':'Abgeschlossene Buchungen','marketing.abandonmentRate':'Abbruchquote',
'marketing.commissionComparison':'Provisionsvergleich',
'marketing.howMuchYouSaveByDrivingDirectBookings':'Wie viel Sie durch Direktbuchungen sparen',
'marketing.directBookingSavings':'Direktbuchungs-Einsparungen',
'marketing.configureHowYourBookingEngineWorks':'Konfigurieren Sie, wie Ihre Buchungsmaschine funktioniert',
'marketing.turnOnoffYourDirectBookingPage':'Direktbuchungsseite ein-/ausschalten',
'marketing.customDomainOptional':'Benutzerdefinierte Domain (optional)',
'marketing.useYourOwnDomainForTheBookingPage':'Verwenden Sie Ihre eigene Domain für die Buchungsseite',
'marketing.displayRoomPricesOnTheBookingPage':'Zimmerpreise auf der Buchungsseite anzeigen',
'marketing.requirePayment':'Zahlung erforderlich','marketing.requirePaymentAtTimeOfBooking':'Zahlung zum Buchungszeitpunkt erforderlich',
'marketing.depositPercentage':'Anzahlungsprozentsatz','marketing.cancellationPolicy':'Stornierungsbedingung',
'marketing.nonrefundable':'Nicht erstattungsfähig','marketing.customPolicy':'Benutzerdefinierte Richtlinie',
'marketing.termsConditionsUrl':'AGB-URL','marketing.privacyPolicyUrl':'Datenschutz-URL',
'marketing.brandingAppearance':'Branding & Erscheinungsbild',
'marketing.customizeTheLookOfYourBookingPage':'Das Aussehen Ihrer Buchungsseite anpassen',
'marketing.logo':'Logo','marketing.embedWidget':'Widget einbetten','marketing.analyticsIntegration':'Analytik-Integration',
'marketing.bookyourhotelcom':'buchung.ihrhotel.de','marketing.last30DaysPerformance':'Leistung der letzten 30 Tage',
'marketing.copiedToClipboard':'In die Zwischenablage kopiert',
'marketing.freeCancellationUpTo24Hours':'Kostenlose Stornierung bis zu 24 Stunden vorher',
'marketing.freeCancellationUpTo48Hours':'Kostenlose Stornierung bis zu 48 Stunden vorher',
'marketing.freeCancellationUpTo7Days':'Kostenlose Stornierung bis zu 7 Tage vorher',
'marketing.recommendedPngOrSvgMax500kb200x80px':'Empfohlen: PNG oder SVG, max. 500KB, 200x80px',
'marketing.promotionsAmpOffers':'Aktionen & Angebote',
'marketing.manageDiscountCodesSeasonalPackagesAndSpecialOffers':'Rabattcodes, Saisonpakete und Sonderangebote verwalten',
'marketing.currentlyRunning':'Derzeit aktiv','marketing.cumulativeDiscountValue':'Kumulativer Rabattwert',
'marketing.expiringSoon':'Läuft bald ab','marketing.fixedAmount':'Festbetrag','marketing.usage':'Nutzung',
'marketing.pause':'Pausieren','marketing.activate':'Aktivieren','marketing.basicInfo':'Grundinformationen',
'marketing.maximumDiscountAmountForPercentagebasedOffers':'Maximaler Rabattbetrag für prozentuale Angebote',
'marketing.restrictions':'Einschränkungen','marketing.minNights':'Min. Nächte',
'marketing.noRoomTypesFoundRoomTypeFilteringWillBeUnavailable':'Keine Zimmertypen gefunden. Zimmertyp-Filterung ist nicht verfügbar.',
'marketing.leaveEmptyToApplyToAllRoomTypes':'Leer lassen, um auf alle Zimmertypen anzuwenden',
'marketing.usageLimits':'Nutzungslimits','marketing.maxTotalUses':'Max. Gesamtverwendungen',
'marketing.leaveEmptyForUnlimited':'Leer lassen für unbegrenzt','marketing.maxUsesPerUser':'Max. Verwendungen pro Benutzer',
'marketing.egSummerSale20Off':'z.B., Sommerschlussverkauf 20% Rabatt','marketing.egSummer20':'z.B., SOMMER20',
'marketing.describeYourPromotion':'Beschreiben Sie Ihre Aktion...','marketing.eg2000':'z.B., 2000',
'marketing.eg5000':'z.B., 5000','marketing.eg2':'z.B., 2','marketing.eg100':'z.B., 100','marketing.eg1':'z.B., 1',
'marketing.pleaseFillInAllRequiredFields':'Bitte füllen Sie alle Pflichtfelder aus',
'marketing.promotionDeleted':'Aktion gelöscht','marketing.promoCodeCopiedToClipboard':'Aktionscode kopiert',
'marketing.discountType':'Rabatttyp *','marketing.discountValue':'Rabattwert *',
'marketing.percentage_1':'Prozentsatz (%)','marketing.endingWithin7Days':'Endet innerhalb von 7 Tagen',
'marketing.thisActionCannotBeUndoneThePromotionCodeWillBePermanentlyRemovedAndAnyExistingBookingsUsingThisCodeWillNotBeAffectedButTheCodeWillNoLongerBeValidForNewBookings':'Diese Aktion kann nicht rückgängig gemacht werden. Der Aktionscode wird dauerhaft entfernt. Bestehende\n              Buchungen mit diesem Code sind nicht betroffen, aber der Code ist nicht mehr für neue Buchungen gültig.',
'marketing.monitorAndRespondToReviewsFromAllSources':'Bewertungen aus allen Quellen überwachen und darauf antworten',
'marketing.acrossAllPlatforms':'Über alle Plattformen','marketing.sentimentScore':'Stimmungspunktzahl',
'marketing.breakdownOfRatingsAcrossAllReviews':'Aufschlüsselung der Bewertungen über alle Bewertungen',
'marketing.categoryScores':'Kategoriebewertungen','marketing.averageRatingsByCategory':'Durchschn. Bewertungen nach Kategorie',
'marketing.positive':'Positiv','marketing.neutral':'Neutral','marketing.negative':'Negativ',
'marketing.recentReviews':'Aktuelle Bewertungen','marketing.propertyResponse':'Immobilien-Antwort',
'marketing.respond':'Antworten','marketing.writeAResponseToThisGuestReview':'Schreiben Sie eine Antwort auf diese Gästebewertung',
'marketing.yourResponse':'Ihre Antwort','marketing.sentiment':'Stimmung',
'marketing.writeYourResponseHere':'Schreiben Sie Ihre Antwort hier...',
'marketing.showingDatareviewslengthOfDatapaginationtotalReviews':'{data.reviews.length} von {data.pagination.total} Bewertungen anzeigen',
'marketing.connectAndManageExternalReviewPlatforms':'Externe Bewertungsplattformen verbinden und verwalten',
'marketing.connectedSources':'Verbundene Quellen','marketing.fromAllSources':'Aus allen Quellen',
'marketing.avgRating':'Durchschn. Bewertung','marketing.acrossPlatforms':'Plattformübergreifend',
'marketing.syncStatus':'Sync-Status','marketing.lastSync':'Letzte Sync.','marketing.autoSync':'Auto-Sync',
'marketing.never':'Nie','marketing.availablePlatforms':'Verfügbare Plattformen',
'marketing.connectToMoreReviewPlatformsToAggregateAllYourReviews':'Verbinden Sie weitere Bewertungsplattformen, um alle Ihre Bewertungen zu aggregieren',
'marketing.enterYourApiCredentialsToConnectTheReviewPlatform':'Geben Sie Ihre API-Zugangsdaten ein, um die Bewertungsplattform zu verbinden',
'marketing.connectionName':'Verbindungsname','marketing.propertylocationId':'Immobilien-/Standort-ID',
'marketing.disconnect':'Trennen','marketing.syncNow':'Jetzt synchronisieren',
'marketing.enterYourApiKey':'Geben Sie Ihren API-Schlüssel ein',
'marketing.yourPropertyIdOnThePlatform':'Ihre Immobilien-ID auf der Plattform',
'marketing.pleaseFillInAllRequiredFields_1':'Bitte füllen Sie alle Pflichtfelder aus',
'marketing.startingSyncForSourcename':'Sync wird gestartet für ${source.name}...',
'marketing.syncFailedPleaseTryAgain':'Sync fehlgeschlagen. Bitte versuchen Sie es erneut.',
'marketing.reviewSourceDisconnected':'Bewertungsquelle getrennt',
// automation remaining
'automation.monitorAutomationExecutionsAndTroubleshootIssues':'Automatisierungsausführungen überwachen und Probleme beheben',
'automation.successful':'Erfolgreich','automation.successRate':'Erfolgsquote','automation.triggerData':'Auslöser-Daten',
'automation.noTriggerData':'Keine Auslöser-Daten','automation.actionsResult':'Aktions-Ergebnis',
'automation.ruleId':'Regel-ID:','automation.trigger':'Auslöser:','automation.logId':'Protokoll-ID:',
'automation.showingLogslengthOfStatstotalexecutionsTotalExecutions':'{logs.length} von {stats.totalExecutions} Gesamtausführungen',
'automation.executions':'Ausführungen','automation.successRate_1':'Erfolgsquote',
'automation.trigger_1':'Auslöser:','automation.configureTriggerEventsAndActionsForThisRule':'Auslöser-Ereignisse und Aktionen für diese Regel konfigurieren',
'automation.triggerEvent':'Auslöser-Ereignis','automation.triggerConditions':'Auslöser-Bedingungen',
'automation.defineWhatHappensWhenTheTriggerFires':'Definieren Sie, was passiert, wenn der Auslöser auslöst',
'automation.pushNotification':'Push-Benachrichtigung',
'automation.ruleWillRunAutomaticallyWhenActive':'Regel wird automatisch ausgeführt, wenn aktiv',
'automation.saving':'Wird gespeichert...','automation.deleting':'Wird gelöscht...',
'automation.egSendWelcomeEmailOnBooking':'z.B., Willkommens-E-Mail bei Buchung senden',
'automation.describeWhatThisRuleDoes':'Beschreiben Sie, was diese Regel tut',
'automation.pleaseSelectAnActionType':'Bitte wählen Sie einen Aktionstyp',
'automation.nameTriggerAndAtLeastOneActionAreRequired':'Name, Auslöser und mindestens eine Aktion sind erforderlich',
'automation.triggerConditionsMustBeValidJson':'Auslöser-Bedingungen müssen gültiges JSON sein',
'automation.automationTemplates':'Automatisierungsvorlagen',
'automation.prebuiltAutomationTemplatesToGetYouStartedQuickly':'Vorgefertigte Automatisierungsvorlagen für einen schnellen Einstieg',
'automation.trySelectingADifferentCategory':'Versuchen Sie eine andere Kategorie',
'automation.popular':'Beliebt','automation.premium':'Premium','automation.trigger_2':'Auslöser:',
'automation.actions_1':'Aktionen:','automation.customizeTemplate':'Vorlage anpassen',
'automation.giveYourAutomationANameAndDescription':'Geben Sie Ihrer Automatisierung einen Namen und eine Beschreibung',
'automation.name':'Name','automation.templateIncludes':'Vorlage beinhaltet:','automation.creating':'Wird erstellt...',
'automation.automationName':'Automatisierungsname','automation.whatThisAutomationDoes':'Was diese Automatisierung tut',
'automation.pleaseEnterANameForTheAutomation':'Bitte geben Sie einen Namen für die Automatisierung ein',
'automation.automationCreatedFromTemplate':'Automatisierung aus Vorlage erstellt',
'automation.savedWorkflows':'Gespeicherte Workflows','automation.noWorkflowsYet':'Noch keine Workflows',
'automation.startBuildingYourWorkflow':'Beginnen Sie Ihren Workflow zu erstellen',
'automation.welcomeEmail':'Willkommens-E-Mail','automation.bookingConfirmation':'Buchungsbestätigung',
'automation.checkoutSummary':'Check-out-Zusammenfassung','automation.feedbackRequest':'Feedback-Anfrage',
'automation.messageTemplate':'Nachrichtenvorlage','automation.descriptionOptional':'Beschreibung (optional)',
'automation.enterSmsMessage':'SMS-Nachricht eingeben...','automation.clearCanvas':'Leinwand leeren',
'automation.pleaseSelectAnOption':'Bitte wählen Sie eine Option',
'automation.workflowNameIsRequired':'Workflowname ist erforderlich',
'automation.workflowMustHaveATrigger':'Workflow muss einen Auslöser haben',
'automation.workflowMustHaveAtLeastOneAction':'Workflow muss mindestens eine Aktion haben',
// inventory remaining
'inventory.netMovement':'Nettobewegung','inventory.consumedToday':'Heute verbraucht',
'inventory.logStockMovement':'Bestandsbewegung protokollieren',
'inventory.recordAStockConsumptionAdditionAdjustmentOrReturn':'Bestandsverbrauch, -zugang, -anpassung oder -rückgabe erfassen.',
'inventory.bookingTaskEtc':'Buchungsnr., Aufgabenr., usw.',
'inventory.additionalNotes':'Zusätzliche Notizen...','inventory.pleaseSelectAStockItem':'Bitte wählen Sie einen Bestandsartikel',
'inventory.quantityMustBeGreaterThan0':'Menge muss größer als 0 sein',
'inventory.consumptionLogCreated':'Verbrauchsprotokoll erstellt','inventory.stockItem':'Bestandsartikel *',
};

let applied = 0;
for (const [k, v] of Object.entries(DICT)) {
  if (!T[k] && src[k]) { T[k] = v; applied++; }
}
console.log('Direct dict translations: ' + applied);

// Second pass: aggressive pattern matching for remaining
const still = Object.keys(src).filter(k => !(k in T));
let patternMatched = 0;

for (const k of still) {
  const val = src[k];
  if (!val || typeof val !== 'string') continue;
  let t = null;
  
  // "X is required" pattern
  if (/^.{3,40} is required$/i.test(val)) {
    const m = val.match(/^(.+) is required$/i);
    if (m) { const words = {'Name':'Name','Email':'E-Mail','Password':'Passwort','Description':'Beschreibung','Code':'Code','Title':'Titel','Subject':'Betreff'}; const w = words[m[1]]; if(w) t = w + ' ist erforderlich'; }
  }
  // "No X" / "No X available" short patterns
  if (!t && /^No [A-Z][a-zA-Z &]+( available)?$/i.test(val) && val.length < 50) {
    const m = val.match(/^No (.+?)( available)?$/i);
    if (m) {
      const nouns = {'data':'Daten','items':'Artikel','records':'Datensätze','results':'Ergebnisse',
        'bookings':'Buchungen','rooms':'Zimmer','guests':'Gäste','staff':'Personal',
        'events':'Veranstaltungen','orders':'Bestellungen','payments':'Zahlungen',
        'invoices':'Rechnungen','tasks':'Aufgaben','channels':'Kanäle','connections':'Verbindungen',
        'devices':'Geräte','tickets':'Tickets','campaigns':'Kampagnen','segments':'Segmente',
        'members':'Mitglieder','tenants':'Mandanten','properties':'Immobilien',
        'categories':'Kategorien','integrations':'Integrationen','metrics':'Kennzahlen',
        'trends':'Trends','suggestions':'Vorschläge','reviews':'Bewertungen',
        'slots':'Plätze','spaces':'Räume','alerts':'Warnungen','notifications':'Benachrichtigungen',
        'messages':'Nachrichten','templates':'Vorlagen','rules':'Regeln','workflows':'Workflows',
        'logs':'Protokolle','photos':'Fotos','images':'Bilder','documents':'Dokumente',
        'files':'Dateien','attachments':'Anhänge','assignments':'Zuweisungen',
        'conditions':'Bedingungen','actions':'Aktionen','triggers':'Auslöser',
        'vehicles':'Fahrzeuge','inventory':'Bestand','stock':'Bestand',
        'consumption':'Verbrauch','vendors':'Lieferanten','suppliers':'Lieferanten',
        'resources':'Ressourcen','amenities':'Ausstattung','facilities':'Einrichtungen',
        'features':'Funktionen','permissions':'Berechtigungen','roles':'Rollen',
        'users':'Benutzer','accounts':'Konten','subscribers':'Abonnenten',
        'feedback':'Feedback','coupons':'Gutscheine','vouchers':'Gutscheine',
        'codes':'Codes','reports':'Berichte','plans':'Pläne',
        'activity':'Aktivität','history':'Verlauf','experience':'Erfahrung'};
      const n = nouns[m[1].toLowerCase()] || m[1];
      t = m[2] ? `Keine ${n} verfügbar` : `Keine ${n}`;
    }
  }
  // "e.g., ..." placeholders
  if (!t && /^e\.g\.[, ]/i.test(val)) { t = val; } // Keep examples
  // "Please ..." short
  if (!t && /^Please [a-z]/i.test(val) && val.length < 60) {
    t = val.replace(/^Please /i, 'Bitte ').replace('Please ', 'Bitte ');
  }
  // "X has been/updated/deleted" pattern
  if (!t && /^.{3,30} (has been|was|is now) (updated|deleted|created|saved|removed)/i.test(val) && val.length < 60) {
    const patterns = {
      'updated':'aktualisiert','deleted':'gelöscht','created':'erstellt','saved':'gespeichert',
      'removed':'entfernt','added':'hinzugefügt','sent':'gesendet','received':'empfangen',
      'approved':'genehmigt','rejected':'abgelehnt','cancelled':'storniert','confirmed':'bestätigt',
      'completed':'abgeschlossen','processed':'verarbeitet','resolved':'gelöst'
    };
    for (const [en, de] of Object.entries(patterns)) {
      const regex = new RegExp(`^(.+) (?:has been|was|is now) ${en}$`, 'i');
      const m = val.match(regex);
      if (m) { t = m[1] + ' ' + de; break; }
    }
  }
  
  if (t) { T[k] = t; patternMatched++; }
}

console.log('Pattern matched: ' + patternMatched);
const finalRemaining = Object.keys(src).filter(k => !(k in T));
console.log('Final remaining: ' + finalRemaining.length);
console.log('Total translations: ' + Object.keys(T).length);

fs.writeFileSync('/tmp/de_translations_final2.json', JSON.stringify(T, null, 2));
