import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { requirePermission } from '@/lib/auth/tenant-context';

// GET /api/wifi/firewall/config/preview — Generate nftables config preview from DB rules
export async function GET(request: NextRequest) {
  const user = await requirePermission(request, 'network.manage');
  if (user instanceof NextResponse) return user;

  try {
    const propertyId = request.nextUrl.searchParams.get('propertyId');
    if (!propertyId) {
      return NextResponse.json(
        { success: false, error: { code: 'VALIDATION_ERROR', message: 'Missing required query parameter: propertyId' } },
        { status: 400 }
      );
    }

    // Fetch all rules with zone info
    const rules = await db.firewallRule.findMany({
      where: { propertyId, tenantId: user.tenantId },
      include: {
        firewallZone: { select: { name: true, inputPolicy: true, forwardPolicy: true, outputPolicy: true } },
      },
      orderBy: { priority: 'asc' },
    });

    const portForwards = await db.portForwardRule.findMany({
      where: { propertyId, tenantId: user.tenantId, enabled: true },
      orderBy: { externalPort: 'asc' },
    });

    const quickBlocks = await db.quickBlock.findMany({
      where: { propertyId, tenantId: user.tenantId, enabled: true },
    });

    // Generate nftables config text
    const lines: string[] = [];
    lines.push('#!/usr/sbin/nft -f');
    lines.push('# Generated by StaySuite Firewall Management');
    lines.push(`# Property: ${propertyId}`);
    lines.push(`# Generated: ${new Date().toISOString()}`);
    lines.push('');

    // Table: inet mangle
    lines.push('table inet mangle {');
    lines.push('  chain firewallchains {');
    lines.push('    type filter hook prerouting priority filter; policy accept;');
    lines.push('  }');
    lines.push('');
    lines.push('  chain firewallchainsdn {');
    lines.push('    type filter hook postrouting priority filter; policy accept;');
    lines.push('  }');
    lines.push('');

    // Group rules by chain
    const rulesByChain: Record<string, typeof rules> = {};
    for (const rule of rules) {
      if (!rule.enabled) continue;
      const chain = rule.chain || 'input';
      if (!rulesByChain[chain]) rulesByChain[chain] = [];
      rulesByChain[chain].push(rule);
    }

    for (const [chain, chainRules] of Object.entries(rulesByChain)) {
      lines.push(`  # Chain: ${chain}`);
      for (const rule of chainRules) {
        const parts: string[] = [];
        if (rule.protocol) parts.push(`ip protocol ${rule.protocol}`);
        if (rule.sourceIp) parts.push(`ip saddr ${rule.sourceIp}`);
        if (rule.destIp) parts.push(`ip daddr ${rule.destIp}`);
        if (rule.destPort) parts.push(rule.protocol ? `${rule.protocol} dport ${rule.destPort}` : `dport ${rule.destPort}`);
        if (rule.sourcePort) parts.push(rule.protocol ? `${rule.protocol} sport ${rule.sourcePort}` : `sport ${rule.sourcePort}`);
        parts.push(rule.action);
        if (rule.comment) parts.push(`comment "${rule.comment}"`);
        lines.push(`    ${parts.join(' ')}`);
      }
      lines.push('');
    }

    lines.push('}');

    // Table: inet nat
    lines.push('');
    lines.push('table inet nat {');
    lines.push('  chain frchainspre {');
    lines.push('    type nat hook prerouting priority dstnat; policy accept;');
    if (portForwards.length > 0) {
      lines.push('    # Port Forwarding Rules');
      for (const pf of portForwards) {
        const proto = pf.protocol === 'both' ? 'ip' : pf.protocol;
        lines.push(`    ${proto} dport ${pf.externalPort} dnat to ${pf.internalIp}:${pf.internalPort} comment "Port Forward: ${pf.name}"`);
      }
    }
    lines.push('  }');
    lines.push('');
    lines.push('  chain frchainspost {');
    lines.push('    type nat hook postrouting priority srcnat; policy accept;');
    lines.push('    masquerade');
    lines.push('  }');
    lines.push('}');

    // Quick blocks as a separate table
    if (quickBlocks.length > 0) {
      lines.push('');
      lines.push('table inet filter {');
      lines.push('  chain quick-blocks {');
      lines.push('    type filter hook input priority raw; policy accept;');
      for (const block of quickBlocks) {
        const typeMap: Record<string, string> = { ip: 'ip saddr', subnet: 'ip saddr', mac: 'ether saddr' };
        lines.push(`    ${typeMap[block.type] || 'ip saddr'} ${block.value} drop comment "Quick Block: ${block.reason || block.value}"`);
      }
      lines.push('  }');
      lines.push('}');
    }

    const config = lines.join('\n');

    return NextResponse.json({ success: true, data: { config } });
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : 'Failed to generate config preview';
    return NextResponse.json({ success: false, error: { message } }, { status: 500 });
  }
}
